/// The Dart sources the plugin template generator writes for an isolated
/// plugin (`.lmplugin` `"isolation": "process"`): the process part that runs
/// in its own process, the in-process UI shell that talks to it over the
/// plugin's channel, and a test for each half.
abstract final class IsolatedPluginSources {
  /// [s] as the body of a single-quoted Dart string literal.
  static String _lit(String s) => s
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\n', r'\n');

  /// `lib/<name>.dart`: both halves.
  static String entryLibrary(String pluginName) => '''// GENERATED BY LUMINA PLUGIN WIZARD
library;

export 'src/${pluginName}_plugin.dart';
export 'src/${pluginName}_process.dart';
''';

  /// `lib/src/<name>_process.dart`: a menu command, a `ping` handler for the
  /// shell, a declarative panel and, with [importer], a `.txt` importer, all
  /// run in the plugin process.
  static String processSource({
    required String pluginName,
    required String pascalName,
    required String friendlyName,
    required bool importer,
  }) {
    final friendly = _lit(friendlyName);
    final dartImports = importer ? "import 'dart:typed_data';\n" : '';
    final packageImports = importer ? "import 'package:lumina/lumina.dart' show LuminaAsset;\n" : '';
    final importerCode = importer
        ? '''

    // Imports run here too: a parser that crashes takes this process down,
    // never the editor.
    context.registerImporter(
      PluginProcessImporter(
        id: '$pluginName.txt',
        extensions: const ['.txt'],
        description: '$friendly Text Importer',
        import: (source, targetDirectory) async {
          final content = await source.readAsString();
          final baseName = source.uri.pathSegments.last.replaceAll('.txt', '');
          final targetPath = '\$targetDirectory/\$baseName.lmas';
          final asset = LuminaAsset(
            assetId: 'txt_\${DateTime.now().millisecondsSinceEpoch}',
            name: baseName,
            type: AssetType.texture,
            rawPayload: Uint8List.fromList(content.codeUnits),
            metadata: {'importedFrom': source.path, 'charCount': content.length.toString()},
          );
          final file = File(targetPath);
          await file.parent.create(recursive: true);
          await file.writeAsBytes(asset.toProtoBufferBytes());
          return targetPath;
        },
      ),
    );'''
        : '';
    return '''// GENERATED BY LUMINA PLUGIN WIZARD
import 'dart:io';
$dartImports
${packageImports}import 'package:lumina_editor_api/lumina_editor_api.dart';

/// The part of $friendly that runs in its own process. Everything that can
/// crash, hang or block belongs here: native (FFI) libraries, child
/// processes, network calls, heavy CPU work (inside `Isolate.run`), file
/// generation. If this process dies, the editor keeps running, marks the
/// plugin stopped and offers Restart.
///
/// The in-process shell (`${pascalName}Plugin`) reaches this side only
/// through `context.processChannel('$pluginName')`: its `call(method, args)`
/// runs a handler registered with [PluginProcessContext.handle].
class ${pascalName}Process extends LuminaPluginProcess {
  int _pings = 0;

  @override
  String get pluginName => '$pluginName';

  @override
  void register(PluginProcessContext context) {
    // A menu item whose command runs in this process.
    context.registerMenuItem(
      'Plugins/$friendly/Say Hello from $friendly',
      PluginProcessCommand(
        id: 'tools.$pluginName.hello',
        label: 'Say Hello from $friendly',
        run: () => context.log('Hello from the $friendly process (pid \$pid)'),
      ),
    );

    // What the shell's panel calls: channel.call('ping', {...}).
    context.handle('ping', (args) {
      _pings++;
      return {'reply': 'pong', 'pings': _pings, 'pid': pid, 'from': args['from']};
    });

    // A declarative panel: the editor renders the spec with its own
    // widgets and sends the user's actions to onEvent.
    context.registerViewPanel(
      PluginProcessViewPanel(
        id: 'panel.$pluginName.status',
        title: '$friendly Status',
        initial: const PluginViewSpec(
          id: '$pluginName.status',
          children: [
            PluginControl(kind: PluginControlKind.text, id: 'status', props: {'value': 'Not pinged yet', 'style': 'muted'}),
            PluginControl(kind: PluginControlKind.button, id: 'ping', props: {'text': 'Ping', 'tone': 'primary', 'enabled': true}),
          ],
        ),
        onEvent: (event, view) {
          if (event.controlId != 'ping' || event.kind != 'pressed') return;
          _pings++;
          view.patch(PluginViewPatch([
            PluginViewPatchOp.set('status', {'value': 'Pinged \$_pings time(s) by process \$pid', 'style': 'body'}),
          ]));
        },
      ),
    );$importerCode
  }

  @override
  Future<void> onShutdown() async {
    // Stop child processes and release native resources here.
  }
}
''';
  }

  /// `lib/src/<name>_plugin.dart`: the UI shell, a panel that calls the
  /// process part through the plugin's channel.
  static String shellSource({
    required String pluginName,
    required String pascalName,
    required String friendlyName,
    required String description,
  }) {
    final friendly = _lit(friendlyName);
    return '''// GENERATED BY LUMINA PLUGIN WIZARD
import 'package:shadcn_flutter/shadcn_flutter.dart';
import 'package:lumina_editor_api/lumina_editor_api.dart';

/// The UI shell of $friendly: it runs inside the editor, so it holds no
/// native library, starts no process and does no heavy work. It talks to
/// `${pascalName}Process` (the plugin's own process) through the channel;
/// while that process is not running, the editor covers this panel with
/// its state and a Restart button.
class ${pascalName}Plugin extends LuminaEditorPlugin {
  @override
  String get pluginName => '$pluginName';

  @override
  void register(LuminaEditorContext context) {
    final channel = context.processChannel(pluginName);
    context.registerPanel(
      EditorPanelDescriptor(
        id: 'panel.$pluginName',
        title: '$friendly',
        icon: LucideIcons.cpu,
        builder: (ctx) => ${pascalName}Panel(channel: channel),
      ),
    );
  }

  @override
  void unregister(LuminaEditorContext context) {}
}

class ${pascalName}Panel extends StatefulWidget {
  const ${pascalName}Panel({super.key, required this.channel});

  final PluginProcessChannel channel;

  @override
  State<${pascalName}Panel> createState() => _${pascalName}PanelState();
}

class _${pascalName}PanelState extends State<${pascalName}Panel> {
  String _reply = 'Not pinged yet';
  bool _busy = false;

  Future<void> _ping() async {
    setState(() => _busy = true);
    try {
      final reply = await widget.channel.call('ping', {'from': 'panel'});
      if (!mounted) return;
      final map = reply is Map ? reply : const {};
      setState(() => _reply = '\${map['reply']} #\${map['pings']} from process \${map['pid']}');
    } on PluginRemoteError catch (e) {
      if (!mounted) return;
      setState(() => _reply = 'Error: \${e.message}');
    } finally {
      if (mounted) setState(() => _busy = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text('$friendly').h4(),
          const SizedBox(height: 8),
          const Text('${_lit(description)}').muted(),
          const SizedBox(height: 16),
          ValueListenableBuilder<PluginProcessState>(
            valueListenable: widget.channel.state,
            builder: (context, state, _) => Text('Process: \${state.status.name}').small(),
          ),
          const SizedBox(height: 8),
          PrimaryButton(
            onPressed: _busy ? null : _ping,
            child: const Text('Ping process'),
          ),
          const SizedBox(height: 8),
          Text(_reply),
        ],
      ),
    );
  }
}
''';
  }

  /// `test/<name>_process_test.dart`: drives the process part through a
  /// recording [PluginProcessContext] (no editor, no child process).
  static String processTest({required String pluginName, required String pascalName}) => '''// Shipped test for the $pascalName process part
import 'dart:async';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/foundation.dart' show ValueListenable, ValueNotifier;
import 'package:flutter_test/flutter_test.dart';
import 'package:lumina_editor_api/lumina_editor_api.dart';
import 'package:$pluginName/$pluginName.dart';

class _RecordingProcessContext implements PluginProcessContext {
  final Map<String, FutureOr<Object?> Function(Map<String, Object?> args)> handlers = {};
  final Map<String, PluginProcessCommand> menuItems = {};
  final List<PluginProcessViewPanel> viewPanels = [];
  final List<PluginProcessImporter> importers = [];
  final List<String> logs = [];

  @override
  String get pluginName => '$pluginName';
  @override
  EditorProjectInfo? get project => null;
  @override
  final ValueListenable<Map<String, Object?>> pluginSettings = ValueNotifier(const {});
  @override
  final PluginStorage storage = PluginStorage(userDir: Directory('\${Directory.systemTemp.path}/${pluginName}_process_test_storage'));
  @override
  EditorLevelAccess get level => throw UnsupportedError('no level in this test');

  @override
  void handle(String method, FutureOr<Object?> Function(Map<String, Object?> args) handler) => handlers[method] = handler;
  @override
  void emit(String name, [Object? data]) {}
  @override
  void progress(String task, {required String step, int? done, int? total, String? message, bool finished = false}) {}
  @override
  void log(String message, {String level = 'info'}) => logs.add(message);
  @override
  Future<void> saveAsset({required String relativePath, Uint8List? bytes, bool generateThumbnail = true}) async {}
  @override
  void registerMenu(PluginMenuSpec menu) {}
  @override
  void registerMenuItem(String menuPath, PluginProcessCommand command,
          {int order = 0, String? section, ValueListenable<bool>? checked}) =>
      menuItems[menuPath] = command;
  @override
  void registerSlotButton(PluginProcessSlotButton button) {}
  @override
  void registerMcpTool(McpTool tool) {}
  @override
  void registerImporter(PluginProcessImporter importer) => importers.add(importer);
  @override
  void registerConsoleCommand(String name, String help, FutureOr<void> Function(List<String> args) handler) {}
  @override
  void registerViewPanel(PluginProcessViewPanel panel) => viewPanels.add(panel);
  @override
  Future<void> showPanel(String panelId) async {}
  @override
  Future<void> hidePanel(String panelId) async {}
  @override
  Future<void> openTab(String tabId, {String? title}) async {}
  @override
  Future<McpToolResult> callMcpTool(String name, Map<String, Object?> arguments) =>
      throw UnsupportedError('no editor MCP in this test');
}

class _View implements PluginViewHandle {
  _View(this.current);

  @override
  PluginViewSpec current;
  @override
  String get viewId => current.id;
  @override
  void replace(PluginViewSpec spec) => current = spec;
  @override
  void patch(PluginViewPatch patch) => current = current.apply(patch);
}

void main() {
  test('$pascalName process answers ping, runs its command and updates its panel', () async {
    final LuminaPluginProcess process = ${pascalName}Process();
    final context = _RecordingProcessContext();
    await process.register(context);

    final reply = await context.handlers['ping']!(const {'from': 'test'}) as Map;
    expect(reply['reply'], 'pong');
    expect(reply['pid'], pid);

    final command = context.menuItems.values.single;
    await command.run();
    expect(context.logs.single, contains('Hello'));

    final panel = context.viewPanels.single;
    final view = _View(panel.initial);
    await panel.onEvent(PluginViewEvent(viewId: view.viewId, controlId: 'ping', kind: 'pressed'), view);
    expect(view.current.find('status')!['value'], contains('Pinged'));
  });
}
''';

  /// `test/<name>_plugin_test.dart`: the shell registers its panel, and the
  /// panel reports a missing process instead of failing.
  static String shellTest({required String pluginName, required String pascalName}) => '''// Shipped test for the $pascalName UI shell
import 'package:flutter_test/flutter_test.dart';
import 'package:shadcn_flutter/shadcn_flutter.dart';
import 'package:lumina_editor_api/lumina_editor_api.dart';
import 'package:$pluginName/$pluginName.dart';

void main() {
  testWidgets('$pascalName panel shows the error when no plugin process is running', (tester) async {
    await tester.pumpWidget(ShadcnApp(
      home: ${pascalName}Panel(channel: PluginProcessChannel.detached('$pluginName')),
    ));
    expect(find.text('Process: disabled'), findsOneWidget);
    await tester.tap(find.text('Ping process'));
    await tester.pumpAndSettle();
    expect(find.textContaining('has no plugin process'), findsOneWidget);
  });
}
''';
}
