import 'package:lumina_editor_data/src/services/plugin_template_generator_service.dart' show PluginTemplateType;

/// The Dart sources the plugin template generator writes for an in-process
/// code plugin: `lib/src/<name>_plugin.dart` per template and its test.
abstract final class CodePluginSources {
  static String pluginSource({
    required PluginTemplateType templateType,
    required String pluginName,
    required String pascalName,
    required String friendlyName,
    required String description,
  }) {
    switch (templateType) {
      case PluginTemplateType.blank:
        return '''// GENERATED BY LUMINA PLUGIN WIZARD
import 'package:shadcn_flutter/shadcn_flutter.dart';
import 'package:lumina_editor_api/lumina_editor_api.dart';

class ${pascalName}Plugin extends LuminaEditorPlugin {
  @override
  String get pluginName => '$pluginName';

  @override
  void register(LuminaEditorContext context) {
    context.registerMenuItem(
      'Plugins/$friendlyName/About $friendlyName',
      EditorCommand(
        id: 'tools.$pluginName.about',
        label: 'About $friendlyName',
        canExecute: () => true,
        execute: (ctx) {
          if (ctx == null) return;
          showOverlay(
            ctx,
            const DialogConfiguration(),
            builder: (c) => AlertDialog(
              title: const Text('$friendlyName'),
              content: const Text('${description.replaceAll("'", "\\'")}\\nVersion: 0.1.0'),
              actions: [
                PrimaryButton(
                  onPressed: () => closeOverlay(c),
                  child: const Text('Close'),
                ),
              ],
            ),
          );
        },
      ),
    );
  }

  @override
  void unregister(LuminaEditorContext context) {}
}
''';

      case PluginTemplateType.editorPanel:
        return '''// GENERATED BY LUMINA PLUGIN WIZARD
import 'package:shadcn_flutter/shadcn_flutter.dart';
import 'package:lumina_editor_api/lumina_editor_api.dart';

class ${pascalName}Plugin extends LuminaEditorPlugin {
  @override
  String get pluginName => '$pluginName';

  @override
  void register(LuminaEditorContext context) {
    // Register menu item
    context.registerMenuItem(
      'Plugins/$friendlyName/About $friendlyName',
      EditorCommand(
        id: 'tools.$pluginName.about',
        label: 'About $friendlyName',
        canExecute: () => true,
        execute: (ctx) {
          if (ctx == null) return;
          showOverlay(
            ctx,
            const DialogConfiguration(),
            builder: (c) => AlertDialog(
              title: const Text('$friendlyName'),
              content: const Text('${description.replaceAll("'", "\\'")}\\nVersion: 0.1.0'),
              actions: [
                PrimaryButton(
                  onPressed: () => closeOverlay(c),
                  child: const Text('Close'),
                ),
              ],
            ),
          );
        },
      ),
    );

    // Register dockable panel
    context.registerPanel(
      EditorPanelDescriptor(
        id: 'panel.$pluginName',
        title: '$friendlyName',
        icon: LucideIcons.layoutGrid,
        builder: (ctx) => const ${pascalName}PanelWidget(),
      ),
    );
  }

  @override
  void unregister(LuminaEditorContext context) {}
}

class ${pascalName}PanelWidget extends StatefulWidget {
  const ${pascalName}PanelWidget({super.key});

  @override
  State<${pascalName}PanelWidget> createState() => _${pascalName}PanelWidgetState();
}

class _${pascalName}PanelWidgetState extends State<${pascalName}PanelWidget> {
  int _counter = 0;

  @override
  Widget build(BuildContext context) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('$friendlyName').h2(),
            const SizedBox(height: 8),
            Text('${description.replaceAll("'", "\\'")}'),
            const SizedBox(height: 16),
            Row(
              children: [
                PrimaryButton(
                  onPressed: () => setState(() => _counter++),
                  child: Text('Count: \$_counter'),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
''';

      case PluginTemplateType.importer:
        return '''// GENERATED BY LUMINA PLUGIN WIZARD
import 'dart:io';
import 'dart:typed_data';
import 'package:shadcn_flutter/shadcn_flutter.dart';
import 'package:lumina_editor_api/lumina_editor_api.dart';
import 'package:lumina/lumina.dart';

class ${pascalName}Plugin extends LuminaEditorPlugin {
  @override
  String get pluginName => '$pluginName';

  @override
  void register(LuminaEditorContext context) {
    context.registerMenuItem(
      'Plugins/$friendlyName/About $friendlyName',
      EditorCommand(
        id: 'tools.$pluginName.about',
        label: 'About $friendlyName',
        canExecute: () => true,
        execute: (ctx) {
          if (ctx == null) return;
          showOverlay(
            ctx,
            const DialogConfiguration(),
            builder: (c) => AlertDialog(
              title: const Text('$friendlyName'),
              content: const Text('${description.replaceAll("'", "\\'")}\\nVersion: 0.1.0'),
              actions: [
                PrimaryButton(
                  onPressed: () => closeOverlay(c),
                  child: const Text('Close'),
                ),
              ],
            ),
          );
        },
      ),
    );

    context.registerImporter(
      EditorImporter(
        extensions: const ['.txt'],
        description: '$friendlyName Text Importer',
        import: (source, ctx) async {
          try {
            final content = await source.readAsString();
            final baseName = source.uri.pathSegments.last.replaceAll('.txt', '');
            final targetPath = '\${ctx.targetDirectory}/\$baseName.lmas';
            final asset = LuminaAsset(
              assetId: 'txt_\${DateTime.now().millisecondsSinceEpoch}',
              name: baseName,
              type: AssetType.texture,
              rawPayload: Uint8List.fromList(content.codeUnits),
              metadata: {
                'importedFrom': source.path,
                'charCount': content.length.toString(),
              },
            );
            final file = File(targetPath);
            await file.parent.create(recursive: true);
            await file.writeAsBytes(asset.toProtoBufferBytes());
            return ImportResult.success(targetPath);
          } catch (e) {
            return ImportResult.failure(e.toString());
          }
        },
      ),
    );
  }

  @override
  void unregister(LuminaEditorContext context) {}
}
''';

      case PluginTemplateType.contentOnly:
        return '';
    }
  }

  static String pluginTest({
    required String pluginName,
    required String pascalName,
  }) {
    return '''// Shipped test for $pascalName plugin
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/foundation.dart' show ValueNotifier;
import 'package:flutter_test/flutter_test.dart';
import 'package:lumina_editor_api/lumina_editor_api.dart';
import 'package:$pluginName/$pluginName.dart';

// Extends (not implements) the context: its members with a default
// (processChannel, reportCrash, ...) need no stub here.
class _TestEditorContext extends LuminaEditorContext {
  final List<String> registeredMenuPaths = [];
  final List<EditorCommand> registeredCommands = [];
  final List<EditorPanelDescriptor> registeredPanels = [];
  final List<EditorImporter> registeredImporters = [];

  @override
  void registerMenuItem(String menuPath, EditorCommand command,
      {EditorMenuItemOptions options = const EditorMenuItemOptions()}) {
    registeredMenuPaths.add(menuPath);
    registeredCommands.add(command);
  }

  @override
  void registerMenu(EditorMenuDescriptor menu) {}

  @override
  void registerToolbarButton(EditorToolbarButton button) {}

  @override
  void registerSlotButton(EditorSlotButton button) {}
  @override
  final EditorPanels panels = EditorPanels.detached();
  @override
  final EditorMcp mcp = EditorMcp.detached();
  @override
  final PluginStorage storage = PluginStorage(userDir: Directory('\${Directory.systemTemp.path}/lumina_plugin_test_storage'));
  @override
  void registerProjectSettingsSection(ProjectSettingsSection section) => projectSettingsSections.add(section);
  final List<ProjectSettingsSection> projectSettingsSections = [];
  @override
  final ValueNotifier<Map<String, Object?>> pluginSettings = ValueNotifier(const {});

  @override
  void registerPanel(EditorPanelDescriptor panel) {
    registeredPanels.add(panel);
  }

  @override
  void registerAssetType(EditorAssetTypeHandler handler) {}

  @override
  void registerImporter(EditorImporter importer) {
    registeredImporters.add(importer);
  }

  @override
  void registerDetailsCustomization(DetailsCustomization c) {}

  @override
  void registerConsoleCommand(String name, String help, void Function(List<String> args) handler) {}

  @override
  void registerTab(EditorTabDescriptor tab) {}

  @override
  void openTab(String tabId, {String? title}) {}

  @override
  Future<void> saveAsset({
    required String relativePath,
    Uint8List? bytes,
    bool generateThumbnail = true,
  }) async {}
}

void main() {
  test('$pascalName registers contributions to context', () {
    final plugin = ${pascalName}Plugin();
    final context = _TestEditorContext();
    plugin.register(context);
    expect(context.registeredMenuPaths, isNotEmpty);
  });
}
''';
  }
}
