name: lumina_editor_api
description: "API for Lumina Editor Plugins."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.12.0
  flutter: ">=1.17.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  lumina:
    path: ../lumina
  lumina_core:
    path: ../lumina_core
  lumina_plugin_protocol:
    path: ../lumina_plugin_protocol
  shadcn_flutter: ^0.0.55
  path: ^1.9.0
  crypto: ^3.0.3
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
