/// Renders a parsed [FilamentMaterialDoc] as the Dart source of
/// `filament_material_api.g.dart`.
library;

import 'package:lumina_ui/ui/features/sub_editors/services/mat_language/mat_api_types.dart';

import 'filament_material_doc.dart';

String _str(String s) =>
    "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$').replaceAll('\n', r'\n')}'";

String _list(List<String> items) => items.isEmpty ? '[]' : '[${items.map(_str).join(', ')}]';

String renderFilamentMaterialApi(FilamentMaterialDoc doc, {required String filamentVersion}) {
  final b = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln('//')
    ..writeln("// Generated by `dart run tool/generate_filament_material_api.dart` from Filament")
    ..writeln("// $filamentVersion's material documentation, docs_src/src_markdeep/Materials.md.html")
    ..writeln('// (https://google.github.io/filament/Materials.md.html).')
    ..writeln('//')
    ..writeln('// One table entry per line.')
    ..writeln('// dart format off')
    ..writeln()
    ..writeln('/// Filament\'s `.mat` language as its material documentation describes it.')
    ..writeln('library;')
    ..writeln()
    ..writeln("import 'package:lumina_ui/ui/features/sub_editors/services/mat_language/mat_api_types.dart';")
    ..writeln()
    ..writeln('/// The Filament release the tables were generated from.')
    ..writeln('const String filamentMaterialApiVersion = ${_str(filamentVersion)};')
    ..writeln();

  b.writeln('/// The `material { }` header keys.');
  b.writeln('const List<MatHeaderKeyInfo> filamentHeaderKeys = [');
  for (final k in doc.headerKeys) {
    b.writeln('  MatHeaderKeyInfo(');
    b.writeln('    name: ${_str(k.name)},');
    b.writeln('    group: ${_str(k.group)},');
    b.writeln('    type: ${_str(k.type)},');
    if (k.values.isNotEmpty) b.writeln('    values: ${_list(k.values)},');
    if (k.defaultValue != null) b.writeln('    defaultValue: ${_str(k.defaultValue!)},');
    b.writeln('    description: ${_str(k.description)},');
    b.writeln('  ),');
  }
  b.writeln('];\n');

  void paramTypes(String name, String doc, List<MatParamTypeInfo> types) {
    b.writeln('/// $doc');
    b.writeln('const List<MatParamTypeInfo> $name = [');
    for (final t in types) {
      b.writeln('  MatParamTypeInfo(${_str(t.name)}, ${_str(t.description)}),');
    }
    b.writeln('];\n');
  }

  paramTypes('filamentParameterTypes', 'The types a `parameters` entry accepts.', doc.parameterTypes);
  paramTypes('filamentConstantTypes', 'The types a `constants` entry accepts.', doc.constantTypes);

  b.writeln('/// The precisions of `parameters` and `variables` entries.');
  b.writeln('const List<String> filamentPrecisions = ${_list(doc.precisions)};\n');

  void entryKeys(String name, String comment, List<MatEntryKeyInfo> keys) {
    b.writeln('/// $comment');
    b.writeln('const List<MatEntryKeyInfo> $name = [');
    for (final k in keys) {
      b.writeln('  MatEntryKeyInfo(${_str(k.name)}, ${_list(k.values)}, ${_str(k.description)}),');
    }
    b.writeln('];\n');
  }

  entryKeys('filamentParameterEntryKeys', 'The keys of a `parameters` entry.', doc.parameterEntryKeys);
  entryKeys('filamentConstantEntryKeys', 'The keys of a `constants` entry.', doc.constantEntryKeys);
  entryKeys('filamentVariableEntryKeys', 'The keys of a `variables` entry object.', doc.variableEntryKeys);
  entryKeys('filamentBlendFunctionKeys', 'The fields of `blendFunction`.', doc.blendFunctionKeys);

  void fields(String name, String comment, List<MatStructFieldInfo> list) {
    b.writeln('/// $comment');
    b.writeln('const List<MatStructFieldInfo> $name = [');
    for (final f in list) {
      b.writeln('  MatStructFieldInfo(');
      b.writeln('    name: ${_str(f.name)},');
      b.writeln('    glslType: ${_str(f.glslType)},');
      if (f.defaultValue != null) b.writeln('    defaultValue: ${_str(f.defaultValue!)},');
      if (f.shadingModels.isNotEmpty) b.writeln('    shadingModels: ${_list(f.shadingModels)},');
      if (f.availability.isNotEmpty) b.writeln('    availability: ${_str(f.availability)},');
      if (f.description.isNotEmpty) b.writeln('    description: ${_str(f.description)},');
      if (f.apiLevel != 1) b.writeln('    apiLevel: ${f.apiLevel},');
      b.writeln('  ),');
    }
    b.writeln('];\n');
  }

  fields('filamentMaterialInputs', 'The fields of `MaterialInputs` (the fragment block\'s `material`).',
      doc.fragmentInputs);
  fields('filamentMaterialVertexInputs',
      'The fields of `MaterialVertexInputs` (the vertex block\'s `material`); `variable0`… stand for the '
          'header\'s `variables`.',
      doc.vertexInputs);

  b.writeln('/// The shader public APIs.');
  b.writeln('const List<MatFunctionInfo> filamentFunctions = [');
  for (final f in doc.functions) {
    b.writeln('  MatFunctionInfo(');
    b.writeln('    name: ${_str(f.name)},');
    b.writeln('    signature: ${_str(f.signature)},');
    b.writeln('    returnType: ${_str(f.returnType)},');
    if (f.stage != MatStage.any) b.writeln('    stage: MatStage.${f.stage.name},');
    b.writeln('    description: ${_str(f.description)},');
    if (f.apiLevel != 1) b.writeln('    apiLevel: ${f.apiLevel},');
    b.writeln('    category: ${_str(f.category)},');
    b.writeln('  ),');
  }
  b.writeln('];\n');

  b.writeln('/// The type aliases Filament recommends over the GLSL names.');
  b.writeln('const List<MatTypeInfo> filamentTypeAliases = [');
  for (final t in doc.typeAliases) {
    b.writeln('  MatTypeInfo(${_str(t.name)}, ${_str(t.glslType)}, ${_str(t.description)}),');
  }
  b.writeln('];\n');

  b.writeln('/// The shader constants.');
  b.writeln('const List<MatConstantInfo> filamentConstants = [');
  for (final c in doc.constants) {
    b.writeln('  MatConstantInfo(${_str(c.name)}, ${_str(c.type)}, ${_str(c.description)}),');
  }
  b.writeln('];');
  return _oneEntryPerLine(b.toString());
}

/// Joins each multi-line `  Type(` … `  ),` entry into one line.
String _oneEntryPerLine(String source) {
  final out = <String>[];
  List<String>? entry;
  for (final line in source.split('\n')) {
    if (entry == null && RegExp(r'^  \w+\($').hasMatch(line)) {
      entry = [line.trimRight()];
    } else if (entry != null && line == '  ),') {
      final args = entry.skip(1).map((l) => l.trim()).join(' ');
      out.add('${entry.first}${args.endsWith(',') ? args.substring(0, args.length - 1) : args}),');
      entry = null;
    } else if (entry != null) {
      entry.add(line);
    } else {
      out.add(line);
    }
  }
  return out.join('\n');
}
