import 'dart:io';
import 'dart:typed_data';

import 'package:lumina/lumina.dart';

/// What [WebLoadingScreenService.write] did.
class WebLoadingScreenReport {
  /// Written files, relative to the project (or to the preview folder).
  final List<String> files;

  /// The logo's file name next to `index.html`, or null (no logo).
  final String? logoFile;

  /// Why the logo could not be used, and similar non-fatal notes.
  final List<String> warnings;

  /// Set when nothing was written (the project has no `web/` platform folder).
  final String? skippedReason;

  const WebLoadingScreenReport({this.files = const [], this.logoFile, this.warnings = const [], this.skippedReason});

  bool get written => skippedReason == null;
}

/// Generates a web build's loading screen from the project's
/// [ProjectWebLoadingStyle]: `web/index.html`, `web/loading.css`,
/// `web/loading.js`, `web/flutter_bootstrap.js` and the logo.
///
/// The page is plain HTML/CSS/JS with nothing from another origin (no fonts,
/// no CDN): it shows from the first byte, before any Flutter code arrives.
/// - `loading.js` wraps `window.fetch` to count the bytes of the engine's
///   wasm and of flutter_filament's module as they stream in, and wraps
///   `_flutter.loader.load` (called from the generated `flutter_bootstrap.js`
///   template, which Flutter fills in at build time) to follow the engine's
///   start;
/// - it exposes `window.luminaLoading.progress(fraction, label)`, which the
///   generated `main()` calls through [LuminaWebLoading] for the renderer and
///   the asset preload;
/// - it fades the screen out on Flutter's `flutter-first-frame` event.
///
/// Packaging (Package Project, Cook & Package) writes these files into the
/// project's `web/` before `flutter build web`; `index.html` is regenerated
/// every time, so edits go in Project Settings, not in the file.
abstract final class WebLoadingScreenService {
  static const String generatedNotice =
      'Generated by Lumina from Project Settings > Packaging & Target > Web Loading Style. Edits here are overwritten when the game is packaged.';

  static const String logoBaseName = 'loading_logo';

  /// Writes the loading screen into `<projectDir>/web` (or [outDir]).
  ///
  /// The logo: [ProjectWebLoadingStyle.logoFromIcon] uses [iconPng] (the
  /// editor's rasterized project icon) when given, else the project icon
  /// file, else the web app icon (`web/icons/Icon-512.png`, which packaging
  /// writes from the project icon). A project-relative image is copied.
  ///
  /// [preview] writes a page for a browser preview: no Flutter bootstrap,
  /// and `loading.js` plays a demo progress instead.
  static WebLoadingScreenReport write({
    required String projectDir,
    required LuminaProject project,
    Uint8List? iconPng,
    String? outDir,
    bool preview = false,
  }) {
    final webDir = Directory('$projectDir/web');
    if (outDir == null && !webDir.existsSync()) {
      return WebLoadingScreenReport(
        skippedReason: '${webDir.path} does not exist, so the project has no web platform '
            '(add it with `flutter create --platforms=web .`)',
      );
    }
    final out = Directory(outDir ?? webDir.path)..createSync(recursive: true);
    final rel = outDir == null ? 'web/' : '';
    final style = project.packaging.webLoadingStyle.resolve(project);
    final warnings = <String>[];
    final files = <String>[];

    final logo = _logoSource(projectDir, project, style, iconPng, warnings);
    for (final old in out.listSync().whereType<File>()) {
      final name = old.uri.pathSegments.last;
      if (name.startsWith('$logoBaseName.') && (logo == null || name != '$logoBaseName.${logo.$1}')) old.deleteSync();
    }
    String? logoFile;
    if (logo != null) {
      logoFile = '$logoBaseName.${logo.$1}';
      File('${out.path}/$logoFile').writeAsBytesSync(logo.$2);
    }

    void put(String name, String content) {
      File('${out.path}/$name').writeAsStringSync(content);
      files.add('$rel$name');
    }

    put('index.html', indexHtml(style, logoFile: logoFile, preview: preview, description: project.description));
    put('loading.css', loadingCss(style));
    put('loading.js', loadingJs(style, preview: preview));
    if (!preview) put('flutter_bootstrap.js', flutterBootstrapJs());
    if (logoFile != null) files.add('$rel$logoFile');
    return WebLoadingScreenReport(files: files, logoFile: logoFile, warnings: warnings);
  }

  /// (extension, bytes) of the logo, or null.
  static (String, Uint8List)? _logoSource(
    String projectDir,
    LuminaProject project,
    ResolvedWebLoadingStyle style,
    Uint8List? iconPng,
    List<String> warnings,
  ) {
    if (style.logo == ProjectWebLoadingStyle.logoNone) return null;
    (String, Uint8List)? fromFile(String path, String what) {
      final file = File(path.startsWith('/') ? path : '$projectDir/$path');
      final ext = path.split('.').last.toLowerCase();
      if (!ProjectWebLoadingStyle.logoExtensions.contains(ext)) {
        warnings.add('The $what $path is not an image a browser shows (${ProjectWebLoadingStyle.logoExtensions.join(', ')}); the loading screen has no logo');
        return null;
      }
      if (!file.existsSync()) {
        warnings.add('The $what $path does not exist; the loading screen has no logo');
        return null;
      }
      return (ext == 'jpeg' ? 'jpg' : ext, file.readAsBytesSync());
    }

    if (style.logo != ProjectWebLoadingStyle.logoFromIcon) return fromFile(style.logo, 'web loading logo');
    if (iconPng != null) return ('png', iconPng);
    if (!project.branding.usesDefaultIcon) return fromFile(project.branding.icon, 'project icon');
    final appIcon = File('$projectDir/web/icons/Icon-512.png');
    if (appIcon.existsSync()) return ('png', appIcon.readAsBytesSync());
    warnings.add('No project icon image was found for the loading screen (web/icons/Icon-512.png is missing)');
    return null;
  }

  static String _html(String s) => s
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&#39;');

  /// The page: the loading screen's markup over the Flutter app.
  static String indexHtml(ResolvedWebLoadingStyle style, {required String? logoFile, bool preview = false, String description = ''}) {
    final title = _html(style.title);
    final progress = switch (style.progressStyle) {
      'ring' => '''
      <div class="lumina-loading-ring-wrap">
        <svg class="lumina-loading-ring" viewBox="0 0 100 100" aria-hidden="true">
          <circle class="lumina-loading-ring-track" cx="50" cy="50" r="44"></circle>
          <circle class="lumina-loading-ring-fill" cx="50" cy="50" r="44" pathLength="100"></circle>
        </svg>
        <div class="lumina-loading-percent lumina-loading-ring-percent">0%</div>
      </div>''',
      'percentage' => '''
      <div class="lumina-loading-percent lumina-loading-percent-large">0%</div>''',
      _ => '''
      <div class="lumina-loading-bar"><div class="lumina-loading-bar-fill"></div></div>''',
    };
    return '''<!DOCTYPE html>
<!-- $generatedNotice -->
<html lang="en"${preview ? ' data-lumina-preview' : ''}>
<head>
  <base href="\$FLUTTER_BASE_HREF">
  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="${_html(description.isEmpty ? style.title : description)}">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="${style.background}">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="$title">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">
  <link rel="icon" type="image/png" href="favicon.png">
  <link rel="manifest" href="manifest.json">
  <title>$title</title>
  <link rel="stylesheet" href="loading.css">
</head>
<body>
  <div id="lumina-loading" class="lumina-loading lumina-style-${style.progressStyle}" role="progressbar" aria-label="Loading $title" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
    <div class="lumina-loading-card">
${logoFile == null ? '' : '      <img class="lumina-loading-logo" src="$logoFile" alt="">\n'}      <h1 class="lumina-loading-title">$title</h1>
${style.subtitle.trim().isEmpty ? '' : '      <p class="lumina-loading-subtitle">${_html(style.subtitle)}</p>\n'}$progress
      <p class="lumina-loading-label">Loading…</p>
    </div>
  </div>
  <script src="loading.js"></script>
${preview ? '' : '  <script src="flutter_bootstrap.js" async></script>\n'}</body>
</html>
''';
  }

  static String loadingCss(ResolvedWebLoadingStyle style) {
    final background = style.gradient == null ? style.background : 'linear-gradient(180deg, ${style.background}, ${style.gradient})';
    return '''/* $generatedNotice */
:root {
  --lumina-bg: ${style.background};
  --lumina-bg-image: $background;
  --lumina-accent: ${style.accent};
  --lumina-text: ${style.text};
  --lumina-fade: ${style.fadeMs}ms;
}
html, body {
  margin: 0;
  height: 100%;
  background: var(--lumina-bg);
}
.lumina-loading {
  position: fixed;
  inset: 0;
  z-index: 2147483647;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--lumina-bg-image);
  color: var(--lumina-text);
  font-family: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
  opacity: 1;
  transition: opacity var(--lumina-fade) ease;
}
.lumina-loading.lumina-done {
  opacity: 0;
  pointer-events: none;
}
.lumina-loading-card {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 14px;
  width: min(420px, 80vw);
  text-align: center;
}
.lumina-loading-logo {
  width: 112px;
  height: 112px;
  object-fit: contain;
}
.lumina-loading-title {
  margin: 0;
  font-size: 28px;
  font-weight: 600;
  letter-spacing: 0.02em;
}
.lumina-loading-subtitle {
  margin: -6px 0 0;
  font-size: 14px;
  opacity: 0.75;
}
.lumina-loading-bar {
  width: 100%;
  height: 6px;
  margin-top: 10px;
  border-radius: 3px;
  background: color-mix(in srgb, var(--lumina-text) 16%, transparent);
  overflow: hidden;
}
.lumina-loading-bar-fill {
  width: 0%;
  height: 100%;
  border-radius: 3px;
  background: var(--lumina-accent);
  transition: width 120ms linear;
}
.lumina-loading-ring-wrap {
  position: relative;
  width: 96px;
  height: 96px;
  margin-top: 6px;
}
.lumina-loading-ring {
  width: 100%;
  height: 100%;
  transform: rotate(-90deg);
}
.lumina-loading-ring circle {
  fill: none;
  stroke-width: 7;
}
.lumina-loading-ring-track {
  stroke: color-mix(in srgb, var(--lumina-text) 16%, transparent);
}
.lumina-loading-ring-fill {
  stroke: var(--lumina-accent);
  stroke-linecap: round;
  stroke-dasharray: 100;
  stroke-dashoffset: 100;
  transition: stroke-dashoffset 120ms linear;
}
.lumina-loading-ring-percent {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 18px;
  font-weight: 600;
}
.lumina-loading-percent-large {
  margin-top: 6px;
  font-size: 44px;
  font-weight: 700;
  color: var(--lumina-accent);
  font-variant-numeric: tabular-nums;
}
.lumina-loading-label {
  margin: 0;
  min-height: 1.3em;
  font-size: 12px;
  opacity: 0.7;
  font-variant-numeric: tabular-nums;
  animation: lumina-pulse 1.6s ease-in-out infinite;
}
/* Keeps a long single download visibly alive. */
@keyframes lumina-pulse {
  50% { opacity: 0.4; }
}
.lumina-loading-bar-fill {
  background-image: linear-gradient(90deg, transparent 0%, rgba(255, 255, 255, 0.35) 50%, transparent 100%);
  background-size: 40% 100%;
  background-repeat: no-repeat;
  animation: lumina-shimmer 1.4s linear infinite;
}
@keyframes lumina-shimmer {
  from { background-position: -40% 0; }
  to { background-position: 140% 0; }
}
.lumina-loading.lumina-error .lumina-loading-label {
  opacity: 1;
  color: #FF6B6B;
}
''';
  }

  /// The loading screen's script. [LuminaWebLoading.rendererStart] and
  /// [LuminaWebLoading.rendererEnd] are the phase boundaries the generated
  /// `main()` reports against.
  static String loadingJs(ResolvedWebLoadingStyle style, {bool preview = false}) {
    const engine = LuminaWebLoading.engineEnd;
    const start = LuminaWebLoading.rendererStart;
    const end = LuminaWebLoading.rendererEnd;
    return '''/* $generatedNotice */
(function () {
  'use strict';
  var FADE_MS = ${style.fadeMs};
  // The share of the bar each loading phase fills. The engine phase is
  // tracked here; the generated main() reports the renderer and the asset
  // preload through window.luminaLoading.progress (LuminaWebLoading).
  var PHASES = { engine: [0, $engine], renderer: [$start, $end], assets: [$end, 1] };

  var root = document.getElementById('lumina-loading');
  var shown = 0;
  var label = 'Loading…';
  var suffix = '';
  var hidden = false;

  function find(cls) { return root ? root.querySelector('.' + cls) : null; }

  function render() {
    if (!root) return;
    var pct = Math.round(shown * 100);
    var fill = find('lumina-loading-bar-fill');
    if (fill) fill.style.width = (shown * 100).toFixed(1) + '%';
    var ring = find('lumina-loading-ring-fill');
    if (ring) ring.style.strokeDashoffset = String(100 - shown * 100);
    var percents = root.querySelectorAll('.lumina-loading-percent');
    for (var i = 0; i < percents.length; i++) percents[i].textContent = pct + '%';
    var text = find('lumina-loading-label');
    if (text) text.textContent = label + suffix;
    root.setAttribute('aria-valuenow', String(pct));
  }

  // Moves the screen to [fraction] (0-1); it never goes backwards.
  function progress(fraction, text) {
    if (hidden) return;
    var f = Math.max(0, Math.min(1, Number(fraction) || 0));
    if (f > shown) shown = f;
    if (text) {
      label = String(text);
      suffix = '';
    }
    render();
  }

  function phase(name, fraction, text) {
    var range = PHASES[name];
    progress(range[0] + (range[1] - range[0]) * Math.max(0, Math.min(1, fraction)), text);
  }

  function fail(message) {
    if (root) root.classList.add('lumina-error');
    label = 'Could not start: ' + message;
    render();
  }

  function hide() {
    if (hidden || !root) return;
    progress(1);
    hidden = true;
    root.classList.add('lumina-done');
    setTimeout(function () {
      if (root && root.parentNode) root.parentNode.removeChild(root);
    }, FADE_MS + 50);
  }

  function mb(bytes) { return (bytes / 1048576).toFixed(1) + ' MB'; }

  // --- download tracking: the real bytes of every engine and renderer file.
  var downloads = {};
  var entrypointDone = false;

  function phaseOf(url) {
    if (/flutter_filament\\.wasm(\\?|\$)/.test(url)) return 'renderer';
    if (/\\/assets\\/contents\\//.test(url)) return 'assets';
    if (/(canvaskit|skwasm|skwasm_heavy|skwasm_st)\\.wasm(\\?|\$)/.test(url) || /main\\.dart\\.(wasm|mjs)(\\?|\$)/.test(url)) return 'engine';
    return null;
  }

  function update(name) {
    var loaded = 0, total = 0, unknown = false;
    for (var url in downloads) {
      var d = downloads[url];
      if (d.phase !== name) continue;
      loaded += d.loaded;
      if (d.total > 0) total += Math.max(d.total, d.loaded); else unknown = true;
      if (d.done && d.total <= 0) total += d.loaded;
    }
    var bytes = total > 0 ? Math.min(1, loaded / total) : 0;
    if (name === 'engine') {
      // The Dart entrypoint (main.dart.js) arrives through a script tag, so
      // it counts once it has loaded; the renderer module streams through fetch.
      var fraction = (entrypointDone ? 0.5 : 0) + 0.5 * bytes;
      phase('engine', fraction, 'Downloading the engine' + (total > 0 && !unknown ? ' (' + mb(loaded) + ' / ' + mb(total) + ')' : ''));
    } else if (name === 'renderer') {
      phase('renderer', bytes, 'Downloading the renderer' + (total > 0 ? ' (' + mb(loaded) + ' / ' + mb(total) + ')' : ''));
    } else if (name === 'assets' && shown < 1) {
      // The preload's count comes from main(); the bytes streaming in go under it.
      suffix = ' · ' + mb(loaded);
      render();
    }
  }

  var nativeFetch = window.fetch;
  if (nativeFetch && window.ReadableStream && window.Response) {
    window.fetch = function (input, init) {
      return nativeFetch.apply(this, arguments).then(function (response) {
        var url = response.url || (typeof input === 'string' ? input : (input && input.url) || '');
        var name = phaseOf(url);
        if (!name || !response.ok || !response.body || hidden) return response;
        var d = downloads[url] = { phase: name, loaded: 0, total: Number(response.headers.get('content-length')) || 0, done: false };
        var reader = response.body.getReader();
        var counted = new ReadableStream({
          pull: function (controller) {
            return reader.read().then(function (chunk) {
              if (chunk.done) {
                d.done = true;
                update(name);
                controller.close();
                return;
              }
              d.loaded += chunk.value.byteLength;
              update(name);
              controller.enqueue(chunk.value);
            });
          },
          cancel: function (reason) { return reader.cancel(reason); }
        });
        var wrapped = new Response(counted, { status: response.status, statusText: response.statusText, headers: response.headers });
        try { Object.defineProperty(wrapped, 'url', { value: response.url }); } catch (e) { /* url stays empty */ }
        return wrapped;
      });
    };
  }

  if (window.PerformanceObserver) {
    try {
      new PerformanceObserver(function (list) {
        list.getEntries().forEach(function (entry) {
          if (!entrypointDone && /main\\.dart\\.js(\\?|\$)/.test(entry.name)) {
            entrypointDone = true;
            update('engine');
          }
        });
      }).observe({ type: 'resource', buffered: true });
    } catch (e) { /* older browsers: the entrypoint counts when it starts */ }
  }

  // --- the Flutter loader (flutter_bootstrap.js hands it over before load()).
  function attach(loader) {
    if (!loader || loader.__luminaAttached) return;
    loader.__luminaAttached = true;
    var load = loader.load.bind(loader);
    loader.load = function (options) {
      options = options || {};
      var onEntrypointLoaded = options.onEntrypointLoaded;
      progress(0.01, 'Downloading the engine');
      var patched = {};
      for (var key in options) patched[key] = options[key];
      patched.onEntrypointLoaded = function (engineInitializer) {
        entrypointDone = true;
        update('engine');
        progress(shown, 'Starting the engine');
        if (onEntrypointLoaded) return onEntrypointLoaded(engineInitializer);
        return engineInitializer.initializeEngine().then(function (appRunner) {
          phase('engine', 1, 'Starting the game');
          return appRunner.runApp();
        });
      };
      var started = load(patched);
      if (started && started.catch) started.catch(function (e) { fail(e && e.message ? e.message : String(e)); });
      return started;
    };
  }

  window.addEventListener('flutter-first-frame', hide);

  window.luminaLoading = {
    progress: progress,
    attach: attach,
    hide: hide,
    phases: PHASES,
    get fraction() { return shown; },
    get label() { return label; },
    get hidden() { return hidden; }
  };
  render();
${preview ? _previewDemo : ''}})();
''';
  }

  /// The browser preview (no Flutter app): walks through the real labels.
  static const String _previewDemo = '''
  // Preview: a demo of the phases, looping, without a game behind it.
  (function demo() {
    var steps = [[0.25, 'Downloading the engine'], [0.55, 'Starting the engine'], [0.72, 'Downloading the renderer'],
      [0.85, 'Loading game assets'], [1, 'Starting the game']];
    var t = 0;
    var timer = setInterval(function () {
      t += 0.01;
      var text = steps[0][1];
      for (var i = 0; i < steps.length; i++) { if (t <= steps[i][0]) { text = steps[i][1]; break; } }
      progress(Math.min(t, 1), text);
      if (t >= 1.3) {
        clearInterval(timer);
        shown = 0;
        demo();
      }
    }, 40);
  })();
''';

  /// The `web/flutter_bootstrap.js` template: Flutter substitutes its loader
  /// and build config at build time; the loading screen is attached to the
  /// loader before it starts.
  static String flutterBootstrapJs() => '''
// $generatedNotice
{{flutter_js}}
{{flutter_build_config}}

if (window.luminaLoading) window.luminaLoading.attach(_flutter.loader);
_flutter.loader.load();
''';
}
