import 'package:lumina/lumina.dart';

/// An Actor Blueprint exercising collision shapes for VM ↔ codegen parity: a
/// Box (Trigger), a Sphere (OverlapAll), a Cylinder (BlockAll) and a Cone
/// (custom grid) built by the component mapping, and the Collision nodes
/// changing them on BeginPlay; Tick reads the overlaps.
LuminaBlueprintDocument collisionShapesBlueprint() {
  final components = [
    LuminaBlueprintComponent(id: 'root', name: 'DefaultSceneRoot', type: 'LuminaSceneComponent'),
    LuminaBlueprintComponent(
        id: 'box',
        name: 'TriggerBox',
        type: 'LuminaBoxComponent',
        parentId: 'root',
        properties: {'boxExtent': [100.0, 100.0, 100.0], 'preset': 'Trigger', 'location': [0.0, 0.0, 100.0]}),
    LuminaBlueprintComponent(
        id: 'sphere',
        name: 'PickupSphere',
        type: 'LuminaSphereComponent',
        parentId: 'root',
        properties: {'radius': 60.0, 'preset': 'OverlapAll', 'location': [200.0, 0.0, 60.0]}),
    LuminaBlueprintComponent(
        id: 'pillar',
        name: 'Pillar',
        type: 'LuminaCylinderComponent',
        parentId: 'root',
        properties: {'radius': 30.0, 'halfHeight': 150.0, 'preset': 'BlockAll', 'location': [-200.0, 0.0, 150.0]}),
    LuminaBlueprintComponent(
        id: 'cone',
        name: 'Cone',
        type: 'LuminaConeComponent',
        parentId: 'root',
        properties: {
          'radius': 40.0,
          'halfHeight': 60.0,
          'preset': 'custom',
          'objectType': 'worldDynamic',
          'responses': {'worldStatic': 'block', 'worldDynamic': 'ignore', 'pawn': 'overlap'},
          'generateOverlapEvents': true,
          'collisionEnabled': true,
        }),
  ];
  final doc = LuminaBlueprintDocument(parentClass: 'LuminaActor', components: components);
  final context = LuminaBlueprintTypeContext.forDocument(doc, className: 'bp_collision_shapes');
  LuminaBlueprintNode place(String id, String nodeId, [Map<String, dynamic>? literals]) =>
      LuminaBlueprintNodeLibrary.place(id, nodeId: nodeId, literals: literals, context: context);
  var n = 0;
  LuminaBlueprintWire wire(String from, String fromPin, String to, String toPin) =>
      LuminaBlueprintWire(id: 'w${n++}', fromNodeId: from, fromPinId: fromPin, toNodeId: to, toPinId: toPin);

  doc.eventGraph.nodes.addAll([
    place('event_beginplay', 'begin'),
    place(LuminaBlueprintNodeLibrary.getComponent, 'box', {'component': 'TriggerBox'}),
    place(LuminaBlueprintNodeLibrary.getComponent, 'sphere', {'component': 'PickupSphere'}),
    place(LuminaBlueprintNodeLibrary.getComponent, 'pillar', {'component': 'Pillar'}),
    place(LuminaBlueprintNodeLibrary.getComponent, 'cone', {'component': 'Cone'}),
    place('get_collision_preset', 'box_preset'),
    place('print_string', 'say_box_preset'),
    place('set_collision_response_to_channel', 'block_pawns', {'channel': 'Pawn', 'response': 'Block'}),
    place('get_collision_response_to_channel', 'pawn_response', {'channel': 'Pawn'}),
    place('print_string', 'say_pawn_response'),
    place('get_collision_preset', 'box_preset_after'),
    place('print_string', 'say_box_preset_after'),
    place('set_sphere_radius', 'grow_sphere', {'radius': 80.0}),
    place('get_sphere_radius', 'sphere_radius'),
    place('float_to_string', 'radius_text', {'decimals': 0}),
    place('print_string', 'say_radius'),
    place('set_box_extent', 'grow_box', {'box_extent': [120.0, 130.0, 140.0]}),
    place('get_box_extent', 'box_extent'),
    place('vector_to_string', 'extent_text'),
    place('print_string', 'say_extent'),
    place('set_collision_preset', 'pillar_overlaps', {'preset': 'OverlapAllDynamic'}),
    place('get_collision_object_type', 'pillar_type'),
    place('print_string', 'say_pillar_type'),
    place('set_generate_overlap_events', 'pillar_quiet', {'generate': false}),
    place('set_collision_object_type', 'cone_pawn', {'object_type': 'Pawn'}),
    place('set_collision_response_to_all_channels', 'cone_ignores', {'response': 'Ignore'}),
    place('set_collision_enabled', 'cone_off', {'new_type': 'NoCollision'}),
    place('get_collision_preset', 'cone_preset'),
    place('print_string', 'say_cone_preset'),
    place('event_tick', 'tick'),
    place('get_overlapping_components', 'overlaps'),
    place('array_length', 'overlap_count'),
    place('int_to_string', 'count_text'),
    place('print_string', 'say_count'),
    place('get_player_character', 'player'),
    place('is_overlapping_actor', 'touching_player'),
    place('bool_to_string', 'touching_text'),
    place('print_string', 'say_touching'),
    place('get_overlapping_actors', 'overlap_actors', {'class': 'Actor:LuminaPawn'}),
    place('array_length', 'actor_count'),
    place('int_to_string', 'actor_count_text'),
    place('print_string', 'say_actor_count'),
  ]);
  doc.eventGraph.wires.addAll([
    wire('begin', 'exec_out', 'say_box_preset', 'exec_in'),
    wire('box', 'return_value', 'box_preset', 'target'),
    wire('box_preset', 'return_value', 'say_box_preset', 'in_string'),
    wire('say_box_preset', 'exec_out', 'block_pawns', 'exec_in'),
    wire('box', 'return_value', 'block_pawns', 'target'),
    wire('block_pawns', 'exec_out', 'say_pawn_response', 'exec_in'),
    wire('box', 'return_value', 'pawn_response', 'target'),
    wire('pawn_response', 'return_value', 'say_pawn_response', 'in_string'),
    wire('say_pawn_response', 'exec_out', 'say_box_preset_after', 'exec_in'),
    wire('box', 'return_value', 'box_preset_after', 'target'),
    wire('box_preset_after', 'return_value', 'say_box_preset_after', 'in_string'),
    wire('say_box_preset_after', 'exec_out', 'grow_sphere', 'exec_in'),
    wire('sphere', 'return_value', 'grow_sphere', 'target'),
    wire('grow_sphere', 'exec_out', 'say_radius', 'exec_in'),
    wire('sphere', 'return_value', 'sphere_radius', 'target'),
    wire('sphere_radius', 'return_value', 'radius_text', 'in_float'),
    wire('radius_text', 'return_value', 'say_radius', 'in_string'),
    wire('say_radius', 'exec_out', 'grow_box', 'exec_in'),
    wire('box', 'return_value', 'grow_box', 'target'),
    wire('grow_box', 'exec_out', 'say_extent', 'exec_in'),
    wire('box', 'return_value', 'box_extent', 'target'),
    wire('box_extent', 'return_value', 'extent_text', 'in_vec'),
    wire('extent_text', 'return_value', 'say_extent', 'in_string'),
    wire('say_extent', 'exec_out', 'pillar_overlaps', 'exec_in'),
    wire('pillar', 'return_value', 'pillar_overlaps', 'target'),
    wire('pillar_overlaps', 'exec_out', 'say_pillar_type', 'exec_in'),
    wire('pillar', 'return_value', 'pillar_type', 'target'),
    wire('pillar_type', 'return_value', 'say_pillar_type', 'in_string'),
    wire('say_pillar_type', 'exec_out', 'pillar_quiet', 'exec_in'),
    wire('pillar', 'return_value', 'pillar_quiet', 'target'),
    wire('pillar_quiet', 'exec_out', 'cone_pawn', 'exec_in'),
    wire('cone', 'return_value', 'cone_pawn', 'target'),
    wire('cone_pawn', 'exec_out', 'cone_ignores', 'exec_in'),
    wire('cone', 'return_value', 'cone_ignores', 'target'),
    wire('cone_ignores', 'exec_out', 'cone_off', 'exec_in'),
    wire('cone', 'return_value', 'cone_off', 'target'),
    wire('cone_off', 'exec_out', 'say_cone_preset', 'exec_in'),
    wire('cone', 'return_value', 'cone_preset', 'target'),
    wire('cone_preset', 'return_value', 'say_cone_preset', 'in_string'),
    wire('tick', 'exec_tick_out', 'say_count', 'exec_in'),
    wire('box', 'return_value', 'overlaps', 'target'),
    wire('overlaps', 'return_value', 'overlap_count', 'target_array'),
    wire('overlap_count', 'return_value', 'count_text', 'in_int'),
    wire('count_text', 'return_value', 'say_count', 'in_string'),
    wire('say_count', 'exec_out', 'say_touching', 'exec_in'),
    wire('box', 'return_value', 'touching_player', 'target'),
    wire('player', 'return_value', 'touching_player', 'other'),
    wire('touching_player', 'return_value', 'touching_text', 'in_bool'),
    wire('touching_text', 'return_value', 'say_touching', 'in_string'),
    wire('say_touching', 'exec_out', 'say_actor_count', 'exec_in'),
    wire('box', 'return_value', 'overlap_actors', 'target'),
    wire('overlap_actors', 'return_value', 'actor_count', 'target_array'),
    wire('actor_count', 'return_value', 'actor_count_text', 'in_int'),
    wire('actor_count_text', 'return_value', 'say_actor_count', 'in_string'),
  ]);
  return doc;
}
