import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:lumina/data/services/blueprint_codegen/blueprint_dart_generator.dart';
import 'package:lumina/lumina.dart';

import 'generated/widget_script/wbp_clicker.g.dart';
import 'widget_blueprint_fixture.dart';

/// A widget's graph compiles into its `WBP<Name>Graph` script class
/// (a `LuminaUserWidget`), which the widget's generated file embeds. The
/// class is committed as `generated/widget_script/wbp_clicker.g.dart` (with
/// the imports a widget file gives it) and played in-process against the VM,
/// trace for trace. Regenerate after an intentional generator change with
/// `UPDATE_GOLDENS=1 flutter test test/blueprint/widget_script_codegen_test.dart`.
const String _golden = 'test/blueprint/generated/widget_script/wbp_clicker.g.dart';

String _goldenFileOf(BlueprintGenerationResult result) {
  final b = StringBuffer()
    ..writeln('// GENERATED by test/blueprint/widget_script_codegen_test.dart: WBP_Clicker\'s graph script,')
    ..writeln('// as a widget file embeds it. UPDATE_GOLDENS=1 rewrites it.')
    ..writeln('// ignore_for_file: camel_case_types, non_constant_identifier_names, unused_import, prefer_const_constructors, '
        'unnecessary_this, dead_code, unused_local_variable, dead_null_aware_expression')
    ..writeln()
    ..writeln("import 'package:lumina/lumina_runtime.dart';")
    ..writeln("import 'package:vector_math/vector_math_64.dart';");
  for (final i in result.imports) {
    b.writeln(i);
  }
  b
    ..writeln()
    ..write(result.code);
  return b.toString();
}

void main() {
  setUp(() => LuminaWidgetClassRegistry.register(clickerWidgetClass));
  tearDown(() {
    LuminaUserWidgets.clear();
    LuminaWidgetClassRegistry.clear();
  });

  test('generateWidgetScript writes WbpClickerGraph: lifecycle hooks and one onWidgetEvent case per bound event', () {
    final result = const BlueprintDartGenerator().generateWidgetScript(clickerBlueprint(), className: 'WbpClickerGraph');
    expect(result.errors, isEmpty);
    final code = result.code!;
    expect(code, contains('class WbpClickerGraph extends LuminaUserWidget with LuminaBlueprintRuntime {'));
    expect(code, contains("String get blueprintClassName => 'WBP_Clicker';"));
    expect(code, contains('void onWidgetPreConstruct(bool isDesignTime) {'));
    expect(code, contains('void onWidgetConstruct() {'));
    expect(code, contains('void onWidgetTick(double inDeltaTime) {'));
    expect(code, contains('void onWidgetDestruct() {'));
    expect(code, contains("case ('StartButton', 'OnClicked'):"));
    expect(code, contains("case ('Volume', 'OnValueChanged'):"));
    expect(code, contains("case ('NameField', 'OnTextCommitted'):"));
    expect(code, contains("LuminaBlueprintFunctionLibrary.getWidgetVariable(this, 'Title')"));
    expect(code, isNot(contains('BEGIN USER CODE')), reason: 'the class is embedded; the widget file owns the regions');

    final generated = _goldenFileOf(result);
    final golden = File(_golden);
    if (Platform.environment['UPDATE_GOLDENS'] == '1') {
      golden
        ..parent.createSync(recursive: true)
        ..writeAsStringSync(generated);
    }
    expect(golden.existsSync(), isTrue, reason: 'run with UPDATE_GOLDENS=1 to create $_golden');
    expect(generated, golden.readAsStringSync(), reason: '$_golden changed; UPDATE_GOLDENS=1 regenerates it');
  });

  test('a widget graph with errors generates nothing and names the node', () {
    final doc = clickerBlueprint();
    doc.blueprint.eventGraph.nodes.add(LuminaBlueprintNodeLibrary.place(LuminaBlueprintNodeLibrary.getWidgetVariable,
        nodeId: 'gone', literals: {'element': 'Deleted'}, context: LuminaBlueprintTypeContext.forWidget(doc)));
    final result = const BlueprintDartGenerator().generateWidgetScript(doc, className: 'WbpClickerGraph');
    expect(result.ok, isFalse);
    expect(result.errors.map((d) => d.nodeId), contains('gone'));
  });

  test('the generated WbpClickerGraph and the VM agree, event for event', () {
    List<String> run(LuminaUserWidget Function() factory) {
      LuminaUserWidgets.register(clickerClass, factory);
      final world = LuminaWorld(worldType: LuminaWorldType.game);
      world.beginPlay();
      final owner = world.spawnActorImmediately(LuminaActor());
      final widget = LuminaBlueprintFunctionLibrary.createWidget(owner, clickerClass) as Map<String, Object?>;
      final script = LuminaUserWidgets.of(widget)! as LuminaBlueprintRuntime;
      final steps = <String>[];
      script.trace = (e) => steps.add('${e.eventNodeId}/${e.nodeId}/${e.registryId}${e.printed == null ? '' : ' "${e.printed}"'}');
      Map<String, Object?> element(String name) => (widget['elements']! as Map)[name] as Map<String, Object?>;
      String state() => 'title=${element('Title')['text']}/${element('Title')['visibility']} charge=${element('Charge')['percent']}';

      element('Title')['visibility'] = 'Collapsed';
      LuminaBlueprintFunctionLibrary.addToViewport(owner, widget, 0);
      steps.add(state());
      for (var i = 0; i < 3; i++) {
        world.tick(0.05);
      }
      steps.add(state());
      LuminaUserWidgets.fire(widget, 'StartButton', 'OnClicked');
      LuminaUserWidgets.fire(widget, 'StartButton', 'OnClicked');
      steps.add(state());
      LuminaUserWidgets.fire(widget, 'Volume', 'OnValueChanged', {'value': 0.75});
      steps.add(state());
      LuminaUserWidgets.fire(widget, 'NameField', 'OnTextCommitted', {'text': 'Ada', 'commit_method': 'OnEnter'});
      steps.add('${state()} inViewport=${widget['inViewport']}');
      LuminaUserWidgets.clear();
      return steps;
    }

    final cls = LuminaBlueprintClass.forWidget(clickerBlueprint());
    final vm = run(cls.instantiateUserWidget);
    final generated = run(WbpClickerGraph.new);
    expect(generated, vm);
    expect(vm, contains('title=Ready/Visible charge=0.0'));
    expect(vm.where((s) => s.startsWith('title=Clicked!/Visible charge=0.3')), hasLength(1), reason: 'three ticks of 0.05 s × 6');
    expect(vm.last, 'title=Ada/Visible charge=0.75 inViewport=false');
    expect(vm.where((s) => s.endsWith('"clicked"')), hasLength(2));
    expect(vm.where((s) => s.endsWith('"bye"')), hasLength(1));
  });
}
