// ignore_for_file: avoid_print

/// Derives `tool/filament/prebuilt_manifest.txt` — the files a prebuilt
/// Filament archive must hold — from the native-assets hooks that consume it
/// (flutter_filament's and flutter_assimp's `hook/build.dart`), so the archive
/// cannot drift from what the hooks read.
///
///   dart tool/filament/prebuilt_manifest.dart            rewrite the manifest
///   dart tool/filament/prebuilt_manifest.dart --check    exit 1 when stale
///
/// Every `'$filament/…'` literal in a hook is one entry: a path whose last
/// segment has an extension is a `file`, anything else an include `dir` (the
/// packagers copy only its headers). `$filamentOut` expands to both output
/// folders, `windowsLib('…')` calls and the `_windowsFilamentLibs` list name
/// Windows libraries. [extraEntries] adds what no hook reads but the archive
/// still carries (the licence and the material compiler).
///
/// Manifest line: `<platforms> <kind> <path> [<built-from>]`, platforms a
/// comma list of `windows`, `linux`, `macos` or `all`; kind `file`, `dir` or
/// `tool` (a host executable copied from `<built-from>` to `<path>`).
library;

import 'dart:convert';
import 'dart:io';

/// Output folder of each platform's Filament build, relative to the checkout.
const windowsOut = 'out/cmake-release-windows';
const unixOut = 'out/cmake-release';

/// Entries no hook names.
const extraEntries = [
  // Apache-2.0: the licence travels with the binaries.
  ManifestEntry('all', 'file', 'LICENSE'),
  // flutter_filament/src/gltf_c.cpp includes gltfio's private
  // FFilamentAsset.h (and so its neighbours) as "gltfio/../../src/…".
  ManifestEntry('all', 'dir', 'libs/gltfio/src'),
  // tool/build_materials.sh (flutter_filament, lumina) compiles materials with
  // the matc of the engine it links; they look in prebuilt-tools-release.
  ManifestEntry('linux,macos', 'tool', 'out/prebuilt-tools-release/tools/matc/matc', '$unixOut/tools/matc/matc'),
  ManifestEntry('windows', 'tool', 'out/prebuilt-tools-release/tools/matc/matc.exe', '$windowsOut/tools/matc/matc.exe'),
];

class ManifestEntry implements Comparable<ManifestEntry> {
  const ManifestEntry(this.platforms, this.kind, this.path, [this.from]);

  /// `all` or a comma list of `windows`, `linux`, `macos`.
  final String platforms;

  /// `file`, `dir` or `tool`.
  final String kind;

  /// Path inside the archive (= inside a Filament checkout).
  final String path;

  /// For `tool`: where the build leaves it, relative to the checkout.
  final String? from;

  bool appliesTo(String os) => platforms == 'all' || platforms.split(',').contains(os);

  @override
  String toString() => [platforms, kind, path, if (from != null) from].join(' ');

  @override
  int compareTo(ManifestEntry other) {
    final byPath = path.compareTo(other.path);
    return byPath != 0 ? byPath : platforms.compareTo(other.platforms);
  }

  @override
  bool operator ==(Object other) => other is ManifestEntry && other.toString() == toString();

  @override
  int get hashCode => toString().hashCode;
}

/// The manifest's entries for the given hook sources.
List<ManifestEntry> manifestEntries(List<String> hookSources) {
  final entries = <ManifestEntry>{};
  void add(String platforms, String path) {
    final last = path.split('/').last;
    entries.add(ManifestEntry(platforms, last.contains('.') ? 'file' : 'dir', path));
  }

  for (final source in hookSources) {
    for (final m in RegExp(r"'\$filament/([^']+)'").allMatches(source)) {
      final path = m.group(1)!;
      if (path.contains(r'$filamentOut')) {
        final rest = path.replaceAll(r'$filamentOut', '\u0000');
        if (rest.contains(r'$')) continue; // a helper's template, not a path
        add('windows', rest.replaceAll('\u0000', windowsOut.substring(4)));
        add('linux,macos', rest.replaceAll('\u0000', unixOut.substring(4)));
      } else if (path.contains(r'$')) {
        continue; // e.g. windowsLib's own `'$filament/out/…/$path'`
      } else if (path.startsWith('$windowsOut/')) {
        add('windows', path);
      } else if (path.startsWith('$unixOut/')) {
        add('linux,macos', path);
      } else {
        add('all', path);
      }
    }
    for (final m in RegExp(r"windowsLib\('([^']+)'\)").allMatches(source)) {
      add('windows', '$windowsOut/${m.group(1)}');
    }
    final list = RegExp(r'const _windowsFilamentLibs = \[(.*?)\];', dotAll: true).firstMatch(source);
    if (list != null) {
      for (final m in RegExp(r"'([^']+)'").allMatches(list.group(1)!)) {
        add('windows', '$windowsOut/${m.group(1)}');
      }
    }
  }
  entries.addAll(extraEntries);
  return entries.toList()..sort();
}

String renderManifest(List<ManifestEntry> entries) => [
      '# Generated by tool/filament/prebuilt_manifest.dart from the native-assets',
      '# hooks (flutter_filament, flutter_assimp); do not edit by hand.',
      '# <platforms> <kind> <path> [<built-from>]',
      for (final e in entries) '$e',
      '',
    ].join('\n');

/// Parses a manifest written by [renderManifest].
List<ManifestEntry> parseManifest(String text) => [
      for (final line in const LineSplitter().convert(text))
        if (line.trim().isNotEmpty && !line.startsWith('#'))
          () {
            final f = line.trim().split(RegExp(r'\s+'));
            return ManifestEntry(f[0], f[1], f[2], f.length > 3 ? f[3] : null);
          }(),
    ];

/// The hook files the manifest is derived from, for the lumina repo at
/// [repoRoot]: flutter_filament's own, and flutter_assimp's wherever the
/// workspace resolved it (a sibling checkout or the pub cache).
List<File> hookFiles(Directory repoRoot) {
  final filamentHook = File('${repoRoot.path}/flutter_filament/hook/build.dart');
  File? assimpHook;
  final config = File('${repoRoot.path}/.dart_tool/package_config.json');
  if (config.existsSync()) {
    final packages = (jsonDecode(config.readAsStringSync()) as Map)['packages'] as List;
    for (final p in packages.cast<Map>()) {
      if (p['name'] == 'flutter_assimp') {
        final root = config.uri.resolve('${p['rootUri']}/');
        assimpHook = File.fromUri(root.resolve('hook/build.dart'));
      }
    }
  }
  assimpHook ??= File('${repoRoot.path}/../tools/flutter_assimp/hook/build.dart');
  for (final f in [filamentHook, assimpHook]) {
    if (!f.existsSync()) throw StateError('hook not found: ${f.path} (run `flutter pub get` first)');
  }
  return [filamentHook, assimpHook];
}

void main(List<String> args) {
  final repoRoot = File.fromUri(Platform.script).parent.parent.parent;
  final manifest = File('${repoRoot.path}/tool/filament/prebuilt_manifest.txt');
  final text = renderManifest(manifestEntries([for (final f in hookFiles(repoRoot)) f.readAsStringSync()]));
  if (args.contains('--check')) {
    final current = manifest.existsSync() ? manifest.readAsStringSync().replaceAll('\r\n', '\n') : '';
    if (current != text) {
      print('${manifest.path} is stale: run dart tool/filament/prebuilt_manifest.dart');
      exitCode = 1;
    }
    return;
  }
  manifest.writeAsStringSync(text);
  print('wrote ${manifest.path}');
}
