// GENERATED by tool/ffigen_web.dart from lib/src/math_types.dart — do not edit.
// ignore_for_file: type=lint, unused_import, unused_element
/*
 * Copyright 2024 flutter_filament authors.
 * Licensed under the Apache License, Version 2.0.
 */

import 'dart:js_interop';

import 'web_ffi/ffi.dart' as ffi;
import 'web_ffi/module.dart';
import 'dart:typed_data';

/// 2D float vector (8 bytes).
final class Float2 extends ffi.Struct {
  Float2.$at(super.$address) : super.$at();

  double get x => FlutterFilamentModule.heap.getFloat32($address, Endian.little);
  set x(double value) => FlutterFilamentModule.heap.setFloat32($address, value, Endian.little);

  double get y => FlutterFilamentModule.heap.getFloat32($address + 4, Endian.little);
  set y(double value) => FlutterFilamentModule.heap.setFloat32($address + 4, value, Endian.little);
}

/// 3D float vector (12 bytes, contiguous without padding).
final class Float3 extends ffi.Struct {
  Float3.$at(super.$address) : super.$at();

  double get x => FlutterFilamentModule.heap.getFloat32($address, Endian.little);
  set x(double value) => FlutterFilamentModule.heap.setFloat32($address, value, Endian.little);

  double get y => FlutterFilamentModule.heap.getFloat32($address + 4, Endian.little);
  set y(double value) => FlutterFilamentModule.heap.setFloat32($address + 4, value, Endian.little);

  double get z => FlutterFilamentModule.heap.getFloat32($address + 8, Endian.little);
  set z(double value) => FlutterFilamentModule.heap.setFloat32($address + 8, value, Endian.little);
}

/// 4D float vector (16 bytes).
final class Float4 extends ffi.Struct {
  Float4.$at(super.$address) : super.$at();

  double get x => FlutterFilamentModule.heap.getFloat32($address, Endian.little);
  set x(double value) => FlutterFilamentModule.heap.setFloat32($address, value, Endian.little);

  double get y => FlutterFilamentModule.heap.getFloat32($address + 4, Endian.little);
  set y(double value) => FlutterFilamentModule.heap.setFloat32($address + 4, value, Endian.little);

  double get z => FlutterFilamentModule.heap.getFloat32($address + 8, Endian.little);
  set z(double value) => FlutterFilamentModule.heap.setFloat32($address + 8, value, Endian.little);

  double get w => FlutterFilamentModule.heap.getFloat32($address + 12, Endian.little);
  set w(double value) => FlutterFilamentModule.heap.setFloat32($address + 12, value, Endian.little);
}

/// 2D int32 vector (8 bytes).
final class Int2 extends ffi.Struct {
  Int2.$at(super.$address) : super.$at();

  int get x => FlutterFilamentModule.heap.getInt32($address, Endian.little);
  set x(int value) => FlutterFilamentModule.heap.setInt32($address, value, Endian.little);

  int get y => FlutterFilamentModule.heap.getInt32($address + 4, Endian.little);
  set y(int value) => FlutterFilamentModule.heap.setInt32($address + 4, value, Endian.little);
}

/// 3D int32 vector (12 bytes).
final class Int3 extends ffi.Struct {
  Int3.$at(super.$address) : super.$at();

  int get x => FlutterFilamentModule.heap.getInt32($address, Endian.little);
  set x(int value) => FlutterFilamentModule.heap.setInt32($address, value, Endian.little);

  int get y => FlutterFilamentModule.heap.getInt32($address + 4, Endian.little);
  set y(int value) => FlutterFilamentModule.heap.setInt32($address + 4, value, Endian.little);

  int get z => FlutterFilamentModule.heap.getInt32($address + 8, Endian.little);
  set z(int value) => FlutterFilamentModule.heap.setInt32($address + 8, value, Endian.little);
}

/// 4D int32 vector (16 bytes).
final class Int4 extends ffi.Struct {
  Int4.$at(super.$address) : super.$at();

  int get x => FlutterFilamentModule.heap.getInt32($address, Endian.little);
  set x(int value) => FlutterFilamentModule.heap.setInt32($address, value, Endian.little);

  int get y => FlutterFilamentModule.heap.getInt32($address + 4, Endian.little);
  set y(int value) => FlutterFilamentModule.heap.setInt32($address + 4, value, Endian.little);

  int get z => FlutterFilamentModule.heap.getInt32($address + 8, Endian.little);
  set z(int value) => FlutterFilamentModule.heap.setInt32($address + 8, value, Endian.little);

  int get w => FlutterFilamentModule.heap.getInt32($address + 12, Endian.little);
  set w(int value) => FlutterFilamentModule.heap.setInt32($address + 12, value, Endian.little);
}

/// 2D uint32 vector (8 bytes).
final class Uint2 extends ffi.Struct {
  Uint2.$at(super.$address) : super.$at();

  int get x => FlutterFilamentModule.heap.getUint32($address, Endian.little);
  set x(int value) => FlutterFilamentModule.heap.setUint32($address, value, Endian.little);

  int get y => FlutterFilamentModule.heap.getUint32($address + 4, Endian.little);
  set y(int value) => FlutterFilamentModule.heap.setUint32($address + 4, value, Endian.little);
}

/// 3D uint32 vector (12 bytes).
final class Uint3 extends ffi.Struct {
  Uint3.$at(super.$address) : super.$at();

  int get x => FlutterFilamentModule.heap.getUint32($address, Endian.little);
  set x(int value) => FlutterFilamentModule.heap.setUint32($address, value, Endian.little);

  int get y => FlutterFilamentModule.heap.getUint32($address + 4, Endian.little);
  set y(int value) => FlutterFilamentModule.heap.setUint32($address + 4, value, Endian.little);

  int get z => FlutterFilamentModule.heap.getUint32($address + 8, Endian.little);
  set z(int value) => FlutterFilamentModule.heap.setUint32($address + 8, value, Endian.little);
}

/// 4D uint32 vector (16 bytes).
final class Uint4 extends ffi.Struct {
  Uint4.$at(super.$address) : super.$at();

  int get x => FlutterFilamentModule.heap.getUint32($address, Endian.little);
  set x(int value) => FlutterFilamentModule.heap.setUint32($address, value, Endian.little);

  int get y => FlutterFilamentModule.heap.getUint32($address + 4, Endian.little);
  set y(int value) => FlutterFilamentModule.heap.setUint32($address + 4, value, Endian.little);

  int get z => FlutterFilamentModule.heap.getUint32($address + 8, Endian.little);
  set z(int value) => FlutterFilamentModule.heap.setUint32($address + 8, value, Endian.little);

  int get w => FlutterFilamentModule.heap.getUint32($address + 12, Endian.little);
  set w(int value) => FlutterFilamentModule.heap.setUint32($address + 12, value, Endian.little);
}

/// 2D boolean vector (2 bytes).
final class Bool2 extends ffi.Struct {
  Bool2.$at(super.$address) : super.$at();

  int get x => FlutterFilamentModule.heap.getUint8($address);
  set x(int value) => FlutterFilamentModule.heap.setUint8($address, value);

  int get y => FlutterFilamentModule.heap.getUint8($address + 1);
  set y(int value) => FlutterFilamentModule.heap.setUint8($address + 1, value);
}

/// 3D boolean vector (3 bytes).
final class Bool3 extends ffi.Struct {
  Bool3.$at(super.$address) : super.$at();

  int get x => FlutterFilamentModule.heap.getUint8($address);
  set x(int value) => FlutterFilamentModule.heap.setUint8($address, value);

  int get y => FlutterFilamentModule.heap.getUint8($address + 1);
  set y(int value) => FlutterFilamentModule.heap.setUint8($address + 1, value);

  int get z => FlutterFilamentModule.heap.getUint8($address + 2);
  set z(int value) => FlutterFilamentModule.heap.setUint8($address + 2, value);
}

/// 4D boolean vector (4 bytes).
final class Bool4 extends ffi.Struct {
  Bool4.$at(super.$address) : super.$at();

  int get x => FlutterFilamentModule.heap.getUint8($address);
  set x(int value) => FlutterFilamentModule.heap.setUint8($address, value);

  int get y => FlutterFilamentModule.heap.getUint8($address + 1);
  set y(int value) => FlutterFilamentModule.heap.setUint8($address + 1, value);

  int get z => FlutterFilamentModule.heap.getUint8($address + 2);
  set z(int value) => FlutterFilamentModule.heap.setUint8($address + 2, value);

  int get w => FlutterFilamentModule.heap.getUint8($address + 3);
  set w(int value) => FlutterFilamentModule.heap.setUint8($address + 3, value);
}

/// 4D signed int16 vector (8 bytes).
final class Short4 extends ffi.Struct {
  Short4.$at(super.$address) : super.$at();

  int get x => FlutterFilamentModule.heap.getInt16($address, Endian.little);
  set x(int value) => FlutterFilamentModule.heap.setInt16($address, value, Endian.little);

  int get y => FlutterFilamentModule.heap.getInt16($address + 2, Endian.little);
  set y(int value) => FlutterFilamentModule.heap.setInt16($address + 2, value, Endian.little);

  int get z => FlutterFilamentModule.heap.getInt16($address + 4, Endian.little);
  set z(int value) => FlutterFilamentModule.heap.setInt16($address + 4, value, Endian.little);

  int get w => FlutterFilamentModule.heap.getInt16($address + 6, Endian.little);
  set w(int value) => FlutterFilamentModule.heap.setInt16($address + 6, value, Endian.little);
}

/// Unit quaternion stored in {x, y, z, w} memory order (16 bytes).
final class Quatf extends ffi.Struct {
  Quatf.$at(super.$address) : super.$at();

  double get x => FlutterFilamentModule.heap.getFloat32($address, Endian.little);
  set x(double value) => FlutterFilamentModule.heap.setFloat32($address, value, Endian.little);

  double get y => FlutterFilamentModule.heap.getFloat32($address + 4, Endian.little);
  set y(double value) => FlutterFilamentModule.heap.setFloat32($address + 4, value, Endian.little);

  double get z => FlutterFilamentModule.heap.getFloat32($address + 8, Endian.little);
  set z(double value) => FlutterFilamentModule.heap.setFloat32($address + 8, value, Endian.little);

  double get w => FlutterFilamentModule.heap.getFloat32($address + 12, Endian.little);
  set w(double value) => FlutterFilamentModule.heap.setFloat32($address + 12, value, Endian.little);
}

/// 3x3 float column-major matrix (36 bytes).
final class Mat3f extends ffi.Struct {
  Mat3f.$at(super.$address) : super.$at();

  ffi.Array<ffi.Float> get elements => ffi.Array<ffi.Float>.$view($address, 9);

  List<double> toList() {
    return List<double>.generate(9, (i) => elements[i]);
  }

  void setFromList(List<double> list) {
    if (list.length != 9) {
      throw ArgumentError.value(list.length, 'list.length', 'Expected 9 elements');
    }
    for (int i = 0; i < 9; i++) {
      elements[i] = list[i];
    }
  }
}

/// 4x4 float column-major matrix (64 bytes).
final class Mat4f extends ffi.Struct {
  Mat4f.$at(super.$address) : super.$at();

  ffi.Array<ffi.Float> get elements => ffi.Array<ffi.Float>.$view($address, 16);

  List<double> toList() {
    return List<double>.generate(16, (i) => elements[i]);
  }

  void setFromList(List<double> list) {
    if (list.length != 16) {
      throw ArgumentError.value(list.length, 'list.length', 'Expected 16 elements');
    }
    for (int i = 0; i < 16; i++) {
      elements[i] = list[i];
    }
  }

  static Float32List asFloat32List(ffi.Pointer<Mat4f> ptr) {
    return ptr.cast<ffi.Float>().asTypedList(16);
  }
}

/// 4x4 double precision column-major matrix (128 bytes).
final class Mat4d extends ffi.Struct {
  Mat4d.$at(super.$address) : super.$at();

  ffi.Array<ffi.Double> get elements => ffi.Array<ffi.Double>.$view($address, 16);

  List<double> toList() {
    return List<double>.generate(16, (i) => elements[i]);
  }

  void setFromList(List<double> list) {
    if (list.length != 16) {
      throw ArgumentError.value(list.length, 'list.length', 'Expected 16 elements');
    }
    for (int i = 0; i < 16; i++) {
      elements[i] = list[i];
    }
  }
}

/// Registers this file's struct layouts with the web ffi layer.
void $registerMathTypes() {
  ffi.$registerStruct<Float2>(8, 4, Float2.$at);
  ffi.$registerStruct<Float3>(12, 4, Float3.$at);
  ffi.$registerStruct<Float4>(16, 4, Float4.$at);
  ffi.$registerStruct<Int2>(8, 4, Int2.$at);
  ffi.$registerStruct<Int3>(12, 4, Int3.$at);
  ffi.$registerStruct<Int4>(16, 4, Int4.$at);
  ffi.$registerStruct<Uint2>(8, 4, Uint2.$at);
  ffi.$registerStruct<Uint3>(12, 4, Uint3.$at);
  ffi.$registerStruct<Uint4>(16, 4, Uint4.$at);
  ffi.$registerStruct<Bool2>(2, 1, Bool2.$at);
  ffi.$registerStruct<Bool3>(3, 1, Bool3.$at);
  ffi.$registerStruct<Bool4>(4, 1, Bool4.$at);
  ffi.$registerStruct<Short4>(8, 2, Short4.$at);
  ffi.$registerStruct<Quatf>(16, 4, Quatf.$at);
  ffi.$registerStruct<Mat3f>(36, 4, Mat3f.$at);
  ffi.$registerStruct<Mat4f>(64, 4, Mat4f.$at);
  ffi.$registerStruct<Mat4d>(128, 8, Mat4d.$at);
}
