import 'dart:io';

import 'package:lumina/data/services/editor_host_generator_service.dart';
import 'package:lumina/data/services/editor_source_vendor_service.dart';
import 'package:lumina/data/services/workspace_paths.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

import 'editor_build_test_support.dart';

/// The per-project editor host package.
void main() {
  final engineRoot = LuminaWorkspace.root;
  late EditorBuildFixture fx;

  setUp(() async => fx = await EditorBuildFixture.create(engineRoot: engineRoot));
  tearDown(() => fx.dispose());

  String slash(String s) => p.normalize(s).replaceAll(r'\', '/');

  test('writes pubspec, main, registrar and a renamed linux runner; a second run is byte-identical', () async {
    final gen = EditorHostGeneratorService(engineRoot: engineRoot, platform: 'linux');
    final plugin = await fx.plugin();
    final result = await gen.generate(fx.projectDir.path, [plugin]);
    expect(result.status, EditorHostStatus.generated);
    expect(result.packageName, 'host_game_editor');

    final host = Directory(p.join(fx.projectDir.path, '.lumina', 'editor'));
    for (final f in ['pubspec.yaml', 'lib/main.dart', 'lib/plugin_registrar.dart', 'linux/CMakeLists.txt']) {
      expect(File(p.join(host.path, f)).existsSync(), isTrue, reason: f);
    }
    final pubspec = File(p.join(host.path, 'pubspec.yaml')).readAsStringSync();
    expect(pubspec, contains('name: host_game_editor'));
    // The editor builds from the project's own copy.
    expect(pubspec, contains('  lumina_ui:\n    path: lumina_ui\n'));
    expect(pubspec, isNot(contains(slash(engineRoot))), reason: 'no absolute path into the engine checkout');
    expect(pubspec, contains("  a_plugin:\n    path: '${slash(fx.pluginDir.path)}'"));
    expect(pubspec, contains('  flutter_filament:\n    path: flutter_filament\n'),
        reason: "lumina_ui's path siblings are pinned to the copy");
    // Packages of other repos (git dependencies) are copied by name.
    expect(pubspec, contains('  lumina_mouse_capture:\n    path: lumina_mouse_capture\n'));
    expect(pubspec, contains('  lumina_marketplace_shared:\n    path: lumina_marketplace_shared\n'));
    expect(pubspec, contains('  flutter_assimp:\n    path: flutter_assimp\n'));
    expect(pubspec, contains('  flutter_riglogic:\n    path: flutter_riglogic\n'));
    expect(pubspec, contains('  flutter_gstreamer:\n    path: flutter_gstreamer\n'));
    expect(pubspec, contains('  lumina_smoke:\n    path: lumina_smoke\n'));
    // No native-assets hook, so no hook settings.
    expect(pubspec, isNot(contains('    flutter_gstreamer:\n      filament_dir:')));
    expect(pubspec, isNot(contains('    lumina_smoke:\n      filament_dir:')));
    // The hooks find Filament (and libc++) inside the host.
    expect(pubspec, contains('hooks:\n  user_defines:\n'));
    expect(pubspec, contains('    flutter_assimp:\n      filament_dir: filament\n      libcxx_dir: flutter_filament/third_party/libcxx\n'));
    // A copied flutter_riglogic takes the prebuilt library of the host's
    // openriglogic link (a release checkout), else its own build.
    expect(pubspec, contains('    flutter_riglogic:\n      filament_dir: filament\n      libcxx_dir: flutter_filament/third_party/libcxx\n'
        '      riglogic_lib_dir: openriglogic/lib\n'));

    final cmake = File(p.join(host.path, 'linux', 'CMakeLists.txt')).readAsStringSync();
    expect(cmake, contains('set(BINARY_NAME "host_game_editor")'));
    expect(cmake, contains('set(APPLICATION_ID "io.github.luminagame.host_game_editor")'));
    expect(cmake, isNot(contains('lumina_ui')));
    expect(Directory(p.join(host.path, 'linux', 'flutter', 'ephemeral')).existsSync(), isFalse);
    expect(File(p.join(host.path, 'linux', 'flutter', 'generated_plugins.cmake')).existsSync(), isFalse,
        reason: "the stock editor's plugin list is regenerated by flutter, not copied");

    final main = File(p.join(host.path, 'lib', 'main.dart')).readAsStringSync();
    expect(main, contains("import 'package:lumina_ui/editor_entry.dart';"));
    expect(main, contains('runLuminaEditor('));
    expect(main, contains('plugins: kEnabledPlugins'));
    expect(File(p.join(host.path, 'lib', 'plugin_registrar.dart')).readAsStringSync(),
        contains("import 'package:a_plugin/a.dart' as a_plugin_plugin;"));

    final first = snapshot(host);
    final again = await gen.generate(fx.projectDir.path, [plugin]);
    expect(again.changed, isFalse);
    final second = snapshot(host);
    expect(second.keys.toSet(), first.keys.toSet());
    for (final k in first.keys) {
      expect(second[k], first[k], reason: '$k is byte-identical');
    }
    expect(Directory('${host.path}.tmp').existsSync(), isFalse);
  });

  test('the windows branch renames the binary, the version resource and the window title', () async {
    if (!Directory(p.join(engineRoot, 'lumina_ui', 'windows')).existsSync()) {
      markTestSkipped('lumina_ui/windows is absent');
      return;
    }
    final gen = EditorHostGeneratorService(engineRoot: engineRoot, platform: 'windows');
    await gen.generate(fx.projectDir.path, [await fx.plugin()]);
    final host = p.join(fx.projectDir.path, '.lumina', 'editor', 'windows');
    expect(File(p.join(host, 'CMakeLists.txt')).readAsStringSync(), contains('set(BINARY_NAME "host_game_editor")'));
    expect(File(p.join(host, 'runner', 'Runner.rc')).readAsStringSync(), contains('"host_game_editor.exe"'));
    expect(File(p.join(host, 'runner', 'main.cpp')).readAsStringSync(), contains('L"host_game_editor"'));
    expect(File(p.join(host, 'runner', 'resources', 'app_icon.ico')).readAsBytesSync(),
        File(p.join(engineRoot, 'lumina_ui', 'windows', 'runner', 'resources', 'app_icon.ico')).readAsBytesSync(),
        reason: 'binary files are copied verbatim');
  });

  // Every project gets its own editor, plugins or not.
  test('zero code plugins: a plugin-less host (lumina_ui only, an empty registrar), byte-identical on a rerun', () async {
    final gen = EditorHostGeneratorService(engineRoot: engineRoot, platform: 'linux');
    final host = Directory(p.join(fx.projectDir.path, '.lumina', 'editor'));
    final result = await gen.generate(fx.projectDir.path, const []);
    expect(result.status, EditorHostStatus.generated);
    expect(result.packageName, 'host_game_editor');
    for (final f in ['pubspec.yaml', 'lib/main.dart', 'lib/plugin_registrar.dart', 'linux/CMakeLists.txt']) {
      expect(File(p.join(host.path, f)).existsSync(), isTrue, reason: f);
    }
    final pubspec = File(p.join(host.path, 'pubspec.yaml')).readAsStringSync();
    expect(pubspec, contains('  lumina_ui:\n    path: lumina_ui\n'));
    expect(pubspec, isNot(contains(slash(fx.pluginDir.path))));
    final registrar = File(p.join(host.path, 'lib', 'plugin_registrar.dart')).readAsStringSync();
    expect(registrar, contains('kEnabledPlugins'));
    expect(registrar, isNot(contains('_plugin;')), reason: 'no plugin import');
    expect((await gen.generate(fx.projectDir.path, const [])).changed, isFalse);
  });

  test('disabling the last code plugin leaves a plugin-less host, not an empty folder', () async {
    final gen = EditorHostGeneratorService(engineRoot: engineRoot, platform: 'linux');
    final host = Directory(p.join(fx.projectDir.path, '.lumina', 'editor'));
    await gen.generate(fx.projectDir.path, [await fx.plugin()]);
    File(p.join(host.path, EditorHostGeneratorService.stampFileName)).writeAsStringSync('{"hash":"abc"}');
    final result = await gen.generate(fx.projectDir.path, const []);
    expect(result.changed, isTrue);
    expect(File(p.join(host.path, 'pubspec.yaml')).readAsStringSync(), isNot(contains(slash(fx.pluginDir.path))));
    expect(File(p.join(host.path, EditorHostGeneratorService.stampFileName)).readAsStringSync(), '{"hash":"abc"}',
        reason: 'the stamp survives, so the resolver can name what changed');
  });

  test('a regeneration rewrites host files in place: the stamp, the source copy and .dart_tool stay', () async {
    final gen = EditorHostGeneratorService(engineRoot: engineRoot, platform: 'linux');
    await gen.generate(fx.projectDir.path, [await fx.plugin()]);
    final host = p.join(fx.projectDir.path, '.lumina', 'editor');
    File(p.join(host, EditorHostGeneratorService.stampFileName)).writeAsStringSync('{"hash":"abc"}');
    File(p.join(host, 'lib', 'main.dart')).writeAsStringSync('// hand-edited\n');
    final copied = File(p.join(host, 'lumina_ui', 'lib', 'x.dart'))
      ..createSync(recursive: true)
      ..writeAsStringSync('// the project copy, edited\n');
    final tool = File(p.join(host, '.dart_tool', 'package_config.json'))
      ..createSync(recursive: true)
      ..writeAsStringSync('{}');
    File(p.join(host, 'linux', 'stale_runner_file.cc')).writeAsStringSync('// gone from the engine\n');
    final r = await gen.generate(fx.projectDir.path, [await fx.plugin()]);
    expect(r.changed, isTrue);
    expect(File(p.join(host, 'lib', 'main.dart')).readAsStringSync(), contains('runLuminaEditor('));
    expect(File(p.join(host, EditorHostGeneratorService.stampFileName)).readAsStringSync(), '{"hash":"abc"}');
    expect(copied.readAsStringSync(), '// the project copy, edited\n');
    expect(tool.existsSync(), isTrue);
    expect(File(p.join(host, 'linux', 'stale_runner_file.cc')).existsSync(), isFalse, reason: 'runner files the engine dropped go');
    expect(Directory('$host.old').existsSync(), isFalse);
    expect(Directory('$host.tmp').existsSync(), isFalse);
  });

  test('an old-layout host (absolute engine path) migrates: relative pubspec, its resolution and build dropped, stamp kept', () async {
    final host = Directory(p.join(fx.projectDir.path, '.lumina', 'editor'))..createSync(recursive: true);
    File(p.join(host.path, 'pubspec.yaml'))
        .writeAsStringSync("name: host_game_editor\ndependencies:\n  lumina_ui:\n    path: '${slash(p.join(engineRoot, 'lumina_ui'))}'\n");
    File(p.join(host.path, 'pubspec.lock')).writeAsStringSync('packages: {}\n');
    File(p.join(host.path, '.dart_tool', 'package_config.json')).createSync(recursive: true);
    File(p.join(host.path, 'build', 'windows', 'x.obj')).createSync(recursive: true);
    File(p.join(host.path, EditorHostGeneratorService.stampFileName)).writeAsStringSync('{"hash":"abc"}');
    expect(EditorHostGeneratorService.isOldLayout(host.path), isTrue);

    final r = await EditorHostGeneratorService(engineRoot: engineRoot, platform: 'linux').generate(fx.projectDir.path, const []);
    expect(r.changed, isTrue);
    expect(File(p.join(host.path, 'pubspec.yaml')).readAsStringSync(), contains('  lumina_ui:\n    path: lumina_ui\n'));
    expect(EditorHostGeneratorService.isOldLayout(host.path), isFalse);
    for (final gone in ['pubspec.lock', '.dart_tool', 'build']) {
      expect(FileSystemEntity.typeSync(p.join(host.path, gone)), FileSystemEntityType.notFound, reason: gone);
    }
    expect(File(p.join(host.path, EditorHostGeneratorService.stampFileName)).readAsStringSync(), '{"hash":"abc"}');
  });

  test('the runner comes from the project copy when it has one', () async {
    final host = p.join(fx.projectDir.path, '.lumina', 'editor');
    File(p.join(host, 'lumina_ui', 'linux', 'CMakeLists.txt'))
      ..createSync(recursive: true)
      ..writeAsStringSync('set(BINARY_NAME "lumina_ui") # from the copy\n');
    await EditorHostGeneratorService(engineRoot: engineRoot, platform: 'linux').generate(fx.projectDir.path, const []);
    expect(File(p.join(host, 'linux', 'CMakeLists.txt')).readAsStringSync(), 'set(BINARY_NAME "host_game_editor") # from the copy\n');
  });

  test('the generated host analyzes with 0 errors', () async {
    final gen = EditorHostGeneratorService(engineRoot: engineRoot);
    await gen.generate(fx.projectDir.path, [await fx.plugin()]);
    final host = p.join(fx.projectDir.path, '.lumina', 'editor');
    // The copy's layout, as links into the engine (copying ~650 MB is the
    // build pipeline's job, covered by editor_source_vendor_service_test).
    final sources = EditorSourceVendorService(engineRoot: engineRoot).packageSources();
    for (final rel in [...EditorSourceVendorService(engineRoot: engineRoot).copyRoots(), 'filament']) {
      final link = Link(p.join(host, rel));
      link.parent.createSync(recursive: true);
      link.createSync(sources[rel] ?? p.join(engineRoot, rel));
    }
    final flutter = Platform.isWindows ? 'flutter.bat' : 'flutter';
    ProcessResult get;
    try {
      get = await Process.run(flutter, ['pub', 'get', '--offline'], workingDirectory: host, runInShell: Platform.isWindows);
    } on ProcessException {
      markTestSkipped('flutter is not on PATH');
      return;
    }
    if (get.exitCode != 0) {
      get = await Process.run(flutter, ['pub', 'get'], workingDirectory: host, runInShell: Platform.isWindows);
    }
    expect(get.exitCode, 0, reason: '${get.stdout}\n${get.stderr}');
    final analyze = await Process.run(Platform.isWindows ? 'dart.bat' : 'dart', ['analyze', '--no-fatal-warnings', 'lib'],
        workingDirectory: host, runInShell: Platform.isWindows);
    expect(analyze.exitCode, 0, reason: '${analyze.stdout}\n${analyze.stderr}');
  }, timeout: const Timeout(Duration(minutes: 5)));
}
