import 'dart:async';
import 'dart:io';

import 'package:flutter/services.dart';
import 'package:lumina/data/services/workspace_paths.dart';
import 'package:lumina_editor_api/lumina_editor_api.dart';
import 'package:path/path.dart' as p;

/// Which editor binary is running. A project editor host
/// (`<project>/.lumina/editor/`, generated by `EditorHostGeneratorService`)
/// passes one to `runLuminaEditor`; the stock editor — the launcher — has none.
class EditorHostInfo {
  /// The host package's name, also its binary's name.
  final String packageName;

  /// The workspace root the host was generated against (holds `lumina_ui/`).
  final String engineRoot;

  const EditorHostInfo({required this.packageName, required this.engineRoot});
}

/// The editor's command line: `--project <path>`, `--rebuild`,
/// `--no-plugins`, `--launcher-exe <path>`, `--update-editor`.
class EditorLaunchArgs {
  final String? project;
  final bool rebuild;
  final bool noPlugins;
  final String? launcherExe;

  /// The user already chose to update the project's editor to this Studio's
  /// engine (a project editor handed off): update without asking again.
  final bool updateEditor;

  const EditorLaunchArgs({this.project, this.rebuild = false, this.noPlugins = false, this.launcherExe, this.updateEditor = false});

  static EditorLaunchArgs parse(List<String> args) {
    String? project, launcherExe;
    var rebuild = false, noPlugins = false, updateEditor = false;
    for (var i = 0; i < args.length; i++) {
      final a = args[i];
      String? value() => i + 1 < args.length ? args[++i] : null;
      if (a == '--project') {
        project = value();
      } else if (a.startsWith('--project=')) {
        project = a.substring('--project='.length);
      } else if (a == '--launcher-exe') {
        launcherExe = value();
      } else if (a.startsWith('--launcher-exe=')) {
        launcherExe = a.substring('--launcher-exe='.length);
      } else if (a == '--rebuild') {
        rebuild = true;
      } else if (a == '--no-plugins') {
        noPlugins = true;
      } else if (a == '--update-editor') {
        updateEditor = true;
      }
    }
    return EditorLaunchArgs(
        project: project, rebuild: rebuild, noPlugins: noPlugins, launcherExe: launcherExe, updateEditor: updateEditor);
  }
}

/// Process-wide state of the running editor: its host, arguments and the
/// code plugins compiled into it. Set once by `runLuminaEditor`; tests set
/// [plugins] to boot an editor with a plugin.
class LuminaEditorHost {
  LuminaEditorHost._();

  static EditorHostInfo? info;
  static EditorLaunchArgs args = const EditorLaunchArgs();

  /// The code plugins compiled into this binary (the host's registrar).
  static List<LuminaEditorPlugin> plugins = const [];

  /// The fingerprint this project editor was built with
  /// (`--dart-define=LUMINA_EDITOR_FINGERPRINT=…` from the build service).
  static const String compiledFingerprint = String.fromEnvironment('LUMINA_EDITOR_FINGERPRINT');

  /// Whether this is a project editor rather than the stock editor.
  static bool get isProjectEditor => info != null;

  /// The workspace root: the host's, else the resolved workspace — never the
  /// working directory, which a project editor does not share with the engine.
  static String get engineRoot => info?.engineRoot ?? LuminaWorkspace.root;

  /// `<engineRoot>/lumina_ui`.
  static String get uiRoot => p.join(engineRoot, 'lumina_ui');

  /// The stock editor's executable, the launcher a project editor hands off
  /// to: `--launcher-exe`, else this binary when it is the stock editor, else
  /// the newest build under `<engineRoot>/lumina_ui/build`.
  static String? launcherExecutable() {
    if (args.launcherExe != null && File(args.launcherExe!).existsSync()) return args.launcherExe;
    if (isProjectEditor) return findStockEditor(info!.engineRoot);
    // The stock editor is the launcher: it relaunches itself. (Under
    // `flutter run` / `flutter test` the binary is not lumina_ui, and the
    // exit(70) contract of the dev launcher script applies.)
    if (p.basenameWithoutExtension(Platform.resolvedExecutable) == 'lumina_ui') return Platform.resolvedExecutable;
    return null;
  }

  static String? findStockEditor(String engineRoot, {String? operatingSystem}) {
    final os = operatingSystem ?? Platform.operatingSystem;
    final build = p.join(engineRoot, 'lumina_ui', 'build');
    final candidates = switch (os) {
      'windows' => [
          for (final cfg in ['Release', 'Debug', 'Profile']) p.join(build, 'windows', 'x64', 'runner', cfg, 'lumina_ui.exe'),
        ],
      'linux' => [
          for (final cfg in ['release', 'debug', 'profile']) p.join(build, 'linux', 'x64', cfg, 'bundle', 'lumina_ui'),
        ],
      'macos' => [
          for (final cfg in ['Release', 'Debug']) p.join(build, 'macos', 'Build', 'Products', cfg, 'lumina_ui.app', 'Contents', 'MacOS', 'lumina_ui'),
        ],
      _ => const <String>[],
    };
    for (final c in candidates) {
      if (File(c).existsSync()) return c;
    }
    return null;
  }
}

/// lumina_ui's own assets, wherever it runs: as the app its keys are
/// `assets/…`; as a project editor host's dependency Flutter bundles them as
/// `packages/lumina_ui/assets/…`. The editor keeps writing `assets/…`, and this
/// bundle — installed as the app's [DefaultAssetBundle] and used for direct
/// loads — maps the key.
class EditorAssets {
  EditorAssets._();

  static const String packagePrefix = 'packages/lumina_ui/';

  /// Whether keys need [packagePrefix]; set by [configure].
  static bool packaged = false;

  static final AssetBundle bundle = _EditorAssetBundle();

  /// The bundle key of lumina_ui asset [path] (`assets/…`).
  static String key(String path) => packaged && path.startsWith('assets/') ? '$packagePrefix$path' : path;

  static Future<ByteData> load(String path) => rootBundle.load(key(path));

  /// Detects the packaged layout from the asset manifest and, when packaged,
  /// registers lumina_ui's bundled fonts under their unqualified family names
  /// (a dependency's fonts are otherwise `packages/lumina_ui/<Family>`).
  static Future<void> configure() async {
    final manifest = await AssetManifest.loadFromAssetBundle(rootBundle);
    final keys = manifest.listAssets();
    packaged = !keys.contains('assets/logo_color.png') && keys.contains('${packagePrefix}assets/logo_color.png');
    if (!packaged) return;
    final mono = FontLoader('JetBrains Mono');
    for (final k in keys.where((k) => k.startsWith('${packagePrefix}assets/fonts/JetBrainsMono-') && k.endsWith('.ttf'))) {
      mono.addFont(rootBundle.load(k));
    }
    await mono.load();
  }
}

class _EditorAssetBundle extends AssetBundle {
  @override
  Future<ByteData> load(String key) => rootBundle.load(EditorAssets.key(key));

  @override
  Future<String> loadString(String key, {bool cache = true}) => rootBundle.loadString(EditorAssets.key(key), cache: cache);

  @override
  Future<T> loadStructuredData<T>(String key, Future<T> Function(String value) parser) =>
      rootBundle.loadStructuredData(EditorAssets.key(key), parser);

  @override
  Future<T> loadStructuredBinaryData<T>(String key, FutureOr<T> Function(ByteData data) parser) =>
      rootBundle.loadStructuredBinaryData(EditorAssets.key(key), parser);

  @override
  Future<ImmutableBuffer> loadBuffer(String key) => rootBundle.loadBuffer(EditorAssets.key(key));

  @override
  void evict(String key) => rootBundle.evict(EditorAssets.key(key));

  @override
  void clear() => rootBundle.clear();
}

/// Starts another editor binary and quits this one: the launcher
/// execs a project editor, a project editor hands back to the launcher.
/// Tests replace [instance] to observe the hand-off instead of exiting.
class EditorHandOff {
  final Future<void> Function(String executable, List<String> arguments) startDetached;
  final void Function(int code) exitApp;

  const EditorHandOff({required this.startDetached, required this.exitApp});

  static EditorHandOff instance = EditorHandOff(
    startDetached: (exe, args) async {
      await Process.start(exe, args, mode: ProcessStartMode.detached);
    },
    exitApp: exit,
  );

  /// The exit code the dev launcher script / `flutter run` wrapper treats as
  /// "rebuild and restart" when there is no launcher to hand off to.
  static const int restartExitCode = 70;

  /// Run before this process exits through a hand-off (the
  /// editor's plugins shut down: `onEditorShutdown`, child processes).
  static final List<Future<void> Function()> beforeExit = [];

  Future<void> _runBeforeExit() async {
    for (final hook in List.of(beforeExit)) {
      try {
        await hook();
      } catch (_) {
        // A hook's own failure is logged by the hook; exiting goes on.
      }
    }
  }

  /// Execs the project editor [executable] for [projectDir] and quits.
  Future<void> execProjectEditor(String executable, String projectDir) async {
    final launcher = LuminaEditorHost.isProjectEditor ? LuminaEditorHost.launcherExecutable() : Platform.resolvedExecutable;
    await startDetached(executable, ['--project', projectDir, if (launcher != null) ...['--launcher-exe', launcher]]);
    await _runBeforeExit();
    exitApp(0);
  }

  /// Relaunches the launcher ([launcher], else
  /// [LuminaEditorHost.launcherExecutable]) on [projectDir] (it resolves,
  /// builds if stale, and opens) and quits; without a launcher, exits with
  /// [restartExitCode]. [updateEditor] passes `--update-editor`: the launcher
  /// updates the project's editor to its engine without asking. Returns
  /// whether a launcher was started.
  Future<bool> restartThroughLauncher(String projectDir, {bool rebuild = false, bool updateEditor = false, String? launcher}) async {
    final exe = launcher ?? LuminaEditorHost.launcherExecutable();
    if (exe == null) {
      await _runBeforeExit();
      exitApp(restartExitCode);
      return false;
    }
    await startDetached(exe, ['--project', projectDir, if (rebuild) '--rebuild', if (updateEditor) '--update-editor']);
    await _runBeforeExit();
    exitApp(0);
    return true;
  }

  /// Starts the launcher ([launcher], else
  /// [LuminaEditorHost.launcherExecutable]) on its project list and quits;
  /// without one, quits. Returns whether a launcher was started.
  Future<bool> returnToLauncher({String? launcher}) async {
    final exe = launcher ?? LuminaEditorHost.launcherExecutable();
    if (exe != null) await startDetached(exe, const []);
    await _runBeforeExit();
    exitApp(0);
    return exe != null;
  }
}
