/// The Dart sources the plugin template generator writes for an isolated
/// plugin (`.lmplugin` `"isolation": "process"`): the process part that runs
/// in its own process, the in-process UI shell that talks to it over the
/// plugin's channel, and a test for each half.
abstract final class IsolatedPluginSources {
  /// [s] as the body of a single-quoted Dart string literal.
  static String _lit(String s) => s
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\n', r'\n');

  /// `lib/<name>.dart`: both halves.
  static String entryLibrary(String pluginName) => '''// GENERATED BY LUMINA PLUGIN WIZARD
library;

export 'package:$pluginName/src/${pluginName}_plugin.dart';
export 'package:$pluginName/src/${pluginName}_process.dart';
''';

  /// `lib/src/<name>_process.dart`: a menu command, a `ping` handler for the
  /// shell, a declarative panel and, with [importer], a `.txt` importer, all
  /// run in the plugin process.
  static String processSource({
    required String pluginName,
    required String pascalName,
    required String friendlyName,
    required bool importer,
  }) {
    final friendly = _lit(friendlyName);
    final dartImports = importer ? "import 'dart:typed_data';\n" : '';
    final packageImports = importer ? "import 'package:lumina_core/lumina_core.dart' show AssetType, LuminaAsset;\n" : '';
    final importerCode = importer
        ? '''

    // Imports run here too: a parser that crashes takes this process down,
    // never the editor.
    context.registerImporter(
      PluginProcessImporter(
        id: '$pluginName.txt',
        extensions: const ['.txt'],
        description: '$friendly Text Importer',
        import: (source, targetDirectory) async {
          final content = await source.readAsString();
          final baseName = source.uri.pathSegments.last.replaceAll('.txt', '');
          final targetPath = '\$targetDirectory/\$baseName.lmas';
          final asset = LuminaAsset(
            assetId: 'txt_\${DateTime.now().millisecondsSinceEpoch}',
            name: baseName,
            type: AssetType.texture,
            rawPayload: Uint8List.fromList(content.codeUnits),
            metadata: {'importedFrom': source.path, 'charCount': content.length.toString()},
          );
          final file = File(targetPath);
          await file.parent.create(recursive: true);
          await file.writeAsBytes(asset.toProtoBufferBytes());
          return targetPath;
        },
      ),
    );'''
        : '';
    return '''// GENERATED BY LUMINA PLUGIN WIZARD
import 'dart:io';
$dartImports
${packageImports}import 'package:lumina_plugin_process/lumina_plugin_process.dart';

/// The part of $friendly that runs in its own process. Everything that can
/// crash, hang or block belongs here: native (FFI) libraries, child
/// processes, network calls, heavy CPU work (inside `Isolate.run`), file
/// generation. If this process dies, the editor keeps running, marks the
/// plugin stopped and offers Restart.
///
/// It imports pure Dart packages only (`lumina_plugin_process`,
/// `lumina_core`, no Flutter): `test/architecture/process_part_reach_test.dart`
/// lists what it may import.
///
/// The in-process shell (`${pascalName}Plugin`) reaches this side only
/// through `context.processChannel('$pluginName')`: its `call(method, args)`
/// runs a handler registered with [PluginProcessContext.handle].
class ${pascalName}Process extends LuminaPluginProcess {
  int _pings = 0;

  @override
  String get pluginName => '$pluginName';

  @override
  void register(PluginProcessContext context) {
    // A menu item whose command runs in this process.
    context.registerMenuItem(
      'Plugins/$friendly/Say Hello from $friendly',
      PluginProcessCommand(
        id: 'tools.$pluginName.hello',
        label: 'Say Hello from $friendly',
        run: () => context.log('Hello from the $friendly process (pid \$pid)'),
      ),
    );

    // What the shell's panel calls: channel.call('ping', {...}).
    context.handle('ping', (args) {
      _pings++;
      return {'reply': 'pong', 'pings': _pings, 'pid': pid, 'from': args['from']};
    });

    // A declarative panel: the editor renders the spec with its own
    // widgets and sends the user's actions to onEvent.
    context.registerViewPanel(
      PluginProcessViewPanel(
        id: 'panel.$pluginName.status',
        title: '$friendly Status',
        initial: const PluginViewSpec(
          id: '$pluginName.status',
          children: [
            PluginControl(kind: PluginControlKind.text, id: 'status', props: {'value': 'Not pinged yet', 'style': 'muted'}),
            PluginControl(kind: PluginControlKind.button, id: 'ping', props: {'text': 'Ping', 'tone': 'primary', 'enabled': true}),
          ],
        ),
        onEvent: (event, view) {
          if (event.controlId != 'ping' || event.kind != 'pressed') return;
          _pings++;
          view.patch(PluginViewPatch([
            PluginViewPatchOp.set('status', {'value': 'Pinged \$_pings time(s) by process \$pid', 'style': 'body'}),
          ]));
        },
      ),
    );$importerCode
  }

  @override
  Future<void> onShutdown() async {
    // Stop child processes and release native resources here.
  }
}
''';
  }

  /// `lib/src/<name>_plugin.dart`: the UI shell, a panel that calls the
  /// process part through the plugin's channel.
  static String shellSource({
    required String pluginName,
    required String pascalName,
    required String friendlyName,
    required String description,
  }) {
    final friendly = _lit(friendlyName);
    return '''// GENERATED BY LUMINA PLUGIN WIZARD
import 'package:shadcn_flutter/shadcn_flutter.dart';
import 'package:lumina_editor_api/lumina_editor_api.dart';

/// The UI shell of $friendly: it runs inside the editor, so it holds no
/// native library, starts no process and does no heavy work. It talks to
/// `${pascalName}Process` (the plugin's own process) through the channel;
/// while that process is not running, the editor covers this panel with
/// its state and a Restart button.
class ${pascalName}Plugin extends LuminaEditorPlugin {
  @override
  String get pluginName => '$pluginName';

  @override
  void register(LuminaEditorContext context) {
    final channel = context.processChannel(pluginName);
    context.registerPanel(
      EditorPanelDescriptor(
        id: 'panel.$pluginName',
        title: '$friendly',
        icon: LucideIcons.cpu,
        builder: (ctx) => ${pascalName}Panel(channel: channel),
      ),
    );
  }

  @override
  void unregister(LuminaEditorContext context) {}
}

class ${pascalName}Panel extends StatefulWidget {
  const ${pascalName}Panel({super.key, required this.channel});

  final PluginProcessChannel channel;

  @override
  State<${pascalName}Panel> createState() => _${pascalName}PanelState();
}

class _${pascalName}PanelState extends State<${pascalName}Panel> {
  String _reply = 'Not pinged yet';
  bool _busy = false;

  Future<void> _ping() async {
    setState(() => _busy = true);
    try {
      final reply = await widget.channel.call('ping', {'from': 'panel'});
      if (!mounted) return;
      final map = reply is Map ? reply : const {};
      setState(() => _reply = '\${map['reply']} #\${map['pings']} from process \${map['pid']}');
    } on PluginRemoteError catch (e) {
      if (!mounted) return;
      setState(() => _reply = 'Error: \${e.message}');
    } finally {
      if (mounted) setState(() => _busy = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text('$friendly').h4(),
          const SizedBox(height: 8),
          const Text('${_lit(description)}').muted(),
          const SizedBox(height: 16),
          ValueListenableBuilder<PluginProcessState>(
            valueListenable: widget.channel.state,
            builder: (context, state, _) => Text('Process: \${state.status.name}').small(),
          ),
          const SizedBox(height: 8),
          PrimaryButton(
            onPressed: _busy ? null : _ping,
            child: const Text('Ping process'),
          ),
          const SizedBox(height: 8),
          Text(_reply),
        ],
      ),
    );
  }
}
''';
  }

  /// `test/<name>_process_test.dart`: runs the process part with
  /// `runPluginProcessMain` against `LoopbackHost` (the editor's side of the
  /// link over a real loopback socket, from `lumina_editor_api/testing.dart`).
  static String processTest({required String pluginName, required String pascalName}) => '''// Shipped test for the $pascalName process part
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:lumina_editor_api/lumina_editor_api.dart';
import 'package:lumina_editor_api/testing.dart';
import 'package:$pluginName/$pluginName.dart';

void main() {
  test('$pascalName process answers ping, runs its command and updates its panel', () async {
    final host = await LoopbackHost.start();
    addTearDown(host.close);
    final exit = runPluginProcessMain(host.launch('$pluginName'), ${pascalName}Process());
    final contributions = await host.contributions;

    final reply = await host.channel.call('ping', const {'from': 'test'}) as Map;
    expect(reply['reply'], 'pong');
    expect(reply['pid'], pid);

    final command = contributions.menuItems.single.command;
    await host.call(PluginMethods.command, {'commandId': command.id});
    final log = await host.next(PluginMethods.log, where: (a) => '\${a['message']}'.contains('Hello'));
    expect(log['message'], contains('Hello'));

    final panel = contributions.panels.single;
    await host.call(
      PluginMethods.viewEvent,
      PluginViewEvent(viewId: panel.view.id, controlId: 'ping', kind: 'pressed').toJson(),
    );
    final update = await host.next(PluginMethods.view);
    final spec = update['spec'] is Map
        ? PluginViewSpec.fromJson((update['spec'] as Map).cast())
        : panel.view.apply(PluginViewPatch.fromJson((update['patch'] as Map).cast()));
    expect(spec.find('status')!['value'], contains('Pinged'));

    await host.call(PluginMethods.shutdown);
    expect(await exit, PluginProcessExitCodes.ok);
  });
}
''';

  /// `test/architecture/process_part_reach_test.dart`: the process part
  /// (the library declaring `<Name>Process` and what it imports) imports only
  /// the listed packages and reaches no Flutter.
  static String processReachTest({required String pascalName, required bool importer}) => '''// Shipped test for the $pascalName process part's imports
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:lumina_editor_api/testing.dart';

/// The packages the process part (${pascalName}Process's library and what it
/// imports from this package) imports directly. Add one here when the
/// process part needs it.
const allowed = {${importer ? "'lumina_core', " : ''}'lumina_plugin_process'};

/// The packages among them that tie the process part to Flutter, each with
/// the reason. Empty: the process part is pure Dart.
const flutterBound = <String, String>{};

void main() {
  test('the process part imports only its recorded packages', () {
    final reach = PluginProcessReach.ofPlugin(Directory.current);
    expect(reach.directPackages, allowed, reason: reach.ownLibraries.join('\\n'));
  });

  test('the process part reaches Flutter only through its recorded packages', () {
    final reach = PluginProcessReach.ofPlugin(Directory.current);
    expect(reach.directFlutterPackages, flutterBound.keys.toSet(), reason: reach.describeFlutter());
    if (flutterBound.isEmpty) expect(reach.flutterPackages, isEmpty, reason: reach.describeFlutter());
  });
}
''';

  /// `test/<name>_plugin_test.dart`: the shell registers its panel, and the
  /// panel reports a missing process instead of failing.
  static String shellTest({required String pluginName, required String pascalName}) => '''// Shipped test for the $pascalName UI shell
import 'package:flutter_test/flutter_test.dart';
import 'package:shadcn_flutter/shadcn_flutter.dart';
import 'package:lumina_editor_api/lumina_editor_api.dart';
import 'package:$pluginName/$pluginName.dart';

void main() {
  testWidgets('$pascalName panel shows the error when no plugin process is running', (tester) async {
    await tester.pumpWidget(ShadcnApp(
      home: ${pascalName}Panel(channel: PluginProcessChannel.detached('$pluginName')),
    ));
    expect(find.text('Process: disabled'), findsOneWidget);
    await tester.tap(find.text('Ping process'));
    await tester.pumpAndSettle();
    expect(find.textContaining('has no plugin process'), findsOneWidget);
  });
}
''';
}
