// Compiles the compute shaders of flutter_filament's Vulkan passes
// (src/shaders/*.comp) to SPIR-V and writes them as C arrays next to the
// wrapper that loads them:
//
//   dart tool/build_post_pass_shaders.dart   (plain dart: no build hooks needed)
//
// Needs `glslc` (the Vulkan SDK's, or VULKAN_SDK/Bin on Windows). The
// generated headers are committed, so a normal build does not need glslc.
import 'dart:io';

const shaders = {
  'src/shaders/post_pass_debug.comp': (
    'src/post_pass_debug_spv.h',
    'kPostPassDebugSpirv',
  ),
};

Future<void> main(List<String> args) async {
  final glslc = _findGlslc();
  for (final entry in shaders.entries) {
    final source = entry.key;
    final (header, symbol) = entry.value;
    final tmp = File(
      '${Directory.systemTemp.path}/${source.split('/').last}.spv',
    );
    final result = await Process.run(glslc, [
      '--target-env=vulkan1.1',
      '-O',
      source,
      '-o',
      tmp.path,
    ]);
    if (result.exitCode != 0) {
      stderr.write(result.stderr);
      exitCode = 1;
      return;
    }
    final bytes = await tmp.readAsBytes();
    await tmp.delete();
    final words = <String>[];
    for (var i = 0; i + 3 < bytes.length; i += 4) {
      final w =
          bytes[i] |
          (bytes[i + 1] << 8) |
          (bytes[i + 2] << 16) |
          (bytes[i + 3] << 24);
      words.add('0x${w.toRadixString(16).padLeft(8, '0')}u');
    }
    final out = StringBuffer()
      ..writeln(
        '// GENERATED by tool/build_post_pass_shaders.dart from $source — do not edit.',
      )
      ..writeln('#pragma once')
      ..writeln('#include <stdint.h>')
      ..writeln('static const uint32_t $symbol[] = {');
    for (var i = 0; i < words.length; i += 8) {
      out.writeln(
        '    ${words.sublist(i, i + 8 > words.length ? words.length : i + 8).join(', ')},',
      );
    }
    out.writeln('};');
    await File(header).writeAsString(out.toString());
    stdout.writeln('$source -> $header (${bytes.length} bytes)');
  }
}

String _findGlslc() {
  final sdk = Platform.environment['VULKAN_SDK'];
  if (sdk != null) {
    final candidate = File(
      '$sdk/${Platform.isWindows ? 'Bin/glslc.exe' : 'bin/glslc'}',
    );
    if (candidate.existsSync()) return candidate.path;
  }
  return 'glslc';
}
