// Copyright 2024 flutter_filament authors.
//
// Licensed under the Apache License, Version 2.0.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// ignore_for_file: avoid_print

library;

import 'dart:io';
import 'package:ffigen/ffigen.dart';

/// Programmatic FFI binding generator for flutter_filament.
///
/// Usage: `dart run tool/ffigen.dart`
void main() {
  final packageRoot = Platform.script.resolve('../');
  final headerFile = packageRoot.resolve('src/filament_c.h');
  final bindingsOutput =
      packageRoot.resolve('lib/src/third_party/filament_c.g.dart');

  final filamentRepoPath = packageRoot.resolve('../filament/').toFilePath();

  FfiGenerator(
    headers: Headers(
      entryPoints: [headerFile],
      include: (header) => header.path.endsWith('_c.h'),
      compilerOptions: [
        '-I${packageRoot.resolve('src').toFilePath()}',
        // The stale vendored headers used to be here; ffigen must parse the
        // same declarations the plugin compiles against.
        '-I${filamentRepoPath}filament/include',
        '-I${filamentRepoPath}filament/backend/include',
        '-I${filamentRepoPath}libs/filabridge/include',
        '-I${filamentRepoPath}libs/gltfio/include',
        '-I${filamentRepoPath}libs/filamat/include',
        '-I${filamentRepoPath}libs/camutils/include',
        '-I${filamentRepoPath}libs/utils/include',
        '-I${filamentRepoPath}libs/math/include',
        '-I${filamentRepoPath}libs/matdbg/include',
        '-I${filamentRepoPath}libs/filaflat/include',
        '-I${filamentRepoPath}third_party/zstd/lib',
        '-I${filamentRepoPath}third_party/robin-map/include',
      ],
    ),
    functions: Functions(
      include: Declarations.includeAll,
      isLeaf: (declaration) {
        final name = declaration.originalName;
        if (name.startsWith('filament_sizeof_') ||
            name.startsWith('filament_enum_') ||
            name.startsWith('filament_test_buffer_descriptor_peek')) {
          return true;
        }
        return false;
      },
    ),
    enums: Enums(
      include: Declarations.includeAll,
    ),
    typedefs: Typedefs(
      include: Declarations.includeAll,
    ),
    structs: Structs(
      include: Declarations.includeAll,
    ),
    unions: Unions(
      include: Declarations.includeAll,
    ),
    output: Output(
      dartFile: bindingsOutput,
      format: true,
      preamble: '''
// Copyright 2024 flutter_filament authors.
// Licensed under the Apache License, Version 2.0.

// AUTO-GENERATED FILE — DO NOT MODIFY.
// Generated by package:ffigen via tool/ffigen.dart.
// To regenerate: dart run tool/ffigen.dart

// ignore_for_file: type=lint, unused_import, unused_element
// ignore_for_file: camel_case_types, non_constant_identifier_names
// ignore_for_file: constant_identifier_names
''',
    ),
  ).generate();

  print('✅ Successfully generated Filament FFI bindings at:');
  print('   lib/src/third_party/filament_c.g.dart');
}
