import 'dart:io';

import 'package:lumina_editor_data/lumina_editor.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:yaml/yaml.dart';

import 'editor_build_test_support.dart';

/// The per-project editor host package.
void main() {
  final engineRoot = LuminaWorkspace.root;
  late EditorBuildFixture fx;

  setUp(() async => fx = await EditorBuildFixture.create(engineRoot: engineRoot));
  tearDown(() => fx.dispose());

  String slash(String s) => p.normalize(s).replaceAll(r'\', '/');

  test('writes pubspec, main, registrar and a renamed linux runner; a second run is byte-identical', () async {
    final gen = EditorHostGeneratorService(engineRoot: engineRoot, platform: 'linux');
    final plugin = await fx.plugin();
    final result = await gen.generate(fx.projectDir.path, [plugin]);
    expect(result.status, EditorHostStatus.generated);
    expect(result.packageName, 'host_game_editor');

    final host = Directory(p.join(fx.projectDir.path, '.lumina', 'editor'));
    for (final f in ['pubspec.yaml', 'lib/main.dart', 'lib/plugin_registrar.dart', 'linux/CMakeLists.txt']) {
      expect(File(p.join(host.path, f)).existsSync(), isTrue, reason: f);
    }
    final pubspec = File(p.join(host.path, 'pubspec.yaml')).readAsStringSync();
    expect(pubspec, contains('name: host_game_editor'));
    // The editor builds from the project's own copy.
    expect(pubspec, contains('  lumina_ui:\n    path: lumina_ui\n'));
    expect(pubspec, isNot(contains(slash(engineRoot))), reason: 'no absolute path into the engine checkout');
    expect(pubspec, contains("  a_plugin:\n    path: '${slash(fx.pluginDir.path)}'"));
    expect(pubspec, contains('  flutter_filament:\n    path: flutter_filament\n'),
        reason: "lumina_ui's path siblings are pinned to the copy");
    // Packages of other repos (git dependencies) are copied by name.
    expect(pubspec, contains('  lumina_mouse_capture:\n    path: lumina_mouse_capture\n'));
    expect(pubspec, contains('  lumina_marketplace_shared:\n    path: lumina_marketplace_shared\n'));
    expect(pubspec, contains('  flutter_assimp:\n    path: flutter_assimp\n'));
    expect(pubspec, contains('  flutter_riglogic:\n    path: flutter_riglogic\n'));
    expect(pubspec, contains('  flutter_gstreamer:\n    path: flutter_gstreamer\n'));
    expect(pubspec, contains('  lumina_smoke:\n    path: lumina_smoke\n'));
    // No native-assets hook, so no hook settings.
    expect(pubspec, isNot(contains('    flutter_gstreamer:\n      filament_dir:')));
    expect(pubspec, isNot(contains('    lumina_smoke:\n      filament_dir:')));
    // The hooks find Filament (and libc++) inside the host.
    expect(pubspec, contains('hooks:\n  user_defines:\n'));
    expect(pubspec, contains('    flutter_assimp:\n      filament_dir: filament\n      libcxx_dir: flutter_filament/third_party/libcxx\n'));
    // A copied flutter_riglogic takes the prebuilt library of the host's
    // openriglogic link (a release checkout), else its own build.
    expect(pubspec, contains('    flutter_riglogic:\n      filament_dir: filament\n      libcxx_dir: flutter_filament/third_party/libcxx\n'
        '      riglogic_lib_dir: openriglogic/lib\n'));

    final cmake = File(p.join(host.path, 'linux', 'CMakeLists.txt')).readAsStringSync();
    expect(cmake, contains('set(BINARY_NAME "host_game_editor")'));
    expect(cmake, contains('set(APPLICATION_ID "io.github.luminagame.host_game_editor")'));
    expect(cmake, isNot(contains('lumina_ui')));
    expect(Directory(p.join(host.path, 'linux', 'flutter', 'ephemeral')).existsSync(), isFalse);
    expect(File(p.join(host.path, 'linux', 'flutter', 'generated_plugins.cmake')).existsSync(), isFalse,
        reason: "the stock editor's plugin list is regenerated by flutter, not copied");

    final main = File(p.join(host.path, 'lib', 'main.dart')).readAsStringSync();
    expect(main, contains("import 'package:lumina_ui/editor_entry.dart';"));
    expect(main, contains('runLuminaEditor('));
    expect(main, contains('plugins: kEnabledPlugins'));
    expect(main, contains('processes: kPluginProcesses'));
    expect(File(p.join(host.path, 'lib', 'plugin_registrar.dart')).readAsStringSync(),
        contains("import 'package:a_plugin/a.dart' as a_plugin_plugin;"));

    final first = snapshot(host);
    final again = await gen.generate(fx.projectDir.path, [plugin]);
    expect(again.changed, isFalse);
    final second = snapshot(host);
    expect(second.keys.toSet(), first.keys.toSet());
    for (final k in first.keys) {
      expect(second[k], first[k], reason: '$k is byte-identical');
    }
    expect(Directory('${host.path}.tmp').existsSync(), isFalse);
  });

  test('an isolated plugin: the registrar maps its name to its process class; the main passes the map', () async {
    await fx.isolate();
    final gen = EditorHostGeneratorService(engineRoot: engineRoot, platform: 'linux');
    final result = await gen.generate(fx.projectDir.path, [await fx.plugin()]);
    final host = result.hostDir!.path;
    final registrar = File(p.join(host, 'lib', 'plugin_registrar.dart')).readAsStringSync();
    expect(registrar, contains('final Map<String, LuminaPluginProcess Function()> kPluginProcesses = {\n'
        "  'a_plugin': () => a_plugin_plugin.AProcess(),\n"
        '};\n'));
    expect(registrar, contains('  a_plugin_plugin.APlugin(),'), reason: 'the UI shell still registers in the editor');
    expect(File(p.join(host, 'lib', 'main.dart')).readAsStringSync(), contains('      processes: kPluginProcesses,\n'));
  });

  test('the windows branch renames the binary, the version resource and the window title', () async {
    if (!Directory(p.join(engineRoot, 'lumina_ui', 'windows')).existsSync()) {
      markTestSkipped('lumina_ui/windows is absent');
      return;
    }
    final gen = EditorHostGeneratorService(engineRoot: engineRoot, platform: 'windows');
    await gen.generate(fx.projectDir.path, [await fx.plugin()]);
    final host = p.join(fx.projectDir.path, '.lumina', 'editor', 'windows');
    expect(File(p.join(host, 'CMakeLists.txt')).readAsStringSync(), contains('set(BINARY_NAME "host_game_editor")'));
    expect(File(p.join(host, 'runner', 'Runner.rc')).readAsStringSync(), contains('"host_game_editor.exe"'));
    expect(File(p.join(host, 'runner', 'main.cpp')).readAsStringSync(), contains('L"host_game_editor"'));
    expect(File(p.join(host, 'runner', 'resources', 'app_icon.ico')).readAsBytesSync(),
        File(p.join(engineRoot, 'lumina_ui', 'windows', 'runner', 'resources', 'app_icon.ico')).readAsBytesSync(),
        reason: 'binary files are copied verbatim');
  });

  // Every project gets its own editor, plugins or not.
  test('zero code plugins: a plugin-less host (lumina_ui only, an empty registrar), byte-identical on a rerun', () async {
    final gen = EditorHostGeneratorService(engineRoot: engineRoot, platform: 'linux');
    final host = Directory(p.join(fx.projectDir.path, '.lumina', 'editor'));
    final result = await gen.generate(fx.projectDir.path, const []);
    expect(result.status, EditorHostStatus.generated);
    expect(result.packageName, 'host_game_editor');
    for (final f in ['pubspec.yaml', 'lib/main.dart', 'lib/plugin_registrar.dart', 'linux/CMakeLists.txt']) {
      expect(File(p.join(host.path, f)).existsSync(), isTrue, reason: f);
    }
    final pubspec = File(p.join(host.path, 'pubspec.yaml')).readAsStringSync();
    expect(pubspec, contains('  lumina_ui:\n    path: lumina_ui\n'));
    expect(pubspec, isNot(contains(slash(fx.pluginDir.path))));
    final registrar = File(p.join(host.path, 'lib', 'plugin_registrar.dart')).readAsStringSync();
    expect(registrar, contains('kEnabledPlugins'));
    expect(registrar, isNot(contains('_plugin;')), reason: 'no plugin import');
    expect((await gen.generate(fx.projectDir.path, const [])).changed, isFalse);
  });

  test('disabling the last code plugin leaves a plugin-less host, not an empty folder', () async {
    final gen = EditorHostGeneratorService(engineRoot: engineRoot, platform: 'linux');
    final host = Directory(p.join(fx.projectDir.path, '.lumina', 'editor'));
    await gen.generate(fx.projectDir.path, [await fx.plugin()]);
    File(p.join(host.path, EditorHostGeneratorService.stampFileName)).writeAsStringSync('{"hash":"abc"}');
    final result = await gen.generate(fx.projectDir.path, const []);
    expect(result.changed, isTrue);
    expect(File(p.join(host.path, 'pubspec.yaml')).readAsStringSync(), isNot(contains(slash(fx.pluginDir.path))));
    expect(File(p.join(host.path, EditorHostGeneratorService.stampFileName)).readAsStringSync(), '{"hash":"abc"}',
        reason: 'the stamp survives, so the resolver can name what changed');
  });

  test('a regeneration rewrites host files in place: the stamp, the source copy and .dart_tool stay', () async {
    final gen = EditorHostGeneratorService(engineRoot: engineRoot, platform: 'linux');
    await gen.generate(fx.projectDir.path, [await fx.plugin()]);
    final host = p.join(fx.projectDir.path, '.lumina', 'editor');
    File(p.join(host, EditorHostGeneratorService.stampFileName)).writeAsStringSync('{"hash":"abc"}');
    File(p.join(host, 'lib', 'main.dart')).writeAsStringSync('// hand-edited\n');
    final copied = File(p.join(host, 'lumina_ui', 'lib', 'x.dart'))
      ..createSync(recursive: true)
      ..writeAsStringSync('// the project copy, edited\n');
    final tool = File(p.join(host, '.dart_tool', 'package_config.json'))
      ..createSync(recursive: true)
      ..writeAsStringSync('{}');
    File(p.join(host, 'linux', 'stale_runner_file.cc')).writeAsStringSync('// gone from the engine\n');
    final r = await gen.generate(fx.projectDir.path, [await fx.plugin()]);
    expect(r.changed, isTrue);
    expect(File(p.join(host, 'lib', 'main.dart')).readAsStringSync(), contains('runLuminaEditor('));
    expect(File(p.join(host, EditorHostGeneratorService.stampFileName)).readAsStringSync(), '{"hash":"abc"}');
    expect(copied.readAsStringSync(), '// the project copy, edited\n');
    expect(tool.existsSync(), isTrue);
    expect(File(p.join(host, 'linux', 'stale_runner_file.cc')).existsSync(), isFalse, reason: 'runner files the engine dropped go');
    expect(Directory('$host.old').existsSync(), isFalse);
    expect(Directory('$host.tmp').existsSync(), isFalse);
  });

  test('an old-layout host (absolute engine path) migrates: relative pubspec, its resolution and build dropped, stamp kept', () async {
    final host = Directory(p.join(fx.projectDir.path, '.lumina', 'editor'))..createSync(recursive: true);
    File(p.join(host.path, 'pubspec.yaml'))
        .writeAsStringSync("name: host_game_editor\ndependencies:\n  lumina_ui:\n    path: '${slash(p.join(engineRoot, 'lumina_ui'))}'\n");
    File(p.join(host.path, 'pubspec.lock')).writeAsStringSync('packages: {}\n');
    File(p.join(host.path, '.dart_tool', 'package_config.json')).createSync(recursive: true);
    File(p.join(host.path, 'build', 'windows', 'x.obj')).createSync(recursive: true);
    File(p.join(host.path, EditorHostGeneratorService.stampFileName)).writeAsStringSync('{"hash":"abc"}');
    expect(EditorHostGeneratorService.isOldLayout(host.path), isTrue);

    final r = await EditorHostGeneratorService(engineRoot: engineRoot, platform: 'linux').generate(fx.projectDir.path, const []);
    expect(r.changed, isTrue);
    expect(File(p.join(host.path, 'pubspec.yaml')).readAsStringSync(), contains('  lumina_ui:\n    path: lumina_ui\n'));
    expect(EditorHostGeneratorService.isOldLayout(host.path), isFalse);
    for (final gone in ['.dart_tool', 'build']) {
      expect(FileSystemEntity.typeSync(p.join(host.path, gone)), FileSystemEntityType.notFound, reason: gone);
    }
    expect(File(p.join(host.path, 'pubspec.lock')).readAsStringSync(), isNot('packages: {}\n'),
        reason: "the old resolution is dropped; the engine lock's versions seed the new one");
    expect(File(p.join(host.path, EditorHostGeneratorService.stampFileName)).readAsStringSync(), '{"hash":"abc"}');
  });

  test('the runner comes from the project copy when it has one', () async {
    final host = p.join(fx.projectDir.path, '.lumina', 'editor');
    File(p.join(host, 'lumina_ui', 'linux', 'CMakeLists.txt'))
      ..createSync(recursive: true)
      ..writeAsStringSync('set(BINARY_NAME "lumina_ui") # from the copy\n');
    await EditorHostGeneratorService(engineRoot: engineRoot, platform: 'linux').generate(fx.projectDir.path, const []);
    expect(File(p.join(host, 'linux', 'CMakeLists.txt')).readAsStringSync(), 'set(BINARY_NAME "host_game_editor") # from the copy\n');
  });

  test('the generated host analyzes with 0 errors', () async {
    // An isolated plugin: the registrar's kPluginProcesses names its process
    // part and the main passes it to runLuminaEditor.
    await fx.isolate();
    final gen = EditorHostGeneratorService(engineRoot: engineRoot);
    await gen.generate(fx.projectDir.path, [await fx.plugin()]);
    final registrar = File(p.join(fx.projectDir.path, '.lumina', 'editor', 'lib', 'plugin_registrar.dart')).readAsStringSync();
    expect(registrar, contains("  'a_plugin': () => a_plugin_plugin.AProcess(),\n"));
    final host = p.join(fx.projectDir.path, '.lumina', 'editor');
    // The copy's layout, as links into the engine (copying ~650 MB is the
    // build pipeline's job, covered by editor_source_vendor_service_test).
    final sources = EditorSourceVendorService(engineRoot: engineRoot).packageSources();
    for (final rel in [...EditorSourceVendorService(engineRoot: engineRoot).copyRoots(), 'filament']) {
      final link = Link(p.join(host, rel));
      link.parent.createSync(recursive: true);
      link.createSync(sources[rel] ?? p.join(engineRoot, rel));
    }
    final flutter = Platform.isWindows ? 'flutter.bat' : 'flutter';
    ProcessResult get;
    try {
      get = await Process.run(flutter, ['pub', 'get', '--offline'], workingDirectory: host, runInShell: Platform.isWindows);
    } on ProcessException {
      markTestSkipped('flutter is not on PATH');
      return;
    }
    if (get.exitCode != 0) {
      get = await Process.run(flutter, ['pub', 'get'], workingDirectory: host, runInShell: Platform.isWindows);
    }
    expect(get.exitCode, 0, reason: '${get.stdout}\n${get.stderr}');
    final analyze = await Process.run(Platform.isWindows ? 'dart.bat' : 'dart', ['analyze', '--no-fatal-warnings', 'lib'],
        workingDirectory: host, runInShell: Platform.isWindows);
    expect(analyze.exitCode, 0, reason: '${analyze.stdout}\n${analyze.stderr}');
  }, timeout: const Timeout(Duration(minutes: 5)));

  test('propagates dependency_overrides from plugin pubspec_overrides.yaml and workspace', () async {
    final pluginDir = fx.pluginDir;
    final extraPkg = Directory(p.join(fx.temp.path, 'custom_tool'))..createSync();
    File(p.join(extraPkg.path, 'pubspec.yaml')).writeAsStringSync('name: custom_tool\nversion: 0.0.1\n');
    File(p.join(pluginDir.path, 'pubspec_overrides.yaml')).writeAsStringSync('''
dependency_overrides:
  custom_tool:
    path: ${p.relative(extraPkg.path, from: pluginDir.path).replaceAll(r'\', '/')}
''');

    final gen = EditorHostGeneratorService(engineRoot: engineRoot, platform: 'linux');
    final plugin = await fx.plugin();
    await gen.generate(fx.projectDir.path, [plugin]);

    final host = Directory(p.join(fx.projectDir.path, '.lumina', 'editor'));
    final pubspec = File(p.join(host.path, 'pubspec.yaml')).readAsStringSync();
    expect(pubspec, contains("  custom_tool:\n    path: '${slash(extraPkg.path)}'"));
  });

  test('a plugin compiled from its folder is also an override, so another plugin depending on it from git resolves', () async {
    final gen = EditorHostGeneratorService(engineRoot: engineRoot, platform: 'linux');
    final plugin = await fx.plugin();
    await gen.generate(fx.projectDir.path, [plugin]);

    final pubspec = loadYaml(File(p.join(fx.projectDir.path, '.lumina', 'editor', 'pubspec.yaml')).readAsStringSync()) as YamlMap;
    final dir = slash(p.absolute(fx.pluginDir.path));
    expect((pubspec['dependencies'] as YamlMap)['a_plugin'], {'path': dir});
    expect((pubspec['dependency_overrides'] as YamlMap)['a_plugin'], {'path': dir});
  });

  // The engine's versions, not pub.dev's newest: a temp engine whose lock
  // pins yaml 3.1.3 while 3.1.4 is published.
  group('the host resolves the engine lock', () {
    late Directory temp;
    late String engine;
    late String projectDir;
    late String host;

    String lockPinning(String version, String sha256, {String extra = ''}) => '''
# Generated by pub
packages:
$extra  yaml:
    dependency: transitive
    description:
      name: yaml
      sha256: "$sha256"
      url: "https://pub.dev"
    source: hosted
    version: "$version"
sdks:
  dart: ">=3.12.0 <4.0.0"
''';
    const old = ('3.1.3', 'b9da305ac7c39faa3f030eccd175340f968459dae4af175130b3fc47e40d76ce');
    const newer = ('3.1.4', 'f67cdd8e07d3c6329146aaef1ba043542b3134c12489f553ca9a7435d1068aea');

    String? lockedVersion(String lockPath, String name) {
      final yaml = loadYaml(File(lockPath).readAsStringSync()) as YamlMap;
      final entry = (yaml['packages'] as YamlMap?)?[name];
      return entry is YamlMap ? '${entry['version']}' : null;
    }

    setUp(() {
      temp = Directory.systemTemp.createTempSync('host_lock_');
      engine = p.join(temp.path, 'engine');
      File(p.join(engine, 'lumina_ui', 'pubspec.yaml'))
        ..createSync(recursive: true)
        ..writeAsStringSync('''
name: lumina_ui
publish_to: none
environment:
  sdk: ^3.12.0
dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.0
''');
      Directory(p.join(engine, 'lumina_ui', 'lib')).createSync();
      Directory(p.join(engine, 'filament')).createSync();
      File(p.join(engine, 'pubspec.lock')).writeAsStringSync(lockPinning(old.$1, old.$2));
      projectDir = p.join(temp.path, 'Game');
      Directory(projectDir).createSync();
      host = EditorHostGeneratorService.hostDirOf(projectDir);
    });
    tearDown(() {
      try {
        temp.deleteSync(recursive: true);
      } on FileSystemException {
        // A Windows handle still open; the system temp folder keeps it.
      }
    });

    test('flutter pub get in a fresh host keeps the version the engine lock pins', () async {
      await EditorSourceVendorService(engineRoot: engine).vendor(host);
      await EditorHostGeneratorService(engineRoot: engine, platform: 'linux').generate(projectDir, const []);
      final flutter = Platform.isWindows ? 'flutter.bat' : 'flutter';
      ProcessResult get;
      try {
        get = await Process.run(flutter, ['pub', 'get', '--offline'], workingDirectory: host, runInShell: Platform.isWindows);
      } on ProcessException {
        markTestSkipped('flutter is not on PATH');
        return;
      }
      if (get.exitCode != 0) {
        get = await Process.run(flutter, ['pub', 'get'], workingDirectory: host, runInShell: Platform.isWindows);
      }
      expect(get.exitCode, 0, reason: '${get.stdout}\n${get.stderr}');
      expect(lockedVersion(p.join(host, 'pubspec.lock'), 'yaml'), old.$1, reason: 'not the newest yaml (${newer.$1})');
      expect(EditorHostGeneratorService(engineRoot: engine).movedFromEngineLock(host), isEmpty);
    }, timeout: const Timeout(Duration(minutes: 3)));

    test("the project's copy keeps the lock it was copied with; a sync takes the engine's new one", () async {
      await EditorSourceVendorService(engineRoot: engine).vendor(host);
      File(p.join(engine, 'pubspec.lock')).writeAsStringSync(lockPinning(newer.$1, newer.$2));
      final gen = EditorHostGeneratorService(engineRoot: engine, platform: 'linux');
      await gen.generate(projectDir, const []);
      expect(lockedVersion(p.join(host, 'pubspec.lock'), 'yaml'), old.$1, reason: 'the copied source was built with ${old.$1}');

      await EditorSourceVendorService(engineRoot: engine).sync(host);
      await gen.generate(projectDir, const []);
      expect(lockedVersion(p.join(host, 'pubspec.lock'), 'yaml'), newer.$1);
    });

    test('a host lock that moved an engine package is put back; packages only the host has stay', () async {
      await EditorSourceVendorService(engineRoot: engine).vendor(host);
      final gen = EditorHostGeneratorService(engineRoot: engine, platform: 'linux');
      await gen.generate(projectDir, const []);
      // What a resolution against pub.dev left behind: the newest yaml, and
      // a package only a code plugin brought.
      File(p.join(host, 'pubspec.lock')).writeAsStringSync(lockPinning(newer.$1, newer.$2, extra: '''
  args:
    dependency: transitive
    description:
      name: args
      sha256: "d0481093c50b1da8910eb0bb301626d4d8eb7284aa739614d2b394ee09e3ea04"
      url: "https://pub.dev"
    source: hosted
    version: "2.7.0"
'''));
      expect(gen.movedFromEngineLock(host), ['yaml ${old.$1} → ${newer.$1}']);

      final r = await gen.generate(projectDir, const []);
      expect(r.changed, isTrue);
      final lock = p.join(host, 'pubspec.lock');
      expect(lockedVersion(lock, 'yaml'), old.$1);
      expect(lockedVersion(lock, 'args'), '2.7.0');
      expect(gen.movedFromEngineLock(host), isEmpty);
      final bytes = File(lock).readAsBytesSync();
      expect((await gen.generate(projectDir, const [])).changed, isFalse);
      expect(File(lock).readAsBytesSync(), bytes, reason: 'an unchanged host keeps its lock');
    });
  });
}
