part of '../blueprint_function_library.dart';

/// [LuminaBlueprintFunctionLibrary.callShapes]: pawn, transform, UI and
/// gameplay nodes.
final Map<String, LuminaBlueprintCallShape> _coreCallShapes = <String, LuminaBlueprintCallShape>{
  'print_string': LuminaBlueprintCallShape('printString', [
    'in_string',
    'print_to_screen',
    'print_to_log',
    'text_color',
    'duration',
    'key',
  ], self: true),
  'add_movement_input': LuminaBlueprintCallShape('addMovementInput', [
    'world_dir',
    'scale_val',
    'force',
  ], self: true),
  'add_controller_yaw_input': LuminaBlueprintCallShape(
    'addControllerYawInput',
    ['val'],
    self: true,
  ),
  'add_controller_pitch_input': LuminaBlueprintCallShape(
    'addControllerPitchInput',
    ['val'],
    self: true,
  ),
  'jump': LuminaBlueprintCallShape('jump', [], self: true),
  'set_free_look': LuminaBlueprintCallShape('setFreeLook', ['enabled'], self: true),
  'is_free_looking': LuminaBlueprintCallShape('isFreeLooking', [], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'stop_jumping': LuminaBlueprintCallShape('stopJumping', [], self: true),
  'set_actor_location': LuminaBlueprintCallShape(
    'setActorLocation',
    ['new_location', 'sweep'],
    self: true,
    outputs: LuminaBlueprintFunctionLibrary._r,
  ),
  'get_control_rotation': LuminaBlueprintCallShape(
    'getControlRotation',
    [],
    self: true,
    outputs: LuminaBlueprintFunctionLibrary._r,
  ),
  'get_velocity': LuminaBlueprintCallShape(
    'getVelocity',
    [],
    self: true,
    outputs: LuminaBlueprintFunctionLibrary._r,
  ),
  'is_falling': LuminaBlueprintCallShape(
    'isFalling',
    [],
    self: true,
    outputs: LuminaBlueprintFunctionLibrary._r,
  ),
  'get_actor_location': LuminaBlueprintCallShape(
    'getActorLocation',
    [],
    self: true,
    outputs: LuminaBlueprintFunctionLibrary._r,
  ),
  'get_actor_rotation': LuminaBlueprintCallShape(
    'getActorRotation',
    [],
    self: true,
    outputs: LuminaBlueprintFunctionLibrary._r,
  ),
  'make_vector2d': LuminaBlueprintCallShape('makeVector2D', [
    'x',
    'y',
  ], outputs: LuminaBlueprintFunctionLibrary._r),
  'break_vector2d': LuminaBlueprintCallShape(
    'breakVector2D',
    ['in_vec'],
    outputs: ['x', 'y'],
  ),
  'make_vector': LuminaBlueprintCallShape('makeVector', [
    'x',
    'y',
    'z',
  ], outputs: LuminaBlueprintFunctionLibrary._r),
  'break_vector': LuminaBlueprintCallShape(
    'breakVector',
    ['in_vec'],
    outputs: ['x', 'y', 'z'],
  ),
  'make_rotator': LuminaBlueprintCallShape('makeRotator', [
    'x',
    'y',
    'z',
  ], outputs: LuminaBlueprintFunctionLibrary._r),
  'break_rotator': LuminaBlueprintCallShape(
    'breakRotator',
    ['in_rot'],
    outputs: ['x', 'y', 'z'],
  ),
  'get_forward_vector': LuminaBlueprintCallShape('getForwardVector', [
    'in_rot',
  ], outputs: LuminaBlueprintFunctionLibrary._r),
  'get_right_vector': LuminaBlueprintCallShape('getRightVector', [
    'in_rot',
  ], outputs: LuminaBlueprintFunctionLibrary._r),
  'calculate_direction': LuminaBlueprintCallShape('calculateDirection', [
    'velocity',
    'base_rotation',
  ], outputs: LuminaBlueprintFunctionLibrary._r),
  'vector_length': LuminaBlueprintCallShape('vectorLength', [
    'in_vec',
  ], outputs: LuminaBlueprintFunctionLibrary._r),
  'vector_length_xy': LuminaBlueprintCallShape('vectorLengthXY', [
    'in_vec',
  ], outputs: LuminaBlueprintFunctionLibrary._r),
  'vector_scale': LuminaBlueprintCallShape('vectorScale', [
    'a',
    'b',
  ], outputs: LuminaBlueprintFunctionLibrary._r),
  'vector_add': LuminaBlueprintCallShape('vectorAdd', [
    'a',
    'b',
  ], outputs: LuminaBlueprintFunctionLibrary._r),
  'float_add': LuminaBlueprintCallShape('floatAdd', ['a', 'b'], outputs: LuminaBlueprintFunctionLibrary._r),
  'float_subtract': LuminaBlueprintCallShape('floatSubtract', [
    'a',
    'b',
  ], outputs: LuminaBlueprintFunctionLibrary._r),
  'float_multiply': LuminaBlueprintCallShape('floatMultiply', [
    'a',
    'b',
  ], outputs: LuminaBlueprintFunctionLibrary._r),
  'float_divide': LuminaBlueprintCallShape('floatDivide', [
    'a',
    'b',
  ], outputs: LuminaBlueprintFunctionLibrary._r),
  'float_clamp': LuminaBlueprintCallShape('floatClamp', [
    'value',
    'min',
    'max',
  ], outputs: LuminaBlueprintFunctionLibrary._r),
  'float_greater': LuminaBlueprintCallShape('floatGreater', [
    'a',
    'b',
  ], outputs: LuminaBlueprintFunctionLibrary._r),
  'float_less': LuminaBlueprintCallShape('floatLess', [
    'a',
    'b',
  ], outputs: LuminaBlueprintFunctionLibrary._r),
  'float_equal': LuminaBlueprintCallShape('floatEqual', [
    'a',
    'b',
  ], outputs: LuminaBlueprintFunctionLibrary._r),
  'bool_and': LuminaBlueprintCallShape('boolAnd', ['a', 'b'], outputs: LuminaBlueprintFunctionLibrary._r),
  'bool_or': LuminaBlueprintCallShape('boolOr', ['a', 'b'], outputs: LuminaBlueprintFunctionLibrary._r),
  'bool_not': LuminaBlueprintCallShape('boolNot', ['a'], outputs: LuminaBlueprintFunctionLibrary._r),
  'create_widget': LuminaBlueprintCallShape(
    'createWidget',
    ['class', 'owning_player'],
    self: true,
    outputs: LuminaBlueprintFunctionLibrary._r,
  ),
  'add_to_viewport': LuminaBlueprintCallShape('addToViewport', [
    'target',
    'z_order',
  ], self: true),
  'remove_from_parent': LuminaBlueprintCallShape('removeFromParent', [
    'target',
  ], self: true),
  'set_widget_visibility': LuminaBlueprintCallShape('setWidgetVisibility', [
    'target',
    'in_visibility',
  ], self: true),
  'is_in_viewport': LuminaBlueprintCallShape('isInViewport', [
    'target',
  ], outputs: LuminaBlueprintFunctionLibrary._r),
  'get_owning_player': LuminaBlueprintCallShape('getOwningPlayer', [
    'target',
  ], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_widget_text': LuminaBlueprintCallShape('setWidgetText', [
    'target',
    'in_text',
  ], self: true),
  'set_widget_percent': LuminaBlueprintCallShape('setWidgetPercent', [
    'target',
    'in_percent',
  ], self: true),
  'get_player_controller': LuminaBlueprintCallShape(
    'getPlayerController',
    ['player_index'],
    self: true,
    outputs: LuminaBlueprintFunctionLibrary._r,
  ),
  'get_player_pawn': LuminaBlueprintCallShape(
    'getPlayerPawn',
    ['player_index'],
    self: true,
    outputs: LuminaBlueprintFunctionLibrary._r,
  ),
  'get_player_character': LuminaBlueprintCallShape(
    'getPlayerCharacter',
    ['player_index'],
    self: true,
    outputs: LuminaBlueprintFunctionLibrary._r,
  ),
  'set_show_mouse_cursor': LuminaBlueprintCallShape('setShowMouseCursor', [
    'target',
    'show_mouse_cursor',
  ], self: true),
  'set_input_mode_game_and_ui': LuminaBlueprintCallShape(
    'setInputModeGameAndUI',
    ['target', 'in_widget_to_focus', 'lock_mouse_to_viewport'],
    self: true,
  ),
  'set_input_mode_game_only': LuminaBlueprintCallShape(
    'setInputModeGameOnly',
    ['target'],
    self: true,
  ),
  'set_input_mode_ui_only': LuminaBlueprintCallShape('setInputModeUIOnly', [
    'target',
    'in_widget_to_focus',
    'lock_mouse_to_viewport',
  ], self: true),
};

/// Objects, widget elements, components, physics.
final Map<String, LuminaBlueprintCallShape> _objectCallShapes = <String, LuminaBlueprintCallShape>{
  // --- objects, widget elements, components -----------------
  'is_valid': LuminaBlueprintCallShape('isValid', ['input_object'], outputs: LuminaBlueprintFunctionLibrary._r),
  'get_class_name': LuminaBlueprintCallShape('getClassName', ['object'], outputs: LuminaBlueprintFunctionLibrary._r),
  'is_a': LuminaBlueprintCallShape('isA', ['object', 'class'], outputs: LuminaBlueprintFunctionLibrary._r),
  'get_display_name': LuminaBlueprintCallShape('getDisplayName', ['object'], outputs: LuminaBlueprintFunctionLibrary._r),
  'get_widget_element': LuminaBlueprintCallShape('getWidgetElement', ['target', 'element'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_element_visibility': LuminaBlueprintCallShape('setElementVisibility', ['target', 'in_visibility'], self: true),
  'get_element_visibility': LuminaBlueprintCallShape('getElementVisibility', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'is_element_visible': LuminaBlueprintCallShape('isElementVisible', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_element_is_enabled': LuminaBlueprintCallShape('setElementIsEnabled', ['target', 'in_is_enabled'], self: true),
  'get_element_is_enabled': LuminaBlueprintCallShape('getElementIsEnabled', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_element_render_opacity': LuminaBlueprintCallShape('setElementRenderOpacity', ['target', 'in_opacity'], self: true),
  'set_element_text': LuminaBlueprintCallShape('setElementText', ['target', 'in_text'], self: true),
  'get_element_text': LuminaBlueprintCallShape('getElementText', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_element_color': LuminaBlueprintCallShape('setElementColor', ['target', 'in_color'], self: true),
  'set_element_font_size': LuminaBlueprintCallShape('setElementFontSize', ['target', 'in_size'], self: true),
  'set_element_shadow_enabled': LuminaBlueprintCallShape('setElementShadowEnabled', ['target', 'in_enabled'], self: true),
  'set_element_shadow_color': LuminaBlueprintCallShape('setElementShadowColor', ['target', 'in_color'], self: true),
  'set_element_shadow_offset': LuminaBlueprintCallShape('setElementShadowOffset', ['target', 'in_offset'], self: true),
  'set_element_outline': LuminaBlueprintCallShape('setElementOutline', ['target', 'in_size', 'in_color'], self: true),
  'set_element_percent': LuminaBlueprintCallShape('setElementPercent', ['target', 'in_percent'], self: true),
  'get_element_percent': LuminaBlueprintCallShape('getElementPercent', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_element_fill_color': LuminaBlueprintCallShape('setElementFillColor', ['target', 'in_color'], self: true),
  'set_element_brush_from_texture':
      LuminaBlueprintCallShape('setElementBrushFromTexture', ['target', 'texture'], self: true),
  'set_element_image_color': LuminaBlueprintCallShape('setElementImageColor', ['target', 'in_color'], self: true),
  'set_element_label': LuminaBlueprintCallShape('setElementLabel', ['target', 'in_label'], self: true),
  'set_element_slider_value': LuminaBlueprintCallShape('setElementSliderValue', ['target', 'in_value'], self: true),
  'get_element_slider_value': LuminaBlueprintCallShape('getElementSliderValue', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_element_is_checked': LuminaBlueprintCallShape('setElementIsChecked', ['target', 'in_is_checked'], self: true),
  'get_element_is_checked': LuminaBlueprintCallShape('getElementIsChecked', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_element_editable_text': LuminaBlueprintCallShape('setElementEditableText', ['target', 'in_text'], self: true),
  'get_element_editable_text': LuminaBlueprintCallShape('getElementEditableText', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_element_hint_text': LuminaBlueprintCallShape('setElementHintText', ['target', 'in_hint_text'], self: true),
  'set_element_selected_option': LuminaBlueprintCallShape('setElementSelectedOption', ['target', 'option'], self: true),
  'get_element_selected_option': LuminaBlueprintCallShape('getElementSelectedOption', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'add_element_option': LuminaBlueprintCallShape('addElementOption', ['target', 'option'], self: true),
  'clear_element_options': LuminaBlueprintCallShape('clearElementOptions', ['target'], self: true),
  'set_element_active_index': LuminaBlueprintCallShape('setElementActiveIndex', ['target', 'index'], self: true),
  'get_element_active_index': LuminaBlueprintCallShape('getElementActiveIndex', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_element_background_color': LuminaBlueprintCallShape('setElementBackgroundColor', ['target', 'in_color'], self: true),
  'set_element_border_color': LuminaBlueprintCallShape('setElementBorderColor', ['target', 'in_color'], self: true),
  'set_element_corner_radius': LuminaBlueprintCallShape('setElementCornerRadius', ['target', 'in_radius'], self: true),
  'set_element_padding': LuminaBlueprintCallShape('setElementPadding', ['target', 'left', 'top', 'right', 'bottom'], self: true),
  'get_component': LuminaBlueprintCallShape('getComponent', ['component'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_component_by_class': LuminaBlueprintCallShape('getComponentByClass', ['class'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'add_component': LuminaBlueprintCallShape('addComponent', ['class', 'name'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_relative_location': LuminaBlueprintCallShape('setRelativeLocation', ['target', 'new_location']),
  'set_relative_rotation': LuminaBlueprintCallShape('setRelativeRotation', ['target', 'new_rotation']),
  'set_relative_scale': LuminaBlueprintCallShape('setRelativeScale', ['target', 'new_scale']),
  'get_relative_location': LuminaBlueprintCallShape('getRelativeLocation', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'get_relative_rotation': LuminaBlueprintCallShape('getRelativeRotation', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'get_relative_scale': LuminaBlueprintCallShape('getRelativeScale', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_world_location': LuminaBlueprintCallShape('setWorldLocation', ['target', 'new_location']),
  'set_world_rotation': LuminaBlueprintCallShape('setWorldRotation', ['target', 'new_rotation']),
  'get_world_location': LuminaBlueprintCallShape('getWorldLocation', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'get_world_rotation': LuminaBlueprintCallShape('getWorldRotation', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'attach_to_component': LuminaBlueprintCallShape('attachToComponent', ['target', 'parent', 'socket_name']),
  'set_component_visibility': LuminaBlueprintCallShape('setComponentVisibility', ['target', 'new_visibility']),
  'set_hidden_in_game': LuminaBlueprintCallShape('setHiddenInGame', ['target', 'new_hidden']),
  'get_socket_location': LuminaBlueprintCallShape('getSocketLocation', ['target', 'in_socket_name'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_target_arm_length': LuminaBlueprintCallShape('setTargetArmLength', ['target', 'target_arm_length']),
  'get_target_arm_length': LuminaBlueprintCallShape('getTargetArmLength', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_camera_lag_enabled': LuminaBlueprintCallShape('setCameraLagEnabled', ['target', 'enabled']),
  'set_camera_lag_speed': LuminaBlueprintCallShape('setCameraLagSpeed', ['target', 'speed']),
  'set_socket_offset': LuminaBlueprintCallShape('setSocketOffset', ['target', 'offset']),
  'set_field_of_view': LuminaBlueprintCallShape('setFieldOfView', ['target', 'in_field_of_view']),
  'get_field_of_view': LuminaBlueprintCallShape('getFieldOfView', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_camera_active': LuminaBlueprintCallShape('setCameraActive', ['target', 'active']),
  'is_camera_active': LuminaBlueprintCallShape('isCameraActive', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'play_animation': LuminaBlueprintCallShape('playAnimation', ['target', 'clip', 'loop']),
  'stop_animation': LuminaBlueprintCallShape('stopAnimation', ['target']),
  'set_anim_class': LuminaBlueprintCallShape('setAnimClass', ['target', 'anim_class'], self: true),
  'set_play_rate': LuminaBlueprintCallShape('setPlayRate', ['target', 'rate']),
  'get_current_clip': LuminaBlueprintCallShape('getCurrentClip', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_static_mesh': LuminaBlueprintCallShape('setStaticMesh', ['target', 'new_mesh'], self: true),
  'set_material': LuminaBlueprintCallShape('setMaterial', ['target', 'element_index', 'material'], self: true),
  'set_collision_enabled': LuminaBlueprintCallShape('setCollisionEnabled', ['target', 'new_type']),
  'set_collision_layer': LuminaBlueprintCallShape('setCollisionLayer', ['target', 'layer']),
  'set_collision_preset': LuminaBlueprintCallShape('setCollisionPreset', ['target', 'preset']),
  'get_collision_preset': LuminaBlueprintCallShape('getCollisionPreset', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_collision_response_to_channel': LuminaBlueprintCallShape('setCollisionResponseToChannel', ['target', 'channel', 'response']),
  'set_collision_response_to_all_channels': LuminaBlueprintCallShape('setCollisionResponseToAllChannels', ['target', 'response']),
  'get_collision_response_to_channel': LuminaBlueprintCallShape('getCollisionResponseToChannel', ['target', 'channel'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_collision_object_type': LuminaBlueprintCallShape('setCollisionObjectType', ['target', 'object_type']),
  'get_collision_object_type': LuminaBlueprintCallShape('getCollisionObjectType', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_generate_overlap_events': LuminaBlueprintCallShape('setGenerateOverlapEvents', ['target', 'generate']),
  'set_box_extent': LuminaBlueprintCallShape('setBoxExtent', ['target', 'box_extent']),
  'get_box_extent': LuminaBlueprintCallShape('getBoxExtent', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_sphere_radius': LuminaBlueprintCallShape('setSphereRadius', ['target', 'radius']),
  'get_sphere_radius': LuminaBlueprintCallShape('getSphereRadius', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_capsule_size': LuminaBlueprintCallShape('setCapsuleSize', ['target', 'radius', 'half_height']),
  'get_scaled_capsule_radius': LuminaBlueprintCallShape('getScaledCapsuleRadius', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'get_scaled_capsule_half_height': LuminaBlueprintCallShape('getScaledCapsuleHalfHeight', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'get_overlapping_actors': LuminaBlueprintCallShape('getOverlappingActors', ['target', 'class'], outputs: LuminaBlueprintFunctionLibrary._r),
  'get_overlapping_components': LuminaBlueprintCallShape('getOverlappingComponents', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'is_overlapping_actor': LuminaBlueprintCallShape('isOverlappingActor', ['target', 'other'], outputs: LuminaBlueprintFunctionLibrary._r),
  // physics
  'set_simulate_physics': LuminaBlueprintCallShape('setSimulatePhysics', ['target', 'simulate']),
  'is_simulating_physics': LuminaBlueprintCallShape('isSimulatingPhysics', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'add_impulse': LuminaBlueprintCallShape('addImpulse', ['target', 'impulse', 'bone_name', 'vel_change']),
  'add_impulse_at_location': LuminaBlueprintCallShape('addImpulseAtLocation', ['target', 'impulse', 'location', 'bone_name']),
  'add_force': LuminaBlueprintCallShape('addForce', ['target', 'force', 'bone_name', 'accel_change']),
  'add_force_at_location': LuminaBlueprintCallShape('addForceAtLocation', ['target', 'force', 'location', 'bone_name']),
  'add_torque': LuminaBlueprintCallShape('addTorqueInRadians', ['target', 'torque', 'bone_name', 'accel_change']),
  'add_angular_impulse': LuminaBlueprintCallShape('addAngularImpulseInRadians', ['target', 'impulse', 'bone_name', 'vel_change']),
  'set_physics_linear_velocity':
      LuminaBlueprintCallShape('setPhysicsLinearVelocity', ['target', 'new_vel', 'add_to_current', 'bone_name']),
  'get_physics_linear_velocity': LuminaBlueprintCallShape('getPhysicsLinearVelocity', ['target', 'bone_name'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_physics_angular_velocity':
      LuminaBlueprintCallShape('setPhysicsAngularVelocityInDegrees', ['target', 'new_ang_vel', 'add_to_current', 'bone_name']),
  'get_physics_angular_velocity':
      LuminaBlueprintCallShape('getPhysicsAngularVelocityInDegrees', ['target', 'bone_name'], outputs: LuminaBlueprintFunctionLibrary._r),
  'get_mass': LuminaBlueprintCallShape('getMass', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_mass_override_in_kg': LuminaBlueprintCallShape('setMassOverrideInKg', ['target', 'bone_name', 'mass_in_kg', 'override_mass']),
  'set_enable_gravity': LuminaBlueprintCallShape('setEnableGravity', ['target', 'gravity_enabled']),
  'set_linear_damping': LuminaBlueprintCallShape('setLinearDamping', ['target', 'in_damping']),
  'set_angular_damping': LuminaBlueprintCallShape('setAngularDamping', ['target', 'in_damping']),
  'wake_rigid_body': LuminaBlueprintCallShape('wakeRigidBody', ['target', 'bone_name']),
  'put_rigid_body_to_sleep': LuminaBlueprintCallShape('putRigidBodyToSleep', ['target', 'bone_name']),
  'is_any_rigid_body_awake': LuminaBlueprintCallShape('isAnyRigidBodyAwake', ['target'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_max_walk_speed': LuminaBlueprintCallShape('setMaxWalkSpeed', ['target', 'max_walk_speed'], self: true),
  'get_max_walk_speed': LuminaBlueprintCallShape('getMaxWalkSpeed', ['target'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_jump_z_velocity': LuminaBlueprintCallShape('setJumpZVelocity', ['target', 'jump_z_velocity'], self: true),
  'get_jump_z_velocity': LuminaBlueprintCallShape('getJumpZVelocity', ['target'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_gravity_scale': LuminaBlueprintCallShape('setGravityScale', ['target', 'gravity_scale'], self: true),
  'get_gravity_scale': LuminaBlueprintCallShape('getGravityScale', ['target'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_air_control': LuminaBlueprintCallShape('setAirControl', ['target', 'air_control'], self: true),
  'get_air_control': LuminaBlueprintCallShape('getAirControl', ['target'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_movement_mode': LuminaBlueprintCallShape('setMovementMode', ['target', 'new_movement_mode'], self: true),
  'get_movement_mode': LuminaBlueprintCallShape('getMovementMode', ['target'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'crouch': LuminaBlueprintCallShape('crouch', ['target'], self: true),
  'un_crouch': LuminaBlueprintCallShape('unCrouch', ['target'], self: true),
  'is_crouched': LuminaBlueprintCallShape('isCrouched', ['target'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'launch_character':
      LuminaBlueprintCallShape('launchCharacter', ['target', 'launch_velocity', 'xy_override', 'z_override'], self: true),
  'stop_movement_immediately': LuminaBlueprintCallShape('stopMovementImmediately', ['target'], self: true),
};

/// Math, string, array, struct.
final Map<String, LuminaBlueprintCallShape> _mathCallShapes = <String, LuminaBlueprintCallShape>{
  // --- math, string, array, struct -------------------------
  for (final (id, method, args) in const [
    ('float_abs', 'floatAbs', ['a']),
    ('float_min', 'floatMin', ['a', 'b']),
    ('float_max', 'floatMax', ['a', 'b']),
    ('float_lerp', 'floatLerp', ['a', 'b', 'alpha']),
    ('float_interp_to', 'floatInterpTo', ['current', 'target', 'delta_time', 'interp_speed']),
    ('float_sqrt', 'floatSqrt', ['a']),
    ('float_power', 'floatPower', ['a', 'b']),
    ('float_modulo', 'floatModulo', ['a', 'b']),
    ('float_sign', 'floatSign', ['a']),
    ('float_map_range_clamped', 'floatMapRangeClamped', ['value', 'in_range_a', 'in_range_b', 'out_range_a', 'out_range_b']),
    ('float_nearly_equal', 'floatNearlyEqual', ['a', 'b', 'error_tolerance']),
    ('float_sin', 'floatSin', ['a']),
    ('float_cos', 'floatCos', ['a']),
    ('float_tan', 'floatTan', ['a']),
    ('float_asin', 'floatAsin', ['a']),
    ('float_acos', 'floatAcos', ['a']),
    ('float_atan', 'floatAtan', ['a']),
    ('float_atan2', 'floatAtan2', ['y', 'x']),
    ('degrees_to_radians', 'degreesToRadians', ['a']),
    ('radians_to_degrees', 'radiansToDegrees', ['a']),
    ('float_greater_equal', 'floatGreaterEqual', ['a', 'b']),
    ('float_less_equal', 'floatLessEqual', ['a', 'b']),
    ('float_not_equal', 'floatNotEqual', ['a', 'b']),
    ('random_float_in_range', 'randomFloatInRange', ['min', 'max']),
    ('random_bool_with_weight', 'randomBoolWithWeight', ['weight']),
    ('select_float', 'selectFloat', ['a', 'b', 'pick_a']),
    ('round', 'round', ['a']),
    ('truncate', 'truncate', ['a']),
    ('ceil', 'ceil', ['a']),
    ('floor', 'floor', ['a']),
    ('int_to_float', 'intToFloat', ['a']),
    ('int_add', 'intAdd', ['a', 'b']),
    ('int_subtract', 'intSubtract', ['a', 'b']),
    ('int_multiply', 'intMultiply', ['a', 'b']),
    ('int_divide', 'intDivide', ['a', 'b']),
    ('int_modulo', 'intModulo', ['a', 'b']),
    ('int_clamp', 'intClamp', ['value', 'min', 'max']),
    ('int_abs', 'intAbs', ['a']),
    ('int_min', 'intMin', ['a', 'b']),
    ('int_max', 'intMax', ['a', 'b']),
    ('int_greater', 'intGreater', ['a', 'b']),
    ('int_less', 'intLess', ['a', 'b']),
    ('int_equal', 'intEqual', ['a', 'b']),
    ('int_not_equal', 'intNotEqual', ['a', 'b']),
    ('int_greater_equal', 'intGreaterEqual', ['a', 'b']),
    ('int_less_equal', 'intLessEqual', ['a', 'b']),
    ('random_integer_in_range', 'randomIntegerInRange', ['min', 'max']),
    ('int_increment', 'intIncrement', ['a']),
    ('select_int', 'selectInt', ['a', 'b', 'pick_a']),
    ('vector_normalize', 'vectorNormalize', ['a']),
    ('vector_dot', 'vectorDot', ['a', 'b']),
    ('vector_cross', 'vectorCross', ['a', 'b']),
    ('vector_distance', 'vectorDistance', ['a', 'b']),
    ('vector_distance_2d', 'vectorDistance2D', ['a', 'b']),
    ('vector_lerp', 'vectorLerp', ['a', 'b', 'alpha']),
    ('vector_interp_to', 'vectorInterpTo', ['current', 'target', 'delta_time', 'interp_speed']),
    ('vector_subtract', 'vectorSubtract', ['a', 'b']),
    ('vector_divide_float', 'vectorDivideFloat', ['a', 'b']),
    ('vector_negate', 'vectorNegate', ['a']),
    ('vector_equal', 'vectorEqual', ['a', 'b', 'error_tolerance']),
    ('vector_project_on_to', 'vectorProjectOnTo', ['a', 'b']),
    ('rotate_vector_around_axis', 'rotateVectorAroundAxis', ['in_vect', 'angle_deg', 'axis']),
    ('get_up_vector', 'getUpVector', ['in_rot']),
    ('random_unit_vector', 'randomUnitVector', <String>[]),
    ('vector_is_zero', 'vectorIsZero', ['a']),
    ('select_vector', 'selectVector', ['a', 'b', 'pick_a']),
    ('combine_rotators', 'combineRotators', ['a', 'b']),
    ('delta_rotator', 'deltaRotator', ['a', 'b']),
    ('rotator_lerp', 'rotatorLerp', ['a', 'b', 'alpha']),
    ('rotator_interp_to', 'rotatorInterpTo', ['current', 'target', 'delta_time', 'interp_speed']),
    ('find_look_at_rotation', 'findLookAtRotation', ['start', 'target']),
    ('rotator_equal', 'rotatorEqual', ['a', 'b', 'error_tolerance']),
    ('clamp_angle', 'clampAngle', ['angle_degrees', 'min_angle', 'max_angle']),
    ('normalize_axis', 'normalizeAxis', ['angle']),
    ('rotator_to_vector', 'rotatorToVector', ['in_rot']),
    ('make_rot_from_x', 'makeRotFromX', ['x']),
    ('make_transform', 'makeTransform', ['location', 'rotation', 'scale']),
    ('compose_transforms', 'composeTransforms', ['a', 'b']),
    ('transform_location', 'transformLocation', ['t', 'location']),
    ('inverse_transform_location', 'inverseTransformLocation', ['t', 'location']),
    ('transform_direction', 'transformDirection', ['t', 'direction']),
    ('make_color', 'makeColor', ['r', 'g', 'b', 'a']),
    ('color_lerp', 'colorLerp', ['a', 'b', 'alpha']),
    ('hex_to_color', 'hexToColor', ['hex']),
    ('color_to_hex', 'colorToHex', ['in_color']),
    ('float_to_string', 'floatToString', ['in_float', 'decimals']),
    ('int_to_string', 'intToString', ['in_int']),
    ('bool_to_string', 'boolToString', ['in_bool']),
    ('vector_to_string', 'vectorToString', ['in_vec']),
    ('rotator_to_string', 'rotatorToString', ['in_rot']),
    ('string_to_float', 'stringToFloat', ['in_string']),
    ('string_to_int', 'stringToInt', ['in_string']),
    ('append', 'append', ['a', 'b']),
    ('append_3', 'append3', ['a', 'b', 'c']),
    ('format_string', 'formatString', ['format', 'arg_0', 'arg_1', 'arg_2', 'arg_3']),
    ('string_length', 'stringLength', ['s']),
    ('string_equal', 'stringEqual', ['a', 'b', 'case_sensitive']),
    ('string_contains', 'stringContains', ['search_in', 'substring', 'use_case']),
    ('string_replace', 'stringReplace', ['source_string', 'from', 'to']),
    ('string_to_upper', 'stringToUpper', ['s']),
    ('string_to_lower', 'stringToLower', ['s']),
    ('string_substring', 'stringSubstring', ['s', 'start_index', 'length']),
    ('string_split', 'stringSplit', ['s', 'separator']),
    ('string_is_empty', 'stringIsEmpty', ['s']),
    ('string_trim', 'stringTrim', ['s']),
    ('select_string', 'selectString', ['a', 'b', 'pick_a']),
    ('select_bool', 'selectBool', ['a', 'b', 'pick_a']),
    ('select_object', 'selectObject', ['a', 'b', 'pick_a']),
    ('array_length', 'arrayLength', ['target_array']),
    ('array_get', 'arrayGet', ['target_array', 'index']),
    ('array_last_index', 'arrayLastIndex', ['target_array']),
    ('array_is_empty', 'arrayIsEmpty', ['target_array']),
    ('array_contains', 'arrayContains', ['target_array', 'item_to_find']),
    ('array_find', 'arrayFind', ['target_array', 'item_to_find']),
    ('array_first', 'arrayFirst', ['target_array']),
    ('array_last', 'arrayLast', ['target_array']),
    ('make_array', 'makeArray', <String>[]),
    ('array_add', 'arrayAdd', ['target_array', 'new_item']),
    ('array_filter_by_class', 'arrayFilterByClass', ['target_array', 'class']),
    ('make_hit_result', 'makeHitResult', ['blocking_hit', 'location', 'impact_point', 'impact_normal', 'distance', 'hit_actor', 'hit_component']),
  ])
    id: LuminaBlueprintCallShape(method, args, outputs: LuminaBlueprintFunctionLibrary._r),
  'break_transform': LuminaBlueprintCallShape('breakTransform', ['in_transform'], outputs: ['location', 'rotation', 'scale']),
  'break_color': LuminaBlueprintCallShape('breakColor', ['in_color'], outputs: ['r', 'g', 'b', 'a']),
  'break_hit_result': LuminaBlueprintCallShape('breakHitResult', ['hit'],
      outputs: ['blocking_hit', 'location', 'impact_point', 'impact_normal', 'distance', 'hit_actor', 'hit_component']),
  'array_remove_index': LuminaBlueprintCallShape('arrayRemoveIndex', ['target_array', 'index']),
  'array_clear': LuminaBlueprintCallShape('arrayClear', ['target_array']),
  'array_set': LuminaBlueprintCallShape('arraySet', ['target_array', 'index', 'item', 'size_to_fit']),
  'array_shuffle': LuminaBlueprintCallShape('arrayShuffle', ['target_array']),
};

/// Engine, traces, view, camera, actor, dispatchers, interfaces, enums,
/// timers.
final Map<String, LuminaBlueprintCallShape> _engineCallShapes = <String, LuminaBlueprintCallShape>{
  // --- engine, traces, view, camera, actor ------------------
  for (final (id, method) in const [
    ('get_frame_rate', 'getFrameRate'),
    ('get_frame_time_ms', 'getFrameTimeMs'),
    ('get_frame_number', 'getFrameNumber'),
    ('get_world_delta_seconds', 'getWorldDeltaSeconds'),
    ('get_game_time_in_seconds', 'getGameTimeInSeconds'),
    ('get_real_time_seconds', 'getRealTimeSeconds'),
    ('get_actor_count', 'getActorCount'),
    ('get_time_dilation', 'getTimeDilation'),
    ('get_look_forward_direction', 'getLookForwardDirection'),
    ('get_view_target', 'getViewTarget'),
    ('get_player_camera_manager', 'getPlayerCameraManager'),
    ('get_active_camera', 'getActiveCamera'),
    ('get_camera_location', 'getCameraLocation'),
    ('get_camera_rotation', 'getCameraRotation'),
  ])
    id: LuminaBlueprintCallShape(method, const [], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_platform_name': const LuminaBlueprintCallShape('getPlatformName', [], outputs: LuminaBlueprintFunctionLibrary._r),
  'is_editor': const LuminaBlueprintCallShape('isEditor', [], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_time_dilation': const LuminaBlueprintCallShape('setTimeDilation', ['time_dilation'], self: true),
  'quit_game': const LuminaBlueprintCallShape('quitGame', [], self: true),
  'line_trace_by_channel': const LuminaBlueprintCallShape('lineTraceByChannel',
      ['start', 'end', 'channel', 'actors_to_ignore', 'draw_debug'], self: true, outputs: ['out_hit', 'return_value']),
  'line_trace_forward': const LuminaBlueprintCallShape('lineTraceForward', ['distance', 'channel', 'draw_debug'],
      self: true, outputs: ['out_hit', 'return_value']),
  'multi_line_trace_by_channel': const LuminaBlueprintCallShape('multiLineTraceByChannel',
      ['start', 'end', 'channel', 'actors_to_ignore', 'draw_debug'], self: true, outputs: ['out_hits', 'return_value']),
  'multi_line_trace_forward': const LuminaBlueprintCallShape('multiLineTraceForward', ['distance', 'channel', 'draw_debug'],
      self: true, outputs: ['out_hits', 'return_value']),
  'sphere_trace_by_channel': const LuminaBlueprintCallShape('sphereTraceByChannel',
      ['start', 'end', 'radius', 'channel', 'actors_to_ignore', 'draw_debug'], self: true, outputs: ['out_hit', 'return_value']),
  'sphere_trace_forward': const LuminaBlueprintCallShape('sphereTraceForward', ['distance', 'radius', 'channel', 'draw_debug'],
      self: true, outputs: ['out_hit', 'return_value']),
  'sphere_overlap_actors': const LuminaBlueprintCallShape('sphereOverlapActors', ['location', 'radius', 'class', 'actors_to_ignore'],
      self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_actor_eyes_view_point': const LuminaBlueprintCallShape('getActorEyesViewPoint', [], self: true, outputs: ['location', 'rotation']),
  'find_look_at_location': const LuminaBlueprintCallShape('findLookAtLocation', ['distance'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_all_actors_of_class': const LuminaBlueprintCallShape('getAllActorsOfClass', ['class'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_level_actor': const LuminaBlueprintCallShape('getLevelActor', ['actor'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_level_actors_of_class': const LuminaBlueprintCallShape('getLevelActorsOfClass', ['class'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_all_actors_with_tag': const LuminaBlueprintCallShape('getAllActorsWithTag', ['tag'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_actors_within_radius': const LuminaBlueprintCallShape('getActorsWithinRadius', ['location', 'radius', 'class'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_actors_in_view_cone': const LuminaBlueprintCallShape('getActorsInViewCone', ['class', 'distance', 'cone_angle'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_closest_actor_of_class_in_direction':
      const LuminaBlueprintCallShape('getClosestActorOfClassInDirection', ['class', 'distance', 'cone_angle'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_view_target': const LuminaBlueprintCallShape('setViewTarget', ['target'], self: true),
  'set_view_target_with_blend':
      const LuminaBlueprintCallShape('setViewTargetWithBlend', ['target', 'blend_time', 'blend_func', 'blend_exp'], self: true),
  'set_active_camera': const LuminaBlueprintCallShape('setCameraActive', ['target', 'active']),
  'spawn_actor_from_class':
      const LuminaBlueprintCallShape('spawnActorFromClass', ['class', 'spawn_transform', 'collision_handling'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'destroy_actor': const LuminaBlueprintCallShape('destroyActor', ['target'], self: true),
  'set_life_span': const LuminaBlueprintCallShape('setLifeSpan', ['target', 'in_life_span'], self: true),
  'get_actor_transform': const LuminaBlueprintCallShape('getActorTransform', ['target'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_actor_transform': const LuminaBlueprintCallShape('setActorTransform', ['target', 'new_transform'], self: true),
  'set_actor_rotation': const LuminaBlueprintCallShape('setActorRotation', ['target', 'new_rotation'], self: true),
  'set_actor_scale_3d': const LuminaBlueprintCallShape('setActorScale3D', ['target', 'new_scale_3d'], self: true),
  'get_actor_scale_3d': const LuminaBlueprintCallShape('getActorScale3D', ['target'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_actor_hidden_in_game': const LuminaBlueprintCallShape('setActorHiddenInGame', ['target', 'new_hidden'], self: true),
  'is_hidden': const LuminaBlueprintCallShape('isHidden', ['target'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_actor_enable_collision':
      const LuminaBlueprintCallShape('setActorEnableCollision', ['target', 'new_actor_enable_collision'], self: true),
  'get_actor_enable_collision': const LuminaBlueprintCallShape('getActorEnableCollision', ['target'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'teleport': const LuminaBlueprintCallShape('teleport', ['target', 'dest_location', 'dest_rotation'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_actor_bounds': const LuminaBlueprintCallShape('getActorBounds', ['target'], self: true, outputs: ['origin', 'box_extent']),
  'get_actor_forward_vector': const LuminaBlueprintCallShape('getActorForwardVector', ['target'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_actor_right_vector': const LuminaBlueprintCallShape('getActorRightVector', ['target'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_actor_up_vector': const LuminaBlueprintCallShape('getActorUpVector', ['target'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'attach_actor_to_component': const LuminaBlueprintCallShape('attachActorToComponent', ['target', 'parent', 'socket_name'], self: true),
  'detach_from_actor': const LuminaBlueprintCallShape('detachFromActor', ['target'], self: true),
  'get_attach_parent_actor': const LuminaBlueprintCallShape('getAttachParentActor', ['target'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_owner': const LuminaBlueprintCallShape('getOwner', ['target'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_owner': const LuminaBlueprintCallShape('setOwner', ['target', 'new_owner'], self: true),
  'get_instigator': const LuminaBlueprintCallShape('getInstigator', ['target'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'actor_has_tag': const LuminaBlueprintCallShape('actorHasTag', ['target', 'tag'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'add_tag': const LuminaBlueprintCallShape('addTag', ['target', 'tag'], self: true),
  'remove_tag': const LuminaBlueprintCallShape('removeTag', ['target', 'tag'], self: true),
  'get_distance_to': const LuminaBlueprintCallShape('getDistanceTo', ['target', 'other_actor'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_horizontal_distance_to': const LuminaBlueprintCallShape('getHorizontalDistanceTo', ['target', 'other_actor'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'is_actor_being_destroyed': const LuminaBlueprintCallShape('isActorBeingDestroyed', ['target'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'apply_damage': const LuminaBlueprintCallShape('applyDamage',
      ['damaged_actor', 'base_damage', 'event_instigator', 'damage_causer', 'damage_type_class'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'apply_point_damage': const LuminaBlueprintCallShape('applyPointDamage',
      ['damaged_actor', 'base_damage', 'hit_from_direction', 'hit_info', 'event_instigator', 'damage_causer', 'damage_type_class'],
      self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'apply_radial_damage': const LuminaBlueprintCallShape('applyRadialDamage',
      ['base_damage', 'origin', 'damage_radius', 'damage_type_class', 'ignore_actors', 'damage_causer', 'instigated_by', 'do_full_damage'],
      self: true, outputs: LuminaBlueprintFunctionLibrary._r),

  // --- dispatchers, interfaces, enums, timers -----------------
  // (call_custom_event, call_function, call_dispatcher and interface_message
  // are variadic: the generator builds their argument map itself.)
  'bind_event_to_dispatcher': const LuminaBlueprintCallShape('bindEventToDispatcher', ['target', 'dispatcher', 'event'], self: true),
  'unbind_event_from_dispatcher': const LuminaBlueprintCallShape('unbindEventFromDispatcher', ['target', 'dispatcher', 'event'], self: true),
  'unbind_all_events': const LuminaBlueprintCallShape('unbindAllEvents', ['target', 'dispatcher'], self: true),
  'implements_interface': const LuminaBlueprintCallShape('doesImplementInterface', ['target', 'interface'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'enum_literal': const LuminaBlueprintCallShape('enumLiteral', ['enum', 'value'], outputs: LuminaBlueprintFunctionLibrary._r),
  'enum_to_string': const LuminaBlueprintCallShape('enumToString', ['value'], outputs: LuminaBlueprintFunctionLibrary._r),
  'enum_to_int': const LuminaBlueprintCallShape('enumToInt', ['enum', 'value'], outputs: LuminaBlueprintFunctionLibrary._r),
  'int_to_enum': const LuminaBlueprintCallShape('intToEnum', ['enum', 'value'], outputs: LuminaBlueprintFunctionLibrary._r),
  'enum_equal': const LuminaBlueprintCallShape('enumEqual', ['a', 'b'], outputs: LuminaBlueprintFunctionLibrary._r),
  'get_enum_value_count': const LuminaBlueprintCallShape('getEnumValueCount', ['enum'], outputs: LuminaBlueprintFunctionLibrary._r),
  'set_timer_by_event': const LuminaBlueprintCallShape('setTimerByEvent', ['event', 'time', 'looping', 'initial_start_delay'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_timer_by_function_name':
      const LuminaBlueprintCallShape('setTimerByFunctionName', ['function_name', 'time', 'looping', 'initial_start_delay'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_timer_for_next_tick': const LuminaBlueprintCallShape('setTimerForNextTick', ['event'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'clear_timer_by_handle': const LuminaBlueprintCallShape('clearTimerByHandle', ['handle'], self: true),
  'clear_and_invalidate_timer': const LuminaBlueprintCallShape('clearAndInvalidateTimer', ['handle'], self: true),
  'pause_timer': const LuminaBlueprintCallShape('pauseTimer', ['handle'], self: true),
  'unpause_timer': const LuminaBlueprintCallShape('unpauseTimer', ['handle'], self: true),
  'is_timer_active': const LuminaBlueprintCallShape('isTimerActive', ['handle'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'is_timer_paused': const LuminaBlueprintCallShape('isTimerPaused', ['handle'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_timer_remaining_time': const LuminaBlueprintCallShape('getTimerRemainingTime', ['handle'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_timer_elapsed_time': const LuminaBlueprintCallShape('getTimerElapsedTime', ['handle'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
};

/// Game framework, save game, input, audio, animation,
/// effects, material, light, debug.
final Map<String, LuminaBlueprintCallShape> _gameFrameworkCallShapes = <String, LuminaBlueprintCallShape>{
  // --- game framework, save game, input, audio, animation, fx, material, light, debug --
  for (final (id, method) in const [
    ('get_game_instance', 'getGameInstance'),
    ('get_game_mode', 'getGameMode'),
    ('get_game_state', 'getGameState'),
    ('is_game_paused', 'isGamePaused'),
    ('get_current_level_name', 'getCurrentLevelName'),
    ('get_game_time_since_creation', 'getGameTimeSinceCreation'),
    ('get_mouse_position', 'getMousePosition'),
    ('get_viewport_size', 'getViewportSize'),
    ('get_last_input_device', 'getLastInputDevice'),
    ('is_playing_montage', 'isPlayingMontage'),
    ('get_current_montage', 'getCurrentMontage'),
    ('get_anim_instance', 'getAnimInstance'),
  ])
    id: LuminaBlueprintCallShape(method, const [], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_player_state': const LuminaBlueprintCallShape('getPlayerState', ['player_index'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_game_paused': const LuminaBlueprintCallShape('setGamePaused', ['paused'], self: true),
  'execute_console_command': const LuminaBlueprintCallShape('executeConsoleCommand', ['command'], self: true),
  'open_level': const LuminaBlueprintCallShape('openLevel', ['level_name', 'options'], self: true),
  'unload_stream_level': const LuminaBlueprintCallShape('unloadStreamLevel', ['level_name'], self: true),
  'is_stream_level_loaded': const LuminaBlueprintCallShape('isStreamLevelLoaded', ['level_name'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'cancel_level_load': const LuminaBlueprintCallShape('cancelLevelLoad', ['level_name'], self: true),
  'is_level_loaded': const LuminaBlueprintCallShape('isLevelLoaded', ['level_name'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'create_save_game_object': const LuminaBlueprintCallShape('createSaveGameObject', ['class'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_save_field': const LuminaBlueprintCallShape('setSaveField', ['target', 'class', 'field', 'value'], self: true),
  'get_save_field': const LuminaBlueprintCallShape('getSaveField', ['target', 'field', 'class'], outputs: LuminaBlueprintFunctionLibrary._r),
  'save_game_to_slot': const LuminaBlueprintCallShape('saveGameToSlot', ['save_game_object', 'slot_name', 'user_index'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'load_game_from_slot': const LuminaBlueprintCallShape('loadGameFromSlot', ['slot_name', 'user_index'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'does_save_game_exist': const LuminaBlueprintCallShape('doesSaveGameExist', ['slot_name', 'user_index'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'delete_game_in_slot': const LuminaBlueprintCallShape('deleteGameInSlot', ['slot_name', 'user_index'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'is_input_key_down': const LuminaBlueprintCallShape('isInputKeyDown', ['key'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_input_key_time_down': const LuminaBlueprintCallShape('getInputKeyTimeDown', ['key'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'was_input_key_just_pressed': const LuminaBlueprintCallShape('wasInputKeyJustPressed', ['key'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'get_input_axis_value': const LuminaBlueprintCallShape('getInputAxisValue', ['axis_name'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_mouse_position': const LuminaBlueprintCallShape('setMousePosition', ['position'], self: true),
  'project_world_to_screen': const LuminaBlueprintCallShape('projectWorldToScreen', ['world_location'], self: true, outputs: ['screen_position', 'return_value']),
  'deproject_screen_to_world':
      const LuminaBlueprintCallShape('deprojectScreenToWorld', ['screen_position'], self: true, outputs: ['world_location', 'world_direction']),
  'enable_input': const LuminaBlueprintCallShape('enableInput', ['player_controller'], self: true),
  'disable_input': const LuminaBlueprintCallShape('disableInput', ['player_controller'], self: true),

  // --- Settings & Scalability -----------------------------------------
  'set_overall_scalability_level': const LuminaBlueprintCallShape('setOverallScalabilityLevel', ['preset'], self: true),
  'get_overall_scalability_level': const LuminaBlueprintCallShape('getOverallScalabilityLevel', [], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_view_distance_quality': const LuminaBlueprintCallShape('setViewDistanceQuality', ['quality'], self: true),
  'get_view_distance_quality': const LuminaBlueprintCallShape('getViewDistanceQuality', [], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_view_distance': const LuminaBlueprintCallShape('setViewDistance', ['distance'], self: true),
  'get_view_distance': const LuminaBlueprintCallShape('getViewDistance', [], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_shadow_quality': const LuminaBlueprintCallShape('setShadowQuality', ['quality'], self: true),
  'get_shadow_quality': const LuminaBlueprintCallShape('getShadowQuality', [], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_anti_aliasing_quality': const LuminaBlueprintCallShape('setAntiAliasingQuality', ['quality'], self: true),
  'get_anti_aliasing_quality': const LuminaBlueprintCallShape('getAntiAliasingQuality', [], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_post_processing_quality': const LuminaBlueprintCallShape('setPostProcessingQuality', ['quality'], self: true),
  'get_post_processing_quality': const LuminaBlueprintCallShape('getPostProcessingQuality', [], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_texture_quality': const LuminaBlueprintCallShape('setTextureQuality', ['quality'], self: true),
  'get_texture_quality': const LuminaBlueprintCallShape('getTextureQuality', [], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_shading_quality': const LuminaBlueprintCallShape('setShadingQuality', ['quality'], self: true),
  'get_shading_quality': const LuminaBlueprintCallShape('getShadingQuality', [], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_resolution_scale': const LuminaBlueprintCallShape('setResolutionScale', ['percent'], self: true),
  'get_resolution_scale': const LuminaBlueprintCallShape('getResolutionScale', [], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_target_fps': const LuminaBlueprintCallShape('setTargetFps', ['fps'], self: true),
  'get_target_fps': const LuminaBlueprintCallShape('getTargetFps', [], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_vsync_enabled': const LuminaBlueprintCallShape('setVsyncEnabled', ['enabled'], self: true),
  'get_vsync_enabled': const LuminaBlueprintCallShape('getVsyncEnabled', [], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'apply_scalability_settings': const LuminaBlueprintCallShape('applyScalabilitySettings', [], self: true),

  'play_sound_2d': const LuminaBlueprintCallShape('playSound2D', ['sound', 'volume', 'pitch', 'start_time'], self: true),
  'play_sound_at_location': const LuminaBlueprintCallShape('playSoundAtLocation', ['sound', 'location', 'volume', 'pitch', 'start_time'], self: true),
  'spawn_sound_2d': const LuminaBlueprintCallShape('spawnSound2D', ['sound', 'volume', 'pitch', 'start_time', 'auto_destroy'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'spawn_sound_attached':
      const LuminaBlueprintCallShape('spawnSoundAttached', ['sound', 'attach_to_component', 'socket_name', 'volume', 'pitch'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'stop_sound': const LuminaBlueprintCallShape('stopSound', ['target'], self: true),
  'fade_out_sound': const LuminaBlueprintCallShape('fadeOutSound', ['target', 'fade_out_duration'], self: true),
  'set_sound_volume': const LuminaBlueprintCallShape('setSoundVolume', ['target', 'volume'], self: true),
  'set_sound_pitch': const LuminaBlueprintCallShape('setSoundPitch', ['target', 'pitch'], self: true),
  'is_sound_playing': const LuminaBlueprintCallShape('isSoundPlaying', ['target'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_sound_class_volume': const LuminaBlueprintCallShape('setSoundClassVolume', ['sound_class', 'volume'], self: true),
  'play_anim_montage': const LuminaBlueprintCallShape('playAnimMontage', ['montage', 'play_rate', 'start_section'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'stop_anim_montage': const LuminaBlueprintCallShape('stopAnimMontage', ['blend_out_time'], self: true),
  'montage_jump_to_section': const LuminaBlueprintCallShape('montageJumpToSection', ['section_name'], self: true),
  'montage_set_next_section': const LuminaBlueprintCallShape('montageSetNextSection', ['section_name', 'next_section'], self: true),
  'set_anim_variable': const LuminaBlueprintCallShape('setAnimVariable', ['name', 'value'], self: true),
  'get_anim_variable': const LuminaBlueprintCallShape('getAnimVariable', ['name'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'spawn_emitter_at_location':
      const LuminaBlueprintCallShape('spawnEmitterAtLocation', ['emitter_template', 'location', 'rotation', 'scale', 'auto_destroy'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'spawn_emitter_attached':
      const LuminaBlueprintCallShape('spawnEmitterAttached', ['emitter_template', 'attach_to_component', 'socket_name', 'auto_destroy'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'spawn_decal_at_location': const LuminaBlueprintCallShape(
      'spawnDecalAtLocation', ['decal_material', 'decal_size', 'location', 'rotation', 'life_span'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'activate_particle_system': const LuminaBlueprintCallShape('activateParticleSystem', ['target', 'reset'], self: true),
  'deactivate_particle_system': const LuminaBlueprintCallShape('deactivateParticleSystem', ['target'], self: true),
  'set_particle_parameter': const LuminaBlueprintCallShape('setParticleParameter', ['target', 'parameter_name', 'value'], self: true),
  'create_dynamic_material_instance': const LuminaBlueprintCallShape('createDynamicMaterialInstance', ['target', 'element_index'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_scalar_parameter_value': const LuminaBlueprintCallShape('setScalarParameterValue', ['target', 'parameter_name', 'value'], self: true),
  'set_vector_parameter_value': const LuminaBlueprintCallShape('setVectorParameterValue', ['target', 'parameter_name', 'value'], self: true),
  'set_texture_parameter_value': const LuminaBlueprintCallShape('setTextureParameterValue', ['target', 'parameter_name', 'value'], self: true),
  'get_scalar_parameter_value': const LuminaBlueprintCallShape('getScalarParameterValue', ['target', 'parameter_name'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_material_scalar_parameter_on_actor':
      const LuminaBlueprintCallShape('setMaterialScalarParameterOnActor', ['target', 'parameter_name', 'value'], self: true),
  'set_light_intensity': const LuminaBlueprintCallShape('setLightIntensity', ['target', 'new_intensity'], self: true),
  'get_light_intensity': const LuminaBlueprintCallShape('getLightIntensity', ['target'], self: true, outputs: LuminaBlueprintFunctionLibrary._r),
  'set_light_color': const LuminaBlueprintCallShape('setLightColor', ['target', 'new_light_color'], self: true),
  'set_light_visibility': const LuminaBlueprintCallShape('setLightVisibility', ['target', 'new_visibility'], self: true),
  'toggle_light_visibility': const LuminaBlueprintCallShape('toggleLightVisibility', ['target'], self: true),
  'set_light_radius': const LuminaBlueprintCallShape('setLightRadius', ['target', 'new_radius'], self: true),
  'set_spot_light_angles': const LuminaBlueprintCallShape('setSpotLightAngles', ['target', 'inner_cone_angle', 'outer_cone_angle'], self: true),
  'print_text': const LuminaBlueprintCallShape('printText', ['in_text', 'print_to_screen', 'print_to_log', 'text_color', 'duration', 'key'], self: true),
  'draw_debug_line': const LuminaBlueprintCallShape('drawDebugLine', ['line_start', 'line_end', 'line_color', 'duration', 'thickness'], self: true),
  'draw_debug_sphere': const LuminaBlueprintCallShape('drawDebugSphere', ['center', 'radius', 'segments', 'line_color', 'duration', 'thickness'], self: true),
  'draw_debug_box': const LuminaBlueprintCallShape('drawDebugBox', ['center', 'extent', 'rotation', 'line_color', 'duration', 'thickness'], self: true),
  'draw_debug_point': const LuminaBlueprintCallShape('drawDebugPoint', ['position', 'size', 'point_color', 'duration'], self: true),
  'draw_debug_arrow': const LuminaBlueprintCallShape('drawDebugArrow', ['line_start', 'line_end', 'arrow_size', 'line_color', 'duration', 'thickness'], self: true),
  'draw_debug_string': const LuminaBlueprintCallShape('drawDebugString', ['text_location', 'text', 'text_color', 'duration'], self: true),
  'draw_debug_capsule':
      const LuminaBlueprintCallShape('drawDebugCapsule', ['center', 'half_height', 'radius', 'rotation', 'line_color', 'duration', 'thickness'], self: true),
  'flush_debug_shapes': const LuminaBlueprintCallShape('flushDebugShapes', [], self: true),
  'breakpoint': const LuminaBlueprintCallShape('breakpoint', [], self: true),
  'log_warning': const LuminaBlueprintCallShape('logWarning', ['in_string'], self: true),
  'log_error': const LuminaBlueprintCallShape('logError', ['in_string'], self: true),
};
