// Generates src/web_stubs_c.cpp: web-build bodies for the C functions whose
// Filament libraries are desktop-only (filamat's runtime material compiler,
// imageio's full codecs). The desktop implementations are compiled out under
// __EMSCRIPTEN__; these keep every filament_* symbol exported so the Dart
// bindings stay identical, and fail softly with a zero value and one log line.
//   node tool/web/gen_web_stubs.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const pkg = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const units = [
  { header: 'filamat_c.h', library: 'filamat (runtime material compiler)' },
  { header: 'imageio_c.h', library: 'imageio (image encoders and decoders)' },
];

const decl = /FFI_PLUGIN_EXPORT\s+([^;{}]*?)\b(filament_\w+)\s*\(([^)]*)\)\s*;/g;
let out = `// GENERATED by tool/web/gen_web_stubs.mjs from ${units.map((u) => u.header).join(', ')} — do not edit.
// Web builds only: these libraries are not part of Filament's WebAssembly build.
#ifdef __EMSCRIPTEN__
#include <cstdio>
${units.map((u) => `#include "${u.header}"`).join('\n')}

static void flutter_filament_web_unavailable(const char* function, const char* library) {
  fprintf(stderr, "[flutter_filament] %s is not available in web builds: %s is desktop-only\\n", function, library);
}
`;
let count = 0;
for (const { header, library } of units) {
  const text = readFileSync(join(pkg, 'src', header), 'utf8').replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
  out += `\n// --- ${header} ---\n`;
  for (const m of text.matchAll(decl)) {
    const ret = m[1].replace(/\s+/g, ' ').trim();
    const params = m[3].replace(/\s+/g, ' ').trim();
    const body = ret === 'void'
      ? `flutter_filament_web_unavailable("${m[2]}", "${library}");`
      : `flutter_filament_web_unavailable("${m[2]}", "${library}");\n  return {};`;
    out += `\n${ret} ${m[2]}(${params}) {\n  ${body}\n}\n`;
    count++;
  }
}
out += '\n#endif  // __EMSCRIPTEN__\n';
writeFileSync(join(pkg, 'src', 'web_stubs_c.cpp'), out);
console.log(`${count} web stubs -> src/web_stubs_c.cpp`);
