import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:lumina_editor_data/lumina_editor.dart';
import 'package:vector_math/vector_math_64.dart';

import '../../../lumina/test/blueprint/combo_box_menu_fixture.dart';
import '../../../lumina/test/blueprint/generated/widget_script/wbp_settings_menu.g.dart';
import '../../../lumina/test/src/game/display_test_support.dart';

/// A settings menu's Combo Box graph compiles into `WbpSettingsMenuGraph`
/// (committed as `generated/widget_script/wbp_settings_menu.g.dart`) and plays
/// exactly as the VM does: options with Vector 2D values, a wildcard Value
/// typed by its wires, Get Selected Option's Label / Value / Index and On
/// Selection Changed from a Blueprint setter (`Direct`) and from the player
/// (`OnMouseClick`). Regenerate after an intentional generator change with
/// `UPDATE_GOLDENS=1 flutter test test/blueprint/combo_box_script_codegen_test.dart`.
const String _golden = '../lumina/test/blueprint/generated/widget_script/wbp_settings_menu.g.dart';

String _goldenFileOf(BlueprintGenerationResult result) {
  final b = StringBuffer()
    ..writeln('// GENERATED by test/blueprint/combo_box_script_codegen_test.dart: WBP_SettingsMenu\'s graph script,')
    ..writeln('// as a widget file embeds it. UPDATE_GOLDENS=1 rewrites it.')
    ..writeln('// ignore_for_file: camel_case_types, non_constant_identifier_names, unused_import, prefer_const_constructors, '
        'unnecessary_this, dead_code, unused_local_variable, dead_null_aware_expression')
    ..writeln()
    ..writeln("import 'package:lumina/lumina_runtime.dart';")
    ..writeln("import 'package:vector_math/vector_math_64.dart';");
  for (final i in result.imports) {
    b.writeln(i);
  }
  b
    ..writeln()
    ..write(result.code);
  return b.toString();
}

void main() {
  setUp(() async {
    resetDisplay();
    installRunner(FakeRunnerWindow());
    await LuminaGameWindow.restore();
    LuminaWidgetClassRegistry.register(settingsMenuWidgetClass);
  });
  tearDown(() {
    LuminaUserWidgets.clear();
    LuminaWidgetClassRegistry.clear();
    resetDisplay();
  });

  test('generateWidgetScript writes WbpSettingsMenuGraph with the combo box calls and a typed On Selection Changed', () {
    final result = const BlueprintDartGenerator().generateWidgetScript(settingsMenuBlueprint(), className: 'WbpSettingsMenuGraph');
    expect(result.errors, isEmpty);
    final code = result.code!;
    expect(code, contains("case ('Resolution', 'OnSelectionChanged'):"));
    expect(code, contains("args['value'] as Vector2?"), reason: 'the event Value is typed Vector 2D by its type setting');
    expect(code, contains('LuminaBlueprintFunctionLibrary.addElementOption(this, '));
    expect(code, contains('LuminaBlueprintFunctionLibrary.getElementSelection('));
    expect(code, contains('LuminaBlueprintFunctionLibrary.findElementOptionIndexByValue('));

    final generated = _goldenFileOf(result);
    final golden = File(_golden);
    if (Platform.environment['UPDATE_GOLDENS'] == '1') {
      golden
        ..parent.createSync(recursive: true)
        ..writeAsStringSync(generated);
    }
    expect(golden.existsSync(), isTrue, reason: 'run with UPDATE_GOLDENS=1 to create $_golden');
    expect(generated, golden.readAsStringSync(), reason: '$_golden changed; UPDATE_GOLDENS=1 regenerates it');
  });

  test('the generated WbpSettingsMenuGraph and the VM agree, event for event', () {
    List<String> run(LuminaUserWidget Function() factory) {
      LuminaUserWidgets.register(settingsMenuClass, factory);
      final world = LuminaWorld(worldType: LuminaWorldType.game);
      world.beginPlay();
      final owner = world.spawnActorImmediately(LuminaActor());
      final widget = LuminaBlueprintFunctionLibrary.createWidget(owner, settingsMenuClass) as Map<String, Object?>;
      final script = LuminaUserWidgets.of(widget)! as LuminaBlueprintRuntime;
      final steps = <String>[];
      script.trace = (e) => steps.add('${e.eventNodeId}/${e.nodeId}/${e.registryId}${e.printed == null ? '' : ' "${e.printed}"'}');
      Map<String, Object?> element(String name) => (widget['elements']! as Map)[name] as Map<String, Object?>;
      String state() {
        final s = LuminaBlueprintFunctionLibrary.getElementSelection(element('Resolution'));
        return 'options=${LuminaComboBoxOptions.labels(element('Resolution')['options']).join('|')} '
            'selected=${s.returnValue}/${s.value}/${s.index} status=${element('Status')['text']}';
      }

      steps.add(state());
      LuminaBlueprintFunctionLibrary.addToViewport(owner, widget, 0);
      steps.add(state());
      // The player picks 1920×1080, as the generated widget reports it.
      final res = element('Resolution');
      LuminaComboBoxOptions.writeSelection(res, LuminaComboBoxOptions.of(res), 3);
      LuminaUserWidgets.fire(widget, 'Resolution', 'OnSelectionChanged', LuminaComboBoxOptions.selected(res, 'OnMouseClick').eventArgs);
      steps.add(state());
      steps.add('staged=${world.getSubsystem<LuminaUserSettingsSubsystem>()!.screenResolutionSetting}');
      LuminaUserWidgets.clear();
      return steps;
    }

    final cls = LuminaBlueprintClass.forWidget(settingsMenuBlueprint());
    final vm = run(cls.instantiateUserWidget);
    final generated = run(WbpSettingsMenuGraph.new);
    expect(generated, vm);
    expect(vm.first, 'options=Native selected=Native/[0.0,0.0]/0 status=');
    expect(vm, contains('options=800×600|1280×720|1280×1024|1920×1080|2560×1080|3440×1440 selected=800×600/[800.0,600.0]/0 status=800×600'));
    expect(vm.where((s) => s.endsWith('"6"')), hasLength(1), reason: 'Get Option Count after the loop');
    expect(vm.where((s) => s.endsWith('"800×600 #0 Direct @0800×600"')), hasLength(1), reason: 'Set Selected Index ran On Selection Changed');
    expect(vm.where((s) => s.endsWith('"1920×1080 #3 OnMouseClick @31920×1080"')), hasLength(1));
    expect(vm.last, 'staged=(1920, 1080)', reason: 'Set Screen Resolution got the picked Vector 2D');
    expect(LuminaBlueprintFunctionLibrary.getElementOptionValue(
        {'options': [{'label': '1920×1080', 'value': Vector2(1920, 1080)}]}, 0), Vector2(1920, 1080));
  });
}
