part of '../node_library.dart';

/// Built-in nodes: engine, traces, self / view, camera, actor, Level
/// Blueprint and actor event nodes.
final List<LuminaBlueprintNodeSpec> _engineAndActorNodes = <LuminaBlueprintNodeSpec>[
  // --- Lumina | Engine ------------------------------------
  for (final (id, title, type, keywords) in const [
    ('get_frame_rate', 'Get Frame Rate', LuminaPinType.float, ['fps', 'frame', 'rate', 'performance', 'stat']),
    ('get_frame_time_ms', 'Get Frame Time (ms)', LuminaPinType.float, ['frame', 'time', 'ms', 'performance', 'stat']),
    ('get_frame_number', 'Get Frame Number', LuminaPinType.integer, ['frame', 'number', 'count', 'tick']),
    ('get_world_delta_seconds', 'Get World Delta Seconds', LuminaPinType.float, ['delta', 'time', 'frame', 'seconds']),
    ('get_game_time_in_seconds', 'Get Game Time in Seconds', LuminaPinType.float, ['time', 'game', 'seconds', 'elapsed']),
    ('get_real_time_seconds', 'Get Real Time Seconds', LuminaPinType.float, ['time', 'real', 'seconds', 'wall', 'clock']),
    ('get_actor_count', 'Get Actor Count', LuminaPinType.integer, ['actor', 'count', 'number', 'world']),
    ('get_time_dilation', 'Get Global Time Dilation', LuminaPinType.float, ['time', 'dilation', 'slomo', 'slow', 'motion']),
    ('get_platform_name', 'Get Platform Name', LuminaPinType.string, ['platform', 'os', 'linux', 'windows', 'web']),
    ('is_editor', 'Is Editor', LuminaPinType.boolean, ['editor', 'pie', 'play in editor']),
  ])
    LuminaBlueprintNodeSpec(
      id: id,
      title: title,
      category: 'Lumina|Engine',
      kind: LuminaBlueprintNodeKind.pure,
      headerColor: _pure,
      keywords: keywords,
      outputs: [_ret(type)],
    ),
  LuminaBlueprintNodeSpec(
    id: 'set_time_dilation',
    title: 'Set Global Time Dilation',
    category: 'Lumina|Engine',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['time', 'dilation', 'slomo', 'slow', 'motion', 'speed'],
    inputs: [_execIn, _f('time_dilation', 'Time Dilation', 1.0)],
    outputs: const [_execOut],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'quit_game',
    title: 'Quit Game',
    category: 'Lumina|Engine',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: ['quit', 'exit', 'close', 'game'],
    inputs: [_execIn],
    outputs: [_execOut],
  ),

  // --- Collision | Trace ----------------------------------
  for (final (id, title, forward, multi, sphere, keywords) in const [
    ('line_trace_by_channel', 'Line Trace By Channel', false, false, false, ['trace', 'ray', 'raycast', 'line', 'hit']),
    ('line_trace_forward', 'Line Trace Forward', true, false, false, ['trace', 'ray', 'raycast', 'look', 'forward', 'aim', 'hit']),
    ('multi_line_trace_by_channel', 'Multi Line Trace By Channel', false, true, false, ['trace', 'ray', 'multi', 'all', 'hits']),
    ('multi_line_trace_forward', 'Multi Line Trace Forward', true, true, false, ['trace', 'ray', 'multi', 'look', 'forward', 'hits']),
    ('sphere_trace_by_channel', 'Sphere Trace By Channel', false, false, true, ['trace', 'sphere', 'sweep', 'hit', 'radius']),
    ('sphere_trace_forward', 'Sphere Trace Forward', true, false, true, ['trace', 'sphere', 'sweep', 'look', 'forward', 'radius']),
  ])
    LuminaBlueprintNodeSpec(
      id: id,
      title: title,
      category: 'Collision|Trace',
      kind: LuminaBlueprintNodeKind.impure,
      headerColor: _function,
      keywords: keywords,
      inputs: [
        _execIn,
        if (forward) _f('distance', 'Distance', 1000.0) else ...[_v('start', 'Start'), _v('end', 'End')],
        if (sphere) _f('radius', 'Radius', 50.0),
        _s('channel', 'Channel', 'Visibility'),
        if (!forward) LuminaBlueprintPinSpec('actors_to_ignore', 'Actors To Ignore', LuminaPinType.array, elementType: LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.anyActor),
        _b('draw_debug', 'Draw Debug'),
      ],
      outputs: [
        _execOut,
        if (multi)
          const LuminaBlueprintPinSpec('out_hits', 'Out Hits', LuminaPinType.array, elementType: LuminaPinType.hitResult)
        else
          const LuminaBlueprintPinSpec('out_hit', 'Out Hit', LuminaPinType.hitResult),
        _ret(LuminaPinType.boolean),
      ],
    ),
  LuminaBlueprintNodeSpec(
    id: 'sphere_overlap_actors',
    title: 'Sphere Overlap Actors',
    category: 'Collision|Trace',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['overlap', 'sphere', 'actors', 'radius', 'query', 'nearby'],
    inputs: [
      _v('location', 'Sphere Pos'),
      _f('radius', 'Sphere Radius', 100.0),
      _s('class', 'Actor Class Filter', LuminaBlueprintObjectClass.anyActor),
      const LuminaBlueprintPinSpec('actors_to_ignore', 'Actors To Ignore', LuminaPinType.array, elementType: LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.anyActor),
    ],
    outputs: const [LuminaBlueprintPinSpec(_returnValue, 'Out Actors', LuminaPinType.array, elementType: LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.anyActor)],
  ),

  // --- Self | View ----------------------------------------
  LuminaBlueprintNodeSpec(
    id: 'get_look_forward_direction',
    title: 'Get Look Forward Direction',
    category: 'Self|View',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['look', 'forward', 'direction', 'aim', 'view', 'control rotation'],
    outputs: [_ret(LuminaPinType.vector)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_actor_eyes_view_point',
    title: 'Get Actor Eyes View Point',
    category: 'Self|View',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['eyes', 'view', 'point', 'camera', 'look', 'head'],
    outputs: const [
      LuminaBlueprintPinSpec('location', 'Location', LuminaPinType.vector),
      LuminaBlueprintPinSpec('rotation', 'Rotation', LuminaPinType.rotator),
    ],
  ),
  LuminaBlueprintNodeSpec(
    id: 'find_look_at_location',
    title: 'Find Look At Location',
    category: 'Self|View',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['look', 'at', 'location', 'ahead', 'aim', 'point'],
    inputs: [_f('distance', 'Distance', 1000.0)],
    outputs: [_ret(LuminaPinType.vector)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_all_actors_of_class',
    title: 'Get All Actors Of Class',
    category: 'Self|View',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['actors', 'class', 'all', 'find', 'world', 'query'],
    inputs: [_s('class', 'Actor Class', LuminaBlueprintObjectClass.anyActor)],
    outputs: const [LuminaBlueprintPinSpec(_returnValue, 'Out Actors', LuminaPinType.array, elementType: LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.anyActor)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_actors_in_view_cone',
    title: 'Get Actors In View Cone',
    category: 'Self|View',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['actors', 'view', 'cone', 'look', 'in front', 'aim', 'visible', 'query'],
    inputs: [_s('class', 'Actor Class', LuminaBlueprintObjectClass.anyActor), _f('distance', 'Distance', 1000.0), _f('cone_angle', 'Cone Angle', 45.0)],
    outputs: const [LuminaBlueprintPinSpec(_returnValue, 'Out Actors', LuminaPinType.array, elementType: LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.anyActor)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_closest_actor_of_class_in_direction',
    title: 'Get Closest Actor Of Class In Direction',
    category: 'Self|View',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['closest', 'nearest', 'actor', 'look', 'direction', 'aim', 'target'],
    inputs: [_s('class', 'Actor Class', LuminaBlueprintObjectClass.anyActor), _f('distance', 'Distance', 1000.0), _f('cone_angle', 'Cone Angle', 45.0)],
    outputs: [_ret(LuminaPinType.object, cls: LuminaBlueprintObjectClass.anyActor)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_all_actors_with_tag',
    title: 'Get All Actors with Tag',
    category: 'Self|View',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['actors', 'tag', 'all', 'find', 'query'],
    inputs: const [LuminaBlueprintPinSpec('tag', 'Tag', LuminaPinType.name, defaultValue: '')],
    outputs: const [LuminaBlueprintPinSpec(_returnValue, 'Out Actors', LuminaPinType.array, elementType: LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.anyActor)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_actors_within_radius',
    title: 'Get Actors Within Radius',
    category: 'Self|View',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['actors', 'radius', 'near', 'nearby', 'distance', 'query'],
    inputs: [_v('location', 'Location'), _f('radius', 'Radius', 500.0), _s('class', 'Actor Class', LuminaBlueprintObjectClass.anyActor)],
    outputs: const [LuminaBlueprintPinSpec(_returnValue, 'Out Actors', LuminaPinType.array, elementType: LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.anyActor)],
  ),

  // --- Camera ---------------------------------------------
  LuminaBlueprintNodeSpec(
    id: 'set_view_target',
    title: 'Set View Target',
    category: 'Camera',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['camera', 'view', 'target', 'switch', 'cut'],
    inputs: [_execIn, _obj('target', 'New View Target', LuminaBlueprintObjectClass.anyActor)],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'set_view_target_with_blend',
    title: 'Set View Target with Blend',
    category: 'Camera',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['camera', 'view', 'target', 'blend', 'switch', 'transition'],
    inputs: [
      _execIn,
      _obj('target', 'New View Target', LuminaBlueprintObjectClass.anyActor),
      _f('blend_time', 'Blend Time', 0.0),
      _s('blend_func', 'Blend Func', 'Linear'),
      _f('blend_exp', 'Blend Exp', 2.0),
    ],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_view_target',
    title: 'Get View Target',
    category: 'Camera',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['camera', 'view', 'target'],
    outputs: [_ret(LuminaPinType.object, cls: LuminaBlueprintObjectClass.anyActor)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_player_camera_manager',
    title: 'Get Player Camera Manager',
    category: 'Camera',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['camera', 'manager', 'player', 'shake', 'fov'],
    outputs: [_ret(LuminaPinType.object)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_active_camera',
    title: 'Get Active Camera',
    category: 'Camera',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['camera', 'active', 'component', 'current'],
    outputs: [_ret(LuminaPinType.object, cls: LuminaBlueprintObjectClass.component(LuminaBlueprintNodeLibrary._cam))],
  ),
  _compSet('set_active_camera', 'Set Active Camera', 'Camera', LuminaBlueprintNodeLibrary._cam, [_b('active', 'Active', true)],
      const ['camera', 'active', 'activate', 'switch']),
  LuminaBlueprintNodeSpec(
    id: 'get_camera_location',
    title: 'Get Camera Location',
    category: 'Camera',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['camera', 'location', 'position', 'view'],
    outputs: [_ret(LuminaPinType.vector)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_camera_rotation',
    title: 'Get Camera Rotation',
    category: 'Camera',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['camera', 'rotation', 'view', 'facing'],
    outputs: [_ret(LuminaPinType.rotator)],
  ),

  // --- Actor ----------------------------------------------
  LuminaBlueprintNodeSpec(
    id: 'spawn_actor_from_class',
    title: 'SpawnActor from Class',
    category: 'Actor',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['spawn', 'actor', 'class', 'create', 'instantiate'],
    inputs: [
      _execIn,
      _s('class', 'Class', ''),
      _xf('spawn_transform', 'Spawn Transform'),
      _s('collision_handling', 'Collision Handling Override', 'Default'),
    ],
    outputs: [_execOut, _ret(LuminaPinType.object, cls: LuminaBlueprintObjectClass.anyActor)],
  ),
  for (final (id, title, values, keywords) in [
    ('destroy_actor', 'DestroyActor', <LuminaBlueprintPinSpec>[], const ['destroy', 'delete', 'remove', 'kill']),
    ('set_life_span', 'Set Life Span', [_f('in_life_span', 'In Life Span', 0.0)], const ['life', 'span', 'destroy', 'after', 'timer']),
    ('set_actor_transform', 'SetActorTransform', [_xf('new_transform', 'New Transform')], const ['transform', 'move', 'place']),
    ('set_actor_rotation', 'SetActorRotation', [_rot('new_rotation', 'New Rotation')], const ['rotation', 'rotate', 'face', 'turn']),
    ('set_actor_scale_3d', 'SetActorScale3D', [_v('new_scale_3d', 'New Scale 3D', const [1.0, 1.0, 1.0])], const ['scale', 'size', 'resize']),
    ('set_actor_hidden_in_game', 'Set Actor Hidden In Game', [_b('new_hidden', 'New Hidden', true)], const ['hidden', 'hide', 'show', 'visible', 'visibility']),
    ('set_actor_enable_collision', 'Set Actor Enable Collision', [_b('new_actor_enable_collision', 'New Actor Enable Collision', true)], const ['collision', 'enable', 'disable']),
    ('detach_from_actor', 'DetachFromActor', <LuminaBlueprintPinSpec>[], const ['detach', 'attach', 'parent', 'release']),
    ('set_owner', 'Set Owner', [_obj('new_owner', 'New Owner', LuminaBlueprintObjectClass.anyActor)], const ['owner', 'set']),
    ('add_tag', 'Add Tag', [const LuminaBlueprintPinSpec('tag', 'Tag', LuminaPinType.name, defaultValue: '')], const ['tag', 'add', 'label']),
    ('remove_tag', 'Remove Tag', [const LuminaBlueprintPinSpec('tag', 'Tag', LuminaPinType.name, defaultValue: '')], const ['tag', 'remove', 'label']),
    ('attach_actor_to_component', 'AttachActorToComponent',
        [_comp(LuminaBlueprintNodeLibrary._scene, 'parent', 'Parent'), const LuminaBlueprintPinSpec('socket_name', 'Socket Name', LuminaPinType.name, defaultValue: '')],
        const ['attach', 'parent', 'component', 'socket']),
  ])
    LuminaBlueprintNodeSpec(
      id: id,
      title: title,
      category: 'Actor',
      kind: LuminaBlueprintNodeKind.impure,
      headerColor: _function,
      keywords: ['actor', ...keywords],
      inputs: [_execIn, _obj('target', 'Target', LuminaBlueprintObjectClass.anyActor), ...values],
      outputs: const [_execOut],
    ),
  LuminaBlueprintNodeSpec(
    id: 'teleport',
    title: 'Teleport',
    category: 'Actor',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['actor', 'teleport', 'move', 'warp', 'location', 'rotation'],
    inputs: [_execIn, _obj('target', 'Target', LuminaBlueprintObjectClass.anyActor), _v('dest_location', 'Dest Location'), _rot('dest_rotation', 'Dest Rotation')],
    outputs: [_execOut, _ret(LuminaPinType.boolean)],
  ),
  for (final (id, title, out, extra, keywords) in [
    ('get_actor_transform', 'GetActorTransform', _ret(LuminaPinType.transform), <LuminaBlueprintPinSpec>[], const ['transform', 'location', 'rotation', 'scale']),
    ('get_actor_scale_3d', 'GetActorScale3D', _ret(LuminaPinType.vector), <LuminaBlueprintPinSpec>[], const ['scale', 'size']),
    ('is_hidden', 'Is Hidden', _ret(LuminaPinType.boolean), <LuminaBlueprintPinSpec>[], const ['hidden', 'visible', 'visibility']),
    ('get_actor_enable_collision', 'Get Actor Enable Collision', _ret(LuminaPinType.boolean), <LuminaBlueprintPinSpec>[], const ['collision', 'enabled']),
    ('get_actor_forward_vector', 'Get Actor Forward Vector', _ret(LuminaPinType.vector), <LuminaBlueprintPinSpec>[], const ['forward', 'direction', 'facing']),
    ('get_actor_right_vector', 'Get Actor Right Vector', _ret(LuminaPinType.vector), <LuminaBlueprintPinSpec>[], const ['right', 'direction', 'side']),
    ('get_actor_up_vector', 'Get Actor Up Vector', _ret(LuminaPinType.vector), <LuminaBlueprintPinSpec>[], const ['up', 'direction']),
    ('get_attach_parent_actor', 'Get Attach Parent Actor', _ret(LuminaPinType.object, cls: LuminaBlueprintObjectClass.anyActor), <LuminaBlueprintPinSpec>[], const ['attach', 'parent']),
    ('get_owner', 'Get Owner', _ret(LuminaPinType.object, cls: LuminaBlueprintObjectClass.anyActor), <LuminaBlueprintPinSpec>[], const ['owner']),
    ('get_instigator', 'Get Instigator', _ret(LuminaPinType.object, cls: 'Actor:LuminaPawn'), <LuminaBlueprintPinSpec>[], const ['instigator', 'pawn', 'damage']),
    ('actor_has_tag', 'Actor Has Tag', _ret(LuminaPinType.boolean), [const LuminaBlueprintPinSpec('tag', 'Tag', LuminaPinType.name, defaultValue: '')], const ['tag', 'has', 'label']),
    ('get_distance_to', 'Get Distance To', _ret(LuminaPinType.float), [_obj('other_actor', 'Other Actor', LuminaBlueprintObjectClass.anyActor)], const ['distance', 'range', 'far']),
    ('get_horizontal_distance_to', 'Get Horizontal Distance To', _ret(LuminaPinType.float), [_obj('other_actor', 'Other Actor', LuminaBlueprintObjectClass.anyActor)], const ['distance', 'horizontal', 'range', '2d']),
    ('is_actor_being_destroyed', 'Is Actor Being Destroyed', _ret(LuminaPinType.boolean), <LuminaBlueprintPinSpec>[], const ['destroyed', 'pending', 'kill', 'valid']),
  ])
    LuminaBlueprintNodeSpec(
      id: id,
      title: title,
      category: 'Actor',
      kind: LuminaBlueprintNodeKind.pure,
      headerColor: _pure,
      keywords: ['actor', ...keywords],
      inputs: [_obj('target', 'Target', LuminaBlueprintObjectClass.anyActor), ...extra],
      outputs: [out],
    ),
  LuminaBlueprintNodeSpec(
    id: 'get_actor_bounds',
    title: 'Get Actor Bounds',
    category: 'Actor',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['actor', 'bounds', 'box', 'extent', 'origin', 'size'],
    inputs: [_obj('target', 'Target', LuminaBlueprintObjectClass.anyActor)],
    outputs: const [
      LuminaBlueprintPinSpec('origin', 'Origin', LuminaPinType.vector),
      LuminaBlueprintPinSpec('box_extent', 'Box Extent', LuminaPinType.vector),
    ],
  ),
  LuminaBlueprintNodeSpec(
    id: 'apply_damage',
    title: 'Apply Damage',
    category: 'Actor|Damage',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['damage', 'hurt', 'health', 'apply', 'hit'],
    inputs: [
      _execIn,
      _obj('damaged_actor', 'Damaged Actor', LuminaBlueprintObjectClass.anyActor),
      _f('base_damage', 'Base Damage', 0.0),
      _obj('event_instigator', 'Event Instigator'),
      _obj('damage_causer', 'Damage Causer', LuminaBlueprintObjectClass.anyActor),
      _s('damage_type_class', 'Damage Type Class', ''),
    ],
    outputs: [_execOut, _ret(LuminaPinType.float)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'apply_point_damage',
    title: 'Apply Point Damage',
    category: 'Actor|Damage',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['damage', 'point', 'hit', 'shot', 'hurt', 'health'],
    inputs: [
      _execIn,
      _obj('damaged_actor', 'Damaged Actor', LuminaBlueprintObjectClass.anyActor),
      _f('base_damage', 'Base Damage', 0.0),
      _v('hit_from_direction', 'Hit From Direction'),
      const LuminaBlueprintPinSpec('hit_info', 'Hit Info', LuminaPinType.hitResult),
      _obj('event_instigator', 'Event Instigator'),
      _obj('damage_causer', 'Damage Causer', LuminaBlueprintObjectClass.anyActor),
      _s('damage_type_class', 'Damage Type Class', ''),
    ],
    outputs: [_execOut, _ret(LuminaPinType.float)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'apply_radial_damage',
    title: 'Apply Radial Damage',
    category: 'Actor|Damage',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['damage', 'radial', 'explosion', 'radius', 'area', 'hurt'],
    inputs: [
      _execIn,
      _f('base_damage', 'Base Damage', 0.0),
      _v('origin', 'Origin'),
      _f('damage_radius', 'Damage Radius', 0.0),
      _s('damage_type_class', 'Damage Type Class', ''),
      const LuminaBlueprintPinSpec('ignore_actors', 'Ignore Actors', LuminaPinType.array, elementType: LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.anyActor),
      _obj('damage_causer', 'Damage Causer', LuminaBlueprintObjectClass.anyActor),
      _obj('instigated_by', 'Instigated By Controller'),
      _b('do_full_damage', 'Do Full Damage'),
    ],
    outputs: [_execOut, _ret(LuminaPinType.boolean)],
  ),

  // --- Level Blueprints -----------------------------------
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.getLevelActor,
    title: 'Get Level Actor',
    category: 'Level Actors',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: ['level', 'actor', 'reference', 'placed', 'create a reference'],
    outputs: [LuminaBlueprintPinSpec(_returnValue, 'Actor', LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.anyActor)],
  ),
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.getLevelActorsOfClass,
    title: 'Get Level Actors Of Class',
    category: 'Level Actors',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['level', 'actors', 'class', 'placed', 'all', 'find'],
    inputs: [_s('class', 'Actor Class', LuminaBlueprintObjectClass.anyActor)],
    outputs: const [
      LuminaBlueprintPinSpec(_returnValue, 'Out Actors', LuminaPinType.array,
          elementType: LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.anyActor)
    ],
  ),
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.eventLevelBeginPlay,
    title: 'Event Level BeginPlay',
    category: 'Level Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: ['level', 'begin', 'start', 'play'],
    outputs: [_execOut],
  ),
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.eventLevelTick,
    title: 'Event Level Tick',
    category: 'Level Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: ['level', 'tick', 'update', 'frame'],
    outputs: [
      LuminaBlueprintPinSpec('exec_tick_out', 'Exec Out', LuminaPinType.exec),
      LuminaBlueprintPinSpec('delta_seconds', 'Delta Seconds', LuminaPinType.float),
    ],
  ),
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.eventLevelEndPlay,
    title: 'Event Level EndPlay',
    category: 'Level Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: ['level', 'end', 'play', 'unload', 'stop'],
    outputs: [_execOut, LuminaBlueprintPinSpec('end_play_reason', 'End Play Reason', LuminaPinType.string)],
  ),
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.eventLevelLoaded,
    title: 'Event Level Loaded',
    category: 'Level Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: ['level', 'loaded', 'load', 'ready'],
    outputs: [_execOut],
  ),
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.eventLevelUnloaded,
    title: 'Event Level Unloaded',
    category: 'Level Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: ['level', 'unloaded', 'unload'],
    outputs: [_execOut],
  ),

  // --- Actor events ---------------------------------------
  const LuminaBlueprintNodeSpec(
    id: 'event_end_play',
    title: 'Event EndPlay',
    category: 'Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: ['end', 'play', 'destroyed', 'unload', 'stop'],
    outputs: [_execOut, LuminaBlueprintPinSpec('end_play_reason', 'End Play Reason', LuminaPinType.string)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'event_destroyed',
    title: 'Event Destroyed',
    category: 'Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: ['destroyed', 'destroy', 'killed', 'removed'],
    outputs: [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'event_any_damage',
    title: 'Event AnyDamage',
    category: 'Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: const ['damage', 'hurt', 'health', 'hit', 'take'],
    outputs: [
      _execOut,
      const LuminaBlueprintPinSpec('damage', 'Damage', LuminaPinType.float),
      const LuminaBlueprintPinSpec('damage_type', 'Damage Type', LuminaPinType.string),
      _obj('instigated_by', 'Instigated By'),
      _obj('damage_causer', 'Damage Causer', LuminaBlueprintObjectClass.anyActor),
    ],
  ),
  LuminaBlueprintNodeSpec(
    id: 'event_take_point_damage',
    title: 'Event PointDamage',
    category: 'Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: const ['damage', 'point', 'hit', 'shot', 'take'],
    outputs: [
      _execOut,
      const LuminaBlueprintPinSpec('damage', 'Damage', LuminaPinType.float),
      const LuminaBlueprintPinSpec('hit_location', 'Hit Location', LuminaPinType.vector),
      const LuminaBlueprintPinSpec('hit_from_direction', 'Shot From Direction', LuminaPinType.vector),
      const LuminaBlueprintPinSpec('damage_type', 'Damage Type', LuminaPinType.string),
      _obj('instigated_by', 'Instigated By'),
      _obj('damage_causer', 'Damage Causer', LuminaBlueprintObjectClass.anyActor),
    ],
  ),
  LuminaBlueprintNodeSpec(
    id: 'event_actor_begin_overlap',
    title: 'Event ActorBeginOverlap',
    category: 'Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: const ['overlap', 'begin', 'touch', 'enter', 'trigger', 'collision'],
    outputs: [_execOut, _obj('other_actor', 'Other Actor', LuminaBlueprintObjectClass.anyActor)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'event_actor_end_overlap',
    title: 'Event ActorEndOverlap',
    category: 'Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: const ['overlap', 'end', 'leave', 'exit', 'trigger', 'collision'],
    outputs: [_execOut, _obj('other_actor', 'Other Actor', LuminaBlueprintObjectClass.anyActor)],
  ),
];
