part of '../node_library.dart';

/// Built-in nodes: events, pawn / controller, UMG, game & player, input and
/// mouse / UI modes.
final List<LuminaBlueprintNodeSpec> _eventPawnUiInputNodes = <LuminaBlueprintNodeSpec>[
  // --- Events ---------------------------------------------------------
  const LuminaBlueprintNodeSpec(
    id: 'event_beginplay',
    title: 'Event BeginPlay',
    category: 'Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: ['begin', 'start', 'spawn'],
    outputs: [_execOut],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'event_tick',
    title: 'Event Tick',
    category: 'Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: ['update', 'frame'],
    outputs: [
      LuminaBlueprintPinSpec('exec_tick_out', 'Exec Out', LuminaPinType.exec),
      LuminaBlueprintPinSpec('delta_seconds', 'Delta Seconds', LuminaPinType.float),
    ],
  ),
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.enhancedInputAction,
    title: 'EnhancedInputAction',
    category: 'Input',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: ['input', 'action', 'key', 'axis', 'move', 'look', 'jump', 'enhanced'],
    outputs: [
      LuminaBlueprintPinSpec('triggered', 'Triggered', LuminaPinType.exec),
      LuminaBlueprintPinSpec('started', 'Started', LuminaPinType.exec),
      LuminaBlueprintPinSpec('ongoing', 'Ongoing', LuminaPinType.exec),
      LuminaBlueprintPinSpec('canceled', 'Canceled', LuminaPinType.exec),
      LuminaBlueprintPinSpec('completed', 'Completed', LuminaPinType.exec),
      LuminaBlueprintPinSpec('action_value', 'Action Value', LuminaPinType.boolean),
    ],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'event_begin_overlap',
    title: 'OnComponentBeginOverlap',
    category: 'Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: ['overlap', 'begin', 'component', 'touch', 'enter'],
    outputs: [
      _execOut,
      LuminaBlueprintPinSpec('other_actor', 'Other Actor', LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.anyActor),
      LuminaBlueprintPinSpec('other_comp', 'Other Comp', LuminaPinType.object, objectClass: 'Component:LuminaCollisionComponent'),
    ],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'event_end_overlap',
    title: 'OnComponentEndOverlap',
    category: 'Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: ['overlap', 'end', 'component', 'leave', 'exit'],
    outputs: [
      _execOut,
      LuminaBlueprintPinSpec('other_actor', 'Other Actor', LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.anyActor),
      LuminaBlueprintPinSpec('other_comp', 'Other Comp', LuminaPinType.object, objectClass: 'Component:LuminaCollisionComponent'),
    ],
  ),
  LuminaBlueprintNodeSpec(
    id: 'event_hit',
    title: 'Event Hit',
    category: 'Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: const ['hit', 'collision', 'block', 'impact', 'bump'],
    outputs: [
      _execOut,
      _obj('self_actor', 'My Actor', LuminaBlueprintObjectClass.anyActor),
      _obj('other_actor', 'Other Actor', LuminaBlueprintObjectClass.anyActor),
      const LuminaBlueprintPinSpec('normal_impulse', 'Normal Impulse', LuminaPinType.vector),
      const LuminaBlueprintPinSpec('hit', 'Hit', LuminaPinType.hitResult),
      const LuminaBlueprintPinSpec('hit_normal', 'Hit Normal', LuminaPinType.vector),
      const LuminaBlueprintPinSpec('impact_point', 'Impact Point', LuminaPinType.vector),
    ],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'event_input_axis',
    title: 'OnInputAxis',
    category: 'Input',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _legacy,
    deprecation: 'Legacy axis input names no action. Replace it with EnhancedInputAction.',
    outputs: [_execOut, LuminaBlueprintPinSpec('axis_value', 'Axis Value', LuminaPinType.float)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'event_input_action',
    title: 'OnInputAction',
    category: 'Input',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _legacy,
    deprecation: 'Legacy action input names no action. Replace it with EnhancedInputAction.',
    outputs: [
      LuminaBlueprintPinSpec('pressed_out', 'Pressed', LuminaPinType.exec),
      LuminaBlueprintPinSpec('released_out', 'Released', LuminaPinType.exec),
    ],
  ),

  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.updateAnimation,
    title: 'Event Blueprint Update Animation',
    category: 'Animation',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: ['anim', 'update', 'tick'],
    outputs: [
      _execOut,
      LuminaBlueprintPinSpec('delta_time_x', 'Delta Time X', LuminaPinType.float),
    ],
  ),
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.transitionResult,
    title: 'Result',
    category: 'Animation',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _flow,
    keywords: ['transition', 'rule', 'can enter'],
    inputs: [LuminaBlueprintPinSpec('can_enter', 'Can Enter Transition', LuminaPinType.boolean, defaultValue: false)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'calculate_direction',
    title: 'Calculate Direction',
    category: 'Animation',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: ['direction', 'strafe', 'angle', 'velocity'],
    inputs: [
      LuminaBlueprintPinSpec('velocity', 'Velocity', LuminaPinType.vector, defaultValue: [0.0, 0.0, 0.0]),
      LuminaBlueprintPinSpec('base_rotation', 'Base Rotation', LuminaPinType.rotator, defaultValue: [0.0, 0.0, 0.0]),
    ],
    outputs: [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.float)],
  ),

  // --- Pawn / controller ---------------------------------------------
  const LuminaBlueprintNodeSpec(
    id: 'add_movement_input',
    title: 'Add Movement Input',
    category: 'Pawn',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: ['move', 'walk', 'direction'],
    inputs: [
      LuminaBlueprintPinSpec('exec_move_in', 'Exec In', LuminaPinType.exec),
      LuminaBlueprintPinSpec('world_dir', 'World Direction', LuminaPinType.vector, defaultValue: [0.0, 1.0, 0.0]),
      LuminaBlueprintPinSpec('scale_val', 'Scale Value', LuminaPinType.float, defaultValue: 1.0),
      LuminaBlueprintPinSpec('force', 'Force', LuminaPinType.boolean, defaultValue: false),
    ],
    outputs: [LuminaBlueprintPinSpec('exec_move_out', 'Exec Out', LuminaPinType.exec)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'add_controller_yaw_input',
    title: 'Add Controller Yaw Input',
    category: 'Pawn',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['turn', 'look', 'yaw', 'mouse'],
    inputs: [_execIn, _f('val', 'Val')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'add_controller_pitch_input',
    title: 'Add Controller Pitch Input',
    category: 'Pawn',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['look', 'up', 'pitch', 'mouse'],
    inputs: [_execIn, _f('val', 'Val')],
    outputs: const [_execOut],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'jump',
    title: 'Jump',
    category: 'Character',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: ['jump', 'character'],
    inputs: [_execIn],
    outputs: [_execOut],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'set_free_look',
    title: 'Set Free Look',
    category: 'Character',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: ['free look', 'alt', 'head', 'camera', 'orbit', 'character', 'aim'],
    inputs: [_execIn, LuminaBlueprintPinSpec('enabled', 'Enabled', LuminaPinType.boolean, defaultValue: true)],
    outputs: [_execOut],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'is_free_looking',
    title: 'Is Free Looking',
    category: 'Character',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: ['free look', 'alt', 'head', 'camera', 'character', 'aim'],
    outputs: [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.boolean)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'stop_jumping',
    title: 'Stop Jumping',
    category: 'Character',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: ['jump', 'release', 'character'],
    inputs: [_execIn],
    outputs: [_execOut],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'set_actor_location',
    title: 'SetActorLocation',
    category: 'Transformation',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: ['teleport', 'position', 'move'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('new_location', 'New Location', LuminaPinType.vector, defaultValue: [0.0, 0.0, 0.0]),
      LuminaBlueprintPinSpec('sweep', 'Sweep', LuminaPinType.boolean, defaultValue: false),
    ],
    outputs: [_execOut, LuminaBlueprintPinSpec(_returnValue, 'Success', LuminaPinType.boolean)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'print_string',
    title: 'Print String',
    category: 'Development',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: 0xFF1B5E20,
    keywords: ['log', 'debug', 'print', 'screen'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('in_string', 'In String', LuminaPinType.string, defaultValue: 'Hello Lumina'),
      LuminaBlueprintPinSpec('print_to_screen', 'Print to Screen', LuminaPinType.boolean, defaultValue: true),
      LuminaBlueprintPinSpec('print_to_log', 'Print to Log', LuminaPinType.boolean, defaultValue: true),
      LuminaBlueprintPinSpec('text_color', 'Text Color', LuminaPinType.color, defaultValue: [0.0, 0.66, 1.0, 1.0]),
      LuminaBlueprintPinSpec('duration', 'Duration', LuminaPinType.float, defaultValue: 2.0),
      LuminaBlueprintPinSpec('key', 'Key', LuminaPinType.name, defaultValue: ''),
    ],
    outputs: [_execOut],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'get_control_rotation',
    title: 'Get Control Rotation',
    category: 'Pawn',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: ['controller', 'camera', 'aim', 'rotation'],
    outputs: [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.rotator)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'get_velocity',
    title: 'Get Velocity',
    category: 'Actor',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: ['speed', 'movement'],
    outputs: [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.vector)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'is_falling',
    title: 'Is Falling',
    category: 'Character',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: ['air', 'jump', 'fall'],
    outputs: [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.boolean)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'get_actor_location',
    title: 'GetActorLocation',
    category: 'Transformation',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: ['position'],
    outputs: [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.vector)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'get_actor_rotation',
    title: 'GetActorRotation',
    category: 'Transformation',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: ['facing'],
    outputs: [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.rotator)],
  ),

  // --- User Interface (UMG) ------------------------------------------
  const LuminaBlueprintNodeSpec(
    id: 'create_widget',
    title: 'Create Widget',
    category: 'User Interface',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: ['widget', 'ui', 'hud', 'create', 'umg', 'user interface'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('class', 'Class', LuminaPinType.string, defaultValue: 'WBP_HUD'),
      LuminaBlueprintPinSpec('owning_player', 'Owning Player', LuminaPinType.object),
    ],
    outputs: [
      _execOut,
      LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.object,
          objectClass: LuminaBlueprintObjectClass.widgetKind),
    ],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'add_to_viewport',
    title: 'Add to Viewport',
    category: 'User Interface',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: ['widget', 'ui', 'hud', 'show', 'display', 'viewport', 'add', 'screen'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('target', 'Target', LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.widgetKind),
      LuminaBlueprintPinSpec('z_order', 'Z-Order', LuminaPinType.integer, defaultValue: 0),
    ],
    outputs: [_execOut],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'remove_from_parent',
    title: 'Remove from Parent',
    category: 'User Interface',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: ['widget', 'ui', 'hud', 'hide', 'remove', 'parent', 'close'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('target', 'Target', LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.widgetKind),
    ],
    outputs: [_execOut],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'set_widget_visibility',
    title: 'Set Visibility (Widget)',
    category: 'User Interface',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: ['widget', 'ui', 'hud', 'visibility', 'visible', 'hidden', 'collapsed', 'set visibility'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('target', 'Target', LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.widgetKind),
      LuminaBlueprintPinSpec('in_visibility', 'In Visibility', LuminaPinType.enumeration,
          defaultValue: 'Visible', enumName: LuminaBlueprintNodeLibrary.slateVisibilityEnum),
    ],
    outputs: [_execOut],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'is_in_viewport',
    title: 'Is In Viewport',
    category: 'User Interface',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: ['widget', 'ui', 'hud', 'viewport', 'check', 'visible'],
    inputs: [
      LuminaBlueprintPinSpec('target', 'Target', LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.widgetKind),
    ],
    outputs: [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.boolean)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'get_owning_player',
    title: 'Get Owning Player',
    category: 'User Interface',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: ['widget', 'ui', 'player', 'controller', 'owner'],
    inputs: [
      LuminaBlueprintPinSpec('target', 'Target', LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.widgetKind),
    ],
    outputs: [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.object)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'set_widget_text',
    title: 'Set Text (Widget)',
    category: 'User Interface',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _legacy,
    deprecation: 'Use Get <element> → Set Text (Text)',
    keywords: ['widget', 'text', 'ui', 'label', 'string', 'set'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('target', 'Target', LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.widgetKind),
      LuminaBlueprintPinSpec('in_text', 'In Text', LuminaPinType.string, defaultValue: ''),
    ],
    outputs: [_execOut],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'set_widget_percent',
    title: 'Set Percent (Widget)',
    category: 'User Interface',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _legacy,
    deprecation: 'Use Get <element> → Set Percent',
    keywords: ['widget', 'progress', 'bar', 'percent', 'ui', 'set'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('target', 'Target', LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.widgetKind),
      LuminaBlueprintPinSpec('in_percent', 'In Percent', LuminaPinType.float, defaultValue: 1.0),
    ],
    outputs: [_execOut],
  ),

  // --- Game & Player --------------------------------------------------
  const LuminaBlueprintNodeSpec(
    id: 'get_player_controller',
    title: 'Get Player Controller',
    category: 'Game|Player',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: ['player', 'controller', 'input', 'ui'],
    inputs: [LuminaBlueprintPinSpec('player_index', 'Player Index', LuminaPinType.integer, defaultValue: 0)],
    outputs: [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.object)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'get_player_pawn',
    title: 'Get Player Pawn',
    category: 'Game|Player',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: ['player', 'pawn', 'character'],
    inputs: [LuminaBlueprintPinSpec('player_index', 'Player Index', LuminaPinType.integer, defaultValue: 0)],
    outputs: [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.object, objectClass: 'Actor:LuminaPawn')],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'get_player_character',
    title: 'Get Player Character',
    category: 'Game|Player',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: ['player', 'character', 'pawn'],
    inputs: [LuminaBlueprintPinSpec('player_index', 'Player Index', LuminaPinType.integer, defaultValue: 0)],
    outputs: [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.object, objectClass: 'Actor:LuminaCharacter')],
  ),

  // --- Input & Mouse / UI Modes ---------------------------------------
  const LuminaBlueprintNodeSpec(
    id: 'set_show_mouse_cursor',
    title: 'Set Show Mouse Cursor',
    category: 'Input|Mouse Interaction',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: ['mouse', 'cursor', 'show', 'hide', 'ui', 'pointer', 'visibility'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('target', 'Target', LuminaPinType.object),
      LuminaBlueprintPinSpec('show_mouse_cursor', 'Show Mouse Cursor', LuminaPinType.boolean, defaultValue: true),
    ],
    outputs: [_execOut],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'set_input_mode_game_and_ui',
    title: 'Set Input Mode Game and UI',
    category: 'Input',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: ['input', 'mode', 'ui', 'game', 'focus', 'mouse', 'cursor'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('target', 'Target', LuminaPinType.object),
      LuminaBlueprintPinSpec('in_widget_to_focus', 'In Widget to Focus', LuminaPinType.object),
      LuminaBlueprintPinSpec('lock_mouse_to_viewport', 'Lock Mouse to Viewport', LuminaPinType.boolean, defaultValue: false),
    ],
    outputs: [_execOut],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'set_input_mode_game_only',
    title: 'Set Input Mode Game Only',
    category: 'Input',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: ['input', 'mode', 'game', 'mouse'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('target', 'Target', LuminaPinType.object),
    ],
    outputs: [_execOut],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'set_input_mode_ui_only',
    title: 'Set Input Mode UI Only',
    category: 'Input',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: ['input', 'mode', 'ui', 'focus', 'mouse', 'cursor'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('target', 'Target', LuminaPinType.object),
      LuminaBlueprintPinSpec('in_widget_to_focus', 'In Widget to Focus', LuminaPinType.object),
      LuminaBlueprintPinSpec('lock_mouse_to_viewport', 'Lock Mouse to Viewport', LuminaPinType.boolean, defaultValue: false),
    ],
    outputs: [_execOut],
  ),
];
