part of '../node_library.dart';

/// Built-in nodes: flow control intrinsics.
final List<LuminaBlueprintNodeSpec> _flowControlNodes = <LuminaBlueprintNodeSpec>[
  // --- Flow control (intrinsics) --------------------------------------
  const LuminaBlueprintNodeSpec(
    id: 'branch',
    title: 'Branch',
    category: 'Flow Control',
    kind: LuminaBlueprintNodeKind.flow,
    headerColor: _flow,
    keywords: ['if', 'condition'],
    inputs: [_execIn, LuminaBlueprintPinSpec('condition', 'Condition', LuminaPinType.boolean, defaultValue: true)],
    outputs: [
      LuminaBlueprintPinSpec('true_out', 'True', LuminaPinType.exec),
      LuminaBlueprintPinSpec('false_out', 'False', LuminaPinType.exec),
    ],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'sequence',
    title: 'Sequence',
    category: 'Flow Control',
    kind: LuminaBlueprintNodeKind.flow,
    headerColor: _flow,
    keywords: ['then', 'order'],
    inputs: [_execIn],
    outputs: [
      LuminaBlueprintPinSpec('then_0', 'Then 0', LuminaPinType.exec),
      LuminaBlueprintPinSpec('then_1', 'Then 1', LuminaPinType.exec),
    ],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'delay',
    title: 'Delay',
    category: 'Flow Control',
    kind: LuminaBlueprintNodeKind.latent,
    headerColor: _math,
    keywords: ['wait', 'timer'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('duration', 'Duration (s)', LuminaPinType.float, defaultValue: 0.2),
    ],
    outputs: [LuminaBlueprintPinSpec('exec_out', 'Completed', LuminaPinType.exec)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'retriggerable_delay',
    title: 'Retriggerable Delay',
    category: 'Flow Control',
    kind: LuminaBlueprintNodeKind.latent,
    headerColor: _math,
    keywords: ['wait', 'timer', 'retrigger', 'restart', 'delay'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('duration', 'Duration (s)', LuminaPinType.float, defaultValue: 0.2),
    ],
    outputs: [LuminaBlueprintPinSpec('exec_out', 'Completed', LuminaPinType.exec)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'do_once',
    title: 'DoOnce',
    category: 'Flow Control',
    kind: LuminaBlueprintNodeKind.flow,
    headerColor: _flow,
    keywords: ['once', 'do once', 'first time', 'latch'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('reset', 'Reset', LuminaPinType.exec),
      LuminaBlueprintPinSpec('start_closed', 'Start Closed', LuminaPinType.boolean, defaultValue: false),
    ],
    outputs: [LuminaBlueprintPinSpec('completed', 'Completed', LuminaPinType.exec)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'flip_flop',
    title: 'FlipFlop',
    category: 'Flow Control',
    kind: LuminaBlueprintNodeKind.flow,
    headerColor: _flow,
    keywords: ['flip', 'flop', 'toggle', 'alternate', 'a b'],
    inputs: [_execIn],
    outputs: [
      LuminaBlueprintPinSpec('a', 'A', LuminaPinType.exec),
      LuminaBlueprintPinSpec('b', 'B', LuminaPinType.exec),
      LuminaBlueprintPinSpec('is_a', 'Is A', LuminaPinType.boolean),
    ],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'gate',
    title: 'Gate',
    category: 'Flow Control',
    kind: LuminaBlueprintNodeKind.flow,
    headerColor: _flow,
    keywords: ['gate', 'open', 'close', 'toggle', 'block', 'enter'],
    inputs: [
      LuminaBlueprintPinSpec('exec_in', 'Enter', LuminaPinType.exec),
      LuminaBlueprintPinSpec('open', 'Open', LuminaPinType.exec),
      LuminaBlueprintPinSpec('close', 'Close', LuminaPinType.exec),
      LuminaBlueprintPinSpec('toggle', 'Toggle', LuminaPinType.exec),
      LuminaBlueprintPinSpec('start_closed', 'Start Closed', LuminaPinType.boolean, defaultValue: false),
    ],
    outputs: [LuminaBlueprintPinSpec('exit', 'Exit', LuminaPinType.exec)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'do_n',
    title: 'DoN',
    category: 'Flow Control',
    kind: LuminaBlueprintNodeKind.flow,
    headerColor: _flow,
    keywords: ['do n', 'times', 'count', 'limit', 'repeat'],
    inputs: [
      LuminaBlueprintPinSpec('exec_in', 'Enter', LuminaPinType.exec),
      LuminaBlueprintPinSpec('n', 'N', LuminaPinType.integer, defaultValue: 1),
      LuminaBlueprintPinSpec('reset', 'Reset', LuminaPinType.exec),
    ],
    outputs: [
      LuminaBlueprintPinSpec('exit', 'Exit', LuminaPinType.exec),
      LuminaBlueprintPinSpec('counter', 'Counter', LuminaPinType.integer),
    ],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'for_loop',
    title: 'ForLoop',
    category: 'Flow Control',
    kind: LuminaBlueprintNodeKind.flow,
    headerColor: _flow,
    keywords: ['for', 'loop', 'iterate', 'repeat', 'index'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('first_index', 'First Index', LuminaPinType.integer, defaultValue: 0),
      LuminaBlueprintPinSpec('last_index', 'Last Index', LuminaPinType.integer, defaultValue: 0),
    ],
    outputs: [
      LuminaBlueprintPinSpec('loop_body', 'Loop Body', LuminaPinType.exec),
      LuminaBlueprintPinSpec('index', 'Index', LuminaPinType.integer),
      LuminaBlueprintPinSpec('completed', 'Completed', LuminaPinType.exec),
    ],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'for_loop_with_break',
    title: 'ForLoopWithBreak',
    category: 'Flow Control',
    kind: LuminaBlueprintNodeKind.flow,
    headerColor: _flow,
    keywords: ['for', 'loop', 'break', 'iterate', 'repeat', 'index'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('first_index', 'First Index', LuminaPinType.integer, defaultValue: 0),
      LuminaBlueprintPinSpec('last_index', 'Last Index', LuminaPinType.integer, defaultValue: 0),
      LuminaBlueprintPinSpec('break', 'Break', LuminaPinType.exec),
    ],
    outputs: [
      LuminaBlueprintPinSpec('loop_body', 'Loop Body', LuminaPinType.exec),
      LuminaBlueprintPinSpec('index', 'Index', LuminaPinType.integer),
      LuminaBlueprintPinSpec('completed', 'Completed', LuminaPinType.exec),
    ],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'while_loop',
    title: 'WhileLoop',
    category: 'Flow Control',
    kind: LuminaBlueprintNodeKind.flow,
    headerColor: _flow,
    keywords: ['while', 'loop', 'repeat', 'until', 'condition'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('condition', 'Condition', LuminaPinType.boolean, defaultValue: false),
    ],
    outputs: [
      LuminaBlueprintPinSpec('loop_body', 'Loop Body', LuminaPinType.exec),
      LuminaBlueprintPinSpec('completed', 'Completed', LuminaPinType.exec),
    ],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'for_each_loop',
    title: 'ForEachLoop',
    category: 'Flow Control',
    kind: LuminaBlueprintNodeKind.flow,
    headerColor: _flow,
    keywords: ['for each', 'loop', 'array', 'iterate', 'element'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('array', 'Array', LuminaPinType.array),
    ],
    outputs: [
      LuminaBlueprintPinSpec('loop_body', 'Loop Body', LuminaPinType.exec),
      LuminaBlueprintPinSpec('array_element', 'Array Element', LuminaPinType.wildcard),
      LuminaBlueprintPinSpec('array_index', 'Array Index', LuminaPinType.integer),
      LuminaBlueprintPinSpec('completed', 'Completed', LuminaPinType.exec),
    ],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'switch_on_int',
    title: 'Switch on Int',
    category: 'Flow Control|Switch',
    kind: LuminaBlueprintNodeKind.flow,
    headerColor: _flow,
    keywords: ['switch', 'case', 'int', 'select', 'branch'],
    inputs: [_execIn, LuminaBlueprintPinSpec('selection', 'Selection', LuminaPinType.integer, defaultValue: 0)],
    outputs: [LuminaBlueprintPinSpec('default', 'Default', LuminaPinType.exec)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'switch_on_string',
    title: 'Switch on String',
    category: 'Flow Control|Switch',
    kind: LuminaBlueprintNodeKind.flow,
    headerColor: _flow,
    keywords: ['switch', 'case', 'string', 'select', 'branch'],
    inputs: [_execIn, LuminaBlueprintPinSpec('selection', 'Selection', LuminaPinType.string, defaultValue: '')],
    outputs: [LuminaBlueprintPinSpec('default', 'Default', LuminaPinType.exec)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'switch_on_name',
    title: 'Switch on Name',
    category: 'Flow Control|Switch',
    kind: LuminaBlueprintNodeKind.flow,
    headerColor: _flow,
    keywords: ['switch', 'case', 'name', 'select', 'branch'],
    inputs: [_execIn, LuminaBlueprintPinSpec('selection', 'Selection', LuminaPinType.name, defaultValue: '')],
    outputs: [LuminaBlueprintPinSpec('default', 'Default', LuminaPinType.exec)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'switch_on_bool',
    title: 'Switch on Bool',
    category: 'Flow Control|Switch',
    kind: LuminaBlueprintNodeKind.flow,
    headerColor: _flow,
    keywords: ['switch', 'case', 'bool', 'branch', 'if'],
    inputs: [_execIn, LuminaBlueprintPinSpec('selection', 'Selection', LuminaPinType.boolean, defaultValue: false)],
    outputs: [
      LuminaBlueprintPinSpec('true_out', 'True', LuminaPinType.exec),
      LuminaBlueprintPinSpec('false_out', 'False', LuminaPinType.exec),
    ],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'multi_gate',
    title: 'MultiGate',
    category: 'Flow Control',
    kind: LuminaBlueprintNodeKind.flow,
    headerColor: _flow,
    keywords: ['multi', 'gate', 'sequence', 'round robin', 'cycle', 'random'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('reset', 'Reset', LuminaPinType.exec),
      LuminaBlueprintPinSpec('is_random', 'Is Random', LuminaPinType.boolean, defaultValue: false),
      LuminaBlueprintPinSpec('loop', 'Loop', LuminaPinType.boolean, defaultValue: false),
      LuminaBlueprintPinSpec('start_index', 'Start Index', LuminaPinType.integer, defaultValue: -1),
    ],
    outputs: [
      LuminaBlueprintPinSpec('out_0', 'Out 0', LuminaPinType.exec),
      LuminaBlueprintPinSpec('out_1', 'Out 1', LuminaPinType.exec),
    ],
  ),
];
