part of '../node_library.dart';

/// Built-in nodes: game framework, level loading, save game, input and
/// screen.
final List<LuminaBlueprintNodeSpec> _gameFrameworkNodes = <LuminaBlueprintNodeSpec>[
  // --- Game framework --------------------------------------
  LuminaBlueprintNodeSpec(
    id: 'get_game_instance',
    title: 'Get Game Instance',
    category: 'Game',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['game', 'instance', 'subsystem'],
    outputs: [_ret(LuminaPinType.object)],
  ),
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.getGameMode,
    title: 'Get Game Mode',
    category: 'Game',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['game', 'mode', 'rules', 'match'],
    outputs: [_ret(LuminaPinType.object, cls: 'Actor:LuminaGameMode')],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_game_state',
    title: 'Get Game State',
    category: 'Game',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['game', 'state', 'match', 'score'],
    outputs: [_ret(LuminaPinType.object)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_player_state',
    title: 'Get Player State',
    category: 'Game|Player',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['player', 'state', 'score', 'health', 'name'],
    inputs: [_i('player_index', 'Player Index')],
    outputs: [_ret(LuminaPinType.object)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'set_game_paused',
    title: 'Set Game Paused',
    category: 'Game',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['pause', 'game', 'freeze', 'menu'],
    inputs: [_execIn, _b('paused', 'Paused', true)],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'is_game_paused',
    title: 'Is Game Paused',
    category: 'Game',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['pause', 'paused', 'game'],
    outputs: [_ret(LuminaPinType.boolean)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'execute_console_command',
    title: 'Execute Console Command',
    category: 'Game',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['console', 'command', 'cheat', 'stat', 'slomo', 'quit'],
    inputs: [_execIn, _s('command', 'Command')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_current_level_name',
    title: 'Get Current Level Name',
    category: 'Game|Level',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['level', 'map', 'name', 'current'],
    outputs: [_ret(LuminaPinType.string)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'open_level',
    title: 'Open Level (by Name)',
    category: 'Game|Level',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['level', 'map', 'open', 'load', 'travel'],
    inputs: [_execIn, LuminaBlueprintPinSpec('level_name', 'Level Name', LuminaPinType.name, defaultValue: ''), _s('options', 'Options')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.loadStreamLevel,
    title: 'Load Stream Level (by Name)',
    category: 'Game|Level',
    kind: LuminaBlueprintNodeKind.latent,
    headerColor: _flow,
    keywords: const ['level', 'stream', 'load', 'sublevel'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('level_name', 'Level Name', LuminaPinType.name, defaultValue: ''),
      _b('make_visible_after_load', 'Make Visible After Load', true),
      _b('should_block_on_load', 'Should Block on Load'),
    ],
    outputs: [_execOut, _exec('completed', 'Completed')],
  ),
  LuminaBlueprintNodeSpec(
    id: 'unload_stream_level',
    title: 'Unload Stream Level (by Name)',
    category: 'Game|Level',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['level', 'stream', 'unload', 'sublevel'],
    inputs: [_execIn, LuminaBlueprintPinSpec('level_name', 'Level Name', LuminaPinType.name, defaultValue: '')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'is_stream_level_loaded',
    title: 'Is Stream Level Loaded',
    category: 'Game|Level',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['level', 'stream', 'loaded', 'sublevel'],
    inputs: [LuminaBlueprintPinSpec('level_name', 'Level Name', LuminaPinType.name, defaultValue: '')],
    outputs: [_ret(LuminaPinType.boolean)],
  ),
  // --- Level loading with progress ---------------------------
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.loadLevel,
    title: 'Load Level',
    category: 'Game|Level',
    kind: LuminaBlueprintNodeKind.latent,
    headerColor: _flow,
    keywords: const ['level', 'load', 'preload', 'async', 'progress', 'loading', 'screen', 'map'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('level_name', 'Level Name', LuminaPinType.name, defaultValue: ''),
      _delegate('on_progress_event', 'On Progress Event'),
      _delegate('on_error_event', 'On Error Event'),
      _delegate('on_success_event', 'On Success Event'),
    ],
    outputs: [
      _execOut,
      _exec('on_progress', 'On Progress'),
      _exec('on_error', 'On Error'),
      _exec('on_success', 'On Success'),
      ..._levelLoadOutputs,
    ],
  ),
  for (final (id, title, keywords) in const [
    (LuminaBlueprintNodeLibrary.changeLevel, 'Change Level', ['level', 'change', 'switch', 'open', 'travel', 'map']),
    (LuminaBlueprintNodeLibrary.loadAndChangeLevel, 'Load And Change Level', ['level', 'load', 'change', 'switch', 'open', 'travel', 'loading', 'map']),
  ])
    LuminaBlueprintNodeSpec(
      id: id,
      title: title,
      category: 'Game|Level',
      kind: LuminaBlueprintNodeKind.latent,
      headerColor: _flow,
      keywords: keywords,
      inputs: [
        _execIn,
        LuminaBlueprintPinSpec('level_name', 'Level Name', LuminaPinType.name, defaultValue: ''),
        _delegate('on_error_event', 'On Error Event'),
        _delegate('on_success_event', 'On Success Event'),
      ],
      outputs: [
        _execOut,
        _exec('on_error', 'On Error'),
        _exec('on_success', 'On Success'),
        _s('error', 'Error'),
        _s('stack_trace', 'Stack Trace'),
      ],
    ),
  LuminaBlueprintNodeSpec(
    id: 'cancel_level_load',
    title: 'Cancel Level Load',
    category: 'Game|Level',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['level', 'load', 'cancel', 'abort', 'stop', 'preload'],
    inputs: [_execIn, LuminaBlueprintPinSpec('level_name', 'Level Name', LuminaPinType.name, defaultValue: '')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'is_level_loaded',
    title: 'Is Level Loaded',
    category: 'Game|Level',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['level', 'loaded', 'preloaded', 'ready'],
    inputs: [LuminaBlueprintPinSpec('level_name', 'Level Name', LuminaPinType.name, defaultValue: '')],
    outputs: [_ret(LuminaPinType.boolean)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_game_time_since_creation',
    title: 'Get Game Time Since Creation',
    category: 'Game',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['time', 'age', 'since', 'creation', 'spawn'],
    outputs: [_ret(LuminaPinType.float)],
  ),

  // --- Save game ---------------------------------------------
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.createSaveGameObject,
    title: 'Create Save Game Object',
    category: 'Save Game',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['save', 'game', 'create', 'object', 'slot'],
    inputs: [_execIn, _s('class', 'Save Game Class')],
    outputs: [_execOut, _ret(LuminaPinType.object, cls: LuminaBlueprintObjectClass.saveGameKind)],
  ),
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.setSaveField,
    title: 'Set Save Field',
    category: 'Save Game',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['save', 'field', 'set', 'variable'],
    inputs: [_execIn, _obj('target', 'Target', LuminaBlueprintObjectClass.saveGameKind), _any('value', 'Value')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.getSaveField,
    title: 'Get Save Field',
    category: 'Save Game',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['save', 'field', 'get', 'variable'],
    inputs: [_obj('target', 'Target', LuminaBlueprintObjectClass.saveGameKind)],
    outputs: [_any(_returnValue, 'Return Value')],
  ),
  LuminaBlueprintNodeSpec(
    id: 'save_game_to_slot',
    title: 'Save Game to Slot',
    category: 'Save Game',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['save', 'game', 'slot', 'write', 'disk'],
    inputs: [_execIn, _obj('save_game_object', 'Save Game Object', LuminaBlueprintObjectClass.saveGameKind), _s('slot_name', 'Slot Name', 'Slot1'), _i('user_index', 'User Index')],
    outputs: [_execOut, _ret(LuminaPinType.boolean)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'load_game_from_slot',
    title: 'Load Game from Slot',
    category: 'Save Game',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['save', 'load', 'game', 'slot', 'read', 'disk'],
    inputs: [_execIn, _s('slot_name', 'Slot Name', 'Slot1'), _i('user_index', 'User Index')],
    outputs: [_execOut, _ret(LuminaPinType.object, cls: LuminaBlueprintObjectClass.saveGameKind)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'does_save_game_exist',
    title: 'Does Save Game Exist',
    category: 'Save Game',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['save', 'exists', 'slot'],
    inputs: [_s('slot_name', 'Slot Name', 'Slot1'), _i('user_index', 'User Index')],
    outputs: [_ret(LuminaPinType.boolean)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'delete_game_in_slot',
    title: 'Delete Game in Slot',
    category: 'Save Game',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['save', 'delete', 'slot', 'remove'],
    inputs: [_execIn, _s('slot_name', 'Slot Name', 'Slot1'), _i('user_index', 'User Index')],
    outputs: [_execOut, _ret(LuminaPinType.boolean)],
  ),
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.asyncSaveGameToSlot,
    title: 'Async Save Game to Slot',
    category: 'Save Game',
    kind: LuminaBlueprintNodeKind.latent,
    headerColor: _flow,
    keywords: const ['save', 'async', 'slot', 'background'],
    inputs: [_execIn, _obj('save_game_object', 'Save Game Object', LuminaBlueprintObjectClass.saveGameKind), _s('slot_name', 'Slot Name', 'Slot1'), _i('user_index', 'User Index')],
    outputs: [_execOut, _exec('completed', 'Completed'), _b('success', 'Success')],
  ),

  // --- Input & screen ---------------------------------------
  for (final (id, title, type, keywords) in const [
    ('is_input_key_down', 'Is Input Key Down', LuminaPinType.boolean, ['key', 'down', 'pressed', 'held']),
    ('get_input_key_time_down', 'Get Input Key Time Down', LuminaPinType.float, ['key', 'time', 'held', 'down']),
    ('was_input_key_just_pressed', 'Was Input Key Just Pressed', LuminaPinType.boolean, ['key', 'pressed', 'just', 'edge']),
  ])
    LuminaBlueprintNodeSpec(
      id: id,
      title: title,
      category: 'Input',
      kind: LuminaBlueprintNodeKind.pure,
      headerColor: _pure,
      keywords: keywords,
      inputs: [LuminaBlueprintPinSpec('key', 'Key', LuminaPinType.name, defaultValue: '')],
      outputs: [_ret(type)],
    ),
  LuminaBlueprintNodeSpec(
    id: 'get_input_axis_value',
    title: 'Get Input Axis Value',
    category: 'Input',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['axis', 'input', 'value', 'mouse', 'stick'],
    inputs: [LuminaBlueprintPinSpec('axis_name', 'Axis Name', LuminaPinType.name, defaultValue: '')],
    outputs: [_ret(LuminaPinType.float)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_mouse_position',
    title: 'Get Mouse Position on Viewport',
    category: 'Input|Mouse Interaction',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['mouse', 'position', 'cursor', 'viewport'],
    outputs: [_ret(LuminaPinType.vector2D)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'set_mouse_position',
    title: 'Set Mouse Position',
    category: 'Input|Mouse Interaction',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['mouse', 'position', 'cursor', 'warp'],
    inputs: [_execIn, LuminaBlueprintPinSpec('position', 'Position', LuminaPinType.vector2D, defaultValue: [0.0, 0.0])],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_viewport_size',
    title: 'Get Viewport Size',
    category: 'Input',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['viewport', 'size', 'screen', 'resolution'],
    outputs: [_ret(LuminaPinType.vector2D)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'project_world_to_screen',
    title: 'Project World to Screen',
    category: 'Input',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['project', 'world', 'screen', 'hud', 'position'],
    inputs: [_v('world_location', 'World Location')],
    outputs: const [
      LuminaBlueprintPinSpec('screen_position', 'Screen Position', LuminaPinType.vector2D),
      LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.boolean),
    ],
  ),
  LuminaBlueprintNodeSpec(
    id: 'deproject_screen_to_world',
    title: 'Deproject Screen to World',
    category: 'Input',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['deproject', 'screen', 'world', 'ray', 'cursor'],
    inputs: [LuminaBlueprintPinSpec('screen_position', 'Screen Position', LuminaPinType.vector2D, defaultValue: [0.0, 0.0])],
    outputs: const [
      LuminaBlueprintPinSpec('world_location', 'World Location', LuminaPinType.vector),
      LuminaBlueprintPinSpec('world_direction', 'World Direction', LuminaPinType.vector),
    ],
  ),
  LuminaBlueprintNodeSpec(
    id: 'enable_input',
    title: 'Enable Input',
    category: 'Input',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['input', 'enable'],
    inputs: [_execIn, _obj('player_controller', 'Player Controller')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'disable_input',
    title: 'Disable Input',
    category: 'Input',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['input', 'disable'],
    inputs: [_execIn, _obj('player_controller', 'Player Controller')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_last_input_device',
    title: 'Get Last Input Device',
    category: 'Input',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['input', 'device', 'gamepad', 'keyboard', 'mouse'],
    outputs: [_ret(LuminaPinType.string)],
  ),
];
