part of '../node_library.dart';

/// Built-in nodes: custom events, functions, macros, dispatchers,
/// interfaces, enums, timers and timelines.
final List<LuminaBlueprintNodeSpec> _graphMemberNodes = <LuminaBlueprintNodeSpec>[
  // --- Custom events, functions, macros -------------------
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.customEvent,
    title: 'Custom Event',
    category: 'Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: const ['custom', 'event', 'call', 'delegate'],
    outputs: [_execOut, _delegate('delegate', 'Delegate')],
  ),
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.callCustomEvent,
    title: 'Call Custom Event',
    category: 'Events',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: ['custom', 'event', 'call', 'trigger'],
    inputs: [_execIn],
    outputs: [_execOut],
  ),
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.functionEntry,
    title: 'Function Entry',
    category: 'Functions',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _variable,
    keywords: ['function', 'entry', 'inputs'],
    outputs: [_execOut],
  ),
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.functionResult,
    title: 'Return Node',
    category: 'Functions',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _variable,
    keywords: ['function', 'return', 'result', 'outputs'],
    inputs: [_execIn],
  ),
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.callFunction,
    title: 'Call Function',
    category: 'Functions',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: ['function', 'call'],
    inputs: [_execIn],
    outputs: [_execOut],
  ),
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.callFunctionPure,
    title: 'Call Function',
    category: 'Functions',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: ['function', 'call', 'pure'],
  ),
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.macroInput,
    title: 'Inputs',
    category: 'Macros',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _flow,
    keywords: ['macro', 'inputs'],
  ),
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.macroOutput,
    title: 'Outputs',
    category: 'Macros',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _flow,
    keywords: ['macro', 'outputs'],
  ),
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.callMacro,
    title: 'Macro',
    category: 'Macros',
    kind: LuminaBlueprintNodeKind.flow,
    headerColor: _flow,
    keywords: ['macro', 'call'],
  ),
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.localVariableGet,
    title: 'Get',
    category: 'Variables|Local',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _variable,
    keywords: ['local', 'variable', 'get'],
    outputs: [LuminaBlueprintPinSpec('value', 'Value', LuminaPinType.float)],
  ),
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.localVariableSet,
    title: 'Set',
    category: 'Variables|Local',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _variable,
    keywords: ['local', 'variable', 'set'],
    inputs: [_execIn, LuminaBlueprintPinSpec('value', 'Value', LuminaPinType.float)],
    outputs: [_execOut, LuminaBlueprintPinSpec('value', 'Value', LuminaPinType.float)],
  ),

  // --- Event dispatchers ------------------------------------
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.callDispatcher,
    title: 'Call Dispatcher',
    category: 'Event Dispatchers',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: ['dispatcher', 'call', 'broadcast', 'event'],
    inputs: [_execIn],
    outputs: [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.bindEventToDispatcher,
    title: 'Bind Event to Dispatcher',
    category: 'Event Dispatchers',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['dispatcher', 'bind', 'event', 'assign', 'listen'],
    inputs: [_execIn, _obj('target', 'Target'), _delegate('event', 'Event')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.unbindEventFromDispatcher,
    title: 'Unbind Event from Dispatcher',
    category: 'Event Dispatchers',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['dispatcher', 'unbind', 'event', 'remove'],
    inputs: [_execIn, _obj('target', 'Target'), _delegate('event', 'Event')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.unbindAllEvents,
    title: 'Unbind all Events from Dispatcher',
    category: 'Event Dispatchers',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['dispatcher', 'unbind', 'all', 'clear'],
    inputs: [_execIn, _obj('target', 'Target')],
    outputs: const [_execOut],
  ),

  // --- Interfaces -------------------------------------------
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.interfaceMessage,
    title: 'Interface Message',
    category: 'Interface Messages',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['interface', 'message', 'call', 'implements'],
    inputs: [_execIn, _obj('target', 'Target')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.implementsInterface,
    title: 'Does Implement Interface',
    category: 'Interface Messages',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['interface', 'implements', 'has', 'is'],
    inputs: [_obj('target', 'Target')],
    outputs: [_ret(LuminaPinType.boolean)],
  ),
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.eventInterfaceFunction,
    title: 'Interface Event',
    category: 'Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: ['interface', 'event', 'implement'],
    outputs: [_execOut],
  ),

  // --- Enums ------------------------------------------------
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.enumLiteral,
    title: 'Enum Literal',
    category: 'Utilities|Enum',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['enum', 'literal', 'value', 'constant'],
    outputs: [_enum(_returnValue, 'Return Value')],
  ),
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.switchOnEnum,
    title: 'Switch on Enum',
    category: 'Flow Control|Switch',
    kind: LuminaBlueprintNodeKind.flow,
    headerColor: _flow,
    keywords: const ['switch', 'enum', 'case', 'select'],
    inputs: [_execIn, _enum('selection', 'Selection')],
  ),
  LuminaBlueprintNodeSpec(
    id: 'enum_to_string',
    title: 'Enum to String',
    category: 'Utilities|Enum',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['enum', 'string', 'name', 'convert'],
    inputs: [_enum('value', 'Value')],
    outputs: [_ret(LuminaPinType.string)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'enum_to_int',
    title: 'Enum to Int',
    category: 'Utilities|Enum',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['enum', 'int', 'index', 'convert', 'byte'],
    inputs: [_enum('value', 'Value')],
    outputs: [_ret(LuminaPinType.integer)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'int_to_enum',
    title: 'Int to Enum',
    category: 'Utilities|Enum',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['enum', 'int', 'index', 'convert', 'byte'],
    inputs: [_i('value', 'Value')],
    outputs: [_enum(_returnValue, 'Return Value')],
  ),
  LuminaBlueprintNodeSpec(
    id: 'enum_equal',
    title: 'Equal (Enum)',
    category: 'Utilities|Enum',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['enum', 'equal', '==', 'compare'],
    inputs: [_enum('a', 'A'), _enum('b', 'B')],
    outputs: [_ret(LuminaPinType.boolean)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_enum_value_count',
    title: 'Get Enum Value Count',
    category: 'Utilities|Enum',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['enum', 'count', 'length', 'values'],
    outputs: [_ret(LuminaPinType.integer)],
  ),

  // --- Timers -----------------------------------------------
  LuminaBlueprintNodeSpec(
    id: 'set_timer_by_event',
    title: 'Set Timer by Event',
    category: 'Utilities|Time',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['timer', 'event', 'delay', 'loop', 'repeat', 'schedule'],
    inputs: [_execIn, _delegate('event', 'Event'), _f('time', 'Time'), _b('looping', 'Looping'), _f('initial_start_delay', 'Initial Start Delay', -1.0)],
    outputs: [_execOut, _handle(_returnValue, 'Return Value')],
  ),
  LuminaBlueprintNodeSpec(
    id: 'set_timer_by_function_name',
    title: 'Set Timer by Function Name',
    category: 'Utilities|Time',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['timer', 'function', 'name', 'delay', 'loop', 'schedule'],
    inputs: [_execIn, _s('function_name', 'Function Name'), _f('time', 'Time'), _b('looping', 'Looping'), _f('initial_start_delay', 'Initial Start Delay', -1.0)],
    outputs: [_execOut, _handle(_returnValue, 'Return Value')],
  ),
  LuminaBlueprintNodeSpec(
    id: 'set_timer_for_next_tick',
    title: 'Set Timer for Next Tick',
    category: 'Utilities|Time',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['timer', 'next', 'tick', 'frame', 'defer'],
    inputs: [_execIn, _delegate('event', 'Event')],
    outputs: [_execOut, _handle(_returnValue, 'Return Value')],
  ),
  for (final (id, title, keywords) in const [
    ('clear_timer_by_handle', 'Clear Timer by Handle', ['timer', 'clear', 'stop', 'cancel']),
    ('pause_timer', 'Pause Timer by Handle', ['timer', 'pause']),
    ('unpause_timer', 'Unpause Timer by Handle', ['timer', 'unpause', 'resume']),
    ('clear_and_invalidate_timer', 'Clear and Invalidate Timer by Handle', ['timer', 'clear', 'invalidate']),
  ])
    LuminaBlueprintNodeSpec(
      id: id,
      title: title,
      category: 'Utilities|Time',
      kind: LuminaBlueprintNodeKind.impure,
      headerColor: _function,
      keywords: keywords,
      inputs: [_execIn, _handle('handle', 'Handle')],
      outputs: const [_execOut],
    ),
  for (final (id, title, type, keywords) in const [
    ('is_timer_active', 'Is Timer Active by Handle', LuminaPinType.boolean, ['timer', 'active', 'running']),
    ('is_timer_paused', 'Is Timer Paused by Handle', LuminaPinType.boolean, ['timer', 'paused']),
    ('get_timer_remaining_time', 'Get Timer Remaining Time by Handle', LuminaPinType.float, ['timer', 'remaining', 'time', 'left']),
    ('get_timer_elapsed_time', 'Get Timer Elapsed Time by Handle', LuminaPinType.float, ['timer', 'elapsed', 'time']),
  ])
    LuminaBlueprintNodeSpec(
      id: id,
      title: title,
      category: 'Utilities|Time',
      kind: LuminaBlueprintNodeKind.pure,
      headerColor: _pure,
      keywords: keywords,
      inputs: [_handle('handle', 'Handle')],
      outputs: [_ret(type)],
    ),

  // --- Timeline ---------------------------------------------
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.timeline,
    title: 'Timeline',
    category: 'Timeline',
    kind: LuminaBlueprintNodeKind.latent,
    headerColor: _flow,
    keywords: const ['timeline', 'curve', 'animate', 'lerp', 'tween', 'play', 'reverse'],
    inputs: [
      _exec('play', 'Play'),
      _exec('play_from_start', 'Play from Start'),
      _exec('stop', 'Stop'),
      _exec('reverse', 'Reverse'),
      _exec('reverse_from_start', 'Reverse from Start'),
      _exec('set_new_time', 'Set New Time'),
      _f('new_time', 'New Time'),
    ],
    outputs: [
      _exec('update', 'Update'),
      _exec('finished', 'Finished'),
      _enum('direction', 'Direction', LuminaBlueprintNodeLibrary.timelineDirectionEnum),
    ],
  ),
];
