part of '../node_library.dart';

/// Built-in nodes: the math library (float, int, vector,
/// rotator, transform, color), strings, arrays and hit results.
final List<LuminaBlueprintNodeSpec> _mathStringArrayNodes = <LuminaBlueprintNodeSpec>[
  // --- Math | Float --------------------------------------
  for (final (id, title, words) in const [
    ('float_min', 'Min (float)', ['minimum', 'smaller']),
    ('float_max', 'Max (float)', ['maximum', 'larger']),
    ('float_modulo', '% (float)', ['modulo', 'fmod', 'remainder']),
    ('float_power', 'Power', ['pow', 'exponent', '^']),
  ])
    _pureNode(id, title, 'Math|Float', [_f('a', id == 'float_power' ? 'Base' : 'A'), _f('b', id == 'float_power' ? 'Exp' : 'B', id == 'float_modulo' ? 1.0 : 0.0)],
        _ret(LuminaPinType.float), words),
  for (final (id, title, words) in const [
    ('float_abs', 'Absolute (float)', ['abs', 'magnitude']),
    ('float_sqrt', 'Square Root', ['sqrt', 'root']),
    ('float_sign', 'Sign (float)', ['sign', 'negative', 'positive']),
    ('float_sin', 'Sin (Degrees)', ['sine', 'trig']),
    ('float_cos', 'Cos (Degrees)', ['cosine', 'trig']),
    ('float_tan', 'Tan (Degrees)', ['tangent', 'trig']),
    ('float_asin', 'Asin (Degrees)', ['arcsine', 'trig']),
    ('float_acos', 'Acos (Degrees)', ['arccosine', 'trig']),
    ('float_atan', 'Atan (Degrees)', ['arctangent', 'trig']),
    ('degrees_to_radians', 'Degrees To Radians', ['deg', 'rad', 'convert']),
    ('radians_to_degrees', 'Radians To Degrees', ['rad', 'deg', 'convert']),
  ])
    _pureNode(id, title, 'Math|Float', [_f('a', 'A')], _ret(LuminaPinType.float), words),
  _pureNode('float_atan2', 'Atan2 (Degrees)', 'Math|Float', [_f('y', 'Y'), _f('x', 'X')], _ret(LuminaPinType.float),
      const ['arctangent', 'trig', 'angle']),
  _pureNode('float_lerp', 'Lerp', 'Math|Float', [_f('a', 'A'), _f('b', 'B'), _f('alpha', 'Alpha')], _ret(LuminaPinType.float),
      const ['interpolate', 'blend', 'mix']),
  _pureNode('float_interp_to', 'FInterp To', 'Math|Float',
      [_f('current', 'Current'), _f('target', 'Target'), _f('delta_time', 'Delta Time'), _f('interp_speed', 'Interp Speed', 1.0)],
      _ret(LuminaPinType.float), const ['interpolate', 'smooth', 'ease', 'finterp']),
  _pureNode('float_map_range_clamped', 'Map Range Clamped', 'Math|Float', [
    _f('value', 'Value'),
    _f('in_range_a', 'In Range A'),
    _f('in_range_b', 'In Range B', 1.0),
    _f('out_range_a', 'Out Range A'),
    _f('out_range_b', 'Out Range B', 1.0),
  ], _ret(LuminaPinType.float), const ['map', 'range', 'remap', 'normalize']),
  _pureNode('float_nearly_equal', 'Nearly Equal (float)', 'Math|Float',
      [_f('a', 'A'), _f('b', 'B'), _f('error_tolerance', 'Error Tolerance', 1e-6)], _ret(LuminaPinType.boolean),
      const ['equal', 'compare', 'approximately', 'tolerance']),
  for (final (id, title, words) in const [
    ('float_greater_equal', 'float >= float', ['compare', 'greater', 'equal']),
    ('float_less_equal', 'float <= float', ['compare', 'less', 'equal']),
    ('float_not_equal', 'float != float', ['compare', 'not equal', 'different']),
  ])
    _pureNode(id, title, 'Math|Float', [_f('a', 'A'), _f('b', 'B')], _ret(LuminaPinType.boolean), words),
  _pureNode('random_float_in_range', 'Random Float in Range', 'Math|Random', [_f('min', 'Min'), _f('max', 'Max', 1.0)],
      _ret(LuminaPinType.float), const ['random', 'rand', 'range']),
  _pureNode('random_bool_with_weight', 'Random Bool with Weight', 'Math|Random', [_f('weight', 'Weight', 0.5)],
      _ret(LuminaPinType.boolean), const ['random', 'chance', 'probability', 'coin']),
  _pureNode('select_float', 'Select (float)', 'Utilities|Flow Control', [_f('a', 'A'), _f('b', 'B'), _b('pick_a', 'Pick A')],
      _ret(LuminaPinType.float), const ['select', 'choose', 'ternary', 'if']),

  // --- Math | Float → Int -------------------------------------------------
  for (final (id, title, words) in const [
    ('round', 'Round', ['round', 'nearest', 'int']),
    ('truncate', 'Truncate', ['trunc', 'int', 'integer part']),
    ('ceil', 'Ceil', ['ceiling', 'round up', 'int']),
    ('floor', 'Floor', ['round down', 'int']),
  ])
    _pureNode(id, title, 'Math|Float', [_f('a', 'A')], _ret(LuminaPinType.integer), words),
  _pureNode('int_to_float', 'To Float (Integer)', 'Math|Conversions', [_i('a', 'A')], _ret(LuminaPinType.float),
      const ['convert', 'cast', 'float', 'int']),

  // --- Math | Int --------------------------------------------------------
  for (final (id, title, words) in const [
    ('int_add', 'int + int', ['plus', 'add']),
    ('int_subtract', 'int - int', ['minus', 'subtract']),
    ('int_multiply', 'int * int', ['times', 'multiply']),
    ('int_divide', 'int / int', ['divide']),
    ('int_modulo', '% (integer)', ['modulo', 'remainder', 'mod']),
    ('int_min', 'Min (int)', ['minimum', 'smaller']),
    ('int_max', 'Max (int)', ['maximum', 'larger']),
  ])
    _pureNode(id, title, 'Math|Integer', [_i('a', 'A'), _i('b', 'B', id == 'int_divide' || id == 'int_multiply' || id == 'int_modulo' ? 1 : 0)],
        _ret(LuminaPinType.integer), words),
  _pureNode('int_clamp', 'Clamp (int)', 'Math|Integer', [_i('value', 'Value'), _i('min', 'Min'), _i('max', 'Max', 100)],
      _ret(LuminaPinType.integer), const ['limit', 'min', 'max']),
  _pureNode('int_abs', 'Absolute (int)', 'Math|Integer', [_i('a', 'A')], _ret(LuminaPinType.integer), const ['abs']),
  _pureNode('int_increment', 'Increment Int', 'Math|Integer', [_i('a', 'A')], _ret(LuminaPinType.integer),
      const ['++', 'plus one', 'add', 'count']),
  for (final (id, title, words) in const [
    ('int_greater', 'int > int', ['compare', 'greater']),
    ('int_less', 'int < int', ['compare', 'less']),
    ('int_equal', 'int == int', ['compare', 'equal']),
    ('int_not_equal', 'int != int', ['compare', 'not equal']),
    ('int_greater_equal', 'int >= int', ['compare', 'greater', 'equal']),
    ('int_less_equal', 'int <= int', ['compare', 'less', 'equal']),
  ])
    _pureNode(id, title, 'Math|Integer', [_i('a', 'A'), _i('b', 'B')], _ret(LuminaPinType.boolean), words),
  _pureNode('random_integer_in_range', 'Random Integer in Range', 'Math|Random', [_i('min', 'Min'), _i('max', 'Max', 10)],
      _ret(LuminaPinType.integer), const ['random', 'rand', 'range', 'dice']),
  _pureNode('select_int', 'Select (int)', 'Utilities|Flow Control', [_i('a', 'A'), _i('b', 'B'), _b('pick_a', 'Pick A')],
      _ret(LuminaPinType.integer), const ['select', 'choose', 'ternary', 'if']),

  // --- Math | Vector -----------------------------------------------------
  _pureNode('vector_normalize', 'Normalize', 'Math|Vector', [_v('a', 'A')], _ret(LuminaPinType.vector),
      const ['unit', 'direction', 'normalise']),
  _pureNode('vector_dot', 'Dot Product', 'Math|Vector', [_v('a', 'A'), _v('b', 'B')], _ret(LuminaPinType.float),
      const ['dot', 'projection']),
  _pureNode('vector_cross', 'Cross Product', 'Math|Vector', [_v('a', 'A'), _v('b', 'B')], _ret(LuminaPinType.vector),
      const ['cross', 'perpendicular', 'normal']),
  _pureNode('vector_distance', 'Distance (Vector)', 'Math|Vector', [_v('a', 'A'), _v('b', 'B')], _ret(LuminaPinType.float),
      const ['distance', 'length', 'between', 'far']),
  _pureNode('vector_distance_2d', 'Distance 2D (Vector)', 'Math|Vector', [_v('a', 'A'), _v('b', 'B')], _ret(LuminaPinType.float),
      const ['distance', 'ground', 'horizontal', 'xy']),
  _pureNode('vector_lerp', 'Lerp (Vector)', 'Math|Vector', [_v('a', 'A'), _v('b', 'B'), _f('alpha', 'Alpha')],
      _ret(LuminaPinType.vector), const ['interpolate', 'blend', 'mix']),
  _pureNode('vector_interp_to', 'VInterp To', 'Math|Vector',
      [_v('current', 'Current'), _v('target', 'Target'), _f('delta_time', 'Delta Time'), _f('interp_speed', 'Interp Speed', 1.0)],
      _ret(LuminaPinType.vector), const ['interpolate', 'smooth', 'ease', 'vinterp']),
  _pureNode('vector_subtract', 'vector - vector', 'Math|Vector', [_v('a', 'A'), _v('b', 'B')], _ret(LuminaPinType.vector),
      const ['minus', 'subtract']),
  _pureNode('vector_divide_float', 'vector / float', 'Math|Vector', [_v('a', 'A'), _f('b', 'B', 1.0)], _ret(LuminaPinType.vector),
      const ['divide', 'scale']),
  _pureNode('vector_negate', 'Negate (Vector)', 'Math|Vector', [_v('a', 'A')], _ret(LuminaPinType.vector),
      const ['negate', 'invert', 'opposite', '-']),
  _pureNode('vector_equal', 'Equal (Vector)', 'Math|Vector', [_v('a', 'A'), _v('b', 'B'), _f('error_tolerance', 'Error Tolerance', 1e-4)],
      _ret(LuminaPinType.boolean), const ['equal', 'compare', 'tolerance']),
  _pureNode('vector_project_on_to', 'Project Vector on to Vector', 'Math|Vector', [_v('a', 'V'), _v('b', 'Target')],
      _ret(LuminaPinType.vector), const ['project', 'projection', 'onto']),
  _pureNode('rotate_vector_around_axis', 'Rotate Vector Around Axis', 'Math|Vector',
      [_v('in_vect', 'In Vect'), _f('angle_deg', 'Angle Deg'), _v('axis', 'Axis', const [0.0, 0.0, 1.0])],
      _ret(LuminaPinType.vector), const ['rotate', 'axis', 'angle', 'spin']),
  _pureNode('get_up_vector', 'Get Up Vector', 'Math|Rotator', [_rot('in_rot', 'In Rot')], _ret(LuminaPinType.vector),
      const ['direction', 'up', 'top']),
  _pureNode('random_unit_vector', 'Random Unit Vector', 'Math|Random', const [], _ret(LuminaPinType.vector),
      const ['random', 'direction', 'sphere']),
  _pureNode('vector_is_zero', 'Is Zero (Vector)', 'Math|Vector', [_v('a', 'A')], _ret(LuminaPinType.boolean),
      const ['zero', 'empty', 'null vector']),
  _pureNode('select_vector', 'Select (Vector)', 'Utilities|Flow Control', [_v('a', 'A'), _v('b', 'B'), _b('pick_a', 'Pick A')],
      _ret(LuminaPinType.vector), const ['select', 'choose', 'ternary', 'if']),

  // --- Math | Rotator ----------------------------------------------------
  _pureNode('combine_rotators', 'Combine Rotators', 'Math|Rotator', [_rot('a', 'A'), _rot('b', 'B')], _ret(LuminaPinType.rotator),
      const ['combine', 'add', 'compose', 'rotate']),
  _pureNode('delta_rotator', 'Delta (Rotator)', 'Math|Rotator', [_rot('a', 'A'), _rot('b', 'B')], _ret(LuminaPinType.rotator),
      const ['delta', 'difference', 'subtract']),
  _pureNode('rotator_lerp', 'Lerp (Rotator)', 'Math|Rotator', [_rot('a', 'A'), _rot('b', 'B'), _f('alpha', 'Alpha')],
      _ret(LuminaPinType.rotator), const ['interpolate', 'blend', 'mix', 'shortest path']),
  _pureNode('rotator_interp_to', 'RInterp To', 'Math|Rotator',
      [_rot('current', 'Current'), _rot('target', 'Target'), _f('delta_time', 'Delta Time'), _f('interp_speed', 'Interp Speed', 1.0)],
      _ret(LuminaPinType.rotator), const ['interpolate', 'smooth', 'ease', 'rinterp']),
  _pureNode('find_look_at_rotation', 'Find Look at Rotation', 'Math|Rotator', [_v('start', 'Start'), _v('target', 'Target')],
      _ret(LuminaPinType.rotator), const ['look at', 'aim', 'face', 'towards']),
  _pureNode('rotator_equal', 'Equal (Rotator)', 'Math|Rotator', [_rot('a', 'A'), _rot('b', 'B'), _f('error_tolerance', 'Error Tolerance', 1e-4)],
      _ret(LuminaPinType.boolean), const ['equal', 'compare', 'tolerance']),
  _pureNode('clamp_angle', 'Clamp Angle', 'Math|Rotator', [_f('angle_degrees', 'Angle Degrees'), _f('min_angle', 'Min Angle Degrees', -180.0), _f('max_angle', 'Max Angle Degrees', 180.0)],
      _ret(LuminaPinType.float), const ['clamp', 'angle', 'limit', 'pitch']),
  _pureNode('normalize_axis', 'Normalize Axis', 'Math|Rotator', [_f('angle', 'Angle')], _ret(LuminaPinType.float),
      const ['normalize', 'axis', 'wrap', '-180', '180']),
  _pureNode('rotator_to_vector', 'Get Rotation X Vector', 'Math|Rotator', [_rot('in_rot', 'In Rot')], _ret(LuminaPinType.vector),
      const ['forward', 'direction', 'x vector', 'to vector']),
  _pureNode('make_rot_from_x', 'Make Rot from X', 'Math|Rotator', [_v('x', 'X')], _ret(LuminaPinType.rotator),
      const ['direction', 'look', 'rotation from vector']),

  // --- Math | Transform / Color ----------------------------------------------
  _pureNode('make_transform', 'Make Transform', 'Math|Transform',
      [_v('location', 'Location'), _rot('rotation', 'Rotation'), _v('scale', 'Scale', const [1.0, 1.0, 1.0])],
      _ret(LuminaPinType.transform), const ['transform', 'make', 'location', 'rotation', 'scale']),
  LuminaBlueprintNodeSpec(
    id: 'break_transform',
    title: 'Break Transform',
    category: 'Math|Transform',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _math,
    keywords: const ['transform', 'split', 'location', 'rotation', 'scale'],
    inputs: [_xf('in_transform', 'In Transform')],
    outputs: const [
      LuminaBlueprintPinSpec('location', 'Location', LuminaPinType.vector),
      LuminaBlueprintPinSpec('rotation', 'Rotation', LuminaPinType.rotator),
      LuminaBlueprintPinSpec('scale', 'Scale', LuminaPinType.vector),
    ],
  ),
  _pureNode('compose_transforms', 'Compose Transforms', 'Math|Transform', [_xf('a', 'A'), _xf('b', 'B')], _ret(LuminaPinType.transform),
      const ['transform', 'multiply', 'combine', 'compose']),
  _pureNode('transform_location', 'Transform Location', 'Math|Transform', [_xf('t', 'T'), _v('location', 'Location')],
      _ret(LuminaPinType.vector), const ['transform', 'local to world', 'position']),
  _pureNode('inverse_transform_location', 'Inverse Transform Location', 'Math|Transform', [_xf('t', 'T'), _v('location', 'Location')],
      _ret(LuminaPinType.vector), const ['transform', 'world to local', 'inverse', 'position']),
  _pureNode('transform_direction', 'Transform Direction', 'Math|Transform', [_xf('t', 'T'), _v('direction', 'Direction')],
      _ret(LuminaPinType.vector), const ['transform', 'direction', 'rotate', 'local to world']),
  _pureNode('make_color', 'Make Color', 'Math|Color', [_f('r', 'R', 1.0), _f('g', 'G', 1.0), _f('b', 'B', 1.0), _f('a', 'A', 1.0)],
      _ret(LuminaPinType.color), const ['color', 'colour', 'rgba', 'linear color', 'make']),
  LuminaBlueprintNodeSpec(
    id: 'break_color',
    title: 'Break Color',
    category: 'Math|Color',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _math,
    keywords: const ['color', 'colour', 'split', 'rgba', 'linear color'],
    inputs: [_color('in_color', 'In Color')],
    outputs: const [
      LuminaBlueprintPinSpec('r', 'R', LuminaPinType.float),
      LuminaBlueprintPinSpec('g', 'G', LuminaPinType.float),
      LuminaBlueprintPinSpec('b', 'B', LuminaPinType.float),
      LuminaBlueprintPinSpec('a', 'A', LuminaPinType.float),
    ],
  ),
  _pureNode('color_lerp', 'Lerp (Color)', 'Math|Color', [_color('a', 'A'), _color('b', 'B'), _f('alpha', 'Alpha')],
      _ret(LuminaPinType.color), const ['color', 'colour', 'interpolate', 'blend', 'mix']),
  _pureNode('hex_to_color', 'Hex to Color', 'Math|Color', [_s('hex', 'Hex', '#FFFFFFFF')], _ret(LuminaPinType.color),
      const ['color', 'colour', 'hex', 'parse', 'html']),
  _pureNode('color_to_hex', 'Color to Hex', 'Math|Color', [_color('in_color', 'In Color')], _ret(LuminaPinType.string),
      const ['color', 'colour', 'hex', 'string', 'html']),

  // --- String / Conversion -------------------------------------------------
  _pureNode('float_to_string', 'To String (float)', 'Utilities|String', [_f('in_float', 'In Float'), _i('decimals', 'Decimals', 2)],
      _ret(LuminaPinType.string), const ['convert', 'string', 'text', 'float', 'fps', 'to string']),
  _pureNode('int_to_string', 'To String (int)', 'Utilities|String', [_i('in_int', 'In Int')], _ret(LuminaPinType.string),
      const ['convert', 'string', 'text', 'int', 'fps', 'to string']),
  _pureNode('bool_to_string', 'To String (bool)', 'Utilities|String', [_b('in_bool', 'In Bool')], _ret(LuminaPinType.string),
      const ['convert', 'string', 'text', 'bool', 'to string']),
  _pureNode('vector_to_string', 'To String (Vector)', 'Utilities|String', [_v('in_vec', 'In Vec')], _ret(LuminaPinType.string),
      const ['convert', 'string', 'text', 'vector', 'to string']),
  _pureNode('rotator_to_string', 'To String (Rotator)', 'Utilities|String', [_rot('in_rot', 'In Rot')], _ret(LuminaPinType.string),
      const ['convert', 'string', 'text', 'rotator', 'to string']),
  _pureNode('string_to_float', 'String to Float', 'Utilities|String', [_s('in_string', 'In String')], _ret(LuminaPinType.float),
      const ['convert', 'parse', 'float', 'number']),
  _pureNode('string_to_int', 'String to Int', 'Utilities|String', [_s('in_string', 'In String')], _ret(LuminaPinType.integer),
      const ['convert', 'parse', 'int', 'number']),
  _pureNode('append', 'Append', 'Utilities|String', [_s('a', 'A'), _s('b', 'B')], _ret(LuminaPinType.string),
      const ['concat', 'concatenate', 'join', '+', 'string', 'fps']),
  _pureNode('append_3', 'Append (3)', 'Utilities|String', [_s('a', 'A'), _s('b', 'B'), _s('c', 'C')], _ret(LuminaPinType.string),
      const ['concat', 'concatenate', 'join', '+', 'string']),
  _pureNode('format_string', 'Format Text', 'Utilities|String', [
    _s('format', 'Format', 'FPS: {0}'),
    _s('arg_0', '{0}'),
    _s('arg_1', '{1}'),
    _s('arg_2', '{2}'),
    _s('arg_3', '{3}'),
  ], _ret(LuminaPinType.string), const ['format', 'text', 'string', 'template', 'placeholder', 'fps']),
  _pureNode('string_length', 'Length (String)', 'Utilities|String', [_s('s', 'S')], _ret(LuminaPinType.integer),
      const ['length', 'count', 'characters', 'len']),
  _pureNode('string_equal', 'Equal (String)', 'Utilities|String', [_s('a', 'A'), _s('b', 'B'), _b('case_sensitive', 'Case Sensitive', true)],
      _ret(LuminaPinType.boolean), const ['equal', 'compare', 'same', 'string']),
  _pureNode('string_contains', 'Contains (String)', 'Utilities|String', [_s('search_in', 'Search In'), _s('substring', 'Substring'), _b('use_case', 'Use Case', true)],
      _ret(LuminaPinType.boolean), const ['contains', 'find', 'substring', 'search']),
  _pureNode('string_replace', 'Replace', 'Utilities|String', [_s('source_string', 'Source String'), _s('from', 'From'), _s('to', 'To')],
      _ret(LuminaPinType.string), const ['replace', 'substitute', 'string']),
  _pureNode('string_to_upper', 'To Upper', 'Utilities|String', [_s('s', 'S')], _ret(LuminaPinType.string), const ['upper', 'uppercase', 'capital']),
  _pureNode('string_to_lower', 'To Lower', 'Utilities|String', [_s('s', 'S')], _ret(LuminaPinType.string), const ['lower', 'lowercase']),
  _pureNode('string_substring', 'Get Substring', 'Utilities|String', [_s('s', 'S'), _i('start_index', 'Start Index'), _i('length', 'Length', 1)],
      _ret(LuminaPinType.string), const ['substring', 'slice', 'part', 'mid']),
  LuminaBlueprintNodeSpec(
    id: 'string_split',
    title: 'Parse Into Array',
    category: 'Utilities|String',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['split', 'parse', 'array', 'separator', 'tokens'],
    inputs: [_s('s', 'S'), _s('separator', 'Separator', ' ')],
    outputs: const [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.array, elementType: LuminaPinType.string)],
  ),
  _pureNode('string_is_empty', 'Is Empty (String)', 'Utilities|String', [_s('s', 'S')], _ret(LuminaPinType.boolean), const ['empty', 'blank', 'none']),
  _pureNode('string_trim', 'Trim', 'Utilities|String', [_s('s', 'S')], _ret(LuminaPinType.string), const ['trim', 'whitespace', 'strip']),
  _pureNode('select_string', 'Select (String)', 'Utilities|Flow Control', [_s('a', 'A'), _s('b', 'B'), _b('pick_a', 'Pick A')],
      _ret(LuminaPinType.string), const ['select', 'choose', 'ternary', 'if']),
  _pureNode('select_bool', 'Select (bool)', 'Utilities|Flow Control', [_b('a', 'A'), _b('b', 'B'), _b('pick_a', 'Pick A')],
      _ret(LuminaPinType.boolean), const ['select', 'choose', 'ternary', 'if']),
  _pureNode('select_object', 'Select (Object)', 'Utilities|Flow Control', [_obj('a', 'A'), _obj('b', 'B'), _b('pick_a', 'Pick A')],
      _ret(LuminaPinType.object), const ['select', 'choose', 'ternary', 'if']),

  // --- Array ------------------------------------------------
  _pureNode('array_length', 'Length (Array)', 'Utilities|Array', [_arr('target_array', 'Target Array')], _ret(LuminaPinType.integer),
      const ['array', 'length', 'count', 'num', 'size']),
  _pureNode('array_get', 'Get (a copy)', 'Utilities|Array', [_arr('target_array', 'Target Array'), _i('index', 'Index')],
      _any(_returnValue, 'Item'), const ['array', 'get', 'index', 'element', 'item']),
  _pureNode('array_last_index', 'Last Index', 'Utilities|Array', [_arr('target_array', 'Target Array')], _ret(LuminaPinType.integer),
      const ['array', 'last', 'index', 'length']),
  _pureNode('array_is_empty', 'Is Empty (Array)', 'Utilities|Array', [_arr('target_array', 'Target Array')], _ret(LuminaPinType.boolean),
      const ['array', 'empty', 'none']),
  _pureNode('array_contains', 'Contains Item', 'Utilities|Array', [_arr('target_array', 'Target Array'), _any('item_to_find', 'Item To Find')],
      _ret(LuminaPinType.boolean), const ['array', 'contains', 'find', 'has', 'includes']),
  _pureNode('array_find', 'Find Item', 'Utilities|Array', [_arr('target_array', 'Target Array'), _any('item_to_find', 'Item To Find')],
      _ret(LuminaPinType.integer), const ['array', 'find', 'index of', 'search']),
  _pureNode('array_first', 'First (Array)', 'Utilities|Array', [_arr('target_array', 'Target Array')], _any(_returnValue, 'Item'),
      const ['array', 'first', 'head']),
  _pureNode('array_last', 'Last (Array)', 'Utilities|Array', [_arr('target_array', 'Target Array')], _any(_returnValue, 'Item'),
      const ['array', 'last', 'tail']),
  LuminaBlueprintNodeSpec(
    id: 'make_array',
    title: 'Make Array',
    category: 'Utilities|Array',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['array', 'make', 'list', 'new', 'literal'],
    inputs: [_any('item_0', '[0]'), _any('item_1', '[1]')],
    outputs: [_arr(_returnValue, 'Array')],
  ),
  LuminaBlueprintNodeSpec(
    id: 'array_add',
    title: 'Add (Array)',
    category: 'Utilities|Array',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['array', 'add', 'push', 'append', 'insert'],
    inputs: [_execIn, _arr('target_array', 'Target Array'), _any('new_item', 'New Item')],
    outputs: [_execOut, _ret(LuminaPinType.integer, name: 'Index')],
  ),
  LuminaBlueprintNodeSpec(
    id: 'array_remove_index',
    title: 'Remove Index',
    category: 'Utilities|Array',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['array', 'remove', 'delete', 'index'],
    inputs: [_execIn, _arr('target_array', 'Target Array'), _i('index', 'Index')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'array_clear',
    title: 'Clear (Array)',
    category: 'Utilities|Array',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['array', 'clear', 'empty', 'reset'],
    inputs: [_execIn, _arr('target_array', 'Target Array')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'array_set',
    title: 'Set Array Elem',
    category: 'Utilities|Array',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['array', 'set', 'index', 'element', 'assign'],
    inputs: [_execIn, _arr('target_array', 'Target Array'), _i('index', 'Index'), _any('item', 'Item'), _b('size_to_fit', 'Size to Fit')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'array_filter_by_class',
    title: 'Filter Array',
    category: 'Utilities|Array',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['array', 'filter', 'class', 'of type', 'where'],
    inputs: [
      const LuminaBlueprintPinSpec('target_array', 'Target Array', LuminaPinType.array, elementType: LuminaPinType.object),
      _s('class', 'Class', 'Actor:LuminaActor'),
    ],
    outputs: const [LuminaBlueprintPinSpec(_returnValue, 'Filtered Array', LuminaPinType.array, elementType: LuminaPinType.object)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'array_shuffle',
    title: 'Shuffle (Array)',
    category: 'Utilities|Array',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['array', 'shuffle', 'random', 'order'],
    inputs: [_execIn, _arr('target_array', 'Target Array')],
    outputs: const [_execOut],
  ),

  // --- Structs: hit result ---------------------------------------------------
  LuminaBlueprintNodeSpec(
    id: 'break_hit_result',
    title: 'Break Hit Result',
    category: 'Collision',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _math,
    keywords: const ['hit', 'trace', 'break', 'impact', 'collision', 'result'],
    inputs: const [LuminaBlueprintPinSpec('hit', 'Hit', LuminaPinType.hitResult)],
    outputs: [
      const LuminaBlueprintPinSpec('blocking_hit', 'Blocking Hit', LuminaPinType.boolean),
      const LuminaBlueprintPinSpec('location', 'Location', LuminaPinType.vector),
      const LuminaBlueprintPinSpec('impact_point', 'Impact Point', LuminaPinType.vector),
      const LuminaBlueprintPinSpec('normal', 'Normal', LuminaPinType.vector),
      const LuminaBlueprintPinSpec('impact_normal', 'Impact Normal', LuminaPinType.vector),
      const LuminaBlueprintPinSpec('time', 'Time', LuminaPinType.float),
      const LuminaBlueprintPinSpec('distance', 'Distance', LuminaPinType.float),
      const LuminaBlueprintPinSpec('trace_start', 'Trace Start', LuminaPinType.vector),
      const LuminaBlueprintPinSpec('trace_end', 'Trace End', LuminaPinType.vector),
      _obj('hit_actor', 'Hit Actor', LuminaBlueprintObjectClass.anyActor),
      _comp(LuminaBlueprintNodeLibrary._coll, 'hit_component', 'Hit Component'),
    ],
  ),
  LuminaBlueprintNodeSpec(
    id: 'make_hit_result',
    title: 'Make Hit Result',
    category: 'Collision',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _math,
    keywords: const ['hit', 'make', 'result', 'test'],
    inputs: [
      _b('blocking_hit', 'Blocking Hit'),
      _v('location', 'Location'),
      _v('impact_point', 'Impact Point'),
      _v('impact_normal', 'Impact Normal', const [0.0, 0.0, 1.0]),
      _f('distance', 'Distance'),
      _obj('hit_actor', 'Hit Actor', LuminaBlueprintObjectClass.anyActor),
      _comp(LuminaBlueprintNodeLibrary._coll, 'hit_component', 'Hit Component'),
    ],
    outputs: const [LuminaBlueprintPinSpec(_returnValue, 'Hit', LuminaPinType.hitResult)],
  ),
];
