part of '../node_library.dart';

/// Built-in nodes: math structs, vectors and floats, objects and casting,
/// widget elements, components and physics.
final List<LuminaBlueprintNodeSpec> _mathObjectComponentNodes = <LuminaBlueprintNodeSpec>[
  // --- Math: structs -------------------------------------------------
  LuminaBlueprintNodeSpec(
    id: 'make_vector2d',
    title: 'Make Vector2D',
    category: 'Math|Vector2D',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _math,
    inputs: [_f('x', 'X'), _f('y', 'Y')],
    outputs: const [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.vector2D)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'break_vector2d',
    title: 'Break Vector2D',
    category: 'Math|Vector2D',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _math,
    keywords: ['split', 'axis'],
    inputs: [LuminaBlueprintPinSpec('in_vec', 'In Vec', LuminaPinType.vector2D, required: true)],
    outputs: [
      LuminaBlueprintPinSpec('x', 'X', LuminaPinType.float),
      LuminaBlueprintPinSpec('y', 'Y', LuminaPinType.float),
    ],
  ),
  LuminaBlueprintNodeSpec(
    id: 'make_vector',
    title: 'Make Vector',
    category: 'Math|Vector',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _math,
    inputs: [_f('x', 'X'), _f('y', 'Y'), _f('z', 'Z')],
    outputs: const [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.vector)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'break_vector',
    title: 'Break Vector',
    category: 'Math|Vector',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _math,
    keywords: ['split'],
    inputs: [LuminaBlueprintPinSpec('in_vec', 'In Vec', LuminaPinType.vector, required: true)],
    outputs: [
      LuminaBlueprintPinSpec('x', 'X', LuminaPinType.float),
      LuminaBlueprintPinSpec('y', 'Y', LuminaPinType.float),
      LuminaBlueprintPinSpec('z', 'Z', LuminaPinType.float),
    ],
  ),
  LuminaBlueprintNodeSpec(
    id: 'make_rotator',
    title: 'Make Rotator',
    category: 'Math|Rotator',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _math,
    inputs: [_f('x', 'X (Pitch)'), _f('y', 'Y (Roll)'), _f('z', 'Z (Yaw)')],
    outputs: const [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.rotator)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'break_rotator',
    title: 'Break Rotator',
    category: 'Math|Rotator',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _math,
    keywords: ['split', 'yaw', 'pitch', 'roll'],
    inputs: [LuminaBlueprintPinSpec('in_rot', 'In Rot', LuminaPinType.rotator, required: true)],
    outputs: [
      LuminaBlueprintPinSpec('x', 'X (Pitch)', LuminaPinType.float),
      LuminaBlueprintPinSpec('y', 'Y (Roll)', LuminaPinType.float),
      LuminaBlueprintPinSpec('z', 'Z (Yaw)', LuminaPinType.float),
    ],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'get_forward_vector',
    title: 'Get Forward Vector',
    category: 'Math|Rotator',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _math,
    keywords: ['direction', 'front'],
    inputs: [LuminaBlueprintPinSpec('in_rot', 'In Rot', LuminaPinType.rotator, defaultValue: [0.0, 0.0, 0.0])],
    outputs: [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.vector)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'get_right_vector',
    title: 'Get Right Vector',
    category: 'Math|Rotator',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _math,
    keywords: ['direction', 'side', 'strafe'],
    inputs: [LuminaBlueprintPinSpec('in_rot', 'In Rot', LuminaPinType.rotator, defaultValue: [0.0, 0.0, 0.0])],
    outputs: [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.vector)],
  ),

  // --- Math: vectors and floats ----------------------------------------
  const LuminaBlueprintNodeSpec(
    id: 'vector_length',
    title: 'Vector Length',
    category: 'Math|Vector',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _math,
    keywords: ['size', 'magnitude', 'speed'],
    inputs: [LuminaBlueprintPinSpec('in_vec', 'Vector', LuminaPinType.vector, defaultValue: [0.0, 0.0, 0.0])],
    outputs: [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.float)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'vector_length_xy',
    title: 'Vector Length XY',
    category: 'Math|Vector',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _math,
    keywords: ['size', 'ground', 'speed', 'horizontal'],
    inputs: [LuminaBlueprintPinSpec('in_vec', 'Vector', LuminaPinType.vector, defaultValue: [0.0, 0.0, 0.0])],
    outputs: [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.float)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'vector_scale',
    title: 'vector * float',
    category: 'Math|Vector',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _math,
    keywords: const ['multiply', 'scale'],
    inputs: [
      const LuminaBlueprintPinSpec('a', 'A', LuminaPinType.vector, defaultValue: [0.0, 0.0, 0.0]),
      _f('b', 'B', 1.0),
    ],
    outputs: const [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.vector)],
  ),
  const LuminaBlueprintNodeSpec(
    id: 'vector_add',
    title: 'vector + vector',
    category: 'Math|Vector',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _math,
    keywords: ['plus', 'add'],
    inputs: [
      LuminaBlueprintPinSpec('a', 'A', LuminaPinType.vector, defaultValue: [0.0, 0.0, 0.0]),
      LuminaBlueprintPinSpec('b', 'B', LuminaPinType.vector, defaultValue: [0.0, 0.0, 0.0]),
    ],
    outputs: [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.vector)],
  ),
  for (final (id, title, words) in const [
    ('float_add', 'float + float', ['plus', 'add']),
    ('float_subtract', 'float - float', ['minus', 'subtract']),
    ('float_multiply', 'float * float', ['times', 'multiply']),
    ('float_divide', 'float / float', ['divide']),
  ])
    LuminaBlueprintNodeSpec(
      id: id,
      title: title,
      category: 'Math|Float',
      kind: LuminaBlueprintNodeKind.pure,
      headerColor: _math,
      keywords: words,
      inputs: [_f('a', 'A'), _f('b', 'B', id == 'float_divide' || id == 'float_multiply' ? 1.0 : 0.0)],
      outputs: const [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.float)],
    ),
  LuminaBlueprintNodeSpec(
    id: 'float_clamp',
    title: 'Clamp (float)',
    category: 'Math|Float',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _math,
    keywords: const ['limit', 'min', 'max'],
    inputs: [_f('value', 'Value'), _f('min', 'Min'), _f('max', 'Max', 1.0)],
    outputs: const [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.float)],
  ),
  for (final (id, title) in const [
    ('float_greater', 'float > float'),
    ('float_less', 'float < float'),
    ('float_equal', 'float == float'),
  ])
    LuminaBlueprintNodeSpec(
      id: id,
      title: title,
      category: 'Math|Float',
      kind: LuminaBlueprintNodeKind.pure,
      headerColor: _math,
      keywords: const ['compare'],
      inputs: [_f('a', 'A'), _f('b', 'B')],
      outputs: const [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.boolean)],
    ),
  for (final (id, title) in const [('bool_and', 'AND Boolean'), ('bool_or', 'OR Boolean')])
    LuminaBlueprintNodeSpec(
      id: id,
      title: title,
      category: 'Math|Boolean',
      kind: LuminaBlueprintNodeKind.pure,
      headerColor: _math,
      keywords: const ['logic'],
      inputs: const [
        LuminaBlueprintPinSpec('a', 'A', LuminaPinType.boolean, defaultValue: false),
        LuminaBlueprintPinSpec('b', 'B', LuminaPinType.boolean, defaultValue: false),
      ],
      outputs: const [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.boolean)],
    ),
  const LuminaBlueprintNodeSpec(
    id: 'bool_not',
    title: 'NOT Boolean',
    category: 'Math|Boolean',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _math,
    keywords: ['logic', 'invert'],
    inputs: [LuminaBlueprintPinSpec('a', 'A', LuminaPinType.boolean, defaultValue: false)],
    outputs: [LuminaBlueprintPinSpec(_returnValue, 'Return Value', LuminaPinType.boolean)],
  ),

  // --- Objects, casting and validity --------------------
  LuminaBlueprintNodeSpec(
    id: 'is_valid',
    title: 'Is Valid',
    category: 'Utilities',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['valid', 'null', 'none', 'exists', 'object'],
    inputs: [_obj('input_object', 'Input Object')],
    outputs: [_ret(LuminaPinType.boolean)],
  ),
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.isValidBranch,
    title: 'Is Valid',
    category: 'Utilities',
    kind: LuminaBlueprintNodeKind.flow,
    headerColor: _flow,
    keywords: const ['valid', 'null', 'none', 'branch', '?', 'is valid?'],
    inputs: [_execIn, _obj('input_object', 'Input Object')],
    outputs: const [
      LuminaBlueprintPinSpec('is_valid', 'Is Valid', LuminaPinType.exec),
      LuminaBlueprintPinSpec('is_not_valid', 'Is Not Valid', LuminaPinType.exec),
    ],
  ),
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.castTo,
    title: 'Cast To',
    category: 'Utilities|Casting',
    kind: LuminaBlueprintNodeKind.flow,
    headerColor: _flow,
    keywords: const ['cast', 'as', 'convert', 'class', 'type'],
    inputs: [_execIn, _obj('object', 'Object'), _s('class', 'Class')],
    outputs: [
      const LuminaBlueprintPinSpec('cast_succeeded', 'Cast Succeeded', LuminaPinType.exec),
      const LuminaBlueprintPinSpec('cast_failed', 'Cast Failed', LuminaPinType.exec),
      _obj('as_class', 'As Class'),
    ],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_class_name',
    title: 'Get Class Name',
    category: 'Utilities',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['class', 'type', 'name', 'object'],
    inputs: [_obj('object', 'Object')],
    outputs: [_ret(LuminaPinType.string)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'is_a',
    title: 'Is A',
    category: 'Utilities',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['is a', 'class', 'instance', 'type', 'kind of'],
    inputs: [_obj('object', 'Object'), _s('class', 'Class')],
    outputs: [_ret(LuminaPinType.boolean)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_display_name',
    title: 'Get Display Name',
    category: 'Utilities',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['name', 'label', 'object', 'actor'],
    inputs: [_obj('object', 'Object')],
    outputs: [_ret(LuminaPinType.string)],
  ),

  // --- Widget elements ------------------------------------
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.getWidgetElement,
    title: 'Get Element',
    category: 'Widget',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _variable,
    keywords: const ['widget', 'element', 'get', 'bind', 'ui'],
    inputs: [
      _obj('target', 'Target', LuminaBlueprintObjectClass.widgetKind),
      const LuminaBlueprintPinSpec('element', 'Element', LuminaPinType.name, defaultValue: ''),
    ],
    outputs: [_ret(LuminaPinType.object, cls: LuminaBlueprintObjectClass.widgetElementKind)],
  ),
  // ESlateVisibility, strings at run time.
  _elementSet('set_element_visibility', 'Set Visibility', 'Widget|Common', null,
      const LuminaBlueprintPinSpec('in_visibility', 'In Visibility', LuminaPinType.enumeration,
          defaultValue: 'Visible', enumName: LuminaBlueprintNodeLibrary.slateVisibilityEnum),
      const ['visibility', 'hidden', 'collapsed', 'show', 'hide', 'eslatevisibility']),
  _elementGet('get_element_visibility', 'Get Visibility', 'Widget|Common', null, LuminaPinType.string,
      const ['visibility', 'hidden', 'collapsed']),
  _elementGet('is_element_visible', 'Is Visible', 'Widget|Common', null, LuminaPinType.boolean,
      const ['visibility', 'visible', 'shown']),
  _elementSet('set_element_is_enabled', 'Set Is Enabled', 'Widget|Common', null,
      _b('in_is_enabled', 'In Is Enabled', true), const ['enabled', 'disabled', 'interactive']),
  _elementGet('get_element_is_enabled', 'Get Is Enabled', 'Widget|Common', null, LuminaPinType.boolean,
      const ['enabled', 'disabled']),
  _elementSet('set_element_render_opacity', 'Set Render Opacity', 'Widget|Common', null,
      _f('in_opacity', 'In Opacity', 1.0), const ['opacity', 'alpha', 'fade', 'transparent']),
  _elementSet('set_element_text', 'Set Text (Text)', 'Widget|Text', 'text', _s('in_text', 'In Text'),
      const ['text', 'label', 'string', 'text block', 'fps']),
  _elementGet('get_element_text', 'Get Text (Text)', 'Widget|Text', 'text', LuminaPinType.string,
      const ['text', 'label', 'string', 'text block']),
  _elementSet('set_element_color', 'Set Color and Opacity', 'Widget|Text', 'text', _color('in_color', 'In Color and Opacity'),
      const ['color', 'colour', 'tint', 'opacity', 'text']),
  _elementSet('set_element_font_size', 'Set Font Size', 'Widget|Text', 'text', _f('in_size', 'In Size', 24.0),
      const ['font', 'size', 'text']),
  // The shadow and outline of any text-bearing element (Text,
  // and the labels of Button, Check Box, Editable Text and Combo Box).
  _elementSet('set_element_shadow_enabled', 'Set Shadow Enabled', 'Widget|Text', null,
      _b('in_enabled', 'In Enabled', true), const ['shadow', 'drop shadow', 'text', 'label']),
  _elementSet('set_element_shadow_color', 'Set Shadow Color and Opacity', 'Widget|Text', null,
      _color('in_color', 'In Color and Opacity', const [0.0, 0.0, 0.0, 0.7]),
      const ['shadow', 'color', 'colour', 'opacity', 'text']),
  _elementSet('set_element_shadow_offset', 'Set Shadow Offset', 'Widget|Text', null,
      const LuminaBlueprintPinSpec('in_offset', 'In Offset', LuminaPinType.vector2D, defaultValue: [1.0, 1.0]),
      const ['shadow', 'offset', 'text']),
  LuminaBlueprintNodeSpec(
    id: 'set_element_outline',
    title: 'Set Outline',
    category: 'Widget|Text',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['widget', 'ui', 'element', 'outline', 'stroke', 'border', 'text', 'font'],
    inputs: [_execIn, _element(), _f('in_size', 'In Size', 1.0), _color('in_color', 'In Color', const [0.0, 0.0, 0.0, 1.0])],
    outputs: const [_execOut],
  ),
  _elementSet('set_element_percent', 'Set Percent', 'Widget|Progress Bar', 'progressBar',
      _f('in_percent', 'In Percent', 1.0), const ['progress', 'bar', 'percent', 'health', 'fill']),
  _elementGet('get_element_percent', 'Get Percent', 'Widget|Progress Bar', 'progressBar', LuminaPinType.float,
      const ['progress', 'bar', 'percent']),
  _elementSet('set_element_fill_color', 'Set Fill Color and Opacity', 'Widget|Progress Bar', 'progressBar',
      _color('in_color', 'In Color'), const ['progress', 'bar', 'color', 'colour', 'fill']),
  _elementSet('set_element_brush_from_texture', 'Set Brush from Texture', 'Widget|Image', 'image',
      _s('texture', 'Texture'), const ['image', 'brush', 'texture', 'picture', 'icon']),
  _elementSet('set_element_image_color', 'Set Color and Opacity (Image)', 'Widget|Image', 'image',
      _color('in_color', 'In Color and Opacity'), const ['image', 'color', 'colour', 'tint', 'opacity']),
  _elementSet('set_element_label', 'Set Label', 'Widget|Button', 'button', _s('in_label', 'In Label'),
      const ['button', 'label', 'caption', 'text']),
  _elementSet('set_element_slider_value', 'Set Value (Slider)', 'Widget|Slider', 'slider', _f('in_value', 'In Value'),
      const ['slider', 'value']),
  _elementGet('get_element_slider_value', 'Get Value (Slider)', 'Widget|Slider', 'slider', LuminaPinType.float,
      const ['slider', 'value']),
  _elementSet('set_element_is_checked', 'Set Is Checked', 'Widget|Check Box', 'checkBox',
      _b('in_is_checked', 'In Is Checked'), const ['check', 'checkbox', 'toggle', 'checked', 'checked state', 'set checked state']),
  _elementGet('get_element_is_checked', 'Is Checked', 'Widget|Check Box', 'checkBox', LuminaPinType.boolean,
      const ['check', 'checkbox', 'toggle', 'checked']),
  _elementSet('set_element_editable_text', 'Set Text (Editable Text)', 'Widget|Editable Text', 'editableText',
      _s('in_text', 'In Text'), const ['editable', 'text', 'input', 'field']),
  _elementGet('get_element_editable_text', 'Get Text (Editable Text)', 'Widget|Editable Text', 'editableText',
      LuminaPinType.string, const ['editable', 'text', 'input', 'field']),
  _elementSet('set_element_hint_text', 'Set Hint Text', 'Widget|Editable Text', 'editableText',
      _s('in_hint_text', 'In Hint Text'), const ['editable', 'hint', 'placeholder']),
  // The Combo Box nodes: node_library/combo_box.dart.
  _elementSet('set_element_active_index', 'Set Active Widget Index', 'Widget|Widget Switcher', 'widgetSwitcher',
      _i('index', 'Index'), const ['switcher', 'active', 'index', 'page', 'tab']),
  _elementGet('get_element_active_index', 'Get Active Widget Index', 'Widget|Widget Switcher', 'widgetSwitcher',
      LuminaPinType.integer, const ['switcher', 'active', 'index', 'page', 'tab']),
  // The Container's background, border, corners and padding.
  _elementSet('set_element_background_color', 'Set Background Color', 'Widget|Container', 'container',
      _color('in_color', 'In Color', const [0.1, 0.1, 0.1, 1.0]), const ['container', 'background', 'color', 'colour', 'fill', 'brush']),
  _elementSet('set_element_border_color', 'Set Border Color', 'Widget|Container', 'container',
      _color('in_color', 'In Color'), const ['container', 'border', 'outline', 'color', 'colour']),
  _elementSet('set_element_corner_radius', 'Set Corner Radius', 'Widget|Container', 'container',
      _f('in_radius', 'In Radius', 8.0), const ['container', 'corner', 'radius', 'rounded', 'round']),
  LuminaBlueprintNodeSpec(
    id: 'set_element_padding',
    title: 'Set Padding',
    category: 'Widget|Container',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['widget', 'ui', 'element', 'container', 'padding', 'margin', 'inset', 'spacing'],
    inputs: [_execIn, _element('container'), _f('left', 'Left'), _f('top', 'Top'), _f('right', 'Right'), _f('bottom', 'Bottom')],
    outputs: const [_execOut],
  ),

  // --- Components -----------------------------------------
  LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.getComponent,
    title: 'Get Component',
    category: 'Components',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _variable,
    keywords: const ['component', 'get', 'self', 'boom', 'camera', 'mesh', 'movement'],
    inputs: const [LuminaBlueprintPinSpec('component', 'Component', LuminaPinType.name, defaultValue: '')],
    outputs: [_ret(LuminaPinType.object, cls: LuminaBlueprintObjectClass.componentKind)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_component_by_class',
    title: 'Get Component by Class',
    category: 'Components',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['component', 'class', 'find', 'get'],
    inputs: [_s('class', 'Component Class', 'Component:LuminaSceneComponent')],
    outputs: [_ret(LuminaPinType.object, cls: LuminaBlueprintObjectClass.componentKind)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'add_component',
    title: 'Add Component',
    category: 'Components',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['component', 'add', 'create', 'spawn', 'new'],
    inputs: [_execIn, _s('class', 'Component Class', 'Component:LuminaSceneComponent'), _s('name', 'Name')],
    outputs: [_execOut, _ret(LuminaPinType.object, cls: LuminaBlueprintObjectClass.componentKind)],
  ),
  _compSet('set_relative_location', 'Set Relative Location', 'Components|Transform', LuminaBlueprintNodeLibrary._scene,
      [_v('new_location', 'New Location')], const ['location', 'position', 'relative', 'move']),
  _compSet('set_relative_rotation', 'Set Relative Rotation', 'Components|Transform', LuminaBlueprintNodeLibrary._scene,
      [_rot('new_rotation', 'New Rotation')], const ['rotation', 'relative', 'rotate']),
  _compSet('set_relative_scale', 'Set Relative Scale 3D', 'Components|Transform', LuminaBlueprintNodeLibrary._scene,
      [_v('new_scale', 'New Scale 3D', const [1.0, 1.0, 1.0])], const ['scale', 'relative', 'size']),
  _compGet('get_relative_location', 'Get Relative Location', 'Components|Transform', LuminaBlueprintNodeLibrary._scene,
      _ret(LuminaPinType.vector), const ['location', 'position', 'relative']),
  _compGet('get_relative_rotation', 'Get Relative Rotation', 'Components|Transform', LuminaBlueprintNodeLibrary._scene,
      _ret(LuminaPinType.rotator), const ['rotation', 'relative']),
  _compGet('get_relative_scale', 'Get Relative Scale 3D', 'Components|Transform', LuminaBlueprintNodeLibrary._scene,
      _ret(LuminaPinType.vector), const ['scale', 'relative']),
  _compSet('set_world_location', 'Set World Location', 'Components|Transform', LuminaBlueprintNodeLibrary._scene,
      [_v('new_location', 'New Location')], const ['location', 'position', 'world', 'move']),
  _compSet('set_world_rotation', 'Set World Rotation', 'Components|Transform', LuminaBlueprintNodeLibrary._scene,
      [_rot('new_rotation', 'New Rotation')], const ['rotation', 'world', 'rotate']),
  _compGet('get_world_location', 'Get World Location', 'Components|Transform', LuminaBlueprintNodeLibrary._scene, _ret(LuminaPinType.vector),
      const ['location', 'position', 'world']),
  _compGet('get_world_rotation', 'Get World Rotation', 'Components|Transform', LuminaBlueprintNodeLibrary._scene, _ret(LuminaPinType.rotator),
      const ['rotation', 'world']),
  _compSet('attach_to_component', 'Attach Component To Component', 'Components|Transform', LuminaBlueprintNodeLibrary._scene, [
    _comp(LuminaBlueprintNodeLibrary._scene, 'parent', 'Parent'),
    const LuminaBlueprintPinSpec('socket_name', 'Socket Name', LuminaPinType.name, defaultValue: ''),
  ], const ['attach', 'parent', 'socket', 'child']),
  _compSet('set_component_visibility', 'Set Visibility (Component)', 'Components|Rendering', LuminaBlueprintNodeLibrary._scene,
      [_b('new_visibility', 'New Visibility', true)], const ['visibility', 'visible', 'hide', 'show', 'render']),
  _compSet('set_hidden_in_game', 'Set Hidden In Game', 'Components|Rendering', LuminaBlueprintNodeLibrary._scene,
      [_b('new_hidden', 'New Hidden')], const ['hidden', 'visibility', 'hide', 'show', 'render']),
  _compGet('get_socket_location', 'Get Socket Location', 'Components|Transform', LuminaBlueprintNodeLibrary._scene, _ret(LuminaPinType.vector),
      const ['socket', 'bone', 'location', 'attach'],
      [const LuminaBlueprintPinSpec('in_socket_name', 'In Socket Name', LuminaPinType.name, defaultValue: '')]),
  _compSet('set_target_arm_length', 'Set Target Arm Length', 'Components|Spring Arm', LuminaBlueprintNodeLibrary._arm,
      [_f('target_arm_length', 'Target Arm Length', 300.0)], const ['spring', 'arm', 'boom', 'length', 'zoom', 'camera']),
  _compGet('get_target_arm_length', 'Get Target Arm Length', 'Components|Spring Arm', LuminaBlueprintNodeLibrary._arm, _ret(LuminaPinType.float),
      const ['spring', 'arm', 'boom', 'length', 'camera']),
  _compSet('set_camera_lag_enabled', 'Set Enable Camera Lag', 'Components|Spring Arm', LuminaBlueprintNodeLibrary._arm,
      [_b('enabled', 'Enabled', true)], const ['spring', 'arm', 'lag', 'camera', 'smooth']),
  _compSet('set_camera_lag_speed', 'Set Camera Lag Speed', 'Components|Spring Arm', LuminaBlueprintNodeLibrary._arm,
      [_f('speed', 'Speed', 10.0)], const ['spring', 'arm', 'lag', 'camera', 'speed']),
  _compSet('set_socket_offset', 'Set Socket Offset', 'Components|Spring Arm', LuminaBlueprintNodeLibrary._arm,
      [_v('offset', 'Offset')], const ['spring', 'arm', 'socket', 'offset', 'camera', 'shoulder']),
  _compSet('set_field_of_view', 'Set Field Of View', 'Components|Camera', LuminaBlueprintNodeLibrary._cam,
      [_f('in_field_of_view', 'In Field Of View', 90.0)], const ['camera', 'fov', 'field of view', 'zoom']),
  _compGet('get_field_of_view', 'Get Field Of View', 'Components|Camera', LuminaBlueprintNodeLibrary._cam, _ret(LuminaPinType.float),
      const ['camera', 'fov', 'field of view']),
  _compSet('set_camera_active', 'Set Active (Camera)', 'Components|Camera', LuminaBlueprintNodeLibrary._cam, [_b('active', 'Active', true)],
      const ['camera', 'active', 'activate', 'deactivate', 'switch', 'view']),
  _compGet('is_camera_active', 'Is Active (Camera)', 'Components|Camera', LuminaBlueprintNodeLibrary._cam, _ret(LuminaPinType.boolean),
      const ['camera', 'active', 'view']),
  _compSet('play_animation', 'Play Animation', 'Components|Skeletal Mesh', LuminaBlueprintNodeLibrary._skel,
      [_s('clip', 'Animation'), _b('loop', 'Looping', true)], const ['animation', 'play', 'clip', 'mesh', 'skeletal']),
  _compSet('stop_animation', 'Stop Animation', 'Components|Skeletal Mesh', LuminaBlueprintNodeLibrary._skel, const [],
      const ['animation', 'stop', 'clip', 'mesh', 'skeletal']),
  _compSet('set_anim_class', 'Set Anim Instance Class', 'Components|Skeletal Mesh', LuminaBlueprintNodeLibrary._skel,
      [_s('anim_class', 'New Class')], const ['animation', 'blueprint', 'anim class', 'instance', 'mesh']),
  _compSet('set_play_rate', 'Set Play Rate', 'Components|Skeletal Mesh', LuminaBlueprintNodeLibrary._skel, [_f('rate', 'Rate', 1.0)],
      const ['animation', 'rate', 'speed', 'play']),
  _compGet('get_current_clip', 'Get Current Animation', 'Components|Skeletal Mesh', LuminaBlueprintNodeLibrary._skel, _ret(LuminaPinType.string),
      const ['animation', 'current', 'clip', 'playing']),
  _compSet('set_static_mesh', 'Set Static Mesh', 'Components|Static Mesh', LuminaBlueprintNodeLibrary._mesh, [_s('new_mesh', 'New Mesh')],
      const ['mesh', 'static', 'model', 'asset', 'swap']),
  _compSet('set_material', 'Set Material', 'Components|Static Mesh', LuminaBlueprintNodeLibrary._mesh,
      [_i('element_index', 'Element Index'), _s('material', 'Material')], const ['material', 'mesh', 'shader', 'skin']),
  _compSet('set_collision_enabled', 'Set Collision Enabled', 'Components|Collision', LuminaBlueprintNodeLibrary._coll,
      [_s('new_type', 'New Type', 'QueryAndPhysics')], const ['collision', 'enabled', 'physics', 'overlap', 'block', 'query']),
  _compSet('set_collision_layer', 'Set Collision Layer', 'Components|Collision', LuminaBlueprintNodeLibrary._coll, [_i('layer', 'Layer', 1)],
      const ['collision', 'layer', 'channel', 'object type']),
  // Presets, the response grid, shape sizes and overlaps.
  _compSet('set_collision_preset', 'Set Collision Preset', 'Components|Collision', LuminaBlueprintNodeLibrary._coll,
      [_s('preset', 'Preset', 'BlockAllDynamic')],
      const ['collision', 'preset', 'profile', 'trigger', 'block all', 'overlap all', 'pawn', 'no collision']),
  _compGet('get_collision_preset', 'Get Collision Preset', 'Components|Collision', LuminaBlueprintNodeLibrary._coll, _ret(LuminaPinType.string),
      const ['collision', 'preset', 'profile']),
  _compSet('set_collision_response_to_channel', 'Set Collision Response To Channel', 'Components|Collision', LuminaBlueprintNodeLibrary._coll,
      [_s('channel', 'Channel', 'Pawn'), _s('response', 'New Response', 'Block')],
      const ['collision', 'response', 'channel', 'ignore', 'overlap', 'block', 'pawn', 'world static', 'world dynamic']),
  _compSet('set_collision_response_to_all_channels', 'Set Collision Response To All Channels', 'Components|Collision', LuminaBlueprintNodeLibrary._coll,
      [_s('response', 'New Response', 'Block')], const ['collision', 'response', 'all', 'ignore', 'overlap', 'block']),
  _compGet('get_collision_response_to_channel', 'Get Collision Response To Channel', 'Components|Collision', LuminaBlueprintNodeLibrary._coll,
      _ret(LuminaPinType.string), const ['collision', 'response', 'channel'], [_s('channel', 'Channel', 'Pawn')]),
  _compSet('set_collision_object_type', 'Set Collision Object Type', 'Components|Collision', LuminaBlueprintNodeLibrary._coll,
      [_s('object_type', 'Object Type', 'WorldDynamic')], const ['collision', 'object type', 'channel', 'pawn', 'world static', 'world dynamic']),
  _compGet('get_collision_object_type', 'Get Collision Object Type', 'Components|Collision', LuminaBlueprintNodeLibrary._coll, _ret(LuminaPinType.string),
      const ['collision', 'object type', 'channel']),
  _compSet('set_generate_overlap_events', 'Set Generate Overlap Events', 'Components|Collision', LuminaBlueprintNodeLibrary._coll,
      [_b('generate', 'Generate Overlap Events', true)], const ['collision', 'overlap', 'events', 'generate', 'trigger']),
  _compSet('set_box_extent', 'Set Box Extent', 'Components|Collision', LuminaBlueprintNodeLibrary._box, [_v('box_extent', 'Box Extent', const [50.0, 50.0, 50.0])],
      const ['collision', 'box', 'extent', 'size', 'half']),
  _compGet('get_box_extent', 'Get Box Extent', 'Components|Collision', LuminaBlueprintNodeLibrary._box, _ret(LuminaPinType.vector),
      const ['collision', 'box', 'extent', 'size']),
  _compSet('set_sphere_radius', 'Set Sphere Radius', 'Components|Collision', LuminaBlueprintNodeLibrary._sphere, [_f('radius', 'Sphere Radius', 50.0)],
      const ['collision', 'sphere', 'radius', 'size']),
  _compGet('get_sphere_radius', 'Get Sphere Radius', 'Components|Collision', LuminaBlueprintNodeLibrary._sphere, _ret(LuminaPinType.float),
      const ['collision', 'sphere', 'radius']),
  _compSet('set_capsule_size', 'Set Capsule Size', 'Components|Collision', LuminaBlueprintNodeLibrary._capsule,
      [_f('radius', 'Radius', 40.0), _f('half_height', 'Half Height', 80.0)], const ['collision', 'capsule', 'radius', 'half height', 'size']),
  _compGet('get_scaled_capsule_radius', 'Get Scaled Capsule Radius', 'Components|Collision', LuminaBlueprintNodeLibrary._capsule, _ret(LuminaPinType.float),
      const ['collision', 'capsule', 'radius', 'scaled']),
  _compGet('get_scaled_capsule_half_height', 'Get Scaled Capsule Half Height', 'Components|Collision', LuminaBlueprintNodeLibrary._capsule,
      _ret(LuminaPinType.float), const ['collision', 'capsule', 'half height', 'scaled']),
  _compGet('get_overlapping_actors', 'Get Overlapping Actors', 'Components|Collision', LuminaBlueprintNodeLibrary._coll,
      const LuminaBlueprintPinSpec(_returnValue, 'Overlapping Actors', LuminaPinType.array,
          elementType: LuminaPinType.object, objectClass: LuminaBlueprintObjectClass.anyActor),
      const ['collision', 'overlap', 'actors', 'inside', 'trigger'], [_s('class', 'Class Filter', LuminaBlueprintObjectClass.anyActor)]),
  _compGet('get_overlapping_components', 'Get Overlapping Components', 'Components|Collision', LuminaBlueprintNodeLibrary._coll,
      const LuminaBlueprintPinSpec(_returnValue, 'Overlapping Components', LuminaPinType.array,
          elementType: LuminaPinType.object, objectClass: 'Component:LuminaCollisionComponent'),
      const ['collision', 'overlap', 'components', 'inside', 'trigger']),
  _compGet('is_overlapping_actor', 'Is Overlapping Actor', 'Components|Collision', LuminaBlueprintNodeLibrary._coll, _ret(LuminaPinType.boolean),
      const ['collision', 'overlap', 'actor', 'inside', 'touching'], [_obj('other', 'Other', LuminaBlueprintObjectClass.anyActor)]),
  _compSet('set_max_walk_speed', 'Set Max Walk Speed', 'Components|Character Movement', LuminaBlueprintNodeLibrary._move,
      [_f('max_walk_speed', 'Max Walk Speed', 600.0)], const ['movement', 'walk', 'speed', 'run', 'sprint']),
  _compGet('get_max_walk_speed', 'Get Max Walk Speed', 'Components|Character Movement', LuminaBlueprintNodeLibrary._move,
      _ret(LuminaPinType.float), const ['movement', 'walk', 'speed']),
  _compSet('set_jump_z_velocity', 'Set Jump Z Velocity', 'Components|Character Movement', LuminaBlueprintNodeLibrary._move,
      [_f('jump_z_velocity', 'Jump Z Velocity', 500.0)], const ['movement', 'jump', 'velocity', 'height']),
  _compGet('get_jump_z_velocity', 'Get Jump Z Velocity', 'Components|Character Movement', LuminaBlueprintNodeLibrary._move,
      _ret(LuminaPinType.float), const ['movement', 'jump', 'velocity']),
  _compSet('set_gravity_scale', 'Set Gravity Scale', 'Components|Character Movement', LuminaBlueprintNodeLibrary._move,
      [_f('gravity_scale', 'Gravity Scale', 1.0)], const ['movement', 'gravity', 'scale', 'fall']),
  _compGet('get_gravity_scale', 'Get Gravity Scale', 'Components|Character Movement', LuminaBlueprintNodeLibrary._move,
      _ret(LuminaPinType.float), const ['movement', 'gravity', 'scale']),
  _compSet('set_air_control', 'Set Air Control', 'Components|Character Movement', LuminaBlueprintNodeLibrary._move,
      [_f('air_control', 'Air Control', 0.35)], const ['movement', 'air', 'control', 'jump']),
  _compGet('get_air_control', 'Get Air Control', 'Components|Character Movement', LuminaBlueprintNodeLibrary._move, _ret(LuminaPinType.float),
      const ['movement', 'air', 'control']),
  _compSet('set_movement_mode', 'Set Movement Mode', 'Components|Character Movement', LuminaBlueprintNodeLibrary._move,
      [_s('new_movement_mode', 'New Movement Mode', 'Walking')],
      const ['movement', 'mode', 'walking', 'falling', 'flying', 'swimming']),
  _compGet('get_movement_mode', 'Get Movement Mode', 'Components|Character Movement', LuminaBlueprintNodeLibrary._move,
      _ret(LuminaPinType.string), const ['movement', 'mode', 'walking', 'falling', 'flying']),
  _compSet('crouch', 'Crouch', 'Components|Character Movement', LuminaBlueprintNodeLibrary._move, const [],
      const ['crouch', 'duck', 'character', 'movement']),
  _compSet('un_crouch', 'Un Crouch', 'Components|Character Movement', LuminaBlueprintNodeLibrary._move, const [],
      const ['crouch', 'stand', 'uncrouch', 'character', 'movement']),
  // --- Physics --------------------------------------------------
  _compSet('set_simulate_physics', 'Set Simulate Physics', 'Physics', LuminaBlueprintNodeLibrary._scene, [_b('simulate', 'Simulate', true)],
      const ['physics', 'simulate', 'rigid body', 'ragdoll', 'enable', 'disable']),
  _compGet('is_simulating_physics', 'Is Simulating Physics', 'Physics', LuminaBlueprintNodeLibrary._scene, _ret(LuminaPinType.boolean),
      const ['physics', 'simulate', 'simulating', 'rigid body']),
  _compSet('add_impulse', 'Add Impulse', 'Physics', LuminaBlueprintNodeLibrary._scene,
      [_v('impulse', 'Impulse'), LuminaBlueprintNodeLibrary._bone, _b('vel_change', 'Vel Change')], const ['physics', 'impulse', 'push', 'kick', 'launch']),
  _compSet('add_impulse_at_location', 'Add Impulse at Location', 'Physics', LuminaBlueprintNodeLibrary._scene,
      [_v('impulse', 'Impulse'), _v('location', 'Location'), LuminaBlueprintNodeLibrary._bone], const ['physics', 'impulse', 'location', 'point', 'push', 'hit']),
  _compSet('add_force', 'Add Force', 'Physics', LuminaBlueprintNodeLibrary._scene,
      [_v('force', 'Force'), LuminaBlueprintNodeLibrary._bone, _b('accel_change', 'Accel Change')], const ['physics', 'force', 'push', 'thrust', 'wind']),
  _compSet('add_force_at_location', 'Add Force at Location', 'Physics', LuminaBlueprintNodeLibrary._scene,
      [_v('force', 'Force'), _v('location', 'Location'), LuminaBlueprintNodeLibrary._bone], const ['physics', 'force', 'location', 'point']),
  _compSet('add_torque', 'Add Torque in Radians', 'Physics', LuminaBlueprintNodeLibrary._scene,
      [_v('torque', 'Torque'), LuminaBlueprintNodeLibrary._bone, _b('accel_change', 'Accel Change')], const ['physics', 'torque', 'spin', 'rotate', 'twist']),
  _compSet('add_angular_impulse', 'Add Angular Impulse in Radians', 'Physics', LuminaBlueprintNodeLibrary._scene,
      [_v('impulse', 'Impulse'), LuminaBlueprintNodeLibrary._bone, _b('vel_change', 'Vel Change')], const ['physics', 'angular', 'impulse', 'spin']),
  _compSet('set_physics_linear_velocity', 'Set Physics Linear Velocity', 'Physics', LuminaBlueprintNodeLibrary._scene,
      [_v('new_vel', 'New Vel'), _b('add_to_current', 'Add to Current'), LuminaBlueprintNodeLibrary._bone], const ['physics', 'velocity', 'speed', 'linear']),
  _compGet('get_physics_linear_velocity', 'Get Physics Linear Velocity', 'Physics', LuminaBlueprintNodeLibrary._scene, _ret(LuminaPinType.vector),
      const ['physics', 'velocity', 'speed', 'linear'], [LuminaBlueprintNodeLibrary._bone]),
  _compSet('set_physics_angular_velocity', 'Set Physics Angular Velocity in Degrees', 'Physics', LuminaBlueprintNodeLibrary._scene,
      [_v('new_ang_vel', 'New Ang Vel'), _b('add_to_current', 'Add to Current'), LuminaBlueprintNodeLibrary._bone], const ['physics', 'angular', 'velocity', 'spin']),
  _compGet('get_physics_angular_velocity', 'Get Physics Angular Velocity in Degrees', 'Physics', LuminaBlueprintNodeLibrary._scene,
      _ret(LuminaPinType.vector), const ['physics', 'angular', 'velocity', 'spin'], [LuminaBlueprintNodeLibrary._bone]),
  _compGet('get_mass', 'Get Mass', 'Physics', LuminaBlueprintNodeLibrary._scene, _ret(LuminaPinType.float), const ['physics', 'mass', 'weight', 'kg']),
  _compSet('set_mass_override_in_kg', 'Set Mass Override in Kg', 'Physics', LuminaBlueprintNodeLibrary._scene,
      [LuminaBlueprintNodeLibrary._bone, _f('mass_in_kg', 'Mass in Kg', 1.0), _b('override_mass', 'Override Mass', true)], const ['physics', 'mass', 'weight', 'kg', 'override']),
  _compSet('set_enable_gravity', 'Set Enable Gravity', 'Physics', LuminaBlueprintNodeLibrary._scene, [_b('gravity_enabled', 'Gravity Enabled', true)],
      const ['physics', 'gravity', 'float', 'fall']),
  _compSet('set_linear_damping', 'Set Linear Damping', 'Physics', LuminaBlueprintNodeLibrary._scene, [_f('in_damping', 'In Damping', 0.01)],
      const ['physics', 'damping', 'drag', 'linear']),
  _compSet('set_angular_damping', 'Set Angular Damping', 'Physics', LuminaBlueprintNodeLibrary._scene, [_f('in_damping', 'In Damping', 0.0)],
      const ['physics', 'damping', 'drag', 'angular', 'spin']),
  _compSet('wake_rigid_body', 'Wake Rigid Body', 'Physics', LuminaBlueprintNodeLibrary._scene, [LuminaBlueprintNodeLibrary._bone], const ['physics', 'wake', 'sleep', 'rigid body']),
  _compSet('put_rigid_body_to_sleep', 'Put Rigid Body to Sleep', 'Physics', LuminaBlueprintNodeLibrary._scene, [LuminaBlueprintNodeLibrary._bone],
      const ['physics', 'sleep', 'rest', 'rigid body']),
  _compGet('is_any_rigid_body_awake', 'Is Any Rigid Body Awake', 'Physics', LuminaBlueprintNodeLibrary._scene, _ret(LuminaPinType.boolean),
      const ['physics', 'awake', 'sleep', 'rigid body']),
  _compGet('is_crouched', 'Is Crouched', 'Components|Character Movement', LuminaBlueprintNodeLibrary._move, _ret(LuminaPinType.boolean),
      const ['crouch', 'crouched', 'character', 'movement']),
  _compSet('launch_character', 'Launch Character', 'Components|Character Movement', LuminaBlueprintNodeLibrary._move, [
    _v('launch_velocity', 'Launch Velocity'),
    _b('xy_override', 'XY Override'),
    _b('z_override', 'Z Override'),
  ], const ['launch', 'impulse', 'knockback', 'jump', 'character', 'movement']),
  _compSet('stop_movement_immediately', 'Stop Movement Immediately', 'Components|Character Movement', LuminaBlueprintNodeLibrary._move,
      const [], const ['stop', 'movement', 'halt', 'freeze', 'velocity']),
];
