part of '../node_library.dart';

/// Built-in nodes: audio, animation, effects, material, light, debug and
/// the variable intrinsics.
final List<LuminaBlueprintNodeSpec> _mediaAndDebugNodes = <LuminaBlueprintNodeSpec>[
  // --- Audio -------------------------------------------------
  LuminaBlueprintNodeSpec(
    id: 'play_sound_2d',
    title: 'Play Sound 2D',
    category: 'Audio',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['sound', 'audio', 'play', '2d', 'ui'],
    inputs: [_execIn, _s('sound', 'Sound'), _f('volume', 'Volume Multiplier', 1.0), _f('pitch', 'Pitch Multiplier', 1.0), _f('start_time', 'Start Time')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'play_sound_at_location',
    title: 'Play Sound at Location',
    category: 'Audio',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['sound', 'audio', 'play', 'location', '3d', 'spatial'],
    inputs: [_execIn, _s('sound', 'Sound'), _v('location', 'Location'), _f('volume', 'Volume Multiplier', 1.0), _f('pitch', 'Pitch Multiplier', 1.0), _f('start_time', 'Start Time')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'spawn_sound_2d',
    title: 'Spawn Sound 2D',
    category: 'Audio',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['sound', 'audio', 'spawn', 'music', 'component'],
    inputs: [_execIn, _s('sound', 'Sound'), _f('volume', 'Volume Multiplier', 1.0), _f('pitch', 'Pitch Multiplier', 1.0), _f('start_time', 'Start Time'), _b('auto_destroy', 'Auto Destroy')],
    outputs: [_execOut, _ret(LuminaPinType.object, cls: 'Component:LuminaAudioComponent')],
  ),
  LuminaBlueprintNodeSpec(
    id: 'spawn_sound_attached',
    title: 'Spawn Sound Attached',
    category: 'Audio',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['sound', 'audio', 'spawn', 'attached', 'component'],
    inputs: [
      _execIn,
      _s('sound', 'Sound'),
      _comp(LuminaBlueprintNodeLibrary._scene, 'attach_to_component', 'Attach to Component'),
      LuminaBlueprintPinSpec('socket_name', 'Attach Point Name', LuminaPinType.name, defaultValue: ''),
      _f('volume', 'Volume Multiplier', 1.0),
      _f('pitch', 'Pitch Multiplier', 1.0),
    ],
    outputs: [_execOut, _ret(LuminaPinType.object, cls: 'Component:LuminaAudioComponent')],
  ),
  _compSet('stop_sound', 'Stop', 'Audio', 'LuminaAudioComponent', const [], const ['sound', 'audio', 'stop']),
  _compSet('fade_out_sound', 'Fade Out', 'Audio', 'LuminaAudioComponent', [_f('fade_out_duration', 'Fade Out Duration', 1.0)], const ['sound', 'audio', 'fade', 'out']),
  _compSet('set_sound_volume', 'Set Volume Multiplier', 'Audio', 'LuminaAudioComponent', [_f('volume', 'New Volume Multiplier', 1.0)], const ['sound', 'audio', 'volume']),
  _compSet('set_sound_pitch', 'Set Pitch Multiplier', 'Audio', 'LuminaAudioComponent', [_f('pitch', 'New Pitch Multiplier', 1.0)], const ['sound', 'audio', 'pitch']),
  _compGet('is_sound_playing', 'Is Playing', 'Audio', 'LuminaAudioComponent', _ret(LuminaPinType.boolean), const ['sound', 'audio', 'playing']),
  LuminaBlueprintNodeSpec(
    id: 'set_sound_class_volume',
    title: 'Set Sound Class Volume',
    category: 'Audio',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['sound', 'class', 'volume', 'master', 'music', 'sfx', 'mix'],
    inputs: [_execIn, _s('sound_class', 'Sound Class', 'Master'), _f('volume', 'Volume', 1.0)],
    outputs: const [_execOut],
  ),

  // --- Video -------------------------------------------------
  LuminaBlueprintNodeSpec(
    id: 'open_video',
    title: 'Open Video',
    category: 'Media|Video',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['video', 'media', 'open', 'movie', 'player', 'controller'],
    inputs: [_execIn, _s('source', 'Source'), _b('auto_play', 'Auto Play'), _b('loop', 'Loop'), _f('volume', 'Volume', 1.0)],
    outputs: [_execOut, _ret(LuminaPinType.object, cls: 'Object:LuminaVideoController')],
  ),
  LuminaBlueprintNodeSpec(
    id: 'play_video',
    title: 'Play Video',
    category: 'Media|Video',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['video', 'media', 'play', 'resume'],
    inputs: [_execIn, _obj('target', 'Video Controller', 'Object:LuminaVideoController')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'pause_video',
    title: 'Pause Video',
    category: 'Media|Video',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['video', 'media', 'pause'],
    inputs: [_execIn, _obj('target', 'Video Controller', 'Object:LuminaVideoController')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'stop_video',
    title: 'Stop Video',
    category: 'Media|Video',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['video', 'media', 'stop'],
    inputs: [_execIn, _obj('target', 'Video Controller', 'Object:LuminaVideoController')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'seek_video',
    title: 'Seek Video',
    category: 'Media|Video',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['video', 'media', 'seek', 'time'],
    inputs: [_execIn, _obj('target', 'Video Controller', 'Object:LuminaVideoController'), _f('seconds', 'Seconds')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'set_video_volume',
    title: 'Set Video Volume',
    category: 'Media|Video',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['video', 'media', 'volume'],
    inputs: [_execIn, _obj('target', 'Video Controller', 'Object:LuminaVideoController'), _f('volume', 'Volume', 1.0)],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'set_video_rate',
    title: 'Set Video Rate',
    category: 'Media|Video',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['video', 'media', 'rate', 'speed'],
    inputs: [_execIn, _obj('target', 'Video Controller', 'Object:LuminaVideoController'), _f('rate', 'Rate', 1.0)],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'set_video_looping',
    title: 'Set Video Looping',
    category: 'Media|Video',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['video', 'media', 'loop'],
    inputs: [_execIn, _obj('target', 'Video Controller', 'Object:LuminaVideoController'), _b('loop', 'Loop')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'is_video_playing',
    title: 'Is Video Playing',
    category: 'Media|Video',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _function,
    keywords: const ['video', 'media', 'playing'],
    inputs: [_obj('target', 'Video Controller', 'Object:LuminaVideoController')],
    outputs: [_ret(LuminaPinType.boolean)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_video_position',
    title: 'Get Video Position',
    category: 'Media|Video',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _function,
    keywords: const ['video', 'media', 'position', 'time'],
    inputs: [_obj('target', 'Video Controller', 'Object:LuminaVideoController')],
    outputs: [_ret(LuminaPinType.float)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_video_duration',
    title: 'Get Video Duration',
    category: 'Media|Video',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _function,
    keywords: const ['video', 'media', 'duration', 'length'],
    inputs: [_obj('target', 'Video Controller', 'Object:LuminaVideoController')],
    outputs: [_ret(LuminaPinType.float)],
  ),

  // --- Animation ---------------------------------------------
  LuminaBlueprintNodeSpec(
    id: 'play_anim_montage',
    title: 'Play Anim Montage',
    category: 'Animation|Montage',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['montage', 'animation', 'play', 'attack', 'anim'],
    inputs: [_execIn, _s('montage', 'Anim Montage'), _f('play_rate', 'In Play Rate', 1.0), LuminaBlueprintPinSpec('start_section', 'Start Section Name', LuminaPinType.name, defaultValue: '')],
    outputs: [_execOut, _ret(LuminaPinType.float)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'stop_anim_montage',
    title: 'Stop Anim Montage',
    category: 'Animation|Montage',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['montage', 'animation', 'stop'],
    inputs: [_execIn, _f('blend_out_time', 'Blend Out Time', 0.25)],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'montage_jump_to_section',
    title: 'Montage Jump to Section',
    category: 'Animation|Montage',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['montage', 'section', 'jump'],
    inputs: [_execIn, LuminaBlueprintPinSpec('section_name', 'Section Name', LuminaPinType.name, defaultValue: '')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'montage_set_next_section',
    title: 'Montage Set Next Section',
    category: 'Animation|Montage',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['montage', 'section', 'next', 'loop'],
    inputs: [
      _execIn,
      LuminaBlueprintPinSpec('section_name', 'Section Name to Change', LuminaPinType.name, defaultValue: ''),
      LuminaBlueprintPinSpec('next_section', 'Next Section', LuminaPinType.name, defaultValue: ''),
    ],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'is_playing_montage',
    title: 'Is Playing Montage',
    category: 'Animation|Montage',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['montage', 'playing', 'animation'],
    outputs: [_ret(LuminaPinType.boolean)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_current_montage',
    title: 'Get Current Montage',
    category: 'Animation|Montage',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['montage', 'current', 'animation'],
    outputs: [_ret(LuminaPinType.string)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_anim_instance',
    title: 'Get Anim Instance',
    category: 'Animation',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['anim', 'instance', 'animation', 'blueprint', 'abp'],
    outputs: [_ret(LuminaPinType.object, cls: 'Component:LuminaAnimBlueprintInstance')],
  ),
  LuminaBlueprintNodeSpec(
    id: 'set_anim_variable',
    title: 'Set Anim Variable',
    category: 'Animation',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['anim', 'variable', 'set', 'animation', 'blueprint'],
    inputs: [_execIn, LuminaBlueprintPinSpec('name', 'Name', LuminaPinType.name, defaultValue: ''), _any('value', 'Value')],
    outputs: const [_execOut],
  ),
  LuminaBlueprintNodeSpec(
    id: 'get_anim_variable',
    title: 'Get Anim Variable',
    category: 'Animation',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['anim', 'variable', 'get', 'animation', 'blueprint'],
    inputs: [LuminaBlueprintPinSpec('name', 'Name', LuminaPinType.name, defaultValue: '')],
    outputs: [_any(_returnValue, 'Return Value')],
  ),
  LuminaBlueprintNodeSpec(
    id: 'event_montage_ended',
    title: 'Event Montage Ended',
    category: 'Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: const ['montage', 'ended', 'finished', 'animation'],
    outputs: [_execOut, _s('montage', 'Montage'), _b('interrupted', 'Interrupted')],
  ),
  LuminaBlueprintNodeSpec(
    id: 'event_anim_notify',
    title: 'Event Anim Notify',
    category: 'Events',
    kind: LuminaBlueprintNodeKind.event,
    headerColor: _event,
    keywords: const ['notify', 'animation', 'montage', 'event'],
    outputs: [_execOut, _s('notify_name', 'Notify Name')],
  ),

  // --- Effects -----------------------------------------------
  LuminaBlueprintNodeSpec(
    id: 'spawn_emitter_at_location',
    title: 'Spawn Emitter at Location',
    category: 'Effects',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['particle', 'emitter', 'spawn', 'fx', 'effect', 'vfx'],
    inputs: [
      _execIn,
      _s('emitter_template', 'Emitter Template'),
      _v('location', 'Location'),
      _rot('rotation', 'Rotation'),
      _v('scale', 'Scale', const [1.0, 1.0, 1.0]),
      _b('auto_destroy', 'Auto Destroy', true),
    ],
    outputs: [_execOut, _ret(LuminaPinType.object, cls: 'Component:LuminaParticleSystemComponent')],
  ),
  LuminaBlueprintNodeSpec(
    id: 'spawn_emitter_attached',
    title: 'Spawn Emitter Attached',
    category: 'Effects',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['particle', 'emitter', 'spawn', 'attached', 'fx', 'vfx'],
    inputs: [
      _execIn,
      _s('emitter_template', 'Emitter Template'),
      _comp(LuminaBlueprintNodeLibrary._scene, 'attach_to_component', 'Attach to Component'),
      LuminaBlueprintPinSpec('socket_name', 'Attach Point Name', LuminaPinType.name, defaultValue: ''),
      _b('auto_destroy', 'Auto Destroy', true),
    ],
    outputs: [_execOut, _ret(LuminaPinType.object, cls: 'Component:LuminaParticleSystemComponent')],
  ),
  _compSet('activate_particle_system', 'Activate', 'Effects', 'LuminaParticleSystemComponent', [_b('reset', 'Reset')], const ['particle', 'activate', 'fx']),
  _compSet('deactivate_particle_system', 'Deactivate', 'Effects', 'LuminaParticleSystemComponent', const [], const ['particle', 'deactivate', 'fx', 'stop']),
  _compSet('set_particle_parameter', 'Set Particle Parameter', 'Effects', 'LuminaParticleSystemComponent',
      [LuminaBlueprintPinSpec('parameter_name', 'Parameter Name', LuminaPinType.name, defaultValue: 'SpawnRate'), _any('value', 'Value')],
      const ['particle', 'parameter', 'spawn rate', 'fx']),
  // Loads and compiles, but the engine has no decal component
  // yet — the validator warns and the node does nothing.
  LuminaBlueprintNodeSpec(
    id: 'spawn_decal_at_location',
    title: 'Spawn Decal at Location',
    category: 'Effects',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['decal', 'spawn', 'material', 'fx', 'effect'],
    inputs: [
      _execIn,
      _s('decal_material', 'Decal Material'),
      _v('decal_size', 'Decal Size', const [128.0, 256.0, 256.0]),
      _v('location', 'Location'),
      _rot('rotation', 'Rotation'),
      _f('life_span', 'Life Span'),
    ],
    outputs: [_execOut, _ret(LuminaPinType.object)],
    unsupported: 'not supported: Lumina has no decal component yet, so the node spawns nothing.',
  ),

  // --- Material ----------------------------------------------
  LuminaBlueprintNodeSpec(
    id: 'create_dynamic_material_instance',
    title: 'Create Dynamic Material Instance',
    category: 'Material',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['material', 'dynamic', 'instance', 'mid', 'create'],
    inputs: [_execIn, _comp(LuminaBlueprintNodeLibrary._mesh), _i('element_index', 'Element Index')],
    outputs: [_execOut, _ret(LuminaPinType.object, cls: 'Object:MaterialInstance')],
  ),
  for (final (id, title, values, keywords) in [
    ('set_scalar_parameter_value', 'Set Scalar Parameter Value', [LuminaBlueprintPinSpec('parameter_name', 'Parameter Name', LuminaPinType.name, defaultValue: ''), _f('value', 'Value')], const ['material', 'scalar', 'parameter', 'float']),
    ('set_vector_parameter_value', 'Set Vector Parameter Value', [LuminaBlueprintPinSpec('parameter_name', 'Parameter Name', LuminaPinType.name, defaultValue: ''), _color('value', 'Value')], const ['material', 'vector', 'parameter', 'color']),
    ('set_texture_parameter_value', 'Set Texture Parameter Value', [LuminaBlueprintPinSpec('parameter_name', 'Parameter Name', LuminaPinType.name, defaultValue: ''), _s('value', 'Value')], const ['material', 'texture', 'parameter']),
  ])
    LuminaBlueprintNodeSpec(
      id: id,
      title: title,
      category: 'Material',
      kind: LuminaBlueprintNodeKind.impure,
      headerColor: _function,
      keywords: keywords,
      inputs: [_execIn, _obj('target', 'Target', 'Object:MaterialInstance'), ...values],
      outputs: const [_execOut],
    ),
  LuminaBlueprintNodeSpec(
    id: 'get_scalar_parameter_value',
    title: 'Get Scalar Parameter Value',
    category: 'Material',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _pure,
    keywords: const ['material', 'scalar', 'parameter', 'get'],
    inputs: [_obj('target', 'Target', 'Object:MaterialInstance'), LuminaBlueprintPinSpec('parameter_name', 'Parameter Name', LuminaPinType.name, defaultValue: '')],
    outputs: [_ret(LuminaPinType.float)],
  ),
  LuminaBlueprintNodeSpec(
    id: 'set_material_scalar_parameter_on_actor',
    title: 'Set Material Scalar Parameter on Actor',
    category: 'Material',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _function,
    keywords: const ['material', 'scalar', 'parameter', 'actor', 'all meshes'],
    inputs: [_execIn, _obj('target', 'Target', LuminaBlueprintObjectClass.anyActor), LuminaBlueprintPinSpec('parameter_name', 'Parameter Name', LuminaPinType.name, defaultValue: ''), _f('value', 'Value')],
    outputs: const [_execOut],
  ),

  // --- Light -------------------------------------------------
  _compSet('set_light_intensity', 'Set Intensity', 'Light', 'LuminaLightComponent', [_f('new_intensity', 'New Intensity', 1000.0)], const ['light', 'intensity', 'brightness']),
  _compGet('get_light_intensity', 'Get Intensity', 'Light', 'LuminaLightComponent', _ret(LuminaPinType.float), const ['light', 'intensity', 'brightness']),
  _compSet('set_light_color', 'Set Light Color', 'Light', 'LuminaLightComponent', [_color('new_light_color', 'New Light Color')], const ['light', 'color', 'colour']),
  _compSet('set_light_visibility', 'Set Visibility', 'Light', 'LuminaLightComponent', [_b('new_visibility', 'New Visibility', true)], const ['light', 'visible', 'on', 'off']),
  _compSet('toggle_light_visibility', 'Toggle Visibility', 'Light', 'LuminaLightComponent', const [], const ['light', 'toggle', 'switch', 'on', 'off']),
  _compSet('set_light_radius', 'Set Attenuation Radius', 'Light', 'LuminaLightComponent', [_f('new_radius', 'New Radius', 1000.0)], const ['light', 'radius', 'attenuation', 'falloff']),
  _compSet('set_spot_light_angles', 'Set Spot Light Angles', 'Light', 'LuminaSpotLightComponent', [_f('inner_cone_angle', 'Inner Cone Angle'), _f('outer_cone_angle', 'Outer Cone Angle', 44.0)], const ['light', 'spot', 'cone', 'angle']),

  // --- Debug -------------------------------------------------
  LuminaBlueprintNodeSpec(
    id: 'print_text',
    title: 'Print Text',
    category: 'Debug',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: 0xFF1B5E20,
    keywords: const ['log', 'debug', 'print', 'text', 'screen'],
    inputs: [
      _execIn,
      _s('in_text', 'In Text', 'Hello'),
      _b('print_to_screen', 'Print to Screen', true),
      _b('print_to_log', 'Print to Log', true),
      _color('text_color', 'Text Color', const [0.0, 0.66, 1.0, 1.0]),
      _f('duration', 'Duration', 2.0),
      LuminaBlueprintPinSpec('key', 'Key', LuminaPinType.name, defaultValue: ''),
    ],
    outputs: const [_execOut],
  ),
  for (final (id, title, values, keywords) in [
    ('draw_debug_line', 'Draw Debug Line', [_v('line_start', 'Line Start'), _v('line_end', 'Line End'), _color('line_color', 'Line Color'), _f('duration', 'Duration'), _f('thickness', 'Thickness')], const ['debug', 'draw', 'line']),
    ('draw_debug_sphere', 'Draw Debug Sphere', [_v('center', 'Center'), _f('radius', 'Radius', 100.0), _i('segments', 'Segments', 12), _color('line_color', 'Line Color'), _f('duration', 'Duration'), _f('thickness', 'Thickness')], const ['debug', 'draw', 'sphere']),
    ('draw_debug_box', 'Draw Debug Box', [_v('center', 'Center'), _v('extent', 'Extent', const [50.0, 50.0, 50.0]), _rot('rotation', 'Rotation'), _color('line_color', 'Line Color'), _f('duration', 'Duration'), _f('thickness', 'Thickness')], const ['debug', 'draw', 'box']),
    ('draw_debug_point', 'Draw Debug Point', [_v('position', 'Position'), _f('size', 'Size', 4.0), _color('point_color', 'Point Color'), _f('duration', 'Duration')], const ['debug', 'draw', 'point']),
    ('draw_debug_arrow', 'Draw Debug Arrow', [_v('line_start', 'Line Start'), _v('line_end', 'Line End'), _f('arrow_size', 'Arrow Size', 10.0), _color('line_color', 'Line Color'), _f('duration', 'Duration'), _f('thickness', 'Thickness')], const ['debug', 'draw', 'arrow', 'direction']),
    ('draw_debug_string', 'Draw Debug String', [_v('text_location', 'Text Location'), _s('text', 'Text'), _color('text_color', 'Text Color'), _f('duration', 'Duration')], const ['debug', 'draw', 'string', 'text', 'label']),
    ('draw_debug_capsule', 'Draw Debug Capsule', [_v('center', 'Center'), _f('half_height', 'Half Height', 80.0), _f('radius', 'Radius', 40.0), _rot('rotation', 'Rotation'), _color('line_color', 'Line Color'), _f('duration', 'Duration'), _f('thickness', 'Thickness')], const ['debug', 'draw', 'capsule']),
  ])
    LuminaBlueprintNodeSpec(
      id: id,
      title: title,
      category: 'Debug',
      kind: LuminaBlueprintNodeKind.impure,
      headerColor: 0xFF1B5E20,
      keywords: keywords,
      inputs: [_execIn, ...values],
      outputs: const [_execOut],
    ),
  for (final (id, title, values, keywords) in [
    ('flush_debug_shapes', 'Flush Persistent Debug Lines', <LuminaBlueprintPinSpec>[], const ['debug', 'flush', 'clear', 'shapes']),
    ('breakpoint', 'Breakpoint', <LuminaBlueprintPinSpec>[], const ['debug', 'breakpoint', 'pause', 'debugger']),
    ('log_warning', 'Log Warning', [_s('in_string', 'In String')], const ['log', 'warning', 'debug']),
    ('log_error', 'Log Error', [_s('in_string', 'In String')], const ['log', 'error', 'debug']),
  ])
    LuminaBlueprintNodeSpec(
      id: id,
      title: title,
      category: 'Debug',
      kind: LuminaBlueprintNodeKind.impure,
      headerColor: 0xFF1B5E20,
      keywords: keywords,
      inputs: [_execIn, ...values],
      outputs: const [_execOut],
    ),

  // --- Variables (intrinsics) -----------------------------------------
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.variableGet,
    title: 'Get',
    category: 'Variables',
    kind: LuminaBlueprintNodeKind.pure,
    headerColor: _variable,
    outputs: [LuminaBlueprintPinSpec('value', 'Value', LuminaPinType.float)],
  ),
  const LuminaBlueprintNodeSpec(
    id: LuminaBlueprintNodeLibrary.variableSet,
    title: 'Set',
    category: 'Variables',
    kind: LuminaBlueprintNodeKind.impure,
    headerColor: _variable,
    inputs: [_execIn, LuminaBlueprintPinSpec('value', 'Value', LuminaPinType.float)],
    outputs: [_execOut, LuminaBlueprintPinSpec('value', 'Value', LuminaPinType.float)],
  ),
];
