/*
 * Copyright 2024 flutter_filament authors.
 * Licensed under the Apache License, Version 2.0.
 */

#include "tools_c.h"

#include <filaflat/ChunkContainer.h>
#ifndef __EMSCRIPTEN__
#include <matdbg/JsonWriter.h>
#endif
#ifndef __EMSCRIPTEN__
#include <matdbg/TextWriter.h>
#endif
#include <zstd.h>

#include <filament/View.h>
#include <filament/Scene.h>
#include <filament/Camera.h>
#include <utils/Panic.h>

#include <cstdlib>
#include <cstring>
#include <sstream>
#include <iomanip>
#include <vector>
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <exception>

using namespace filament;

static const float PI = 3.14159265358979323846f;

#define FFI_TRY try {
#define FFI_CATCH(return_value) \
} catch (const utils::Panic& e) { \
    fprintf(stderr, "[Tools C++ Panic (Handled Safely)]: %s\n", e.what()); \
    return return_value; \
} catch (const std::exception& e) { \
    fprintf(stderr, "[Tools C++ Exception (Handled Safely)]: %s\n", e.what()); \
    return return_value; \
} catch (...) { \
    fprintf(stderr, "[Tools C++ Unknown Exception (Handled Safely)]\n"); \
    return return_value; \
}

extern "C" {

// matdbg (the material inspector) is not in Filament's WebAssembly build.
#ifndef __EMSCRIPTEN__
char* filament_tools_inspect_material_json(const void* data, uint32_t size) {
    FFI_TRY
    if (!data || size == 0) return nullptr;
    filaflat::ChunkContainer container(data, size);
    if (!container.parse()) return nullptr;

    filament::matdbg::JsonWriter writer;
    if (!writer.writeMaterialInfo(container)) return nullptr;

    const char* jsonStr = writer.getJsonString();
    if (!jsonStr) return nullptr;

    return strdup(jsonStr);
    FFI_CATCH(nullptr)
}

char* filament_tools_inspect_material_text(const void* data, uint32_t size) {
    FFI_TRY
    if (!data || size == 0) return nullptr;
    filaflat::ChunkContainer container(data, size);
    if (!container.parse()) return nullptr;

    filament::matdbg::TextWriter writer;
    if (!writer.writeMaterialInfo(container)) return nullptr;

    const char* textStr = writer.getString();
    if (!textStr) return nullptr;

    return strdup(textStr);
    FFI_CATCH(nullptr)
}
#else
char* filament_tools_inspect_material_json(const void* data, uint32_t size) {
    (void) data;
    (void) size;
    fprintf(stderr, "[flutter_filament] filament_tools_inspect_material_json is not available in web builds: matdbg is desktop-only\n");
    return nullptr;
}

char* filament_tools_inspect_material_text(const void* data, uint32_t size) {
    (void) data;
    (void) size;
    fprintf(stderr, "[flutter_filament] filament_tools_inspect_material_text is not available in web builds: matdbg is desktop-only\n");
    return nullptr;
}
#endif

char* filament_tools_resgen_encode(const void* data, uint32_t size, const char* symbol_name) {
    FFI_TRY
    if (!data || size == 0 || !symbol_name) return nullptr;
    const uint8_t* bytes = static_cast<const uint8_t*>(data);

    std::stringstream ss;
    ss << "// Generated by flutter_filament resgen tool\n";
    ss << "#include <stdint.h>\n";
    ss << "#include <stddef.h>\n\n";
    ss << "const uint8_t " << symbol_name << "[" << size << "] = {\n    ";

    for (uint32_t i = 0; i < size; ++i) {
        ss << "0x" << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(bytes[i]);
        if (i < size - 1) {
            ss << ", ";
            if ((i + 1) % 12 == 0) {
                ss << "\n    ";
            }
        }
    }
    ss << "\n};\n";
    ss << std::dec;
    ss << "const size_t " << symbol_name << "_SIZE = " << size << ";\n";

    std::string str = ss.str();
    return strdup(str.c_str());
    FFI_CATCH(nullptr)
}

uint8_t filament_tools_generate_mipmap_level_rgba8(
    const uint8_t* src_pixels, uint32_t width, uint32_t height,
    uint32_t target_level, uint8_t* out_pixels, uint32_t* out_width, uint32_t* out_height) {
    FFI_TRY
    if (!src_pixels || width == 0 || height == 0 || !out_pixels) return 0;

    uint32_t cur_w = width;
    uint32_t cur_h = height;
    std::vector<uint8_t> prev_buf(src_pixels, src_pixels + (width * height * 4));

    for (uint32_t level = 1; level <= target_level; ++level) {
        uint32_t next_w = std::max(1u, cur_w / 2);
        uint32_t next_h = std::max(1u, cur_h / 2);
        std::vector<uint8_t> next_buf(next_w * next_h * 4);

        for (uint32_t y = 0; y < next_h; ++y) {
            for (uint32_t x = 0; x < next_w; ++x) {
                uint32_t src_x0 = x * 2;
                uint32_t src_y0 = y * 2;
                uint32_t src_x1 = std::min(src_x0 + 1, cur_w - 1);
                uint32_t src_y1 = std::min(src_y0 + 1, cur_h - 1);

                for (int c = 0; c < 4; ++c) {
                    uint32_t p0 = prev_buf[(src_y0 * cur_w + src_x0) * 4 + c];
                    uint32_t p1 = prev_buf[(src_y0 * cur_w + src_x1) * 4 + c];
                    uint32_t p2 = prev_buf[(src_y1 * cur_w + src_x0) * 4 + c];
                    uint32_t p3 = prev_buf[(src_y1 * cur_w + src_x1) * 4 + c];

                    next_buf[(y * next_w + x) * 4 + c] = static_cast<uint8_t>((p0 + p1 + p2 + p3) / 4);
                }
            }
        }

        prev_buf = std::move(next_buf);
        cur_w = next_w;
        cur_h = next_h;

        if (cur_w == 1 && cur_h == 1 && level < target_level) {
            break;
        }
    }

    if (out_width) *out_width = cur_w;
    if (out_height) *out_height = cur_h;
    std::memcpy(out_pixels, prev_buf.data(), prev_buf.size());
    return 1;
    FFI_CATCH(0)
}

char* filament_tools_minify_glsl(const char* glsl_code, uint32_t options) {
    FFI_TRY
    if (!glsl_code) return nullptr;

    std::string src(glsl_code);
    std::stringstream ss;
    bool in_block_comment = false;

    std::istringstream stream(src);
    std::string line;
    while (std::getline(stream, line)) {
        std::string cleaned;
        for (size_t i = 0; i < line.length(); ++i) {
            if (in_block_comment) {
                if (i + 1 < line.length() && line[i] == '*' && line[i + 1] == '/') {
                    in_block_comment = false;
                    ++i;
                }
                continue;
            }

            if (i + 1 < line.length() && line[i] == '/' && line[i + 1] == '/') {
                break;
            }

            if (i + 1 < line.length() && line[i] == '/' && line[i + 1] == '*') {
                in_block_comment = true;
                ++i;
                continue;
            }

            cleaned += line[i];
        }

        size_t start = cleaned.find_first_not_of(" \t");
        if (start == std::string::npos) {
            continue;
        }
        size_t end = cleaned.find_last_not_of(" \t");
        std::string trimmed = cleaned.substr(start, end - start + 1);

        if (!trimmed.empty()) {
            ss << trimmed << "\n";
        }
    }

    std::string result = ss.str();
    return strdup(result.c_str());
    FFI_CATCH(nullptr)
}

uint8_t filament_tools_blend_normal_maps_rgba8(
    const uint8_t* base_pixels, const uint8_t* detail_pixels,
    uint32_t width, uint32_t height, uint8_t* out_pixels) {
    FFI_TRY
    if (!base_pixels || !detail_pixels || !out_pixels || width == 0 || height == 0) {
        return 0;
    }

    uint32_t total_pixels = width * height;
    for (uint32_t i = 0; i < total_pixels; ++i) {
        uint32_t idx = i * 4;

        float n1_x = (base_pixels[idx + 0] / 255.0f) * 2.0f - 1.0f;
        float n1_y = (base_pixels[idx + 1] / 255.0f) * 2.0f - 1.0f;
        float n1_z = (base_pixels[idx + 2] / 255.0f) * 2.0f - 1.0f;

        float n2_x = (detail_pixels[idx + 0] / 255.0f) * 2.0f - 1.0f;
        float n2_y = (detail_pixels[idx + 1] / 255.0f) * 2.0f - 1.0f;
        float n2_z = (detail_pixels[idx + 2] / 255.0f) * 2.0f - 1.0f;

        float u_x = n1_x;
        float u_y = n1_y;
        float u_z = n1_z + 1.0f;

        float v_x = -n2_x;
        float v_y = -n2_y;
        float v_z = n2_z;

        float dot_u_v = u_x * v_x + u_y * v_y + u_z * v_z;
        float scale = dot_u_v / std::max(1e-5f, u_z);

        float r_x = u_x * scale - v_x;
        float r_y = u_y * scale - v_y;
        float r_z = u_z * scale - v_z;

        float len = std::sqrt(r_x * r_x + r_y * r_y + r_z * r_z);
        if (len > 1e-5f) {
            r_x /= len;
            r_y /= len;
            r_z /= len;
        } else {
            r_x = 0.0f; r_y = 0.0f; r_z = 1.0f;
        }

        out_pixels[idx + 0] = static_cast<uint8_t>(std::clamp((r_x * 0.5f + 0.5f) * 255.0f, 0.0f, 255.0f));
        out_pixels[idx + 1] = static_cast<uint8_t>(std::clamp((r_y * 0.5f + 0.5f) * 255.0f, 0.0f, 255.0f));
        out_pixels[idx + 2] = static_cast<uint8_t>(std::clamp((r_z * 0.5f + 0.5f) * 255.0f, 0.0f, 255.0f));
        out_pixels[idx + 3] = base_pixels[idx + 3];
    }

    return 1;
    FFI_CATCH(0)
}

float filament_tools_compute_dielectric_f0(float ior) {
    if (ior <= 0.0f) return 0.04f;
    float val = (ior - 1.0f) / (ior + 1.0f);
    return val * val;
}

void filament_tools_compute_conductor_f0(
    float n_r, float n_g, float n_b,
    float k_r, float k_g, float k_b,
    float* out_f0_r, float* out_f0_g, float* out_f0_b) {
    FFI_TRY
    auto calc = [](float n, float k) {
        float num = (n - 1.0f) * (n - 1.0f) + k * k;
        float den = (n + 1.0f) * (n + 1.0f) + k * k;
        return (den > 1e-5f) ? (num / den) : 0.0f;
    };

    if (out_f0_r) *out_f0_r = calc(n_r, k_r);
    if (out_f0_g) *out_f0_g = calc(n_g, k_g);
    if (out_f0_b) *out_f0_b = calc(n_b, k_b);
    FFI_CATCH()
}

uint8_t filament_tools_compute_spherical_harmonics_rgba8(
    const uint8_t* equirect_pixels, uint32_t width, uint32_t height, float* out_sh3_rgb_27floats) {
    FFI_TRY
    if (!equirect_pixels || width == 0 || height == 0 || !out_sh3_rgb_27floats) {
        return 0;
    }

    std::memset(out_sh3_rgb_27floats, 0, 27 * sizeof(float));

    float total_weight = 0.0f;
    for (uint32_t y = 0; y < height; ++y) {
        float v = (y + 0.5f) / static_cast<float>(height);
        float theta = v * PI;
        float sin_theta = std::sin(theta);

        for (uint32_t x = 0; x < width; ++x) {
            float u = (x + 0.5f) / static_cast<float>(width);
            float phi = u * 2.0f * PI;

            float dir_x = sin_theta * std::cos(phi);
            float dir_y = std::cos(theta);
            float dir_z = sin_theta * std::sin(phi);

            uint32_t idx = (y * width + x) * 4;
            float r = equirect_pixels[idx + 0] / 255.0f;
            float g = equirect_pixels[idx + 1] / 255.0f;
            float b = equirect_pixels[idx + 2] / 255.0f;

            float sh_basis[9];
            sh_basis[0] = 0.282095f;
            sh_basis[1] = 0.488603f * dir_y;
            sh_basis[2] = 0.488603f * dir_z;
            sh_basis[3] = 0.488603f * dir_x;
            sh_basis[4] = 1.092548f * dir_x * dir_y;
            sh_basis[5] = 1.092548f * dir_y * dir_z;
            sh_basis[6] = 0.315392f * (3.0f * dir_z * dir_z - 1.0f);
            sh_basis[7] = 1.092548f * dir_x * dir_z;
            sh_basis[8] = 0.546274f * (dir_x * dir_x - dir_y * dir_y);

            float weight = sin_theta;
            total_weight += weight;

            for (int i = 0; i < 9; ++i) {
                out_sh3_rgb_27floats[i * 3 + 0] += r * sh_basis[i] * weight;
                out_sh3_rgb_27floats[i * 3 + 1] += g * sh_basis[i] * weight;
                out_sh3_rgb_27floats[i * 3 + 2] += b * sh_basis[i] * weight;
            }
        }
    }

    if (total_weight > 1e-5f) {
        float norm = (4.0f * PI) / total_weight;
        for (int i = 0; i < 27; ++i) {
            out_sh3_rgb_27floats[i] *= norm;
        }
    }

    return 1;
    FFI_CATCH(0)
}

uint8_t filament_tools_compare_images_rgba8(
    const uint8_t* pixels_a, const uint8_t* pixels_b, uint32_t width, uint32_t height,
    uint8_t* out_diff_pixels, float* out_mean_error, float* out_max_error) {
    FFI_TRY
    if (!pixels_a || !pixels_b || width == 0 || height == 0) return 0;

    uint32_t total_channels = width * height * 4;
    double total_diff = 0.0;
    float max_diff = 0.0f;

    for (uint32_t i = 0; i < total_channels; i += 4) {
        int diff_r = std::abs(static_cast<int>(pixels_a[i + 0]) - static_cast<int>(pixels_b[i + 0]));
        int diff_g = std::abs(static_cast<int>(pixels_a[i + 1]) - static_cast<int>(pixels_b[i + 1]));
        int diff_b = std::abs(static_cast<int>(pixels_a[i + 2]) - static_cast<int>(pixels_b[i + 2]));
        int diff_a = std::abs(static_cast<int>(pixels_a[i + 3]) - static_cast<int>(pixels_b[i + 3]));

        total_diff += (diff_r + diff_g + diff_b + diff_a) / 4.0;
        float pixel_max = std::max({(float)diff_r, (float)diff_g, (float)diff_b, (float)diff_a});
        if (pixel_max > max_diff) max_diff = pixel_max;

        if (out_diff_pixels) {
            out_diff_pixels[i + 0] = static_cast<uint8_t>(diff_r);
            out_diff_pixels[i + 1] = static_cast<uint8_t>(diff_g);
            out_diff_pixels[i + 2] = static_cast<uint8_t>(diff_b);
            out_diff_pixels[i + 3] = 255;
        }
    }

    if (out_mean_error) *out_mean_error = static_cast<float>(total_diff / (width * height * 255.0));
    if (out_max_error) *out_max_error = max_diff / 255.0f;

    return 1;
    FFI_CATCH(0)
}

float filament_tools_compute_specular_ao(float roughness, float ndotv, float ao) {
    FFI_TRY
    float alpha = std::clamp(roughness, 0.0f, 1.0f);
    float clamped_ao = std::clamp(ao, 0.0f, 1.0f);
    float exponent = 1.0f / (1.0f + 5.0f * alpha);
    return std::clamp(std::pow(clamped_ao, exponent), 0.0f, 1.0f);
    FFI_CATCH(0.0f)
}

void* filament_tools_zstd_compress(const void* data, uint32_t size, uint32_t* out_compressed_size) {
    FFI_TRY
    if (!data || size == 0 || !out_compressed_size) return nullptr;

    size_t max_dest_size = ZSTD_compressBound(size);
    void* dest_buf = std::malloc(max_dest_size);
    if (!dest_buf) return nullptr;

    size_t comp_size = ZSTD_compress(dest_buf, max_dest_size, data, size, 3);
    if (ZSTD_isError(comp_size)) {
        std::free(dest_buf);
        return nullptr;
    }

    *out_compressed_size = static_cast<uint32_t>(comp_size);
    return dest_buf;
    FFI_CATCH(nullptr)
}

void* filament_tools_zstd_decompress(const void* compressed_data, uint32_t compressed_size, uint32_t* out_decompressed_size) {
    FFI_TRY
    if (!compressed_data || compressed_size == 0 || !out_decompressed_size) return nullptr;

    unsigned long long orig_size = ZSTD_getFrameContentSize(compressed_data, compressed_size);
    if (orig_size == ZSTD_CONTENTSIZE_ERROR || orig_size == ZSTD_CONTENTSIZE_UNKNOWN) {
        return nullptr;
    }

    void* dest_buf = std::malloc(static_cast<size_t>(orig_size));
    if (!dest_buf) return nullptr;

    size_t decomp_size = ZSTD_decompress(dest_buf, static_cast<size_t>(orig_size), compressed_data, compressed_size);
    if (ZSTD_isError(decomp_size)) {
        std::free(dest_buf);
        return nullptr;
    }

    *out_decompressed_size = static_cast<uint32_t>(decomp_size);
    return dest_buf;
    FFI_CATCH(nullptr)
}

char* filament_tools_dump_frame_pipeline_json(void* view, void* scene, void* camera) {
    FFI_TRY
    std::stringstream ss;
    ss << "{\n";
    ss << "  \"view\": {\n";
    ss << "    \"pointer\": \"" << view << "\"\n";
    ss << "  },\n";
    ss << "  \"scene\": {\n";
    ss << "    \"pointer\": \"" << scene << "\"\n";
    ss << "  },\n";
    ss << "  \"camera\": {\n";
    ss << "    \"pointer\": \"" << camera << "\"\n";
    ss << "  }\n";
    ss << "}";

    std::string str = ss.str();
    return strdup(str.c_str());
    FFI_CATCH(nullptr)
}

void filament_tools_free_string(char* str) {
    FFI_TRY
    if (str) {
        free(str);
    }
    FFI_CATCH()
}

void filament_tools_free_buffer(void* ptr) {
    FFI_TRY
    if (ptr) {
        free(ptr);
    }
    FFI_CATCH()
}

}
