// GENERATED by tool/web/gen_web_stubs.mjs from filamat_c.h, matc_c.h, imageio_c.h — do not edit.
// Web builds only: these libraries are not part of Filament's WebAssembly build.
#ifdef __EMSCRIPTEN__
#include <cstdio>
#include "filamat_c.h"
#include "matc_c.h"
#include "imageio_c.h"

static void flutter_filament_web_unavailable(const char* function, const char* library) {
  fprintf(stderr, "[flutter_filament] %s is not available in web builds: %s is desktop-only
", function, library);
}

// --- filamat_c.h ---

void filament_filamat_init(void) {
  flutter_filament_web_unavailable("filament_filamat_init", "filamat (runtime material compiler)");
}

void filament_filamat_shutdown(void) {
  flutter_filament_web_unavailable("filament_filamat_shutdown", "filamat (runtime material compiler)");
}

void* filament_material_builder_create(void) {
  flutter_filament_web_unavailable("filament_material_builder_create", "filamat (runtime material compiler)");
  return {};
}

void filament_material_builder_destroy(void* builder) {
  flutter_filament_web_unavailable("filament_material_builder_destroy", "filamat (runtime material compiler)");
}

void filament_material_builder_set_name(void* builder, const char* name) {
  flutter_filament_web_unavailable("filament_material_builder_set_name", "filamat (runtime material compiler)");
}

void filament_material_builder_set_code(void* builder, const char* glsl_code) {
  flutter_filament_web_unavailable("filament_material_builder_set_code", "filamat (runtime material compiler)");
}

void filament_material_builder_set_shading(void* builder, int shading) {
  flutter_filament_web_unavailable("filament_material_builder_set_shading", "filamat (runtime material compiler)");
}

void filament_material_builder_set_double_sided(void* builder, bool double_sided) {
  flutter_filament_web_unavailable("filament_material_builder_set_double_sided", "filamat (runtime material compiler)");
}

void filament_material_builder_require_attribute(void* builder, int attribute) {
  flutter_filament_web_unavailable("filament_material_builder_require_attribute", "filamat (runtime material compiler)");
}

void filament_material_builder_parameter_sampler(void* builder, const char* name, int sampler_type) {
  flutter_filament_web_unavailable("filament_material_builder_parameter_sampler", "filamat (runtime material compiler)");
}

void filament_material_builder_parameter(void* builder, const char* name, int uniform_type, int precision) {
  flutter_filament_web_unavailable("filament_material_builder_parameter", "filamat (runtime material compiler)");
}

void filament_material_builder_parameter_array(void* builder, const char* name, size_t size, int uniform_type, int precision) {
  flutter_filament_web_unavailable("filament_material_builder_parameter_array", "filamat (runtime material compiler)");
}

void filament_material_builder_constant_bool(void* builder, const char* name, bool default_value) {
  flutter_filament_web_unavailable("filament_material_builder_constant_bool", "filamat (runtime material compiler)");
}

void filament_material_builder_constant_int(void* builder, const char* name, int32_t default_value) {
  flutter_filament_web_unavailable("filament_material_builder_constant_int", "filamat (runtime material compiler)");
}

void filament_material_builder_constant_float(void* builder, const char* name, float default_value) {
  flutter_filament_web_unavailable("filament_material_builder_constant_float", "filamat (runtime material compiler)");
}

void filament_material_builder_material_vertex(void* builder, const char* code) {
  flutter_filament_web_unavailable("filament_material_builder_material_vertex", "filamat (runtime material compiler)");
}

void filament_material_builder_variable(void* builder, int variable, const char* name) {
  flutter_filament_web_unavailable("filament_material_builder_variable", "filamat (runtime material compiler)");
}

void filament_material_builder_variable_precision(void* builder, int variable, const char* name, int precision) {
  flutter_filament_web_unavailable("filament_material_builder_variable_precision", "filamat (runtime material compiler)");
}

void filament_material_builder_vertex_domain(void* builder, int domain) {
  flutter_filament_web_unavailable("filament_material_builder_vertex_domain", "filamat (runtime material compiler)");
}

void filament_material_builder_vertex_domain_device_jittered(void* builder, bool jittered) {
  flutter_filament_web_unavailable("filament_material_builder_vertex_domain_device_jittered", "filamat (runtime material compiler)");
}

void filament_material_builder_flip_uv(void* builder, bool flip) {
  flutter_filament_web_unavailable("filament_material_builder_flip_uv", "filamat (runtime material compiler)");
}

void filament_material_builder_blending(void* builder, int blending_mode) {
  flutter_filament_web_unavailable("filament_material_builder_blending", "filamat (runtime material compiler)");
}

void filament_material_builder_custom_blend_functions(void* builder, int src_rgb, int src_a, int dst_rgb, int dst_a) {
  flutter_filament_web_unavailable("filament_material_builder_custom_blend_functions", "filamat (runtime material compiler)");
}

void filament_material_builder_post_lighting_blending(void* builder, int blending_mode) {
  flutter_filament_web_unavailable("filament_material_builder_post_lighting_blending", "filamat (runtime material compiler)");
}

void filament_material_builder_transparency_mode(void* builder, int mode) {
  flutter_filament_web_unavailable("filament_material_builder_transparency_mode", "filamat (runtime material compiler)");
}

void filament_material_builder_mask_threshold(void* builder, float threshold) {
  flutter_filament_web_unavailable("filament_material_builder_mask_threshold", "filamat (runtime material compiler)");
}

void filament_material_builder_alpha_to_coverage(void* builder, bool enable) {
  flutter_filament_web_unavailable("filament_material_builder_alpha_to_coverage", "filamat (runtime material compiler)");
}

void filament_material_builder_refraction_mode(void* builder, int mode) {
  flutter_filament_web_unavailable("filament_material_builder_refraction_mode", "filamat (runtime material compiler)");
}

void filament_material_builder_refraction_type(void* builder, int type) {
  flutter_filament_web_unavailable("filament_material_builder_refraction_type", "filamat (runtime material compiler)");
}

void filament_material_builder_culling(void* builder, int culling_mode) {
  flutter_filament_web_unavailable("filament_material_builder_culling", "filamat (runtime material compiler)");
}

void filament_material_builder_color_write(void* builder, bool enable) {
  flutter_filament_web_unavailable("filament_material_builder_color_write", "filamat (runtime material compiler)");
}

void filament_material_builder_depth_write(void* builder, bool enable) {
  flutter_filament_web_unavailable("filament_material_builder_depth_write", "filamat (runtime material compiler)");
}

void filament_material_builder_depth_culling(void* builder, bool enable) {
  flutter_filament_web_unavailable("filament_material_builder_depth_culling", "filamat (runtime material compiler)");
}

void filament_material_builder_instanced(void* builder, bool enable) {
  flutter_filament_web_unavailable("filament_material_builder_instanced", "filamat (runtime material compiler)");
}

void filament_material_builder_material_domain(void* builder, int domain) {
  flutter_filament_web_unavailable("filament_material_builder_material_domain", "filamat (runtime material compiler)");
}

void filament_material_builder_group_size(void* builder, uint32_t x, uint32_t y, uint32_t z) {
  flutter_filament_web_unavailable("filament_material_builder_group_size", "filamat (runtime material compiler)");
}

void filament_material_builder_output(void* builder, int qualifier, int target, int precision, int type, const char* name, int location) {
  flutter_filament_web_unavailable("filament_material_builder_output", "filamat (runtime material compiler)");
}

void filament_material_builder_enable_framebuffer_fetch(void* builder) {
  flutter_filament_web_unavailable("filament_material_builder_enable_framebuffer_fetch", "filamat (runtime material compiler)");
}

void filament_material_builder_subpass(void* builder, int type, const char* name) {
  flutter_filament_web_unavailable("filament_material_builder_subpass", "filamat (runtime material compiler)");
}

void filament_material_builder_platform(void* builder, int platform) {
  flutter_filament_web_unavailable("filament_material_builder_platform", "filamat (runtime material compiler)");
}

void filament_material_builder_target_api(void* builder, int api) {
  flutter_filament_web_unavailable("filament_material_builder_target_api", "filamat (runtime material compiler)");
}

void filament_material_builder_optimization(void* builder, int level) {
  flutter_filament_web_unavailable("filament_material_builder_optimization", "filamat (runtime material compiler)");
}

void filament_material_builder_variant_filter(void* builder, uint64_t mask) {
  flutter_filament_web_unavailable("filament_material_builder_variant_filter", "filamat (runtime material compiler)");
}

void filament_material_builder_shader_define(void* builder, const char* name, const char* value) {
  flutter_filament_web_unavailable("filament_material_builder_shader_define", "filamat (runtime material compiler)");
}

void filament_material_builder_shadow_multiplier(void* builder, bool enabled) {
  flutter_filament_web_unavailable("filament_material_builder_shadow_multiplier", "filamat (runtime material compiler)");
}

void filament_material_builder_transparent_shadow(void* builder, bool enabled) {
  flutter_filament_web_unavailable("filament_material_builder_transparent_shadow", "filamat (runtime material compiler)");
}

void filament_material_builder_colored_penumbra(void* builder, bool enabled) {
  flutter_filament_web_unavailable("filament_material_builder_colored_penumbra", "filamat (runtime material compiler)");
}

void filament_material_builder_shadow_far_attenuation(void* builder, bool enabled) {
  flutter_filament_web_unavailable("filament_material_builder_shadow_far_attenuation", "filamat (runtime material compiler)");
}

void filament_material_builder_quality(void* builder, int quality) {
  flutter_filament_web_unavailable("filament_material_builder_quality", "filamat (runtime material compiler)");
}

void filament_material_builder_feature_level(void* builder, int level) {
  flutter_filament_web_unavailable("filament_material_builder_feature_level", "filamat (runtime material compiler)");
}

void filament_material_builder_include_essl1(void* builder, bool enabled) {
  flutter_filament_web_unavailable("filament_material_builder_include_essl1", "filamat (runtime material compiler)");
}

void filament_material_builder_interpolation(void* builder, int interpolation) {
  flutter_filament_web_unavailable("filament_material_builder_interpolation", "filamat (runtime material compiler)");
}

void filament_material_builder_specular_anti_aliasing(void* builder, bool enabled) {
  flutter_filament_web_unavailable("filament_material_builder_specular_anti_aliasing", "filamat (runtime material compiler)");
}

void filament_material_builder_specular_anti_aliasing_variance(void* builder, float variance) {
  flutter_filament_web_unavailable("filament_material_builder_specular_anti_aliasing_variance", "filamat (runtime material compiler)");
}

void filament_material_builder_specular_anti_aliasing_threshold(void* builder, float threshold) {
  flutter_filament_web_unavailable("filament_material_builder_specular_anti_aliasing_threshold", "filamat (runtime material compiler)");
}

void filament_material_builder_clear_coat_ior_change(void* builder, bool enabled) {
  flutter_filament_web_unavailable("filament_material_builder_clear_coat_ior_change", "filamat (runtime material compiler)");
}

void filament_material_builder_linear_fog(void* builder, bool enabled) {
  flutter_filament_web_unavailable("filament_material_builder_linear_fog", "filamat (runtime material compiler)");
}

void filament_material_builder_custom_surface_shading(void* builder, bool enabled) {
  flutter_filament_web_unavailable("filament_material_builder_custom_surface_shading", "filamat (runtime material compiler)");
}

void filament_material_builder_reflection_mode(void* builder, int mode) {
  flutter_filament_web_unavailable("filament_material_builder_reflection_mode", "filamat (runtime material compiler)");
}

void filament_material_builder_multi_bounce_ambient_occlusion(void* builder, bool enabled) {
  flutter_filament_web_unavailable("filament_material_builder_multi_bounce_ambient_occlusion", "filamat (runtime material compiler)");
}

void filament_material_builder_specular_ambient_occlusion(void* builder, int mode) {
  flutter_filament_web_unavailable("filament_material_builder_specular_ambient_occlusion", "filamat (runtime material compiler)");
}

void filament_material_builder_print_shaders(void* builder, bool enabled) {
  flutter_filament_web_unavailable("filament_material_builder_print_shaders", "filamat (runtime material compiler)");
}

void filament_material_builder_save_raw_variants(void* builder, bool enabled) {
  flutter_filament_web_unavailable("filament_material_builder_save_raw_variants", "filamat (runtime material compiler)");
}

void filament_material_builder_generate_debug_info(void* builder, bool enabled) {
  flutter_filament_web_unavailable("filament_material_builder_generate_debug_info", "filamat (runtime material compiler)");
}

void* filament_material_builder_build(void* builder, size_t* out_size) {
  flutter_filament_web_unavailable("filament_material_builder_build", "filamat (runtime material compiler)");
  return {};
}

void filament_filamat_free_package(void* package_bytes) {
  flutter_filament_web_unavailable("filament_filamat_free_package", "filamat (runtime material compiler)");
}

// --- matc_c.h ---

void* filament_matc_compile(const char* source, size_t length, const char* file_name, const char* include_dir, const char* default_name, int platform, int target_api, int optimization, bool debug, uint32_t variant_filter, size_t* out_size, char** out_diagnostics) {
  flutter_filament_web_unavailable("filament_matc_compile", "filamat (runtime material compiler)");
  return {};
}

void filament_matc_free(void* pointer) {
  flutter_filament_web_unavailable("filament_matc_free", "filamat (runtime material compiler)");
}

// --- imageio_c.h ---

FilLinearImage* filament_image_decode(const uint8_t* data, size_t size, const char* source_name, int color_space) {
  flutter_filament_web_unavailable("filament_image_decode", "imageio (image encoders and decoders)");
  return {};
}

bool filament_image_encode(int format, const FilLinearImage* img, const char* compression, uint8_t** out_data, size_t* out_size) {
  flutter_filament_web_unavailable("filament_image_encode", "imageio (image encoders and decoders)");
  return {};
}

void filament_image_encode_free(uint8_t* data) {
  flutter_filament_web_unavailable("filament_image_encode_free", "imageio (image encoders and decoders)");
}

FilBasisEncoderBuilder* filament_basis_encoder_builder_create(uint32_t mip_count, bool grayscale, bool normals, bool linear) {
  flutter_filament_web_unavailable("filament_basis_encoder_builder_create", "imageio (image encoders and decoders)");
  return {};
}

void filament_basis_encoder_builder_miplevel(FilBasisEncoderBuilder* b, uint32_t mip, const FilLinearImage* img) {
  flutter_filament_web_unavailable("filament_basis_encoder_builder_miplevel", "imageio (image encoders and decoders)");
}

void filament_basis_encoder_builder_intermediate_format(FilBasisEncoderBuilder* b, bool uastc) {
  flutter_filament_web_unavailable("filament_basis_encoder_builder_intermediate_format", "imageio (image encoders and decoders)");
}

FilBasisEncoder* filament_basis_encoder_builder_build(FilBasisEncoderBuilder* b) {
  flutter_filament_web_unavailable("filament_basis_encoder_builder_build", "imageio (image encoders and decoders)");
  return {};
}

void filament_basis_encoder_builder_destroy(FilBasisEncoderBuilder* b) {
  flutter_filament_web_unavailable("filament_basis_encoder_builder_destroy", "imageio (image encoders and decoders)");
}

bool filament_basis_encoder_encode(FilBasisEncoder* e) {
  flutter_filament_web_unavailable("filament_basis_encoder_encode", "imageio (image encoders and decoders)");
  return {};
}

size_t filament_basis_encoder_get_ktx2_byte_count(const FilBasisEncoder* e) {
  flutter_filament_web_unavailable("filament_basis_encoder_get_ktx2_byte_count", "imageio (image encoders and decoders)");
  return {};
}

const uint8_t* filament_basis_encoder_get_ktx2_data(const FilBasisEncoder* e) {
  flutter_filament_web_unavailable("filament_basis_encoder_get_ktx2_data", "imageio (image encoders and decoders)");
  return {};
}

void filament_basis_encoder_destroy(FilBasisEncoder* e) {
  flutter_filament_web_unavailable("filament_basis_encoder_destroy", "imageio (image encoders and decoders)");
}

#endif  // __EMSCRIPTEN__
