/// The Linux runner's window-mode files a generated game gets
/// (`linux/runner/lumina_window_mode.{h,cc}`), written by
/// `GameWindowRunnerService`.
library;

const String kLinuxWindowModeHeader = r'''
// GENERATED by Lumina Studio (Project Settings > Start Fullscreen). Do not edit:
// it is rewritten on every code generation.
#ifndef RUNNER_LUMINA_WINDOW_MODE_H_
#define RUNNER_LUMINA_WINDOW_MODE_H_

#include <flutter_linux/flutter_linux.h>
#include <gtk/gtk.h>

// Gives the game window its modes: windowed and fullscreen
// (gtk_window_fullscreen, X11 and Wayland). Starts in the project's Start
// Fullscreen mode before the window is shown, toggles on Alt+Enter and F11,
// and answers the "lumina/game_window" channel (getMode, setMode, getInfo;
// calls modeChanged after a key toggle). It also reports the monitors
// (GdkMonitor: current mode only) and resizes or moves the window for the
// game's screen resolution (getDisplays, setClientSize, moveToMonitor; calls
// displayChanged).
//
// Call once from my_application_activate, after fl_register_plugins.
void lumina_window_mode_attach(GtkWindow* window, FlView* view);

#endif  // RUNNER_LUMINA_WINDOW_MODE_H_
''';

/// The `.cc`; `{{START_FULLSCREEN}}` is `TRUE` or `FALSE`.
const String kLinuxWindowModeSource = r'''
// GENERATED by Lumina Studio (Project Settings > Start Fullscreen). Do not edit:
// it is rewritten on every code generation.
#include "lumina_window_mode.h"

#include <gdk/gdkkeysyms.h>
#include <string.h>

static const gboolean kStartFullscreen = {{START_FULLSCREEN}};
static const char kWindowed[] = "windowed";
static const char kBorderless[] = "borderless_fullscreen";

static GtkWindow* g_window = nullptr;
static FlMethodChannel* g_channel = nullptr;
static gboolean g_fullscreen = FALSE;
static guint g_swallowed_key = 0;

static const char* mode_id() { return g_fullscreen ? kBorderless : kWindowed; }

static void set_fullscreen(gboolean on) {
  if (on) {
    gtk_window_fullscreen(g_window);
  } else {
    gtk_window_unfullscreen(g_window);
  }
  g_fullscreen = on;
}

static void notify_mode_changed() {
  if (g_channel == nullptr) return;
  g_autoptr(FlValue) args = fl_value_new_map();
  fl_value_set_string_take(args, "mode", fl_value_new_string(mode_id()));
  fl_method_channel_invoke_method(g_channel, "modeChanged", args, nullptr,
                                  nullptr, nullptr);
}

static gboolean window_state_cb(GtkWidget* widget, GdkEventWindowState* event,
                                gpointer user_data) {
  if (event->changed_mask & GDK_WINDOW_STATE_FULLSCREEN) {
    g_fullscreen = (event->new_window_state & GDK_WINDOW_STATE_FULLSCREEN) != 0;
  }
  return FALSE;
}

static gboolean is_toggle_key(GdkEventKey* event) {
  if (event->keyval == GDK_KEY_F11) return TRUE;
  return (event->keyval == GDK_KEY_Return || event->keyval == GDK_KEY_KP_Enter) &&
         (event->state & GDK_MOD1_MASK) != 0;
}

// Runs before the Flutter view gets the key: Alt+Enter and F11 never reach
// the game.
static gboolean key_press_cb(GtkWidget* widget, GdkEventKey* event,
                             gpointer user_data) {
  if (!is_toggle_key(event)) return FALSE;
  if (g_swallowed_key != event->keyval) {
    set_fullscreen(!g_fullscreen);
    notify_mode_changed();
  }
  g_swallowed_key = event->keyval;
  return TRUE;
}

static gboolean key_release_cb(GtkWidget* widget, GdkEventKey* event,
                               gpointer user_data) {
  if (g_swallowed_key == 0 || event->keyval != g_swallowed_key) return FALSE;
  g_swallowed_key = 0;
  return TRUE;
}

{{DISPLAY}}

static void method_call_cb(FlMethodChannel* channel, FlMethodCall* call,
                           gpointer user_data) {
  const gchar* method = fl_method_call_get_name(call);
  g_autoptr(FlMethodResponse) response = nullptr;
  if (strcmp(method, "getMode") == 0) {
    g_autoptr(FlValue) result = fl_value_new_string(mode_id());
    response = FL_METHOD_RESPONSE(fl_method_success_response_new(result));
  } else if (strcmp(method, "setMode") == 0) {
    FlValue* args = fl_method_call_get_args(call);
    FlValue* value = (args != nullptr && fl_value_get_type(args) == FL_VALUE_TYPE_MAP)
                         ? fl_value_lookup_string(args, "mode")
                         : nullptr;
    const gchar* mode = (value != nullptr && fl_value_get_type(value) == FL_VALUE_TYPE_STRING)
                            ? fl_value_get_string(value)
                            : "";
    if (strcmp(mode, kBorderless) == 0 || strcmp(mode, kWindowed) == 0) {
      set_fullscreen(strcmp(mode, kBorderless) == 0);
      g_autoptr(FlValue) result = fl_value_new_bool(TRUE);
      response = FL_METHOD_RESPONSE(fl_method_success_response_new(result));
    } else {
      response = FL_METHOD_RESPONSE(
          fl_method_error_response_new("unknown_mode", "Unknown window mode", nullptr));
    }
  } else if (strcmp(method, "getInfo") == 0) {
    gint width = 0;
    gint height = 0;
    gtk_window_get_size(g_window, &width, &height);
    const gint scale = gtk_widget_get_scale_factor(GTK_WIDGET(g_window));
    g_autoptr(FlValue) result = fl_value_new_map();
    fl_value_set_string_take(result, "mode", fl_value_new_string(mode_id()));
    fl_value_set_string_take(result, "popup", fl_value_new_bool(g_fullscreen));
    FlValue* client = fl_value_new_list();
    fl_value_append_take(client, fl_value_new_int(width * scale));
    fl_value_append_take(client, fl_value_new_int(height * scale));
    fl_value_set_string_take(result, "client", client);
    response = FL_METHOD_RESPONSE(fl_method_success_response_new(result));
  } else if (FlMethodResponse* display = handle_display_call(method, fl_method_call_get_args(call))) {
    // getDisplays, setClientSize, moveToMonitor.
    response = display;
  } else {
    response = FL_METHOD_RESPONSE(fl_method_not_implemented_response_new());
  }
  fl_method_call_respond(call, response, nullptr);
}

void lumina_window_mode_attach(GtkWindow* window, FlView* view) {
  g_window = window;
  FlEngine* engine = fl_view_get_engine(view);
  g_autoptr(FlStandardMethodCodec) codec = fl_standard_method_codec_new();
  g_channel = fl_method_channel_new(fl_engine_get_binary_messenger(engine),
                                    "lumina/game_window", FL_METHOD_CODEC(codec));
  fl_method_channel_set_method_call_handler(g_channel, method_call_cb, nullptr,
                                            nullptr);
  g_signal_connect(window, "window-state-event", G_CALLBACK(window_state_cb),
                   nullptr);
  g_signal_connect(window, "key-press-event", G_CALLBACK(key_press_cb), nullptr);
  g_signal_connect(window, "key-release-event", G_CALLBACK(key_release_cb),
                   nullptr);
  watch_displays();
  // Before the window is shown (it shows on the first frame): it opens
  // fullscreen on the monitor it maps to.
  if (kStartFullscreen) set_fullscreen(TRUE);
}
''';
