/// The Windows runner's window-mode files a generated game gets
/// (`windows/runner/lumina_window_mode.{h,cpp}`), written by
/// `GameWindowRunnerService`.
library;

const String kWindowsWindowModeHeader = r'''
// GENERATED by Lumina Studio (Project Settings > Start Fullscreen). Do not edit:
// it is rewritten on every code generation.
#ifndef RUNNER_LUMINA_WINDOW_MODE_H_
#define RUNNER_LUMINA_WINDOW_MODE_H_

#include <flutter/binary_messenger.h>
#include <windows.h>

// Gives the game window its modes: windowed and borderless fullscreen (a
// WS_POPUP window covering the whole monitor it is on, taskbar included, at
// the monitor's native resolution). Starts in the project's Start Fullscreen
// mode while the window is still hidden, toggles on Alt+Enter and F11
// (restoring the windowed placement), keeps covering the monitor through
// display and DPI changes, and answers the "lumina/game_window" channel
// (getMode, setMode, getInfo; calls modeChanged after a key toggle). It also
// reports the monitors and their display modes and resizes or moves the
// window for the game's screen resolution (getDisplays, setClientSize,
// moveToMonitor; calls displayChanged).
//
// Call once from FlutterWindow::OnCreate, after SetChildContent.
void LuminaWindowModeAttach(flutter::BinaryMessenger* messenger, HWND window,
                            HWND view);

#endif  // RUNNER_LUMINA_WINDOW_MODE_H_
''';

/// The `.cpp`; `{{START_FULLSCREEN}}` is `true` or `false`.
const String kWindowsWindowModeSource = r'''
// GENERATED by Lumina Studio (Project Settings > Start Fullscreen). Do not edit:
// it is rewritten on every code generation.
#include "lumina_window_mode.h"

#include <dwmapi.h>
#include <flutter/encodable_value.h>
#include <flutter/method_channel.h>
#include <flutter/standard_method_codec.h>
#include <flutter_windows.h>

#include <algorithm>
#include <memory>
#include <set>
#include <string>
#include <tuple>
#include <vector>

namespace {

constexpr bool kStartFullscreen = {{START_FULLSCREEN}};
constexpr char kChannelName[] = "lumina/game_window";
constexpr char kWindowed[] = "windowed";
constexpr char kBorderless[] = "borderless_fullscreen";

// DWMWA_WINDOW_CORNER_PREFERENCE / DWMWCP_* (Windows 11; older SDKs lack them).
constexpr DWORD kDwmCornerPreference = 33;
constexpr DWORD kDwmCornerDefault = 0;
constexpr DWORD kDwmCornerDoNotRound = 1;

using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

HWND g_window = nullptr;
HWND g_view = nullptr;
WNDPROC g_window_proc = nullptr;
WNDPROC g_view_proc = nullptr;
bool g_fullscreen = false;
LONG_PTR g_windowed_style = WS_OVERLAPPEDWINDOW;
WINDOWPLACEMENT g_windowed_placement = {sizeof(WINDOWPLACEMENT)};
bool g_have_placement = false;
WPARAM g_swallowed_key = 0;
std::unique_ptr<flutter::MethodChannel<EncodableValue>> g_channel;

const char* ModeId() { return g_fullscreen ? kBorderless : kWindowed; }

MONITORINFO MonitorOf(HWND window) {
  MONITORINFO info = {sizeof(MONITORINFO)};
  ::GetMonitorInfo(::MonitorFromWindow(window, MONITOR_DEFAULTTONEAREST),
                   &info);
  return info;
}

void SetRoundedCorners(bool rounded) {
  DWORD preference = rounded ? kDwmCornerDefault : kDwmCornerDoNotRound;
  ::DwmSetWindowAttribute(g_window, kDwmCornerPreference, &preference,
                          sizeof(preference));
}

// Covers the whole monitor the window is on (rcMonitor, not the work area:
// the taskbar is covered too).
void FitToMonitor() {
  const RECT r = MonitorOf(g_window).rcMonitor;
  UINT flags = SWP_NOOWNERZORDER | SWP_FRAMECHANGED;
  if (!::IsWindowVisible(g_window)) flags |= SWP_NOACTIVATE;
  ::SetWindowPos(g_window, HWND_TOP, r.left, r.top, r.right - r.left,
                 r.bottom - r.top, flags);
}

void EnterFullscreen() {
  if (g_fullscreen) {
    FitToMonitor();
    return;
  }
  if (::IsZoomed(g_window)) {
    // Leave maximized first so the saved placement restores to it later.
    g_have_placement = ::GetWindowPlacement(g_window, &g_windowed_placement) != FALSE;
    ::ShowWindow(g_window, SW_RESTORE);
  } else {
    g_have_placement = ::GetWindowPlacement(g_window, &g_windowed_placement) != FALSE;
  }
  const LONG_PTR style = ::GetWindowLongPtr(g_window, GWL_STYLE);
  g_windowed_style = style & ~(WS_VISIBLE | WS_MAXIMIZE | WS_MINIMIZE);
  g_fullscreen = true;
  ::SetWindowLongPtr(g_window, GWL_STYLE,
                     (style & ~(WS_OVERLAPPEDWINDOW | WS_MAXIMIZE | WS_MINIMIZE)) |
                         WS_POPUP);
  SetRoundedCorners(false);
  FitToMonitor();
}

void ExitFullscreen() {
  if (!g_fullscreen) return;
  g_fullscreen = false;
  const bool visible = ::IsWindowVisible(g_window) != FALSE;
  ::SetWindowLongPtr(g_window, GWL_STYLE,
                     g_windowed_style | (visible ? WS_VISIBLE : 0));
  SetRoundedCorners(true);
  if (g_have_placement) {
    WINDOWPLACEMENT placement = g_windowed_placement;
    if (!visible) {
      placement.showCmd = SW_HIDE;
    } else if (placement.showCmd != SW_SHOWMAXIMIZED) {
      placement.showCmd = SW_SHOWNORMAL;
    }
    ::SetWindowPlacement(g_window, &placement);
  }
  ::SetWindowPos(g_window, nullptr, 0, 0, 0, 0,
                 SWP_NOMOVE | SWP_NOSIZE | SWP_NOZORDER | SWP_NOOWNERZORDER |
                     SWP_FRAMECHANGED);
}

void NotifyModeChanged() {
  if (!g_channel) return;
  g_channel->InvokeMethod(
      "modeChanged",
      std::make_unique<EncodableValue>(EncodableMap{
          {EncodableValue("mode"), EncodableValue(std::string(ModeId()))}}));
}

void Toggle() {
  if (g_fullscreen) {
    ExitFullscreen();
  } else {
    EnterFullscreen();
  }
  NotifyModeChanged();
}

EncodableValue RectValue(const RECT& r) {
  return EncodableValue(EncodableList{
      EncodableValue(static_cast<int32_t>(r.left)),
      EncodableValue(static_cast<int32_t>(r.top)),
      EncodableValue(static_cast<int32_t>(r.right)),
      EncodableValue(static_cast<int32_t>(r.bottom))});
}

EncodableValue Info() {
  RECT window = {};
  ::GetWindowRect(g_window, &window);
  RECT client = {};
  ::GetClientRect(g_view ? g_view : g_window, &client);
  const MONITORINFO monitor = MonitorOf(g_window);
  const LONG_PTR style = ::GetWindowLongPtr(g_window, GWL_STYLE);
  return EncodableValue(EncodableMap{
      {EncodableValue("mode"), EncodableValue(std::string(ModeId()))},
      {EncodableValue("window"), RectValue(window)},
      {EncodableValue("monitor"), RectValue(monitor.rcMonitor)},
      {EncodableValue("work"), RectValue(monitor.rcWork)},
      {EncodableValue("client"),
       EncodableValue(EncodableList{
           EncodableValue(static_cast<int32_t>(client.right - client.left)),
           EncodableValue(static_cast<int32_t>(client.bottom - client.top))})},
      {EncodableValue("popup"), EncodableValue((style & WS_POPUP) != 0)},
      {EncodableValue("caption"),
       EncodableValue((style & WS_CAPTION) == WS_CAPTION)},
      {EncodableValue("foreground"),
       EncodableValue(::GetForegroundWindow() == g_window)},
  });
}

{{DISPLAY}}

bool IsToggleKey(UINT message, WPARAM key, LPARAM flags) {
  const bool alt = (flags & (1 << 29)) != 0;
  if (message == WM_SYSKEYDOWN && key == VK_RETURN && alt) return true;
  return (message == WM_KEYDOWN || message == WM_SYSKEYDOWN) && key == VK_F11;
}

// The Flutter view has the keyboard focus: Alt+Enter and F11 are taken here,
// before Flutter sees them, with their repeats, key-ups and the Alt+Enter
// WM_SYSCHAR (which would beep).
LRESULT CALLBACK ViewProc(HWND hwnd, UINT message, WPARAM wparam,
                          LPARAM lparam) {
  if (IsToggleKey(message, wparam, lparam)) {
    if ((lparam & (1 << 30)) == 0) Toggle();
    g_swallowed_key = wparam;
    return 0;
  }
  if ((message == WM_KEYUP || message == WM_SYSKEYUP) &&
      g_swallowed_key != 0 && wparam == g_swallowed_key) {
    g_swallowed_key = 0;
    return 0;
  }
  if (message == WM_SYSCHAR && wparam == VK_RETURN) return 0;
  return ::CallWindowProc(g_view_proc, hwnd, message, wparam, lparam);
}

// While fullscreen the window keeps covering its monitor when the display or
// its DPI changes (the default handler would apply the suggested windowed
// rectangle).
LRESULT CALLBACK WindowProc(HWND hwnd, UINT message, WPARAM wparam,
                            LPARAM lparam) {
  const LRESULT result =
      ::CallWindowProc(g_window_proc, hwnd, message, wparam, lparam);
  if (g_fullscreen && (message == WM_DPICHANGED || message == WM_DISPLAYCHANGE)) {
    FitToMonitor();
  }
  WatchDisplays(message);
  return result;
}

void HandleCall(const flutter::MethodCall<EncodableValue>& call,
                std::unique_ptr<flutter::MethodResult<EncodableValue>> result) {
  const std::string& method = call.method_name();
  if (method == "getMode") {
    result->Success(EncodableValue(std::string(ModeId())));
  } else if (method == "setMode") {
    std::string mode;
    if (const auto* args = std::get_if<EncodableMap>(call.arguments())) {
      const auto it = args->find(EncodableValue("mode"));
      if (it != args->end()) {
        if (const auto* text = std::get_if<std::string>(&it->second)) mode = *text;
      }
    }
    if (mode == kBorderless) {
      EnterFullscreen();
      result->Success(EncodableValue(true));
    } else if (mode == kWindowed) {
      ExitFullscreen();
      result->Success(EncodableValue(true));
    } else {
      result->Error("unknown_mode", "Unknown window mode: " + mode);
    }
  } else if (method == "getInfo") {
    result->Success(Info());
  } else if (HandleDisplayCall(call, result)) {
    // getDisplays, setClientSize, moveToMonitor.
  } else {
    result->NotImplemented();
  }
}

}  // namespace

void LuminaWindowModeAttach(flutter::BinaryMessenger* messenger, HWND window,
                            HWND view) {
  g_window = window;
  g_view = view;
  g_window_proc = reinterpret_cast<WNDPROC>(::SetWindowLongPtr(
      window, GWLP_WNDPROC, reinterpret_cast<LONG_PTR>(WindowProc)));
  if (view) {
    g_view_proc = reinterpret_cast<WNDPROC>(::SetWindowLongPtr(
        view, GWLP_WNDPROC, reinterpret_cast<LONG_PTR>(ViewProc)));
  }
  g_channel = std::make_unique<flutter::MethodChannel<EncodableValue>>(
      messenger, kChannelName, &flutter::StandardMethodCodec::GetInstance());
  g_channel->SetMethodCallHandler(HandleCall);
  g_last_monitor = ::MonitorFromWindow(window, MONITOR_DEFAULTTONEAREST);
  if (kStartFullscreen) {
    // The windowed size Alt+Enter returns to: centred on the monitor.
    RECT r = {};
    ::GetWindowRect(window, &r);
    const RECT work = MonitorOf(window).rcWork;
    const LONG w = r.right - r.left;
    const LONG h = r.bottom - r.top;
    ::SetWindowPos(window, nullptr, work.left + ((work.right - work.left) - w) / 2,
                   work.top + ((work.bottom - work.top) - h) / 2, 0, 0,
                   SWP_NOSIZE | SWP_NOZORDER | SWP_NOACTIVATE);
    // The window is still hidden (it shows on the first frame): it never
    // appears windowed.
    EnterFullscreen();
  }
}
''';
